import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const sidebarInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "sidebar.workspaceDeck.openCard": ["Open {{card}}", "{{card}} öffnen", "Ouvrir {{card}}"],
  "sidebar.workspaceDeck.views": [
    "{{title}} views",
    "Ansichten für {{title}}",
    "Vues de {{title}}",
  ],
  "sidebar.toggleMain": [
    "Toggle main sidebar",
    "Hauptseitenleiste umschalten",
    "Afficher ou masquer la barre latérale principale",
  ],
  "sidebar.navigation.goToThreads": ["Go to threads", "Zu den Chats", "Accéder aux discussions"],
  "sidebar.navigation.back": ["Back", "Zurück", "Retour"],
  "sidebar.navigation.settings": ["Settings", "Einstellungen", "Réglages"],
  "sidebar.navigation.pullRequests": ["Pull Requests", "Pull Requests", "Demandes de tirage"],
  "sidebar.navigation.usage": ["Usage", "Nutzung", "Utilisation"],
  "sidebar.error.unexpected": [
    "An unexpected error occurred.",
    "Ein unerwarteter Fehler ist aufgetreten.",
    "Une erreur inattendue s’est produite.",
  ],
  "sidebar.error.occurred": ["Error occurred", "Fehler aufgetreten", "Une erreur s’est produite"],
  "sidebar.thread.branchMismatch": [
    "You’re currently checked out on another branch.",
    "Aktuell ist ein anderer Branch ausgecheckt.",
    "Une autre branche est actuellement extraite.",
  ],
  "sidebar.thread.runningTerminals": [
    { one: "{{count}} terminal process running", other: "{{count}} terminal processes running" },
    { one: "{{count}} Terminalprozess läuft", other: "{{count}} Terminalprozesse laufen" },
    {
      one: "{{count}} processus de terminal en cours",
      other: "{{count}} processus de terminal en cours",
    },
  ],
  "sidebar.status.working": ["Working", "Arbeitet", "En cours"],
  "sidebar.status.monitoring": ["Monitoring", "Überwacht", "Surveillance"],
  "sidebar.status.approval": ["Approval", "Freigabe", "Approbation"],
  "sidebar.status.input": ["Input", "Eingabe", "Saisie"],
  "sidebar.status.failed": ["Failed", "Fehlgeschlagen", "Échec"],
  "sidebar.status.woke": ["Woke", "Aufgewacht", "Réveillé"],
  "sidebar.status.done": ["Done", "Erledigt", "Terminé"],
  "sidebar.status.connecting": ["Connecting", "Verbindung wird hergestellt", "Connexion"],
  "sidebar.status.completed": ["Completed", "Abgeschlossen", "Terminée"],
  "sidebar.status.pendingApproval": [
    "Pending Approval",
    "Freigabe ausstehend",
    "Approbation en attente",
  ],
  "sidebar.status.awaitingInput": ["Awaiting Input", "Wartet auf Eingabe", "En attente de saisie"],
  "sidebar.status.planReady": ["Plan Ready", "Plan bereit", "Plan prêt"],
  "sidebar.thread.title": ["Thread title", "Chat-Titel", "Titre de la discussion"],
  "sidebar.thread.snooze": ["Snooze thread", "Chat zurückstellen", "Reporter la discussion"],
  "sidebar.thread.discardDraft": ["Discard draft", "Entwurf verwerfen", "Supprimer le brouillon"],
  "sidebar.thread.unpin": ["Unpin thread", "Chat lösen", "Désépingler la discussion"],
  "sidebar.thread.pinned": ["Pinned", "Angeheftet", "Épinglé"],
  "sidebar.thread.dismissWoke": [
    "Dismiss Woke notification",
    "Aufgewacht-Hinweis schließen",
    "Masquer la notification de réveil",
  ],
  "sidebar.thread.wakeNow": [
    "Wake thread now",
    "Chat jetzt aufwecken",
    "Réveiller la discussion maintenant",
  ],
  "sidebar.thread.unsettle": [
    "Un-settle thread",
    "Chat wieder aktivieren",
    "Réactiver la discussion",
  ],
  "sidebar.thread.settle": ["Settle thread", "Chat abschließen", "Classer la discussion"],
  "sidebar.thread.pathCopied": ["Path copied", "Pfad kopiert", "Chemin copié"],
  "sidebar.thread.copyPathFailed": [
    "Failed to copy path",
    "Pfad konnte nicht kopiert werden",
    "Échec de la copie du chemin",
  ],
  "sidebar.thread.branchCopied": ["Branch copied", "Branch kopiert", "Branche copiée"],
  "sidebar.thread.copyBranchFailed": [
    "Failed to copy branch",
    "Branch konnte nicht kopiert werden",
    "Échec de la copie de la branche",
  ],
  "sidebar.thread.idCopied": [
    "Thread ID copied",
    "Chat-ID kopiert",
    "Identifiant de discussion copié",
  ],
  "sidebar.thread.copyIdFailed": [
    "Failed to copy thread ID",
    "Chat-ID konnte nicht kopiert werden",
    "Échec de la copie de l’identifiant de discussion",
  ],
  "sidebar.thread.titleEmpty": [
    "Thread title cannot be empty",
    "Der Chat-Titel darf nicht leer sein",
    "Le titre de la discussion ne peut pas être vide",
  ],
  "sidebar.thread.renameFailed": [
    "Failed to rename thread",
    "Chat konnte nicht umbenannt werden",
    "Échec du renommage de la discussion",
  ],
  "sidebar.thread.settleFailed": [
    "Failed to settle thread",
    "Chat konnte nicht abgeschlossen werden",
    "Échec du classement de la discussion",
  ],
  "sidebar.thread.unsettleFailed": [
    "Failed to un-settle thread",
    "Chat konnte nicht reaktiviert werden",
    "Échec de la réactivation de la discussion",
  ],
  "sidebar.thread.wakeFailed": [
    "Failed to wake thread",
    "Chat konnte nicht aufgeweckt werden",
    "Échec du réveil de la discussion",
  ],
  "sidebar.thread.pinFailed": [
    "Failed to pin thread",
    "Chat konnte nicht angeheftet werden",
    "Échec de l’épinglage de la discussion",
  ],
  "sidebar.thread.unpinFailed": [
    "Failed to unpin thread",
    "Chat konnte nicht gelöst werden",
    "Échec du désépinglage de la discussion",
  ],
  "sidebar.thread.reorderPinnedFailed": [
    "Failed to reorder pinned threads",
    "Angeheftete Chats konnten nicht neu sortiert werden",
    "Échec du réordonnancement des discussions épinglées",
  ],
  "sidebar.thread.snoozeFailed": [
    "Failed to snooze thread",
    "Chat konnte nicht zurückgestellt werden",
    "Échec du report de la discussion",
  ],
  "sidebar.thread.snoozeManyFailed": [
    "Failed to snooze threads",
    "Chats konnten nicht zurückgestellt werden",
    "Échec du report des discussions",
  ],
  "sidebar.thread.snoozedUntil": [
    "Snoozed until {{time}}",
    "Zurückgestellt bis {{time}}",
    "Reportée jusqu’à {{time}}",
  ],
  "sidebar.thread.undo": ["Undo", "Rückgängig", "Annuler"],
  "sidebar.thread.regenerateTitlesFailed": [
    "Failed to regenerate thread titles",
    "Chat-Titel konnten nicht neu erzeugt werden",
    "Échec de la régénération des titres des discussions",
  ],
  "sidebar.thread.menu.regenerateTitlesCount": [
    "Regenerate titles ({{count}})",
    "Titel neu erzeugen ({{count}})",
    "Régénérer les titres ({{count}})",
  ],
  "sidebar.thread.menu.regeneratingTitlesCount": [
    "Regenerating… ({{count}})",
    "Werden neu erzeugt… ({{count}})",
    "Régénération… ({{count}})",
  ],
  "sidebar.thread.deleteManyFailed": [
    "Failed to delete threads",
    "Chats konnten nicht gelöscht werden",
    "Échec de la suppression des discussions",
  ],
  "sidebar.thread.createFailed": [
    "Could not create thread",
    "Chat konnte nicht erstellt werden",
    "Impossible de créer la discussion",
  ],
  "sidebar.thread.regenerateTitleFailed": [
    "Failed to regenerate thread title",
    "Chat-Titel konnte nicht neu erzeugt werden",
    "Échec de la régénération du titre de la discussion",
  ],
  "sidebar.thread.pathUnavailable": [
    "Path unavailable",
    "Pfad nicht verfügbar",
    "Chemin indisponible",
  ],
  "sidebar.thread.pathUnavailableDescription": [
    "This thread does not have a workspace path to copy.",
    "Dieser Chat besitzt keinen Workspace-Pfad zum Kopieren.",
    "Cette discussion ne possède aucun chemin d’espace de travail à copier.",
  ],
  "sidebar.thread.archiveNavigationFailed": [
    "Thread archived, but navigation failed",
    "Chat archiviert, Navigation jedoch fehlgeschlagen",
    "Discussion archivée, mais la navigation a échoué",
  ],
  "sidebar.thread.archiveFailed": [
    "Failed to archive thread",
    "Chat konnte nicht archiviert werden",
    "Échec de l’archivage de la discussion",
  ],
  "sidebar.thread.archiveConfirm": [
    'Archive thread "{{title}}"?',
    "Chat „{{title}}“ archivieren?",
    "Archiver la discussion « {{title}} » ?",
  ],
  "sidebar.thread.deleteFailed": [
    "Failed to delete thread",
    "Chat konnte nicht gelöscht werden",
    "Échec de la suppression de la discussion",
  ],
  "sidebar.thread.deleteConfirm": [
    'Delete thread "{{title}}"?',
    "Chat „{{title}}“ löschen?",
    "Supprimer la discussion « {{title}} » ?",
  ],
  "sidebar.thread.deleteHistoryWarning": [
    "This permanently clears conversation history for this thread.",
    "Dadurch wird der Gesprächsverlauf dieses Chats dauerhaft gelöscht.",
    "Cette action efface définitivement l’historique de cette discussion.",
  ],
  "sidebar.thread.deleteManyConfirm": [
    { one: "Delete {{count}} thread?", other: "Delete {{count}} threads?" },
    { one: "{{count}} Chat löschen?", other: "{{count}} Chats löschen?" },
    { one: "Supprimer {{count}} discussion ?", other: "Supprimer {{count}} discussions ?" },
  ],
  "sidebar.thread.deleteManyHistoryWarning": [
    "This permanently clears conversation history for these threads.",
    "Dadurch wird der Gesprächsverlauf dieser Chats dauerhaft gelöscht.",
    "Cette action efface définitivement l’historique de ces discussions.",
  ],
  "sidebar.thread.action.settleCount": [
    "Settle ({{count}})",
    "Abschließen ({{count}})",
    "Classer ({{count}})",
  ],
  "sidebar.thread.action.snoozeCount": [
    "Snooze ({{count}})",
    "Zurückstellen ({{count}})",
    "Reporter ({{count}})",
  ],
  "sidebar.thread.action.markUnreadCount": [
    "Mark unread ({{count}})",
    "Als ungelesen markieren ({{count}})",
    "Marquer comme non lues ({{count}})",
  ],
  "sidebar.thread.action.deleteCount": [
    "Delete ({{count}})",
    "Löschen ({{count}})",
    "Supprimer ({{count}})",
  ],
  "sidebar.thread.action.archiveCount": [
    "Archive ({{count}})",
    "Archivieren ({{count}})",
    "Archiver ({{count}})",
  ],
  "sidebar.thread.archiveManyConfirm": [
    { one: "Archive {{count}} thread?", other: "Archive {{count}} threads?" },
    { one: "{{count}} Chat archivieren?", other: "{{count}} Chats archivieren?" },
    { one: "Archiver {{count}} discussion ?", other: "Archiver {{count}} discussions ?" },
  ],
  "sidebar.thread.archiveManyFailed": [
    "Failed to archive threads",
    "Chats konnten nicht archiviert werden",
    "Échec de l’archivage des discussions",
  ],
  "sidebar.project.chooseEnvironmentFailed": [
    "Could not choose environment",
    "Umgebung konnte nicht ausgewählt werden",
    "Impossible de choisir l’environnement",
  ],
  "sidebar.thread.menu.newOnBranch": [
    "New thread on {{branch}}",
    "Neuer Chat auf {{branch}}",
    "Nouvelle discussion sur {{branch}}",
  ],
  "sidebar.thread.menu.pin": ["Pin thread", "Chat anheften", "Épingler la discussion"],
  "sidebar.thread.menu.unpin": ["Unpin thread", "Chat lösen", "Désépingler la discussion"],
  "sidebar.thread.menu.wake": ["Wake thread", "Chat aufwecken", "Réveiller la discussion"],
  "sidebar.thread.menu.snooze": ["Snooze", "Zurückstellen", "Reporter"],
  "sidebar.thread.menu.rename": ["Rename thread", "Chat umbenennen", "Renommer la discussion"],
  "sidebar.thread.menu.regenerate": [
    "Regenerate title",
    "Titel neu erzeugen",
    "Régénérer le titre",
  ],
  "sidebar.thread.menu.regenerating": ["Regenerating…", "Wird neu erzeugt…", "Régénération…"],
  "sidebar.thread.regeneratingTitle": [
    "Regenerating title",
    "Titel wird neu erzeugt",
    "Régénération du titre",
  ],
  "sidebar.thread.settleAction": ["Settle", "Abschließen", "Classer"],
  "sidebar.thread.menu.markUnread": [
    "Mark unread",
    "Als ungelesen markieren",
    "Marquer comme non lue",
  ],
  "sidebar.thread.menu.copy": ["Copy", "Kopieren", "Copier"],
  "sidebar.thread.menu.path": ["Path", "Pfad", "Chemin"],
  "sidebar.thread.menu.branch": ["Branch", "Branch", "Branche"],
  "sidebar.thread.menu.id": ["Thread ID", "Chat-ID", "Identifiant de discussion"],
  "sidebar.thread.menu.archive": ["Archive thread", "Chat archivieren", "Archiver la discussion"],
  "sidebar.thread.menu.delete": ["Delete", "Löschen", "Supprimer"],
  "sidebar.thread.snoozedSummary": [
    { one: "Snoozed {{count}} thread", other: "Snoozed {{count}} threads" },
    { one: "{{count}} Chat zurückgestellt", other: "{{count}} Chats zurückgestellt" },
    { one: "{{count}} discussion reportée", other: "{{count}} discussions reportées" },
  ],
  "sidebar.thread.snoozedPartialSummary": [
    "Snoozed {{count}} of {{total}} threads",
    "{{count}} von {{total}} Chats zurückgestellt",
    "{{count}} discussions sur {{total}} reportées",
  ],
  "sidebar.thread.snoozeFailedCount": [
    {
      one: "{{count}} thread couldn’t be snoozed.",
      other: "{{count}} threads couldn’t be snoozed.",
    },
    {
      one: "{{count}} Chat konnte nicht zurückgestellt werden.",
      other: "{{count}} Chats konnten nicht zurückgestellt werden.",
    },
    {
      one: "{{count}} discussion n’a pas pu être reportée.",
      other: "{{count}} discussions n’ont pas pu être reportées.",
    },
  ],
  "sidebar.search.placeholder": ["Search", "Suchen", "Rechercher"],
  "sidebar.search.threads": [
    "Search threads",
    "Chats durchsuchen",
    "Rechercher dans les discussions",
  ],
  "sidebar.search.clear": [
    "Clear thread search",
    "Chat-Suche leeren",
    "Effacer la recherche de discussions",
  ],
  "sidebar.search.results": [
    "Thread search results",
    "Chat-Suchergebnisse",
    "Résultats de recherche des discussions",
  ],
  "sidebar.search.noThreads": [
    "No threads found",
    "Keine Chats gefunden",
    "Aucune discussion trouvée",
  ],
  "sidebar.thread.new": ["New thread", "Neuer Chat", "Nouvelle discussion"],
  "sidebar.thread.newWithShortcut": [
    "New thread ({{shortcut}})",
    "Neuer Chat ({{shortcut}})",
    "Nouvelle discussion ({{shortcut}})",
  ],
  "sidebar.thread.newInCurrentProject": [
    "New thread in current project: Shift+click",
    "Neuer Chat im aktuellen Projekt: Umschalt+Klick",
    "Nouvelle discussion dans le projet actuel : Maj+clic",
  ],
  "sidebar.project.filter": [
    "Filter threads by project",
    "Chats nach Projekt filtern",
    "Filtrer les discussions par projet",
  ],
  "sidebar.project.all": ["All projects", "Alle Projekte", "Tous les projets"],
  "sidebar.project.search": ["Search projects", "Projekte durchsuchen", "Rechercher des projets"],
  "sidebar.project.searchPlaceholder": [
    "Search projects…",
    "Projekte durchsuchen…",
    "Rechercher des projets…",
  ],
  "sidebar.project.noMatches": [
    "No matching projects.",
    "Keine passenden Projekte.",
    "Aucun projet correspondant.",
  ],
  "sidebar.project.settingsFor": [
    "Project settings for {{project}}",
    "Projekteinstellungen für {{project}}",
    "Réglages du projet {{project}}",
  ],
  "sidebar.project.new": ["New project", "Neues Projekt", "Nouveau projet"],
  "sidebar.project.noProjects": [
    "No projects yet",
    "Noch keine Projekte",
    "Aucun projet pour le moment",
  ],
  "sidebar.project.groupedCount": [
    { one: "{{count}} project", other: "{{count}} projects" },
    { one: "{{count}} Projekt", other: "{{count}} Projekte" },
    { one: "{{count}} projet", other: "{{count}} projets" },
  ],
  "sidebar.thread.noThreads": [
    "No threads yet",
    "Noch keine Chats",
    "Aucune discussion pour le moment",
  ],
  "sidebar.thread.noThreadsInProject": [
    "No threads in {{project}} yet",
    "Noch keine Chats in {{project}}",
    "Aucune discussion dans {{project}} pour le moment",
  ],
  "sidebar.section.pinnedThreads": ["Pinned threads", "Angeheftete Chats", "Discussions épinglées"],
  "sidebar.section.snoozed": ["Snoozed", "Zurückgestellt", "Reportées"],
  "sidebar.section.snoozedCount": [
    "Snoozed ({{count}})",
    "Zurückgestellt ({{count}})",
    "Reportées ({{count}})",
  ],
  "sidebar.section.settled": ["Settled", "Abgeschlossen", "Classées"],
  "sidebar.section.settledCount": [
    "Settled ({{count}})",
    "Abgeschlossen ({{count}})",
    "Classées ({{count}})",
  ],
  "sidebar.olderProjects.label": ["Older projects", "Ältere Projekte", "Projets plus anciens"],
  "sidebar.olderProjects.count": [
    { one: "{{count}} older project", other: "{{count}} older projects" },
    { one: "{{count}} älteres Projekt", other: "{{count}} ältere Projekte" },
    { one: "{{count}} projet plus ancien", other: "{{count}} projets plus anciens" },
  ],
  "sidebar.olderProjects.tooltip": [
    "No work activity for more than 7 days.",
    "Seit mehr als 7 Tagen keine Arbeitsaktivität.",
    "Aucune activité de travail depuis plus de 7 jours.",
  ],
  "sidebar.classic.noThreads": [
    "No threads yet",
    "Noch keine Chats",
    "Aucune discussion pour le moment",
  ],
  "sidebar.classic.showMore": ["Show more", "Mehr anzeigen", "Afficher plus"],
  "sidebar.classic.showMoreCount": [
    { one: "Show {{count}} more", other: "Show {{count}} more" },
    { one: "Noch {{count}} anzeigen", other: "Noch {{count}} anzeigen" },
    { one: "Afficher {{count}} de plus", other: "Afficher {{count}} de plus" },
  ],
  "sidebar.classic.showLess": ["Show less", "Weniger anzeigen", "Afficher moins"],
  "sidebar.classic.showSettled": [
    "Show settled chats",
    "Abgeschlossene Chats anzeigen",
    "Afficher les discussions classées",
  ],
  "sidebar.classic.hideSettled": [
    "Hide settled chats",
    "Abgeschlossene Chats ausblenden",
    "Masquer les discussions classées",
  ],
  "sidebar.classic.options": [
    "Sidebar options",
    "Seitenleistenoptionen",
    "Options de la barre latérale",
  ],
  "sidebar.classic.projects": ["Projects", "Projekte", "Projets"],
  "sidebar.classic.addProject": ["Add project", "Projekt hinzufügen", "Ajouter un projet"],
  "sidebar.classic.confirm": ["Confirm", "Bestätigen", "Confirmer"],
  "sidebar.classic.search": ["Search", "Suchen", "Rechercher"],
  "sidebar.classic.archive": ["Archive", "Archivieren", "Archiver"],
  "sidebar.classic.previewOpenFailed": [
    "Unable to open preview",
    "Vorschau konnte nicht geöffnet werden",
    "Impossible d’ouvrir l’aperçu",
  ],
  "sidebar.classic.previewOpenFailedDescription": [
    "The preview could not be opened.",
    "Die Vorschau konnte nicht geöffnet werden.",
    "L’aperçu n’a pas pu être ouvert.",
  ],
  "sidebar.classic.threadActionFailed": [
    "Thread action failed",
    "Chat-Aktion fehlgeschlagen",
    "Échec de l’action sur la discussion",
  ],
  "sidebar.classic.openLocalhost": [
    "Open localhost:{{port}}",
    "localhost:{{port}} öffnen",
    "Ouvrir localhost:{{port}}",
  ],
  "sidebar.classic.confirmArchive": [
    "Confirm archive {{title}}",
    "Archivierung von {{title}} bestätigen",
    "Confirmer l’archivage de {{title}}",
  ],
  "sidebar.classic.archiveThread": [
    "Archive {{title}}",
    "{{title}} archivieren",
    "Archiver {{title}}",
  ],
  "sidebar.classic.remote": ["Remote", "Remote", "Distant"],
  "sidebar.classic.local": ["Local", "Lokal", "Local"],
  "sidebar.classic.localSandboxProject": [
    "Local sandbox project",
    "Lokales Sandbox-Projekt",
    "Projet bac à sable local",
  ],
  "sidebar.classic.remoteProject": ["Remote project", "Remote-Projekt", "Projet distant"],
  "sidebar.classic.localSandbox": [
    "Local sandbox: {{environments}}",
    "Lokale Sandbox: {{environments}}",
    "Bac à sable local : {{environments}}",
  ],
  "sidebar.classic.remoteEnvironment": [
    "Remote environment: {{environments}}",
    "Remote-Umgebung: {{environments}}",
    "Environnement distant : {{environments}}",
  ],
  "sidebar.classic.createThreadIn": [
    "Create new thread in {{project}}",
    "Neuen Chat in {{project}} erstellen",
    "Créer une discussion dans {{project}}",
  ],
  "sidebar.classic.connectionFailed": [
    "Couldn’t connect {{environments}}",
    "Verbindung mit {{environments}} fehlgeschlagen",
    "Impossible de se connecter à {{environments}}",
  ],
  "sidebar.classic.connecting": [
    "Connecting to {{environments}}",
    "Verbindung mit {{environments}} wird hergestellt",
    "Connexion à {{environments}}",
  ],
  "sidebar.classic.backendNoResponse": [
    "The backend didn’t respond.",
    "Das Backend hat nicht geantwortet.",
    "Le serveur n’a pas répondu.",
  ],
  "sidebar.classic.chatsPerProject": [
    "Chats per project",
    "Chats pro Projekt",
    "Discussions par projet",
  ],
  "sidebar.project.renameTitle": ["Rename project", "Projekt umbenennen", "Renommer le projet"],
  "sidebar.project.renameDescriptionPath": [
    "Update the title for {{path}}.",
    "Titel für {{path}} aktualisieren.",
    "Mettre à jour le titre de {{path}}.",
  ],
  "sidebar.project.renameDescription": [
    "Update the project title.",
    "Projekttitel aktualisieren.",
    "Mettre à jour le titre du projet.",
  ],
  "sidebar.project.title": ["Project title", "Projekttitel", "Titre du projet"],
  "sidebar.project.save": ["Save", "Speichern", "Enregistrer"],
  "sidebar.project.groupingTitle": [
    "Project grouping",
    "Projektgruppierung",
    "Regroupement des projets",
  ],
  "sidebar.project.groupingDescriptionPath": [
    "Choose how {{path}} should be grouped in the sidebar.",
    "Auswählen, wie {{path}} in der Seitenleiste gruppiert werden soll.",
    "Choisissez comment regrouper {{path}} dans la barre latérale.",
  ],
  "sidebar.project.groupingDescription": [
    "Choose how this project should be grouped in the sidebar.",
    "Auswählen, wie dieses Projekt in der Seitenleiste gruppiert werden soll.",
    "Choisissez comment regrouper ce projet dans la barre latérale.",
  ],
  "sidebar.project.groupingRule": ["Grouping rule", "Gruppierungsregel", "Règle de regroupement"],
  "sidebar.project.grouping.globalDefault": [
    "Use global default",
    "Globalen Standard verwenden",
    "Utiliser la valeur globale",
  ],
  "sidebar.project.grouping.repository": [
    "Group by repository",
    "Nach Repository gruppieren",
    "Regrouper par dépôt",
  ],
  "sidebar.project.grouping.repositoryPath": [
    "Group by repository path",
    "Nach Repository-Pfad gruppieren",
    "Regrouper par chemin de dépôt",
  ],
  "sidebar.project.grouping.separate": ["Keep separate", "Getrennt halten", "Garder séparé"],
  "sidebar.project.grouping.repositoryDescription": [
    "Projects from the same repository share one sidebar row.",
    "Projekte aus demselben Repository teilen sich eine Zeile in der Seitenleiste.",
    "Les projets du même dépôt partagent une ligne dans la barre latérale.",
  ],
  "sidebar.project.grouping.repositoryPathDescription": [
    "Projects group only when both the repository and repo-relative path match.",
    "Projekte werden nur gruppiert, wenn Repository und relativer Repository-Pfad übereinstimmen.",
    "Les projets ne sont regroupés que si le dépôt et le chemin relatif correspondent.",
  ],
  "sidebar.project.grouping.separateDescription": [
    "Every project path gets its own sidebar row.",
    "Jeder Projektpfad erhält eine eigene Zeile in der Seitenleiste.",
    "Chaque chemin de projet possède sa propre ligne dans la barre latérale.",
  ],
  "sidebar.sort.lastUserMessage": [
    "Last user message",
    "Letzte Benutzernachricht",
    "Dernier message utilisateur",
  ],
  "sidebar.sort.createdAt": ["Created at", "Erstellt am", "Date de création"],
  "sidebar.sort.manual": ["Manual", "Manuell", "Manuel"],
  "sidebar.sort.projects": ["Sort projects", "Projekte sortieren", "Trier les projets"],
  "sidebar.sort.threads": ["Sort threads", "Chats sortieren", "Trier les discussions"],
  "sidebar.project.useGlobalDefault": [
    "Use global default ({{mode}})",
    "Globalen Standard verwenden ({{mode}})",
    "Utiliser la valeur globale ({{mode}})",
  ],
  "sidebar.project.titleEmpty": [
    "Project title cannot be empty",
    "Der Projekttitel darf nicht leer sein",
    "Le titre du projet ne peut pas être vide",
  ],
  "sidebar.project.renameFailed": [
    "Failed to rename project",
    "Projekt konnte nicht umbenannt werden",
    "Échec du renommage du projet",
  ],
  "sidebar.project.notEmpty": [
    "Project is not empty",
    "Projekt ist nicht leer",
    "Le projet n’est pas vide",
  ],
  "sidebar.project.notEmptyDescription": [
    "Delete all threads in this project before removing it.",
    "Vor dem Entfernen alle Chats in diesem Projekt löschen.",
    "Supprimez toutes les discussions de ce projet avant de le retirer.",
  ],
  "sidebar.project.deleteAnyway": ["Delete anyway", "Trotzdem löschen", "Supprimer quand même"],
  "sidebar.project.removeConfirm": [
    'Remove project "{{project}}"?',
    "Projekt „{{project}}“ entfernen?",
    "Retirer le projet « {{project}} » ?",
  ],
  "sidebar.project.removeWithThreadsConfirm": [
    {
      one: 'Remove project "{{project}}" and delete its {{count}} thread?',
      other: 'Remove project "{{project}}" and delete its {{count}} threads?',
    },
    {
      one: "Projekt „{{project}}“ entfernen und seinen {{count}} Chat löschen?",
      other: "Projekt „{{project}}“ entfernen und seine {{count}} Chats löschen?",
    },
    {
      one: "Retirer le projet « {{project}} » et supprimer sa {{count}} discussion ?",
      other: "Retirer le projet « {{project}} » et supprimer ses {{count}} discussions ?",
    },
  ],
  "sidebar.project.path": ["Path: {{path}}", "Pfad: {{path}}", "Chemin : {{path}}"],
  "sidebar.project.environment": [
    "Environment: {{environment}}",
    "Umgebung: {{environment}}",
    "Environnement : {{environment}}",
  ],
  "sidebar.project.removeEntryOnly": [
    "This removes only this project entry.",
    "Dadurch wird nur dieser Projekteintrag entfernt.",
    "Seule cette entrée de projet sera retirée.",
  ],
  "sidebar.project.actionCannotUndo": [
    "This action cannot be undone.",
    "Diese Aktion kann nicht rückgängig gemacht werden.",
    "Cette action est irréversible.",
  ],
  "sidebar.project.removeFailed": [
    'Failed to remove "{{project}}"',
    "„{{project}}“ konnte nicht entfernt werden",
    "Échec du retrait de « {{project}} »",
  ],
  "sidebar.project.removeUnknownError": [
    "Unknown error removing project.",
    "Unbekannter Fehler beim Entfernen des Projekts.",
    "Erreur inconnue lors du retrait du projet.",
  ],
  "sidebar.project.menu.rename": ["Rename", "Umbenennen", "Renommer"],
  "sidebar.project.menu.group": ["Group into…", "Gruppieren unter…", "Regrouper dans…"],
  "sidebar.project.menu.copyPath": ["Copy Path", "Pfad kopieren", "Copier le chemin"],
  "sidebar.project.menu.remove": ["Remove", "Entfernen", "Retirer"],
  "sidebar.branch.runOn": ["Run on", "Ausführen auf", "Exécuter sur"],
  "sidebar.branch.workspace": ["Workspace", "Workspace", "Espace de travail"],
  "sidebar.branch.newWorktree": ["New worktree", "Neuer Worktree", "Nouvel arbre de travail"],
  "sidebar.branch.currentCheckout": [
    "Current checkout",
    "Aktueller Checkout",
    "Extraction actuelle",
  ],
  "sidebar.branch.currentWorktree": [
    "Current worktree",
    "Aktueller Worktree",
    "Arbre de travail actuel",
  ],
  "sidebar.branch.worktree": ["Worktree", "Worktree", "Arbre de travail"],
  "sidebar.branch.localCheckout": ["Local checkout", "Lokaler Checkout", "Extraction locale"],
  "sidebar.branch.previousWorktree": [
    "Previous worktree",
    "Vorheriger Worktree",
    "Arbre de travail précédent",
  ],
  "sidebar.branch.previousWorktreeBranch": [
    "Previous worktree ({{branch}})",
    "Vorheriger Worktree ({{branch}})",
    "Arbre de travail précédent ({{branch}})",
  ],
  "sidebar.branch.loadingRefs": [
    "Loading refs…",
    "Refs werden geladen…",
    "Chargement des références…",
  ],
  "sidebar.branch.loadingMoreRefs": [
    "Loading more refs…",
    "Weitere Refs werden geladen…",
    "Chargement d’autres références…",
  ],
  "sidebar.branch.showingRefs": [
    "Showing {{shown}} of {{total}} refs",
    "{{shown}} von {{total}} Refs werden angezeigt",
    "{{shown}} références sur {{total}} affichées",
  ],
  "sidebar.branch.nameCopied": [
    "Branch name copied",
    "Branch-Name kopiert",
    "Nom de branche copié",
  ],
  "sidebar.branch.copyNameFailed": [
    "Failed to copy branch name",
    "Branch-Name konnte nicht kopiert werden",
    "Échec de la copie du nom de branche",
  ],
  "sidebar.branch.copyName": [
    "Copy branch name",
    "Branch-Name kopieren",
    "Copier le nom de branche",
  ],
  "sidebar.branch.switchFailed": [
    "Failed to switch ref.",
    "Ref konnte nicht gewechselt werden.",
    "Échec du changement de référence.",
  ],
  "sidebar.branch.createFailed": [
    "Failed to create and switch ref.",
    "Ref konnte nicht erstellt und gewechselt werden.",
    "Échec de la création et du changement de référence.",
  ],
  "sidebar.branch.searchPlaceholder": [
    "Search refs…",
    "Refs durchsuchen…",
    "Rechercher des références…",
  ],
  "sidebar.branch.noRefs": ["No refs found.", "Keine Refs gefunden.", "Aucune référence trouvée."],
  "sidebar.branch.createNew": [
    'Create new ref "{{name}}"',
    "Neue Ref „{{name}}“ erstellen",
    "Créer la référence « {{name}} »",
  ],
  "sidebar.branch.badge.current": ["current", "aktuell", "actuelle"],
  "sidebar.branch.badge.worktree": ["worktree", "Worktree", "arbre de travail"],
  "sidebar.branch.badge.remote": ["remote", "remote", "distante"],
  "sidebar.branch.badge.default": ["default", "Standard", "par défaut"],
  "sidebar.branch.startFromOrigin": [
    "Start from origin",
    "Von Origin starten",
    "Démarrer depuis origin",
  ],
  "sidebar.branch.startWorktreeFromOrigin": [
    "Start worktree from origin",
    "Worktree von Origin starten",
    "Démarrer l’arbre de travail depuis origin",
  ],
  "sidebar.branch.startFromOriginDescription": [
    "Creates the worktree from the latest matching branch on origin instead of your local branch.",
    "Erstellt den Worktree aus dem neuesten passenden Branch auf Origin statt aus dem lokalen Branch.",
    "Crée l’arbre de travail depuis la dernière branche correspondante sur origin plutôt que depuis la branche locale.",
  ],
  "sidebar.branch.checkoutChangeRequest": [
    "Checkout {{kind}}",
    "{{kind}} auschecken",
    "Extraire {{kind}}",
  ],
  "sidebar.branch.openChangeRequest": [
    "Open {{kind}} #{{number}} ({{state}})",
    "{{kind}} #{{number}} öffnen ({{state}})",
    "Ouvrir {{kind}} #{{number}} ({{state}})",
  ],
  "sidebar.script.import": ["Import", "Importieren", "Importer"],
  "sidebar.script.projectScripts": ["Project scripts", "Projektskripte", "Scripts du projet"],
  "sidebar.script.run": ["Run {{name}}", "{{name}} ausführen", "Exécuter {{name}}"],
  "sidebar.script.actions": ["Script actions", "Skriptaktionen", "Actions du script"],
  "sidebar.script.edit": ["Edit {{name}}", "{{name}} bearbeiten", "Modifier {{name}}"],
  "sidebar.script.setupSuffix": [
    "{{name}} (setup)",
    "{{name}} (Einrichtung)",
    "{{name}} (configuration)",
  ],
  "sidebar.script.projectActions": ["Project actions", "Projektaktionen", "Actions du projet"],
  "sidebar.script.addAction": ["Add action", "Aktion hinzufügen", "Ajouter une action"],
  "sidebar.script.fromProjectFile": ["From t3.json", "Aus t3.json", "Depuis t3.json"],
  "sidebar.script.importFailed": [
    "Failed to import action.",
    "Aktion konnte nicht importiert werden.",
    "Échec de l’importation de l’action.",
  ],
  "sidebar.script.editor.addTitle": ["Add Action", "Aktion hinzufügen", "Ajouter une action"],
  "sidebar.script.editor.editTitle": ["Edit Action", "Aktion bearbeiten", "Modifier l’action"],
  "sidebar.script.editor.description": [
    "Actions are project-scoped commands you can run from the top bar or keybindings.",
    "Aktionen sind projektbezogene Befehle, die über die obere Leiste oder Tastenkürzel ausgeführt werden können.",
    "Les actions sont des commandes propres au projet, exécutables depuis la barre supérieure ou par raccourci clavier.",
  ],
  "sidebar.script.editor.name": ["Name", "Name", "Nom"],
  "sidebar.script.editor.chooseIcon": ["Choose icon", "Symbol auswählen", "Choisir une icône"],
  "sidebar.script.editor.icon.play": ["Play", "Start", "Exécuter"],
  "sidebar.script.editor.icon.test": ["Test", "Test", "Test"],
  "sidebar.script.editor.icon.lint": ["Lint", "Lint", "Lint"],
  "sidebar.script.editor.icon.configure": ["Configure", "Konfigurieren", "Configurer"],
  "sidebar.script.editor.icon.build": ["Build", "Build", "Compilation"],
  "sidebar.script.editor.icon.debug": ["Debug", "Debug", "Débogage"],
  "sidebar.script.editor.keybinding": ["Keybinding", "Tastenkürzel", "Raccourci clavier"],
  "sidebar.script.editor.pressShortcut": [
    "Press shortcut",
    "Tastenkürzel drücken",
    "Appuyez sur un raccourci",
  ],
  "sidebar.script.editor.shortcutHelp": [
    "Press a shortcut. Use Backspace to clear.",
    "Ein Tastenkürzel drücken. Zum Leeren die Rücktaste verwenden.",
    "Appuyez sur un raccourci. Utilisez Retour arrière pour l’effacer.",
  ],
  "sidebar.script.editor.command": ["Command", "Befehl", "Commande"],
  "sidebar.script.editor.previewUrl": [
    "Preview URL (optional)",
    "Vorschau-URL (optional)",
    "URL d’aperçu (facultative)",
  ],
  "sidebar.script.editor.previewUrlHelp": [
    "Open this URL in the in-app preview when this action runs.",
    "Diese URL in der integrierten Vorschau öffnen, wenn die Aktion ausgeführt wird.",
    "Ouvrir cette URL dans l’aperçu intégré lorsque l’action s’exécute.",
  ],
  "sidebar.script.editor.runOnWorktreeCreate": [
    "Run automatically on worktree creation",
    "Beim Erstellen eines Worktrees automatisch ausführen",
    "Exécuter automatiquement à la création d’un arbre de travail",
  ],
  "sidebar.script.editor.autoOpenPreview": [
    "Open preview automatically when this action runs",
    "Vorschau beim Ausführen dieser Aktion automatisch öffnen",
    "Ouvrir automatiquement l’aperçu lors de l’exécution de cette action",
  ],
  "sidebar.script.editor.nameRequired": [
    "Name is required.",
    "Ein Name ist erforderlich.",
    "Le nom est obligatoire.",
  ],
  "sidebar.script.editor.commandRequired": [
    "Command is required.",
    "Ein Befehl ist erforderlich.",
    "La commande est obligatoire.",
  ],
  "sidebar.script.editor.saveFailed": [
    "Failed to save action.",
    "Aktion konnte nicht gespeichert werden.",
    "Échec de l’enregistrement de l’action.",
  ],
  "sidebar.script.editor.delete": ["Delete", "Löschen", "Supprimer"],
  "sidebar.script.editor.cancel": ["Cancel", "Abbrechen", "Annuler"],
  "sidebar.script.editor.saveChanges": [
    "Save changes",
    "Änderungen speichern",
    "Enregistrer les modifications",
  ],
  "sidebar.script.editor.saveAction": ["Save action", "Aktion speichern", "Enregistrer l’action"],
  "sidebar.script.editor.deleteTitle": [
    'Delete action "{{name}}"?',
    "Aktion „{{name}}“ löschen?",
    "Supprimer l’action « {{name}} » ?",
  ],
  "sidebar.script.editor.cannotUndo": [
    "This action cannot be undone.",
    "Diese Aktion kann nicht rückgängig gemacht werden.",
    "Cette action est irréversible.",
  ],
  "sidebar.script.editor.deleteAction": ["Delete action", "Aktion löschen", "Supprimer l’action"],
  "sidebar.providerUpdate.dismiss": [
    "Dismiss provider update notice",
    "Provider-Update-Hinweis schließen",
    "Masquer la notification de mise à jour du fournisseur",
  ],
  "sidebar.providerUpdate.dismissUntilChange": [
    "Dismiss until provider status changes",
    "Bis zur nächsten Provider-Statusänderung ausblenden",
    "Masquer jusqu’au prochain changement d’état du fournisseur",
  ],
  "sidebar.update.available": ["Update available", "Update verfügbar", "Mise à jour disponible"],
  "sidebar.update.checking": [
    "Checking for updates…",
    "Updates werden gesucht…",
    "Recherche de mises à jour…",
  ],
  "sidebar.update.check": [
    "Check for updates",
    "Nach Updates suchen",
    "Rechercher des mises à jour",
  ],
  "sidebar.update.readyToDownload": [
    "Update ready to download",
    "Update zum Download bereit",
    "Mise à jour prête à être téléchargée",
  ],
  "sidebar.update.versionReadyToDownload": [
    "Update {{version}} ready to download",
    "Update {{version}} zum Download bereit",
    "Mise à jour {{version}} prête à être téléchargée",
  ],
  "sidebar.update.downloading": [
    "Downloading update",
    "Update wird heruntergeladen",
    "Téléchargement de la mise à jour",
  ],
  "sidebar.update.downloadingProgress": [
    "Downloading update ({{percent}}%)",
    "Update wird heruntergeladen ({{percent}} %)",
    "Téléchargement de la mise à jour ({{percent}} %)",
  ],
  "sidebar.update.downloaded": [
    "Update {{version}} downloaded. Click to restart and install.",
    "Update {{version}} heruntergeladen. Zum Neustarten und Installieren klicken.",
    "Mise à jour {{version}} téléchargée. Cliquez pour redémarrer et l’installer.",
  ],
  "sidebar.update.downloadRetry": [
    "Download failed for {{version}}. Click to retry.",
    "Download für {{version}} fehlgeschlagen. Zum Wiederholen klicken.",
    "Échec du téléchargement de {{version}}. Cliquez pour réessayer.",
  ],
  "sidebar.update.installRetry": [
    "Install failed for {{version}}. Click to retry.",
    "Installation von {{version}} fehlgeschlagen. Zum Wiederholen klicken.",
    "Échec de l’installation de {{version}}. Cliquez pour réessayer.",
  ],
  "sidebar.update.failed": ["Update failed", "Update fehlgeschlagen", "Échec de la mise à jour"],
  "sidebar.update.current": ["Up to date", "Aktuell", "À jour"],
  "sidebar.update.installConfirm": [
    "Install update{{version}} and restart T3 Code?\n\nAny running tasks will be interrupted. Make sure you’re ready before continuing.",
    "Update{{version}} installieren und T3 Code neu starten?\n\nAlle laufenden Aufgaben werden unterbrochen. Vor dem Fortfahren sicherstellen, dass alles bereit ist.",
    "Installer la mise à jour{{version}} et redémarrer T3 Code ?\n\nToutes les tâches en cours seront interrompues. Vérifiez que vous êtes prêt avant de continuer.",
  ],
  "sidebar.update.whatsChanged": ["What’s changed", "Was ist neu", "Nouveautés"],
  "sidebar.update.changesIn": [
    "Changes in {{version}}",
    "Änderungen in {{version}}",
    "Modifications dans {{version}}",
  ],
  "sidebar.update.intelOnAppleSilicon": [
    "Intel build on Apple Silicon",
    "Intel-Build auf Apple Silicon",
    "Version Intel sur Apple Silicon",
  ],
  "sidebar.update.downloadArmBuild": [
    "Download ARM build",
    "ARM-Build herunterladen",
    "Télécharger la version ARM",
  ],
  "sidebar.update.installArmBuild": [
    "Install ARM build",
    "ARM-Build installieren",
    "Installer la version ARM",
  ],
  "sidebar.update.armDownloadDescription": [
    "This Mac has Apple Silicon, but T3 Code is still running the Intel build under Rosetta. Download the available update to switch to the native Apple Silicon build.",
    "Dieser Mac hat Apple Silicon, T3 Code verwendet unter Rosetta jedoch noch den Intel-Build. Das verfügbare Update herunterladen, um zum nativen Apple-Silicon-Build zu wechseln.",
    "Ce Mac utilise Apple Silicon, mais T3 Code exécute encore la version Intel sous Rosetta. Téléchargez la mise à jour disponible pour passer à la version native Apple Silicon.",
  ],
  "sidebar.update.armInstallDescription": [
    "This Mac has Apple Silicon, but T3 Code is still running the Intel build under Rosetta. Restart to install the downloaded Apple Silicon build.",
    "Dieser Mac hat Apple Silicon, T3 Code verwendet unter Rosetta jedoch noch den Intel-Build. Neu starten, um den heruntergeladenen Apple-Silicon-Build zu installieren.",
    "Ce Mac utilise Apple Silicon, mais T3 Code exécute encore la version Intel sous Rosetta. Redémarrez pour installer la version Apple Silicon téléchargée.",
  ],
  "sidebar.update.armNextDescription": [
    "This Mac has Apple Silicon, but T3 Code is still running the Intel build under Rosetta. The next app update will replace it with the native Apple Silicon build.",
    "Dieser Mac hat Apple Silicon, T3 Code verwendet unter Rosetta jedoch noch den Intel-Build. Das nächste App-Update ersetzt ihn durch den nativen Apple-Silicon-Build.",
    "Ce Mac utilise Apple Silicon, mais T3 Code exécute encore la version Intel sous Rosetta. La prochaine mise à jour le remplacera par la version native Apple Silicon.",
  ],
  "sidebar.update.downloadFailed": [
    "Could not download update",
    "Update konnte nicht heruntergeladen werden",
    "Impossible de télécharger la mise à jour",
  ],
  "sidebar.update.downloadStartFailed": [
    "Could not start update download",
    "Update-Download konnte nicht gestartet werden",
    "Impossible de lancer le téléchargement de la mise à jour",
  ],
  "sidebar.update.confirmFailed": [
    "Could not confirm update",
    "Update konnte nicht bestätigt werden",
    "Impossible de confirmer la mise à jour",
  ],
  "sidebar.update.installFailed": [
    "Could not install update",
    "Update konnte nicht installiert werden",
    "Impossible d’installer la mise à jour",
  ],
  "sidebar.update.checkFailed": [
    "Could not check for updates",
    "Updates konnten nicht geprüft werden",
    "Impossible de rechercher des mises à jour",
  ],
  "sidebar.update.downloadUnavailable": [
    "Automatic updates are not available in this build.",
    "Automatische Updates sind in diesem Build nicht verfügbar.",
    "Les mises à jour automatiques ne sont pas disponibles dans cette version.",
  ],
  "sidebar.update.confirmationFailed": [
    "Update confirmation failed.",
    "Update-Bestätigung fehlgeschlagen.",
    "Échec de la confirmation de la mise à jour.",
  ],
  "sidebar.update.checkError": [
    "Update check failed.",
    "Update-Prüfung fehlgeschlagen.",
    "Échec de la recherche de mises à jour.",
  ],
});

export type SidebarInterfaceMessageKey = (typeof sidebarInterfaceCatalog.keys)[number];
