import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const uiInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "ui.notification.dismiss": [
    "Dismiss notification",
    "Benachrichtigung schließen",
    "Masquer la notification",
  ],
  "ui.loading": ["Loading", "Wird geladen", "Chargement"],
  "ui.close": ["Close", "Schließen", "Fermer"],
  "ui.remove": ["Remove", "Entfernen", "Retirer"],
  "ui.commandPalette.label": ["Command palette", "Befehlspalette", "Palette de commandes"],
  "ui.commandPalette.navigate": ["Navigate", "Navigieren", "Naviguer"],
  "ui.commandPalette.back": ["Back", "Zurück", "Retour"],
  "ui.commandPalette.repository": ["Repository", "Repository", "Dépôt"],
  "ui.commandPalette.filePicker": ["File picker", "Dateiauswahl", "Sélecteur de fichiers"],
  "ui.commandPalette.searchProjectContents": [
    "Search project contents",
    "Projektinhalte durchsuchen",
    "Rechercher dans le projet",
  ],
  "ui.commandPalette.youPrefix": ["You:", "Du:", "Vous :"],
  "ui.commandPalette.agentPrefix": ["Agent:", "Agent:", "Agent :"],
  "ui.commandPalette.noMatchingActions": [
    "No matching actions.",
    "Keine passenden Aktionen.",
    "Aucune action correspondante.",
  ],
  "ui.commandPalette.noMatchingItems": [
    "No matching commands, projects, or threads.",
    "Keine passenden Befehle, Projekte oder Chats.",
    "Aucune commande, aucun projet ni aucune discussion correspondante.",
  ],
  "ui.commandPalette.remote": ["Remote", "Remote", "Distant"],
  "ui.commandPalette.local": ["Local", "Lokal", "Local"],
  "ui.commandPalette.localFolder": ["Local folder", "Lokaler Ordner", "Dossier local"],
  "ui.commandPalette.browseFolder": [
    "Browse a folder on disk",
    "Ordner auf dem Datenträger auswählen",
    "Parcourir un dossier sur le disque",
  ],
  "ui.commandPalette.gitUrl": ["Git URL", "Git-URL", "URL Git"],
  "ui.commandPalette.providerRepository": [
    "{{provider}} repository",
    "{{provider}}-Repository",
    "Dépôt {{provider}}",
  ],
  "ui.commandPalette.cloneRemoteUrl": [
    "Clone from a remote URL",
    "Von einer Remote-URL klonen",
    "Cloner depuis une URL distante",
  ],
  "ui.commandPalette.cloneProviderRepository": [
    "Clone {{provider}} {{path}}",
    "{{provider}} {{path}} klonen",
    "Cloner {{provider}} {{path}}",
  ],
  "ui.commandPalette.setupRequired": [
    "Setup required",
    "Einrichtung erforderlich",
    "Configuration requise",
  ],
  "ui.commandPalette.configureProvider": [
    "Open Settings → Source Control to configure this provider.",
    "Einstellungen → Quellcodeverwaltung öffnen, um diesen Anbieter einzurichten.",
    "Ouvrez Réglages → Gestion du code source pour configurer ce fournisseur.",
  ],
  "ui.commandPalette.providerStatusUnavailable": [
    "Provider status unavailable. Open Settings → Source Control and rescan.",
    "Anbieterstatus nicht verfügbar. Einstellungen → Quellcodeverwaltung öffnen und erneut prüfen.",
    "État du fournisseur indisponible. Ouvrez Réglages → Gestion du code source et relancez l’analyse.",
  ],
  "ui.commandPalette.providerUnauthenticated": [
    "{{provider}} is not authenticated. Open Settings → Source Control for setup guidance.",
    "{{provider}} ist nicht authentifiziert. Einrichtungshinweise findest du unter Einstellungen → Quellcodeverwaltung.",
    "{{provider}} n’est pas authentifié. Consultez Réglages → Gestion du code source pour le configurer.",
  ],
  "ui.commandPalette.sources": ["Sources", "Quellen", "Sources"],
  "ui.commandPalette.environmentUnavailable": [
    "Environment unavailable",
    "Umgebung nicht verfügbar",
    "Environnement indisponible",
  ],
  "ui.commandPalette.selectedEnvironment": [
    "The selected environment",
    "Die ausgewählte Umgebung",
    "L’environnement sélectionné",
  ],
  "ui.commandPalette.environmentNotConnected": [
    "{{environment}} is not connected.",
    "{{environment}} ist nicht verbunden.",
    "{{environment}} n’est pas connecté.",
  ],
  "ui.commandPalette.thisDevice": ["This device", "Dieses Gerät", "Cet appareil"],
  "ui.commandPalette.environments": ["Environments", "Umgebungen", "Environnements"],
  "ui.commandPalette.browseUnavailable": [
    "Unable to browse projects",
    "Projekte können nicht durchsucht werden",
    "Impossible de parcourir les projets",
  ],
  "ui.commandPalette.noEnvironment": [
    "No environment is available.",
    "Keine Umgebung ist verfügbar.",
    "Aucun environnement n’est disponible.",
  ],
  "ui.commandPalette.projects": ["Projects", "Projekte", "Projets"],
  "ui.commandPalette.newThreadIn": ["New thread in", "Neuer Chat in", "Nouvelle discussion dans"],
  "ui.commandPalette.newThreadInMenu": [
    "New thread in…",
    "Neuer Chat in…",
    "Nouvelle discussion dans…",
  ],
  "ui.commandPalette.goToFile": ["Go to file", "Zu Datei wechseln", "Accéder au fichier"],
  "ui.commandPalette.addProject": ["Add project", "Projekt hinzufügen", "Ajouter un projet"],
  "ui.commandPalette.openWslFolder": [
    "Open WSL folder",
    "WSL-Ordner öffnen",
    "Ouvrir un dossier WSL",
  ],
  "ui.commandPalette.toggleThemeEditor": [
    "Toggle theme editor",
    "Theme-Editor umschalten",
    "Afficher ou masquer l’éditeur de thème",
  ],
  "ui.commandPalette.openSettings": [
    "Open settings",
    "Einstellungen öffnen",
    "Ouvrir les réglages",
  ],
  "ui.commandPalette.projectSettings": [
    "Project settings",
    "Projekteinstellungen",
    "Réglages du projet",
  ],
  "ui.commandPalette.failedAddProject": [
    "Failed to add project",
    "Projekt konnte nicht hinzugefügt werden",
    "Impossible d’ajouter le projet",
  ],
  "ui.commandPalette.windowsPathUnsupported": [
    "Windows-style paths are only supported on Windows.",
    "Pfade im Windows-Stil werden nur unter Windows unterstützt.",
    "Les chemins de type Windows ne sont pris en charge que sous Windows.",
  ],
  "ui.commandPalette.relativePathNeedsProject": [
    "Relative paths require an active project.",
    "Relative Pfade erfordern ein aktives Projekt.",
    "Les chemins relatifs nécessitent un projet actif.",
  ],
  "ui.commandPalette.failedOpenProject": [
    "Failed to open project",
    "Projekt konnte nicht geöffnet werden",
    "Impossible d’ouvrir le projet",
  ],
  "ui.commandPalette.errorFallback": [
    "An error occurred.",
    "Ein Fehler ist aufgetreten.",
    "Une erreur s’est produite.",
  ],
  "ui.commandPalette.repositoryLookupFailed": [
    "Repository lookup failed",
    "Repository-Suche fehlgeschlagen",
    "Échec de la recherche du dépôt",
  ],
  "ui.commandPalette.cloneFailed": ["Clone failed", "Klonen fehlgeschlagen", "Échec du clonage"],
  "ui.commandPalette.selectCloneFolder": [
    "Select a folder to clone into",
    "Zielordner zum Klonen auswählen",
    "Sélectionnez un dossier de destination",
  ],
  "ui.commandPalette.createAndClone": ["Create & Clone", "Erstellen und klonen", "Créer et cloner"],
  "ui.commandPalette.clone": ["Clone", "Klonen", "Cloner"],
  "ui.commandPalette.createAndAdd": [
    "Create & Add",
    "Erstellen und hinzufügen",
    "Créer et ajouter",
  ],
  "ui.commandPalette.add": ["Add", "Hinzufügen", "Ajouter"],
  "ui.commandPalette.continue": ["Continue", "Weiter", "Continuer"],
  "ui.commandPalette.lookup": ["Lookup", "Suchen", "Rechercher"],
  "ui.commandPalette.working": ["Working", "Wird verarbeitet", "Traitement"],
  "ui.commandPalette.cloning": ["Cloning", "Wird geklont", "Clonage"],
  "ui.commandPalette.select": ["Select", "Auswählen", "Sélectionner"],
  "ui.commandPalette.openIn": [
    "Open in {{fileManager}}",
    "In {{fileManager}} öffnen",
    "Ouvrir dans {{fileManager}}",
  ],
  "ui.commandPalette.unableRun": [
    "Unable to run command",
    "Befehl konnte nicht ausgeführt werden",
    "Impossible d’exécuter la commande",
  ],
  "ui.commandPalette.unexpectedError": [
    "An unexpected error occurred.",
    "Ein unerwarteter Fehler ist aufgetreten.",
    "Une erreur inattendue s’est produite.",
  ],
  "ui.commandPalette.wslAddFailed": [
    "Could not add WSL project",
    "WSL-Projekt konnte nicht hinzugefügt werden",
    "Impossible d’ajouter le projet WSL",
  ],
  "ui.commandPalette.wslStartBackend": [
    "Start the matching WSL backend, then choose the folder again.",
    "Starte das passende WSL-Backend und wähle den Ordner erneut aus.",
    "Démarrez le serveur WSL correspondant, puis sélectionnez à nouveau le dossier.",
  ],
  "ui.commandPalette.enterCloneUrl": [
    "Enter Git clone URL",
    "Git-Klon-URL eingeben",
    "Saisir l’URL de clonage Git",
  ],
  "ui.commandPalette.enterProviderRepository": [
    "Enter {{provider}} repository ({{path}})",
    "{{provider}}-Repository eingeben ({{path}})",
    "Saisissez le dépôt {{provider}} ({{path}})",
  ],
  "ui.commandPalette.enterCloneUrlHint": [
    "Enter a Git clone URL and press Enter to continue.",
    "Eine Git-Klon-URL eingeben und zum Fortfahren die Eingabetaste drücken.",
    "Saisissez une URL de clonage Git et appuyez sur Entrée pour continuer.",
  ],
  "ui.commandPalette.enterRepositoryHint": [
    "Enter a repository path and press Enter to look it up.",
    "Einen Repository-Pfad eingeben und zum Suchen die Eingabetaste drücken.",
    "Saisissez un chemin de dépôt et appuyez sur Entrée pour le rechercher.",
  ],
  "ui.commandPalette.chooseCloneDestination": [
    "Choose a destination path and press Enter to clone.",
    "Einen Zielpfad auswählen und zum Klonen die Eingabetaste drücken.",
    "Choisissez un chemin de destination et appuyez sur Entrée pour cloner.",
  ],
  "ui.commandPalette.createFolderHint": [
    "Press Enter to create this folder and add it as a project.",
    "Die Eingabetaste drücken, um diesen Ordner zu erstellen und als Projekt hinzuzufügen.",
    "Appuyez sur Entrée pour créer ce dossier et l’ajouter comme projet.",
  ],
  "ui.commandPalette.searchingThreads": [
    "Searching thread messages…",
    "Chatnachrichten werden durchsucht…",
    "Recherche dans les messages…",
  ],
  "ui.commandPalette.searchAllPlaceholder": [
    "Search commands, projects, and threads…",
    "Befehle, Projekte und Chats durchsuchen…",
    "Rechercher des commandes, projets et discussions…",
  ],
  "ui.commandPalette.projectPathPlaceholder": [
    "Enter project path (e.g. ~/projects/my-app)",
    "Projektpfad eingeben (z. B. ~/projects/meine-app)",
    "Saisissez le chemin du projet (par ex. ~/projets/mon-app)",
  ],
  "ui.commandPalette.searchPlaceholder": ["Search…", "Suchen…", "Rechercher…"],
  "ui.commandPalette.pathPlaceholder": [
    "Enter path (e.g. ~/projects/my-app)",
    "Pfad eingeben (z. B. ~/projects/meine-app)",
    "Saisissez le chemin (par ex. ~/projets/mon-app)",
  ],
  "ui.confirm.title": ["Confirm action", "Aktion bestätigen", "Confirmer l’action"],
  "ui.confirm.description": [
    "This action requires your confirmation.",
    "Diese Aktion erfordert eine Bestätigung.",
    "Cette action nécessite votre confirmation.",
  ],
  "ui.confirm.confirm": ["Confirm", "Bestätigen", "Confirmer"],
  "ui.thread.noActive": ["No active thread", "Kein aktiver Chat", "Aucune discussion active"],
  "ui.thread.pickToContinue": [
    "Pick a thread to continue",
    "Chat auswählen, um fortzufahren",
    "Sélectionnez une discussion pour continuer",
  ],
  "ui.thread.selectOrCreate": [
    "Select an existing thread or create a new one to get started.",
    "Einen vorhandenen Chat auswählen oder einen neuen erstellen.",
    "Sélectionnez une discussion existante ou créez-en une nouvelle pour commencer.",
  ],
  "ui.thread.startFailed": [
    "Couldn’t start a new thread",
    "Neuer Chat konnte nicht gestartet werden",
    "Impossible de démarrer une nouvelle discussion",
  ],
  "ui.thread.startFailedDescription": [
    "The project is still available. Try opening the draft again.",
    "Das Projekt ist weiterhin verfügbar. Den Entwurf erneut öffnen.",
    "Le projet est toujours disponible. Essayez de rouvrir le brouillon.",
  ],
  "ui.thread.tryAgain": ["Try again", "Erneut versuchen", "Réessayer"],
  "ui.project.emptyTitle": [
    "What should we work on?",
    "Woran sollen wir arbeiten?",
    "Sur quoi devons-nous travailler ?",
  ],
  "ui.project.emptyDescription": [
    "Add a project to start your first thread.",
    "Ein Projekt hinzufügen, um den ersten Chat zu starten.",
    "Ajoutez un projet pour démarrer votre première discussion.",
  ],
  "ui.project.add": ["Add project", "Projekt hinzufügen", "Ajouter un projet"],
  "ui.rightPanel.openSurface": ["Open a surface", "Ansicht öffnen", "Ouvrir une surface"],
  "ui.rightPanel.chooseSurface": [
    "Choose what to show in the right panel.",
    "Auswählen, was im rechten Panel angezeigt wird.",
    "Choisissez ce qui doit apparaître dans le panneau droit.",
  ],
  "ui.rightPanel.addSurface": [
    "Add panel surface",
    "Panel-Ansicht hinzufügen",
    "Ajouter une surface au panneau",
  ],
  "ui.rightPanel.surface.browser": ["Browser", "Browser", "Navigateur"],
  "ui.rightPanel.surface.terminal": ["Terminal", "Terminal", "Terminal"],
  "ui.rightPanel.surface.files": ["Files", "Dateien", "Fichiers"],
  "ui.rightPanel.surface.diff": ["Diff", "Diff", "Diff"],
  "ui.rightPanel.surface.pullRequest": ["Pull request", "Pull Request", "Demande de tirage"],
  "ui.rightPanel.surface.browserDescription": [
    "Open a local app or URL.",
    "Lokale App oder URL öffnen.",
    "Ouvrir une application locale ou une URL.",
  ],
  "ui.rightPanel.surface.terminalDescription": [
    "Start a shell in this workspace.",
    "Shell in diesem Workspace starten.",
    "Démarrer un shell dans cet espace de travail.",
  ],
  "ui.rightPanel.surface.filesDescription": [
    "Browse and read workspace files.",
    "Workspace-Dateien durchsuchen und lesen.",
    "Parcourir et lire les fichiers de l’espace de travail.",
  ],
  "ui.rightPanel.surface.diffDescription": [
    "Review changes in this thread.",
    "Änderungen in diesem Chat prüfen.",
    "Examiner les modifications de cette discussion.",
  ],
  "ui.rightPanel.surface.pullRequestDescription": [
    "Open this branch's pull request.",
    "Pull Request dieses Branches öffnen.",
    "Ouvrir la demande de tirage de cette branche.",
  ],
  "ui.rightPanel.disabled.browser": [
    "Browser previews are only available in the T3 Code desktop app.",
    "Browser-Vorschauen sind nur in der T3-Code-Desktop-App verfügbar.",
    "Les aperçus du navigateur sont disponibles uniquement dans l’application de bureau T3 Code.",
  ],
  "ui.rightPanel.disabled.terminal": [
    "Terminal surfaces are only available from a project thread.",
    "Terminalansichten sind nur in einem Projektchat verfügbar.",
    "Les surfaces de terminal sont disponibles uniquement depuis une discussion de projet.",
  ],
  "ui.rightPanel.disabled.files": [
    "Files are only available when a project is open.",
    "Dateien sind nur bei geöffnetem Projekt verfügbar.",
    "Les fichiers sont disponibles uniquement lorsqu’un projet est ouvert.",
  ],
  "ui.rightPanel.disabled.diff": [
    "Diff is only available for server threads in Git repositories.",
    "Diffs sind nur für Serverchats in Git-Repositories verfügbar.",
    "Le diff est disponible uniquement pour les discussions serveur dans des dépôts Git.",
  ],
  "ui.rightPanel.disabled.pullRequest": [
    "This thread's branch has no pull request yet.",
    "Der Branch dieses Chats hat noch keinen Pull Request.",
    "La branche de cette discussion ne possède pas encore de demande de tirage.",
  ],
  "ui.rightPanel.disabled.knowledgeGraph": [
    "Update this environment and enable the project Knowledge Graph first.",
    "Aktualisiere diese Umgebung und aktiviere zuerst den Projekt-Wissensgraph.",
    "Mettez à jour cet environnement et activez d’abord le graphe de connaissances du projet.",
  ],
  "ui.rightPanel.hint.browser": [
    "Only available in the desktop app.",
    "Nur in der Desktop-App verfügbar.",
    "Disponible uniquement dans l’application de bureau.",
  ],
  "ui.rightPanel.hint.project": [
    "Available when a project is open.",
    "Bei geöffnetem Projekt verfügbar.",
    "Disponible lorsqu’un projet est ouvert.",
  ],
  "ui.rightPanel.hint.diff": [
    "Available for Git repositories.",
    "Für Git-Repositories verfügbar.",
    "Disponible pour les dépôts Git.",
  ],
  "ui.rightPanel.hint.pullRequest": [
    "No pull request on this branch yet.",
    "Noch kein Pull Request auf diesem Branch.",
    "Aucune demande de tirage sur cette branche.",
  ],
  "ui.rightPanel.hint.knowledgeGraph": [
    "Enable it in Better T3 settings for this environment.",
    "Aktiviere ihn in den Better-T3-Einstellungen dieser Umgebung.",
    "Activez-le dans les réglages Better T3 de cet environnement.",
  ],
  "ui.rightPanel.tab.mute": ["Mute tab", "Tab stummschalten", "Couper le son de l’onglet"],
  "ui.rightPanel.tab.unmute": [
    "Unmute tab",
    "Tab-Stummschaltung aufheben",
    "Rétablir le son de l’onglet",
  ],
  "ui.rightPanel.tab.muteAria": [
    "Mute {{title}}",
    "{{title}} stummschalten",
    "Couper le son de {{title}}",
  ],
  "ui.rightPanel.tab.unmuteAria": [
    "Unmute {{title}}",
    "Stummschaltung von {{title}} aufheben",
    "Rétablir le son de {{title}}",
  ],
  "ui.rightPanel.tab.closeAria": ["Close {{title}}", "{{title}} schließen", "Fermer {{title}}"],
  "ui.rightPanel.menu.copyPath": ["Copy path", "Pfad kopieren", "Copier le chemin"],
  "ui.rightPanel.menu.close": ["Close", "Schließen", "Fermer"],
  "ui.rightPanel.menu.closeOthers": ["Close others", "Andere schließen", "Fermer les autres"],
  "ui.rightPanel.menu.closeRight": ["Close to the right", "Rechts schließen", "Fermer à droite"],
  "ui.rightPanel.menu.closeAll": ["Close all", "Alle schließen", "Tout fermer"],
  "ui.sidebar.title": ["Sidebar", "Seitenleiste", "Barre latérale"],
  "ui.sidebar.description": [
    "Displays the mobile sidebar.",
    "Zeigt die mobile Seitenleiste an.",
    "Affiche la barre latérale mobile.",
  ],
  "ui.sidebar.toggle": [
    "Toggle sidebar",
    "Seitenleiste umschalten",
    "Afficher ou masquer la barre latérale",
  ],
  "ui.quitHold.hint": [
    "Hold {{shortcut}} to Quit",
    "{{shortcut}} gedrückt halten, um zu beenden",
    "Maintenez {{shortcut}} pour quitter",
  ],
  "ui.slowRequests.title": [
    "Some requests are slow",
    "Einige Anfragen sind langsam",
    "Certaines requêtes sont lentes",
  ],
  "ui.slowRequests.description": [
    {
      one: "{{formattedCount}} request has been waiting longer than {{seconds}} seconds.",
      other: "{{formattedCount}} requests have been waiting longer than {{seconds}} seconds.",
    },
    {
      one: "{{formattedCount}} Anfrage wartet seit mehr als {{seconds}} Sekunden.",
      other: "{{formattedCount}} Anfragen warten seit mehr als {{seconds}} Sekunden.",
    },
    {
      one: "{{formattedCount}} requête attend depuis plus de {{seconds}} secondes.",
      other: "{{formattedCount}} requêtes attendent depuis plus de {{seconds}} secondes.",
    },
  ],
  "ui.slowRequests.started": ["Started {{time}}", "Gestartet um {{time}}", "Démarrée à {{time}}"],
  "ui.slowRequests.hide": ["Hide requests", "Anfragen ausblenden", "Masquer les requêtes"],
  "ui.slowRequests.show": ["Show requests", "Anfragen anzeigen", "Afficher les requêtes"],
  "ui.threadStatus.terminalRunning": [
    "Terminal process running",
    "Terminalprozess läuft",
    "Processus de terminal en cours",
  ],
  "ui.threadStatus.worktree": ["Worktree: {{path}}", "Worktree: {{path}}", "Worktree : {{path}}"],
  "ui.threadStatus.worktreeBranch": [
    "Worktree: {{path}} ({{branch}})",
    "Worktree: {{path}} ({{branch}})",
    "Worktree : {{path}} ({{branch}})",
  ],
  "ui.threadStatus.remote": ["Remote", "Remote", "Distant"],
  "ui.threadStatus.open": ["Open", "Offen", "Ouverte"],
  "ui.threadStatus.closed": ["Closed", "Geschlossen", "Fermée"],
  "ui.threadStatus.merged": ["Merged", "Zusammengeführt", "Fusionnée"],
  "ui.threadStatus.changeRequestLabel": [
    "{{name}} {{state}}",
    "{{name}} {{state}}",
    "{{name}} {{state}}",
  ],
  "ui.threadStatus.changeRequestLead": [
    "{{name}} #{{number}} - {{state}}",
    "{{name}} #{{number}} - {{state}}",
    "{{name}} n°{{number}} - {{state}}",
  ],
});

export type UiInterfaceMessageKey = (typeof uiInterfaceCatalog.keys)[number];
