import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const projectIndexingInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "projectIndexing.title": ["Project Indexing", "Projektindexierung", "Indexation du projet"],
  "projectIndexing.globalTitle": [
    "Project Indexing defaults",
    "Voreinstellungen zur Projektindexierung",
    "Réglages par défaut de l’indexation",
  ],
  "projectIndexing.masterEnabled": [
    "Enable project indexing on this environment",
    "Projektindexierung für diese Umgebung aktivieren",
    "Activer l’indexation des projets sur cet environnement",
  ],
  "projectIndexing.masterDescription": [
    "Allow enabled projects to index and update knowledge. Project settings stay saved when this is off.",
    "Freigegebene Projekte können ihren Index erstellen und aktualisieren. Beim Ausschalten bleiben ihre Einstellungen erhalten.",
    "Autorisez les projets activés à créer et actualiser leur index. Leurs réglages restent enregistrés lorsque cette option est désactivée.",
  ],
  "projectIndexing.defaultModel": [
    "Default AI review model",
    "Standardmodell für die KI-Prüfung",
    "Modèle par défaut pour la revue par l’IA",
  ],
  "projectIndexing.defaultModelDescription": [
    "Used only for manually requested AI code reviews when a project has no override.",
    "Wird nur für manuell gestartete KI-Codeprüfungen verwendet, wenn das Projekt kein eigenes Modell hat.",
    "Utilisé uniquement pour les revues de code lancées manuellement si le projet n’a pas de modèle spécifique.",
  ],
  "projectIndexing.projectSettings": [
    "Manage project indexing",
    "Indexierung je Projekt verwalten",
    "Gérer l’indexation par projet",
  ],
  "projectIndexing.projectSettingsDescription": [
    "Choose a project in Projects to enable and manage its local index.",
    "Wähle unter Projekte ein Projekt aus, um seinen lokalen Index zu aktivieren und zu verwalten.",
    "Choisissez un projet dans Projets pour activer et gérer son index local.",
  ],
  "projectIndexing.useDefaultModel": [
    "Use environment default",
    "Standardmodell der Umgebung verwenden",
    "Utiliser le modèle par défaut de l’environnement",
  ],
  "projectIndexing.inheritedModel": [
    "Inherited: {{model}}",
    "Übernommen: {{model}}",
    "Hérité : {{model}}",
  ],
  "projectIndexing.resumeModel": [
    "Resume uses the job’s model: {{model}}",
    "Beim Fortsetzen wird das Modell des laufenden Auftrags verwendet: {{model}}",
    "La reprise utilise le modèle de la tâche : {{model}}",
  ],
  "projectIndexing.resumeModelChanged": [
    "The project override differs from this job’s model. Cancel the job and start a new analysis to use the override.",
    "Das Projektmodell unterscheidet sich vom Modell dieses Auftrags. Brich den Auftrag ab und starte eine neue Analyse, um das Projektmodell zu verwenden.",
    "Le modèle du projet diffère de celui de cette tâche. Annulez la tâche et lancez une nouvelle analyse pour utiliser le modèle du projet.",
  ],
  "projectIndexing.noDefaultModel": [
    "No default AI review model is configured.",
    "Es ist kein Standardmodell für die KI-Prüfung festgelegt.",
    "Aucun modèle par défaut pour la revue par l’IA n’est configuré.",
  ],
  "projectIndexing.masterOff": [
    "Project indexing is disabled for this environment. Enable it in Better T3 → Project Indexing.",
    "Die Projektindexierung ist für diese Umgebung ausgeschaltet. Aktiviere sie unter Better T3 → Projektindexierung.",
    "L’indexation des projets est désactivée pour cet environnement. Activez-la dans Better T3 → Indexation du projet.",
  ],
  "projectIndexing.modelOverrideDescription": [
    "Choose a project override, or use the environment default.",
    "Wähle ein eigenes Modell für dieses Projekt oder übernimm das Standardmodell der Umgebung.",
    "Choisissez un modèle spécifique à ce projet ou utilisez le modèle par défaut de l’environnement.",
  ],
  "projectIndexing.selectProjectFirst": [
    "Select a project to view its indexing settings.",
    "Wähle ein Projekt aus, um seine Indexeinstellungen anzuzeigen.",
    "Sélectionnez un projet pour afficher ses réglages d’indexation.",
  ],
  "projectIndexing.legacyDefaults": [
    "This server supports project indexing settings but not environment defaults.",
    "Dieser Server unterstützt Indexeinstellungen je Projekt, aber noch keine zentralen Voreinstellungen.",
    "Ce serveur prend en charge les réglages d’indexation par projet, mais pas les réglages par défaut de l’environnement.",
  ],
  "projectIndexing.scope": ["Project scope", "Projektbereich", "Périmètre du projet"],
  "projectIndexing.unsupported": [
    "This environment does not support Project Indexing. Update its server to use this feature.",
    "Diese Umgebung unterstützt die Projektindexierung nicht. Aktualisiere ihren Server, um diese Funktion zu nutzen.",
    "Cet environnement ne prend pas en charge l’indexation du projet. Mettez son serveur à jour pour utiliser cette fonction.",
  ],
  "projectIndexing.enabled": [
    "Enable project indexing",
    "Projektindexierung aktivieren",
    "Activer l’indexation du projet",
  ],
  "projectIndexing.enabledDescription": [
    "Keep a local index of source files, symbols, imports, calls, and explicit rules. No model is required.",
    "Lokalen Index für Quelldateien, Symbole, Imports, Aufrufe und ausdrückliche Regeln pflegen. Dafür ist kein Modell nötig.",
    "Conservez un index local des fichiers, symboles, imports, appels et règles explicites. Aucun modèle n’est requis.",
  ],
  "projectIndexing.model": ["AI review model", "Modell für KI-Prüfung", "Modèle de revue par l’IA"],
  "projectIndexing.modelDescription": [
    "Used only when you explicitly start an AI review of code changes.",
    "Wird nur verwendet, wenn du ausdrücklich eine KI-Prüfung von Codeänderungen startest.",
    "Utilisé uniquement lorsque vous lancez explicitement une revue des modifications par l’IA.",
  ],
  "projectIndexing.chooseModel": ["Choose a model", "Modell auswählen", "Choisir un modèle"],
  "projectIndexing.modelUnavailable": ["Unavailable", "Nicht verfügbar", "Indisponible"],
  "projectIndexing.modelRequired": [
    "Choose a model before starting an AI review.",
    "Wähle vor einer KI-Prüfung ein Modell aus.",
    "Choisissez un modèle avant de lancer une revue par l’IA.",
  ],
  "projectIndexing.checkingModel": [
    "Checking model support…",
    "Modellunterstützung wird geprüft…",
    "Vérification de la prise en charge du modèle…",
  ],
  "projectIndexing.modelUnsupported": [
    "This model cannot run the optional AI review.",
    "Dieses Modell kann die optionale KI-Prüfung nicht ausführen.",
    "Ce modèle ne peut pas effectuer la revue facultative par l’IA.",
  ],
  "projectIndexing.checkModelAgain": [
    "Check model support again",
    "Modellunterstützung erneut prüfen",
    "Revérifier la prise en charge du modèle",
  ],
  "projectIndexing.automaticAiUpdate": [
    "Automatic AI Update",
    "Automatische KI-Aktualisierung",
    "Mise à jour automatique par l’IA",
  ],
  "projectIndexing.automaticAiUpdateDescription": [
    "After the first analysis, update AI knowledge when project files change. This is independent of enabling the index.",
    "Nach der ersten Analyse das KI-Wissen aktualisieren, wenn sich Projektdateien ändern. Diese Einstellung ist unabhängig von der Aktivierung des Index.",
    "Après la première analyse, actualisez les connaissances de l’IA lorsque les fichiers du projet changent. Ce réglage est indépendant de l’activation de l’index.",
  ],
  "projectIndexing.reviewEnabled": [
    "AI diff review",
    "KI-Prüfung von Änderungen",
    "Revue des modifications par l’IA",
  ],
  "projectIndexing.enableReview": [
    "Enable code review",
    "Codeprüfung aktivieren",
    "Activer la revue de code",
  ],
  "projectIndexing.reviewEnabledDescription": [
    "Enable manual code-change reviews using the project's index and the actual source diff.",
    "Manuell gestartete Prüfungen von Codeänderungen anhand des Projektindex und der tatsächlichen Quellcodeänderungen aktivieren.",
    "Activez les revues de code lancées manuellement à partir de l’index du projet et des modifications réelles du code source.",
  ],
  "projectIndexing.loading": [
    "Loading project index…",
    "Projektindex wird geladen…",
    "Chargement de l’index du projet…",
  ],
  "projectIndexing.retry": ["Retry", "Erneut versuchen", "Réessayer"],
  "projectIndexing.analyze": ["Index project", "Projekt indizieren", "Indexer le projet"],
  "projectIndexing.retryIndexing": [
    "Try indexing again",
    "Indexierung erneut starten",
    "Relancer l’indexation",
  ],
  "projectIndexing.resumeIndexing": [
    "Resume indexing",
    "Indexierung fortsetzen",
    "Reprendre l’indexation",
  ],
  "projectIndexing.staticFacts": [
    "{{files}} files · {{symbols}} index entries · {{imports}} imports · {{calls}} calls",
    "{{files}} Dateien · {{symbols}} Indexeinträge · {{imports}} Imports · {{calls}} Aufrufe",
    "{{files}} fichiers · {{symbols}} entrées d’index · {{imports}} imports · {{calls}} appels",
  ],
  "projectIndexing.staticRelationships": [
    "Static call relationships",
    "Statische Aufrufbeziehungen",
    "Relations d’appel statiques",
  ],
  "projectIndexing.staticRelationshipsHint": [
    "Confirmed source relationships do not prove runtime execution order.",
    "Bestätigte Quellcodebeziehungen belegen keine Ausführungsreihenfolge zur Laufzeit.",
    "Les relations confirmées dans le code ne prouvent pas l’ordre d’exécution à l’exécution.",
  ],
  "projectIndexing.staticPackages": ["Packages", "Pakete", "Paquets"],
  "projectIndexing.staticDependencies": ["Dependencies", "Abhängigkeiten", "Dépendances"],
  "projectIndexing.staticSources": ["Source locations", "Quellstellen", "Emplacements source"],
  "projectIndexing.staticRules": ["Explicit rules", "Ausdrückliche Regeln", "Règles explicites"],
  "projectIndexing.imports": ["Imports", "Imports", "Imports"],
  "projectIndexing.importResolution.workspace": [
    "Workspace file",
    "Datei im Projekt",
    "Fichier du projet",
  ],
  "projectIndexing.importResolution.external": [
    "External package",
    "Externes Paket",
    "Paquet externe",
  ],
  "projectIndexing.importResolution.unresolved": ["Unresolved", "Nicht aufgelöst", "Non résolu"],
  "projectIndexing.resolvedImports": [
    "{{resolved}} / {{total}} imports resolved to project files",
    "{{resolved}} / {{total}} Imports auf Projektdateien aufgelöst",
    "{{resolved}} / {{total}} imports résolus vers des fichiers du projet",
  ],
  "projectIndexing.reviewModel": [
    "AI review model",
    "Modell für KI-Prüfung",
    "Modèle de revue par l’IA",
  ],
  "projectIndexing.reviewModelDescription": [
    "Used only when you explicitly start a code review. Indexing runs locally without it.",
    "Wird nur bei ausdrücklich gestarteten Codeprüfungen verwendet. Die Indexierung läuft ohne Modell lokal.",
    "Utilisé uniquement pour les revues de code lancées explicitement. L’indexation locale n’en a pas besoin.",
  ],
  "projectIndexing.updateServer": [
    "Update the server to use model-free project indexing.",
    "Aktualisiere den Server für die modellfreie Projektindexierung.",
    "Mettez le serveur à jour pour utiliser l’indexation du projet sans modèle.",
  ],
  "projectIndexing.callsites": ["Calls", "Aufrufe", "Appels"],
  "projectIndexing.rebuild": ["Rebuild index", "Index neu aufbauen", "Reconstruire l’index"],
  "projectIndexing.pause": ["Pause", "Pausieren", "Suspendre"],
  "projectIndexing.resume": ["Resume", "Fortsetzen", "Reprendre"],
  "projectIndexing.cancel": ["Cancel job", "Auftrag abbrechen", "Annuler la tâche"],
  "projectIndexing.clear": ["Clear index", "Index löschen", "Effacer l’index"],
  "projectIndexing.clearTitle": [
    "Clear this project's index?",
    "Index dieses Projekts löschen?",
    "Effacer l’index de ce projet ?",
  ],
  "projectIndexing.clearDescription": [
    "Remove the index for {{project}} on {{environment}}. Project files and conversation history are preserved. Analysis can build it again.",
    "Den Index für {{project}} in {{environment}} entfernen. Projektdateien und Gesprächsverlauf bleiben erhalten. Eine neue Analyse kann den Index wieder aufbauen.",
    "Supprimez l’index de {{project}} sur {{environment}}. Les fichiers du projet et l’historique des conversations sont conservés. Une analyse pourra le reconstruire.",
  ],
  "projectIndexing.rebuildTitle": [
    "Rebuild this project's index?",
    "Index dieses Projekts neu aufbauen?",
    "Reconstruire l’index de ce projet ?",
  ],
  "projectIndexing.rebuildDescription": [
    "Rebuild the local index for {{project}} on {{environment}} from its current files.",
    "Den lokalen Index für {{project}} in {{environment}} aus den aktuellen Dateien neu aufbauen.",
    "Reconstruisez l’index local de {{project}} sur {{environment}} à partir de ses fichiers actuels.",
  ],
  "projectIndexing.files": ["Files indexed", "Indexierte Dateien", "Fichiers indexés"],
  "projectIndexing.chatFileProgress": [
    "{{indexed}} / {{eligible}} files",
    "{{indexed}} / {{eligible}} Dateien",
    "{{indexed}} / {{eligible}} fichiers",
  ],
  "projectIndexing.entities": ["Entities", "Entitäten", "Entités"],
  "projectIndexing.semanticCoverage": ["AI analysis", "KI-Analyse", "Analyse par l’IA"],
  "projectIndexing.preparingAnalysis": [
    "Preparing analysis batches…",
    "Analysepakte werden vorbereitet…",
    "Préparation des lots d’analyse…",
  ],
  "projectIndexing.analysisUnitsProgress": [
    "{{completed}} / {{total}} analysis units",
    "{{completed}} / {{total}} Analyseeinheiten",
    "{{completed}} / {{total}} unités d’analyse",
  ],
  "projectIndexing.discoveredProgress": [
    "{{count}} files found",
    "{{count}} Dateien gefunden",
    "{{count}} fichiers trouvés",
  ],
  "projectIndexing.indexSummary": [
    "{{files}} files · {{entities}} entities",
    "{{files}} Dateien · {{entities}} Entitäten",
    "{{files}} fichiers · {{entities}} entités",
  ],
  "projectIndexing.indexDetails": ["Index details", "Indexdetails", "Détails de l’index"],
  "projectIndexing.coverageAfterRun": [
    "Calculated when analysis finishes",
    "Wird nach Abschluss berechnet",
    "Calculée à la fin de l’analyse",
  ],
  "projectIndexing.options": ["Options", "Optionen", "Options"],
  "projectIndexing.maintenance": ["Maintenance", "Verwaltung", "Maintenance"],
  "projectIndexing.compactState.discovering": ["Scanning", "Erfassen", "Inventaire"],
  "projectIndexing.compactState.extracting": ["Extracting", "Extrahieren", "Extraction"],
  "projectIndexing.compactState.resolving": ["Resolving", "Verknüpfen", "Résolution"],
  "projectIndexing.resolutionProgress": [
    "Files extracted. Checking relationships: {{resolved}} calls resolved · {{candidates}} candidates.",
    "Dateien extrahiert. Beziehungen werden geprüft: {{resolved}} Aufrufe aufgelöst · {{candidates}} Kandidaten.",
    "Fichiers extraits. Vérification des relations : {{resolved}} appels résolus · {{candidates}} candidats.",
  ],
  "projectIndexing.compactState.analyzing": ["Analyzing", "Analysieren", "Analyse"],
  "projectIndexing.compactState.waiting-for-provider": [
    "Waiting for model",
    "Warten auf Modell",
    "Attente du modèle",
  ],
  "projectIndexing.compactState.waiting-for-resources": [
    "Waiting for resources",
    "Warten auf Ressourcen",
    "Attente de ressources",
  ],
  "projectIndexing.compactState.updating": ["Saving", "Speichern", "Enregistrement"],
  "projectIndexing.updatedAt": ["Updated {{time}}", "Aktualisiert {{time}}", "Mis à jour {{time}}"],
  "projectIndexing.disabledHint": [
    "Indexing is off. Existing indexed data is preserved until you clear it.",
    "Die Indexierung ist ausgeschaltet. Bereits indexierte Daten bleiben erhalten, bis du sie löschst.",
    "L’indexation est désactivée. Les données déjà indexées sont conservées jusqu’à leur suppression.",
  ],
  "projectIndexing.noIndex": [
    "No index yet. Select Index project to build one locally.",
    "Noch kein Index vorhanden. Wähle „Projekt indizieren“, um ihn lokal zu erstellen.",
    "Aucun index pour le moment. Sélectionnez Indexer le projet pour le créer localement.",
  ],
  "projectIndexing.callsiteCoverage": [
    "Calls: {{resolved}} resolved · {{candidate}} candidates · {{unresolved}} unresolved.",
    "Aufrufe: {{resolved}} aufgelöst · {{candidate}} Kandidaten · {{unresolved}} nicht aufgelöst.",
    "Appels : {{resolved}} résolus · {{candidate}} candidats · {{unresolved}} non résolus.",
  ],
  "projectIndexing.fileGaps": [
    "{{skipped}} paths excluded · {{failed}} files failed.",
    "{{skipped}} Pfade ausgeschlossen · {{failed}} Dateien fehlgeschlagen.",
    "{{skipped}} chemins exclus · {{failed}} fichiers en échec.",
  ],
  "projectIndexing.gaps": [
    "Known gaps ({{count}})",
    "Bekannte Lücken ({{count}})",
    "Lacunes connues ({{count}})",
  ],
  "projectIndexing.reportedIssues": [
    "{{count}} reported issues",
    "{{count}} gemeldete Probleme",
    "{{count}} problèmes signalés",
  ],
  "projectIndexing.reportedIssue": ["Reported issue", "Gemeldetes Problem", "Problème signalé"],
  "projectIndexing.moreGaps": [
    "{{count}} more gaps are recorded in the index.",
    "{{count}} weitere Lücken sind im Index erfasst.",
    "{{count}} autres lacunes sont consignées dans l’index.",
  ],
  "projectIndexing.unitProgress": [
    "Analysis units: {{completed}} completed · {{pending}} pending · {{failed}} failed · {{stale}} stale.",
    "Analyseeinheiten: {{completed}} abgeschlossen · {{pending}} ausstehend · {{failed}} fehlgeschlagen · {{stale}} veraltet.",
    "Unités d’analyse : {{completed}} terminées · {{pending}} en attente · {{failed}} en échec · {{stale}} obsolètes.",
  ],
  "projectIndexing.state.disabled": [
    "Indexing disabled",
    "Indexierung deaktiviert",
    "Indexation désactivée",
  ],
  "projectIndexing.state.idle": [
    "Ready to index",
    "Bereit zur Indexierung",
    "Prêt pour l’indexation",
  ],
  "projectIndexing.state.queued": [
    "Indexing queued",
    "Indexierung vorgemerkt",
    "Indexation en attente",
  ],
  "projectIndexing.state.discovering": [
    "Discovering project files",
    "Projektdateien werden erfasst",
    "Recherche des fichiers du projet",
  ],
  "projectIndexing.state.extracting": [
    "Extracting source entities",
    "Quellcode-Entitäten werden extrahiert",
    "Extraction des entités du code source",
  ],
  "projectIndexing.state.analyzing": [
    "Analyzing project behavior",
    "Projektverhalten wird analysiert",
    "Analyse du comportement du projet",
  ],
  "projectIndexing.state.resolving": [
    "Resolving source relationships",
    "Quellcode-Beziehungen werden aufgelöst",
    "Résolution des relations du code source",
  ],
  "projectIndexing.state.updating": [
    "Updating project knowledge",
    "Projektwissen wird aktualisiert",
    "Mise à jour des connaissances du projet",
  ],
  "projectIndexing.state.partial": [
    "Partial index · review known gaps",
    "Unvollständiger Index · bekannte Lücken prüfen",
    "Index partiel · vérifiez les lacunes connues",
  ],
  "projectIndexing.state.waiting-for-provider": [
    "Waiting for the selected provider",
    "Warten auf den ausgewählten Provider",
    "En attente du fournisseur sélectionné",
  ],
  "projectIndexing.state.waiting-for-resources": [
    "Waiting for resources",
    "Warten auf Ressourcen",
    "En attente de ressources",
  ],
  "projectIndexing.state.ready": ["Index ready", "Index bereit", "Index prêt"],
  "projectIndexing.state.paused": [
    "Indexing paused",
    "Indexierung pausiert",
    "Indexation suspendue",
  ],
  "projectIndexing.state.cancelled": [
    "Indexing cancelled",
    "Indexierung abgebrochen",
    "Indexation annulée",
  ],
  "projectIndexing.state.failed": [
    "Indexing failed",
    "Indexierung fehlgeschlagen",
    "Échec de l’indexation",
  ],
  "projectIndexing.failedSummary": [
    "The latest run stopped before completion. These counts may include unpublished work.",
    "Der letzte Lauf wurde vorzeitig beendet. Diese Zahlen können noch unveröffentlichte Daten enthalten.",
    "La dernière exécution s’est arrêtée avant la fin. Ces chiffres peuvent inclure des données non publiées.",
  ],
  "projectIndexing.graph": ["Knowledge Graph", "Wissensgraph", "Graphe de connaissances"],
  "projectIndexing.graphDescription": [
    "Explore the files, symbols, and connections in your project index.",
    "Erkunde Dateien, Symbole und Verbindungen deines Projektindex.",
    "Explorez les fichiers, symboles et connexions de votre index de projet.",
  ],
  "projectIndexing.graphMap": ["Project map", "Projektübersicht", "Carte du projet"],
  "projectIndexing.graphOverviewCount": [
    "{{files}} files · {{nodes}} nodes · {{relationships}} connections",
    "{{files}} Dateien · {{nodes}} Knoten · {{relationships}} Verbindungen",
    "{{files}} fichiers · {{nodes}} nœuds · {{relationships}} connexions",
  ],
  "projectIndexing.graphDirectory": ["Folder", "Ordner", "Dossier"],
  "projectIndexing.graphRoot": ["Project", "Projekt", "Projet"],
  "projectIndexing.graphUp": ["Up one level", "Eine Ebene höher", "Niveau supérieur"],
  "projectIndexing.graphFileCount": ["{{count}} files", "{{count}} Dateien", "{{count}} fichiers"],
  "projectIndexing.graphFilesOmitted": [
    "{{count}} files are outside the visible groups. Open a folder or search to explore further.",
    "{{count}} Dateien liegen außerhalb der sichtbaren Gruppen. Öffne einen Ordner oder nutze die Suche.",
    "{{count}} fichiers sont hors des groupes visibles. Ouvrez un dossier ou utilisez la recherche.",
  ],
  "projectIndexing.graphOverviewLegend": [
    "Expand folders and files in place; select them again to collapse. Dashed links show containment. Arrows show resolved imports and calls, not runtime execution. The map reflects the published index.",
    "Klappe Ordner und Dateien direkt im Graphen auf und durch erneutes Klicken wieder zu. Gestrichelte Linien zeigen die Zugehörigkeit. Pfeile zeigen aufgelöste Imports und Aufrufe, keine Laufzeitausführung. Die Karte zeigt den veröffentlichten Index.",
    "Dépliez les dossiers et fichiers sur place ; cliquez à nouveau pour les replier. Les liens pointillés indiquent l’appartenance. Les flèches montrent les imports et appels résolus, pas l’exécution. La carte reflète l’index publié.",
  ],
  "projectIndexing.graphExpand": ["Expand branch", "Zweig aufklappen", "Déplier la branche"],
  "projectIndexing.graphCollapse": ["Collapse branch", "Zweig zuklappen", "Replier la branche"],
  "projectIndexing.graphHierarchy": ["Contains", "Enthält", "Contient"],
  "projectIndexing.graphLoadingBranch": [
    "Loading {{path}}…",
    "{{path}} wird geladen…",
    "Chargement de {{path}}…",
  ],
  "projectIndexing.graphBranchUnavailable": [
    "This folder is unavailable in this snapshot. Refresh results and try again.",
    "Dieser Ordner ist in diesem Indexstand nicht verfügbar. Aktualisiere die Ergebnisse und versuche es erneut.",
    "Ce dossier est indisponible dans cet instantané. Actualisez les résultats et réessayez.",
  ],
  "projectIndexing.graphNoSymbols": [
    "This file has no symbols in the current results.",
    "Diese Datei hat in den aktuellen Ergebnissen keine Symbole.",
    "Ce fichier n’a pas de symboles dans les résultats actuels.",
  ],
  "projectIndexing.graphExpandLimit": [
    "Showing a limited set of nodes. Collapse a branch to make room, or search for a file or symbol.",
    "Es wird eine begrenzte Auswahl gezeigt. Klappe einen Zweig zu, um Platz zu schaffen, oder suche nach einer Datei oder einem Symbol.",
    "Le nombre de nœuds affichés est limité. Repliez une branche ou recherchez un fichier ou un symbole.",
  ],
  "projectIndexing.graphSymbols": ["Symbols", "Symbole", "Symboles"],
  "projectIndexing.graphTypes": ["Types", "Typen", "Types"],
  "projectIndexing.graphZoomIn": ["Zoom in", "Vergrößern", "Zoom avant"],
  "projectIndexing.graphZoomOut": ["Zoom out", "Verkleinern", "Zoom arrière"],
  "projectIndexing.graphFit": ["Fit graph", "Graph einpassen", "Ajuster le graphe"],
  "projectIndexing.graphNavigation": [
    "Drag to pan · Scroll to zoom · Select to explore",
    "Ziehen zum Verschieben · Scrollen zum Zoomen · Auswählen zum Erkunden",
    "Glisser pour déplacer · Défiler pour zoomer · Sélectionner pour explorer",
  ],
  "projectIndexing.graphRelationships": [
    "Reading this map",
    "Diese Karte lesen",
    "Lire cette carte",
  ],
  "projectIndexing.graphResults": [
    "Browse {{count}} symbols",
    "{{count}} Symbole durchsuchen",
    "Parcourir {{count}} symboles",
  ],
  "projectIndexing.clearSearch": ["Clear search", "Suche zurücksetzen", "Effacer la recherche"],
  "projectIndexing.showingOverview": [
    "The map above still shows the project overview.",
    "Die Karte oben zeigt weiterhin die Projektübersicht.",
    "La carte ci-dessus affiche toujours la vue d’ensemble du projet.",
  ],
  "projectIndexing.searchHelp": [
    "Try a file path or the beginning of a symbol name. Include stale results to find recently changed sources.",
    "Versuche einen Dateipfad oder den Anfang eines Symbolnamens. Beziehe veraltete Ergebnisse ein, um kürzlich geänderte Quellen zu finden.",
    "Essayez un chemin de fichier ou le début d’un nom de symbole. Incluez les résultats obsolètes pour retrouver les sources récemment modifiées.",
  ],
  "projectIndexing.graphLegend": [
    "Solid: resolved calls · Dashed: candidates · Dotted: contains",
    "Durchgezogen: aufgelöste Aufrufe · Gestrichelt: Kandidaten · Gepunktet: enthält",
    "Trait plein : appels résolus · Tirets : candidats · Pointillés : contient",
  ],
  "projectIndexing.graphMapLegend": [
    "Solid: resolved calls · Blue: imports · Dashed: candidates · Dotted: contains · Hollow nodes: older or unverified source",
    "Durchgezogen: aufgelöste Aufrufe · Blau: Imports · Gestrichelt: Kandidaten · Gepunktet: enthält · Hohle Knoten: ältere oder ungeprüfte Quelle",
    "Trait plein : appels résolus · Bleu : imports · Tirets : candidats · Pointillés : contient · Nœuds creux : source ancienne ou non vérifiée",
  ],
  "projectIndexing.graphCount": [
    "{{entities}} entities · {{relationships}} relationships",
    "{{entities}} Entitäten · {{relationships}} Beziehungen",
    "{{entities}} entités · {{relationships}} relations",
  ],
  "projectIndexing.graphOmitted": [
    "{{count}} additional entities are listed below. Search to narrow the graph.",
    "{{count}} weitere Entitäten sind unten aufgeführt. Grenze den Graphen mit der Suche ein.",
    "{{count}} entités supplémentaires sont listées ci-dessous. Utilisez la recherche pour réduire le graphe.",
  ],
  "projectIndexing.graphRelationshipsOmitted": [
    "Some relationships are omitted from this bounded view.",
    "Einige Beziehungen fehlen in dieser begrenzten Ansicht.",
    "Certaines relations sont omises dans cette vue limitée.",
  ],
  "projectIndexing.freshness.current": ["Current", "Aktuell", "À jour"],
  "projectIndexing.freshness.stale": ["Stale", "Veraltet", "Obsolète"],
  "projectIndexing.freshness.missing": ["Source missing", "Quelle fehlt", "Source manquante"],
  "projectIndexing.freshness.unknown": [
    "Freshness unknown",
    "Aktualität unbekannt",
    "Actualité non vérifiée",
  ],
  "projectIndexing.verification.title": ["Verification", "Nachweise", "Vérification"],
  "projectIndexing.verification.contextProvided": [
    "Project context provided",
    "Projektkontext bereitgestellt",
    "Contexte du projet fourni",
  ],
  "projectIndexing.verification.sourceHashes": [
    "Source hashes: {{matched}} matched · {{changed}} changed · {{missing}} missing · {{unverified}} unverified",
    "Quellcode-Hashes: {{matched}} übereinstimmend · {{changed}} geändert · {{missing}} fehlend · {{unverified}} ungeprüft",
    "Empreintes des sources : {{matched}} identiques · {{changed}} modifiées · {{missing}} absentes · {{unverified}} non vérifiées",
  ],
  "projectIndexing.verification.sourceState.complete": [
    "Source hashes checked",
    "Quellcode-Hashes geprüft",
    "Empreintes des sources vérifiées",
  ],
  "projectIndexing.verification.sourceState.partial": [
    "Source comparison incomplete",
    "Quellcodeabgleich unvollständig",
    "Comparaison des sources incomplète",
  ],
  "projectIndexing.verification.sourceState.unavailable": [
    "Source comparison unavailable",
    "Quellcodeabgleich nicht verfügbar",
    "Comparaison des sources indisponible",
  ],
  "projectIndexing.verification.checksNotRun": [
    "Indexing did not run tests or other checks.",
    "Die Indexierung hat keine Tests oder anderen Prüfungen ausgeführt.",
    "L’indexation n’a exécuté aucun test ni autre contrôle.",
  ],
  "projectIndexing.verification.unavailable": [
    "This result does not report verification evidence.",
    "Dieses Ergebnis enthält keine Angaben zu erfolgten Prüfungen.",
    "Ce résultat ne fournit aucune preuve de vérification.",
  ],
  "projectIndexing.descriptions": ["Modules and flows", "Module und Abläufe", "Modules et flux"],
  "projectIndexing.modules": ["Modules", "Module", "Modules"],
  "projectIndexing.flows": ["Flows", "Abläufe", "Flux"],
  "projectIndexing.descriptionCount": [
    "{{modules}} modules · {{flows}} flows",
    "{{modules}} Module · {{flows}} Abläufe",
    "{{modules}} modules · {{flows}} flux",
  ],
  "projectIndexing.descriptionsOmitted": [
    "Showing {{shown}} of {{total}} descriptions in this result.",
    "{{shown}} von {{total}} Beschreibungen dieses Ergebnisses werden angezeigt.",
    "{{shown}} descriptions sur {{total}} sont affichées dans ce résultat.",
  ],
  "projectIndexing.relatedEntities": [
    "Related entities",
    "Zugehörige Entitäten",
    "Entités associées",
  ],
  "projectIndexing.flowSteps": ["Flow steps", "Ablaufschritte", "Étapes du flux"],
  "projectIndexing.stepsOmitted": [
    "{{count}} more steps are recorded.",
    "{{count}} weitere Schritte sind erfasst.",
    "{{count}} étapes supplémentaires sont enregistrées.",
  ],
  "projectIndexing.reviewSource.before": [
    "Before change",
    "Vor der Änderung",
    "Avant la modification",
  ],
  "projectIndexing.reviewSource.after": [
    "After change",
    "Nach der Änderung",
    "Après la modification",
  ],
  "projectIndexing.reviewSource.excerpt": [
    "Source excerpt from diff",
    "Quellcodeauszug aus dem Diff",
    "Extrait du code source du diff",
  ],
  "projectIndexing.provenance.parser": [
    "Parser evidence",
    "Parser-Beleg",
    "Preuve issue de l’analyseur syntaxique",
  ],
  "projectIndexing.provenance.compiler": [
    "Compiler evidence",
    "Compiler-Beleg",
    "Preuve issue du compilateur",
  ],
  "projectIndexing.provenance.llm": ["AI analysis", "KI-Analyse", "Analyse par l’IA"],
  "projectIndexing.provenance.manual": ["Manual evidence", "Manueller Beleg", "Preuve manuelle"],
  "projectIndexing.kind.file": ["File", "Datei", "Fichier"],
  "projectIndexing.kind.class": ["Class", "Klasse", "Classe"],
  "projectIndexing.kind.interface": ["Interface", "Schnittstelle", "Interface"],
  "projectIndexing.kind.method": ["Method", "Methode", "Méthode"],
  "projectIndexing.kind.function": ["Function", "Funktion", "Fonction"],
  "projectIndexing.kind.constructor": ["Constructor", "Konstruktor", "Constructeur"],
  "projectIndexing.kind.property": ["Property", "Eigenschaft", "Propriété"],
  "projectIndexing.kind.variable": ["Variable", "Variable", "Variable"],
  "projectIndexing.kind.type": ["Type", "Typ", "Type"],
  "projectIndexing.kind.namespace": ["Namespace", "Namensraum", "Espace de noms"],
  "projectIndexing.kind.module": ["Module", "Modul", "Module"],
  "projectIndexing.kind.enum": ["Enum", "Aufzählung", "Énumération"],
  "projectIndexing.kind.initializer": ["Initializer", "Initialisierer", "Initialiseur"],
  "projectIndexing.kind.lambda": ["Lambda", "Lambda", "Lambda"],
  "projectIndexing.resolution.resolved": ["Resolved", "Aufgelöst", "Résolu"],
  "projectIndexing.resolution.candidate": ["Candidate", "Kandidat", "Candidat"],
  "projectIndexing.resolution.unresolved": ["Unresolved", "Nicht aufgelöst", "Non résolu"],
  "projectIndexing.no.callers": [
    "No callers are recorded in this result.",
    "Dieses Ergebnis enthält keine Aufrufer.",
    "Aucun appelant n’est enregistré dans ce résultat.",
  ],
  "projectIndexing.no.callees": [
    "No calls are recorded in this result.",
    "Dieses Ergebnis enthält keine Aufrufe.",
    "Aucun appel n’est enregistré dans ce résultat.",
  ],
  "projectIndexing.container": [
    "Defined in {{name}}",
    "Definiert in {{name}}",
    "Défini dans {{name}}",
  ],
  "projectIndexing.loadContainer": [
    "Load containing entity",
    "Übergeordnete Entität laden",
    "Charger l’entité parente",
  ],
  "projectIndexing.behavior": ["Behavior", "Verhalten", "Comportement"],
  "projectIndexing.noBehavior": [
    "No AI behavior analysis is available for this entity yet.",
    "Für diese Entität liegt noch keine KI-Verhaltensanalyse vor.",
    "Aucune analyse du comportement par l’IA n’est encore disponible pour cette entité.",
  ],
  "projectIndexing.behaviorNotIncluded": [
    "No behavior analysis is included in this bounded result.",
    "Dieses begrenzte Ergebnis enthält keine Verhaltensanalyse.",
    "Ce résultat limité ne contient aucune analyse du comportement.",
  ],
  "projectIndexing.loadMoreContext": [
    "Load more entity context",
    "Weiteren Entitätskontext laden",
    "Charger davantage de contexte pour l’entité",
  ],
  "projectIndexing.inputs": ["Inputs", "Eingaben", "Entrées"],
  "projectIndexing.outputs": ["Outputs", "Ausgaben", "Sorties"],
  "projectIndexing.sideEffects": ["Side effects", "Seiteneffekte", "Effets de bord"],
  "projectIndexing.errorPaths": ["Error paths", "Fehlerpfade", "Chemins d’erreur"],
  "projectIndexing.invariants": ["Invariants", "Invarianten", "Invariants"],
  "projectIndexing.callers": ["Callers", "Aufrufer", "Appelants"],
  "projectIndexing.callees": ["Callees", "Aufgerufene Funktionen", "Fonctions appelées"],
  "projectIndexing.detailTruncated": [
    "This detail is bounded. Additional relationships or evidence may be omitted.",
    "Diese Detailansicht ist begrenzt. Weitere Beziehungen oder Belege können fehlen.",
    "Cette vue détaillée est limitée. Des relations ou des preuves supplémentaires peuvent être omises.",
  ],
  "projectIndexing.evidence": ["Source evidence", "Quellcodebelege", "Preuves dans le code source"],
  "projectIndexing.loadingEntity": [
    "Loading entity and call relationships…",
    "Entität und Aufrufbeziehungen werden geladen…",
    "Chargement de l’entité et des relations d’appel…",
  ],
  "projectIndexing.entityUnavailable": [
    "This entity is no longer available in the current index. Refresh or search for its current name.",
    "Diese Entität ist im aktuellen Index nicht mehr verfügbar. Aktualisiere die Ansicht oder suche nach ihrem aktuellen Namen.",
    "Cette entité n’est plus disponible dans l’index actuel. Actualisez la vue ou recherchez son nom actuel.",
  ],
  "projectIndexing.search": [
    "Search indexed entities",
    "Indexierte Entitäten durchsuchen",
    "Rechercher dans les entités indexées",
  ],
  "projectIndexing.searchPlaceholder": [
    "Search classes, methods, functions, and files…",
    "Klassen, Methoden, Funktionen und Dateien suchen…",
    "Rechercher des classes, méthodes, fonctions et fichiers…",
  ],
  "projectIndexing.includeStale": [
    "Include stale results",
    "Veraltete Ergebnisse einbeziehen",
    "Inclure les résultats obsolètes",
  ],
  "projectIndexing.loadingEntities": [
    "Loading indexed entities…",
    "Indexierte Entitäten werden geladen…",
    "Chargement des entités indexées…",
  ],
  "projectIndexing.noResults": [
    "No indexed entities match this search.",
    "Keine indexierten Entitäten passen zu dieser Suche.",
    "Aucune entité indexée ne correspond à cette recherche.",
  ],
  "projectIndexing.noEntities": [
    "No source symbols are available in this index.",
    "In diesem Index sind keine Quellcode-Symbole verfügbar.",
    "Aucun symbole source n’est disponible dans cet index.",
  ],
  "projectIndexing.noSearchableIndex": [
    "No searchable index yet",
    "Noch kein durchsuchbarer Index",
    "Aucun index consultable pour le moment",
  ],
  "projectIndexing.noSearchableIndexHint": [
    "Finish indexing to search files, symbols, and relationships here.",
    "Schließe die Indexierung ab, um hier Dateien, Symbole und Beziehungen zu durchsuchen.",
    "Terminez l’indexation pour rechercher ici des fichiers, des symboles et des relations.",
  ],
  "projectIndexing.queryTruncated": [
    "Showing a bounded result. Use search or the next page for more entities.",
    "Ein begrenztes Ergebnis wird angezeigt. Nutze die Suche oder die nächste Seite für weitere Entitäten.",
    "Le résultat affiché est limité. Utilisez la recherche ou la page suivante pour voir d’autres entités.",
  ],
  "projectIndexing.firstPage": ["First page", "Erste Seite", "Première page"],
  "projectIndexing.nextPage": ["Next page", "Nächste Seite", "Page suivante"],
  "projectIndexing.refreshResults": [
    "Refresh results",
    "Ergebnisse aktualisieren",
    "Actualiser les résultats",
  ],
  "projectIndexing.usage.complete": [
    "Measured model usage",
    "Gemessene Modellnutzung",
    "Utilisation mesurée du modèle",
  ],
  "projectIndexing.usage.partial": [
    "Partial model usage reported",
    "Modellnutzung teilweise gemeldet",
    "Utilisation du modèle partiellement rapportée",
  ],
  "projectIndexing.usage.unavailable": [
    "Token usage unavailable",
    "Tokennutzung nicht verfügbar",
    "Utilisation des jetons indisponible",
  ],
  "projectIndexing.inputTokens": [
    "{{count}} input tokens",
    "{{count}} Eingabe-Token",
    "{{count}} jetons d’entrée",
  ],
  "projectIndexing.outputTokens": [
    "{{count}} output tokens",
    "{{count}} Ausgabe-Token",
    "{{count}} jetons de sortie",
  ],
  "projectIndexing.requests": ["{{count}} requests", "{{count}} Anfragen", "{{count}} requêtes"],
  "projectIndexing.reviewDescription": [
    "Review the selected source diff with the configured analysis model. Findings include exact source locations.",
    "Die ausgewählten Quellcodeänderungen mit dem konfigurierten Analysemodell prüfen. Ergebnisse enthalten genaue Quellcodepositionen.",
    "Examinez les modifications sélectionnées avec le modèle d’analyse configuré. Les observations indiquent des emplacements précis dans le code source.",
  ],
  "projectIndexing.reviewScope": [
    "Changes to review",
    "Zu prüfende Änderungen",
    "Modifications à examiner",
  ],
  "projectIndexing.reviewScope.workingtree": [
    "Working tree changes",
    "Änderungen im Arbeitsverzeichnis",
    "Modifications de l’arbre de travail",
  ],
  "projectIndexing.reviewScope.staged": [
    "Staged changes",
    "Zum Commit vorgemerkte Änderungen",
    "Modifications préparées pour le commit",
  ],
  "projectIndexing.reviewing": [
    "Reviewing changes…",
    "Änderungen werden geprüft…",
    "Examen des modifications…",
  ],
  "projectIndexing.reviewChanges": [
    "Review changes",
    "Änderungen prüfen",
    "Examiner les modifications",
  ],
  "projectIndexing.reviewUnavailable": [
    "This environment does not support AI diff review.",
    "Diese Umgebung unterstützt keine KI-Prüfung von Änderungen.",
    "Cet environnement ne prend pas en charge la revue des modifications par l’IA.",
  ],
  "projectIndexing.noReviewFindings": [
    "No findings were returned for this diff. Check any reported gaps before relying on the result.",
    "Für diese Änderungen wurden keine Befunde gemeldet. Prüfe gemeldete Lücken, bevor du dich auf das Ergebnis verlässt.",
    "Aucune observation n’a été retournée pour ces modifications. Vérifiez les lacunes signalées avant de vous fier au résultat.",
  ],
  "projectIndexing.severity.info": ["Info", "Info", "Info"],
  "projectIndexing.severity.warning": ["Warning", "Warnung", "Avertissement"],
  "projectIndexing.severity.error": ["Error", "Fehler", "Erreur"],
  "projectIndexing.reviewCategory.correctness": ["Correctness", "Korrektheit", "Exactitude"],
  "projectIndexing.reviewCategory.security": ["Security", "Sicherheit", "Sécurité"],
  "projectIndexing.reviewCategory.performance": ["Performance", "Leistung", "Performances"],
  "projectIndexing.reviewCategory.maintainability": [
    "Maintainability",
    "Wartbarkeit",
    "Maintenabilité",
  ],
  "projectIndexing.reviewCategory.testing": ["Testing", "Tests", "Tests"],
  "projectIndexing.reviewCategory.other": ["Other", "Sonstiges", "Autre"],
  "projectIndexing.openSettings": [
    "Open Project Indexing settings",
    "Einstellungen zur Projektindexierung öffnen",
    "Ouvrir les réglages d’indexation du projet",
  ],
  "projectIndexing.graphDisabled": [
    "Enable Project Indexing for this project to explore its source entities and call relationships.",
    "Aktiviere die Projektindexierung für dieses Projekt, um seine Quellcode-Entitäten und Aufrufbeziehungen zu erkunden.",
    "Activez l’indexation de ce projet pour explorer les entités de son code source et leurs relations d’appel.",
  ],
  "projectIndexing.scopeChanged": [
    "The project workspace changed. Refresh to load its current index.",
    "Der Projekt-Workspace hat sich geändert. Aktualisiere die Ansicht, um seinen aktuellen Index zu laden.",
    "L’espace de travail du projet a changé. Actualisez la vue pour charger son index actuel.",
  ],
  "projectIndexing.noProjects": [
    "Connect an environment with a project to manage indexing.",
    "Verbinde eine Umgebung mit einem Projekt, um die Indexierung zu verwalten.",
    "Connectez un environnement contenant un projet pour gérer l’indexation.",
  ],
  "projectIndexing.selectProject": [
    "Select project and environment",
    "Projekt und Umgebung auswählen",
    "Sélectionner le projet et l’environnement",
  ],
  "projectIndexing.projectScope": [
    "Project workspace",
    "Projekt-Workspace",
    "Espace de travail du projet",
  ],
  "projectIndexing.threadScope": [
    "Current thread workspace",
    "Workspace des aktuellen Threads",
    "Espace de travail du fil actuel",
  ],
  "projectIndexing.readOnly": [
    "This connection can inspect the index but cannot change it.",
    "Diese Verbindung kann den Index anzeigen, aber nicht ändern.",
    "Cette connexion permet de consulter l’index, mais pas de le modifier.",
  ],
  "projectIndexing.readUnavailable": [
    "This connection does not have permission to read the project index.",
    "Diese Verbindung hat keine Berechtigung, den Projektindex zu lesen.",
    "Cette connexion n’a pas l’autorisation de lire l’index du projet.",
  ],
  "projectIndexing.coverage": [
    "{{indexed}} / {{eligible}} files · {{analyzed}} / {{entities}} entities analyzed",
    "{{indexed}} / {{eligible}} Dateien · {{analyzed}} / {{entities}} Entitäten analysiert",
    "{{indexed}} / {{eligible}} fichiers · {{analyzed}} / {{entities}} entités analysées",
  ],
  "projectIndexing.sourceTruncated": [
    "This file preview is truncated.",
    "Diese Dateivorschau ist gekürzt.",
    "Cet aperçu du fichier est tronqué.",
  ],
});

export type ProjectIndexingInterfaceMessageKey =
  (typeof projectIndexingInterfaceCatalog.keys)[number];

export const projectIndexingFeatureCopy = {
  "knowledge.projectIndexingMaster": {
    label: ["Project Indexing", "Projektindexierung", "Indexation des projets"],
    description: [
      "Enable local indexing for this environment. Each project starts its first index explicitly.",
      "Lokale Indexierung für diese Umgebung freigeben. Jedes Projekt startet seinen ersten Index ausdrücklich.",
      "Activez l’indexation locale pour cet environnement. Chaque projet lance explicitement son premier index.",
    ],
  },
  "knowledge.projectIndexingDefaultModel": {
    label: [
      "Default AI review model",
      "Standardmodell für KI-Prüfung",
      "Modèle de revue par l’IA par défaut",
    ],
    description: [
      "Used only for manually requested code reviews in projects without their own review model.",
      "Wird nur für manuell gestartete Codeprüfungen in Projekten ohne eigenes Prüfmodell verwendet.",
      "Utilisé uniquement pour les revues de code lancées manuellement dans les projets sans modèle de revue spécifique.",
    ],
  },
  "knowledge.projectIndexing": {
    label: ["Project Indexing", "Projektindexierung", "Indexation du projet"],
    description: [
      "Index source files, symbols, imports, calls, and explicit rules locally without a model.",
      "Quelldateien, Symbole, Imports, Aufrufe und ausdrückliche Regeln lokal ohne Modell indizieren.",
      "Indexez localement les fichiers, symboles, imports, appels et règles explicites sans modèle.",
    ],
  },
  "knowledge.projectIndexingReview": {
    label: ["AI diff review", "KI-Prüfung von Änderungen", "Revue des modifications par l’IA"],
    description: [
      "Enable manually requested reviews of staged or working tree changes using project knowledge and a selected review model.",
      "Manuell angeforderte Prüfungen von vorgemerkten Änderungen oder Änderungen im Arbeitsverzeichnis mit Projektwissen und einem ausgewählten Prüfmodell aktivieren.",
      "Activez les revues lancées manuellement des modifications préparées ou de l’arbre de travail à l’aide des connaissances du projet et d’un modèle de revue choisi.",
    ],
  },
} as const;
