import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const settingsConnectionsInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "settings.sourceControlWriting.section": [
    "Text generation",
    "Textgenerierung",
    "Génération de texte",
  ],
  "settings.sourceControlWriting.style": [
    "Source control writing style",
    "Schreibstil für die Quellcodeverwaltung",
    "Style de rédaction pour la gestion du code source",
  ],
  "settings.sourceControlWriting.repoConventions": [
    "Repository conventions",
    "Repository-Konventionen",
    "Conventions du dépôt",
  ],
  "settings.sourceControlWriting.repoConventionsDescription": [
    "In each project, matches recent change descriptions and change request titles.",
    "Passt sich in jedem Projekt an aktuelle Änderungsbeschreibungen und Titel von Änderungsanfragen an.",
    "S’adapte, dans chaque projet, aux descriptions récentes et aux titres des demandes de modification.",
  ],
  "settings.sourceControlWriting.conventionalCommits": [
    "Conventional Commits",
    "Conventional Commits",
    "Conventional Commits",
  ],
  "settings.sourceControlWriting.conventionalCommitsDescription": [
    "Uses Conventional Commit prefixes for change descriptions; change request titles and descriptions stay concise.",
    "Verwendet Conventional-Commit-Präfixe für Änderungsbeschreibungen; Titel und Beschreibungen von Änderungsanfragen bleiben knapp.",
    "Utilise les préfixes Conventional Commits pour les descriptions; les titres et descriptions des demandes restent concis.",
  ],
  "settings.sourceControlWriting.custom": [
    "Custom instructions",
    "Eigene Anweisungen",
    "Instructions personnalisées",
  ],
  "settings.sourceControlWriting.customDescription": [
    "Applies your instructions to change descriptions and change request titles and descriptions in every project.",
    "Wendet deine Anweisungen in jedem Projekt auf Änderungsbeschreibungen sowie Titel und Beschreibungen von Änderungsanfragen an.",
    "Applique vos instructions aux descriptions et aux titres des demandes de modification dans chaque projet.",
  ],
  "settings.sourceControlWriting.customPlaceholder": [
    "Keep titles concise. Use short bullet points in descriptions.",
    "Halte Titel knapp. Verwende kurze Aufzählungspunkte in Beschreibungen.",
    "Gardez les titres concis. Utilisez des listes courtes dans les descriptions.",
  ],
  "settings.sourceControlWriting.customAria": [
    "Custom source control writing instructions",
    "Eigene Schreibanweisungen für die Quellcodeverwaltung",
    "Instructions de rédaction personnalisées pour la gestion du code source",
  ],
  "settings.sourceControlWriting.followTemplates": [
    "Follow change request templates",
    "Vorlagen für Änderungsanfragen verwenden",
    "Suivre les modèles de demande de modification",
  ],
  "settings.sourceControlWriting.followTemplatesDescription": [
    "Structures change request descriptions using the current repository's template when one is available.",
    "Strukturiert Beschreibungen von Änderungsanfragen anhand der Vorlage des aktuellen Repositorys, sofern eine verfügbar ist.",
    "Structure les descriptions selon le modèle du dépôt actuel lorsqu’il est disponible.",
  ],
  "settings.sourceControlWriting.writerModel": [
    "Source control writer model",
    "Modell für Quellcodeverwaltungstexte",
    "Modèle de rédaction pour la gestion du code source",
  ],
  "settings.sourceControlWriting.writerModelDescription": [
    "Optional model override for change descriptions, change request titles and descriptions, and branch or bookmark names. Off uses the global text generation model.",
    "Optionale Modellauswahl für Änderungsbeschreibungen, Titel und Beschreibungen von Änderungsanfragen sowie Branch- oder Lesezeichennamen. Aus verwendet das globale Textgenerierungsmodell.",
    "Modèle facultatif pour les descriptions, les titres des demandes et les noms de branche ou de signet. Désactivé utilise le modèle global de génération de texte.",
  ],
  "settings.sourceControlWriting.separateWriterModel": [
    "Use a separate source control writer model",
    "Separates Modell für Quellcodeverwaltungstexte verwenden",
    "Utiliser un modèle de rédaction distinct pour la gestion du code source",
  ],
  "settings.sourceControl.authenticated": ["Authenticated", "Authentifiziert", "Authentifié"],
  "settings.sourceControl.notAuthenticated": [
    "Not authenticated",
    "Nicht authentifiziert",
    "Non authentifié",
  ],
  "settings.sourceControl.statusUnknown": ["Status unknown", "Status unbekannt", "État inconnu"],
  "settings.sourceControl.accountVisibility": [
    "Toggle source control account visibility",
    "Sichtbarkeit des Quellcodeverwaltungskontos umschalten",
    "Afficher ou masquer le compte de gestion du code source",
  ],
  "settings.sourceControl.revealAccount": [
    "Click to reveal account",
    "Klicken, um das Konto anzuzeigen",
    "Cliquer pour afficher le compte",
  ],
  "settings.sourceControl.hideAccount": [
    "Click to hide account",
    "Klicken, um das Konto auszublenden",
    "Cliquer pour masquer le compte",
  ],
  "settings.sourceControl.comingSoon": ["Coming Soon", "Demnächst", "Bientôt disponible"],
  "settings.sourceControl.comingSoonDescription": [
    "Support for {{provider}} is coming soon.",
    "Unterstützung für {{provider}} folgt demnächst.",
    "La prise en charge de {{provider}} sera bientôt disponible.",
  ],
  "settings.sourceControl.notAvailable": [
    "Not available on this server: {{hint}}",
    "Auf diesem Server nicht verfügbar: {{hint}}",
    "Indisponible sur ce serveur : {{hint}}",
  ],
  "settings.sourceControl.authenticatedAs": [
    "Authenticated as",
    "Authentifiziert als",
    "Authentifié en tant que",
  ],
  "settings.sourceControl.availableWithHint": [
    "Available. {{hint}}",
    "Verfügbar. {{hint}}",
    "Disponible. {{hint}}",
  ],
  "settings.sourceControl.unauthenticatedDescription": [
    "{{provider}} is not authenticated on this server. Sign in or configure credentials using the {{tool}} tool on the server host to enable change request features.",
    "{{provider}} ist auf diesem Server nicht authentifiziert. Melde dich an oder richte Zugangsdaten mit dem Tool {{tool}} auf dem Serverhost ein, um Änderungsanfragen zu aktivieren.",
    "{{provider}} n’est pas authentifié sur ce serveur. Connectez-vous ou configurez les identifiants avec l’outil {{tool}} sur l’hôte pour activer les demandes de modification.",
  ],
  "settings.sourceControl.verifyFailed": [
    "Could not verify {{provider}}. {{detail}}",
    "{{provider}} konnte nicht überprüft werden. {{detail}}",
    "Impossible de vérifier {{provider}}. {{detail}}",
  ],
  "settings.sourceControl.available": ["Available", "Verfügbar", "Disponible"],
  "settings.sourceControl.toggleDetails": [
    "Toggle {{provider}} details",
    "Details zu {{provider}} umschalten",
    "Afficher ou masquer les détails de {{provider}}",
  ],
  "settings.sourceControl.availability": [
    "{{provider}} availability",
    "Verfügbarkeit von {{provider}}",
    "Disponibilité de {{provider}}",
  ],
  "settings.sourceControl.fetchInterval": [
    "Fetch interval",
    "Fetch-Intervall",
    "Intervalle de récupération",
  ],
  "settings.sourceControl.fetchPolicy": [
    "This interval is configured for Git only. The shared Background activity policy still decides whether Git refreshes may run when the timer fires. Custom intervals appear as Advanced in General settings.",
    "Dieses Intervall gilt nur für Git. Die gemeinsame Richtlinie für Hintergrundaktivitäten entscheidet weiterhin, ob Git-Aktualisierungen beim Ablauf des Timers ausgeführt werden dürfen. Benutzerdefinierte Intervalle erscheinen in den allgemeinen Einstellungen als Erweitert.",
    "Cet intervalle ne concerne que Git. La règle d’activité en arrière-plan décide toujours si l’actualisation Git peut s’exécuter lorsque le minuteur arrive à échéance. Les intervalles personnalisés apparaissent comme Avancés dans les réglages généraux.",
  ],
  "settings.sourceControl.fetchDescription": [
    "Refresh remote branch status in the background. Set this to 0 seconds if Git credentials or security keys should only be prompted by explicit Git actions.",
    "Status entfernter Branches im Hintergrund aktualisieren. Auf 0 Sekunden setzen, wenn Git-Zugangsdaten oder Sicherheitsschlüssel nur durch ausdrückliche Git-Aktionen angefordert werden sollen.",
    "Actualise l’état des branches distantes en arrière-plan. Réglez sur 0 seconde si les identifiants Git ou clés de sécurité ne doivent être demandés que lors d’actions Git explicites.",
  ],
  "settings.sourceControl.decreaseFetch": [
    "Decrease fetch interval",
    "Fetch-Intervall verringern",
    "Réduire l’intervalle de récupération",
  ],
  "settings.sourceControl.fetchSeconds": [
    "Automatic Git fetch interval in seconds",
    "Automatisches Git-Fetch-Intervall in Sekunden",
    "Intervalle de récupération Git automatique en secondes",
  ],
  "settings.sourceControl.increaseFetch": [
    "Increase fetch interval",
    "Fetch-Intervall erhöhen",
    "Augmenter l’intervalle de récupération",
  ],
  "settings.sourceControl.seconds": ["seconds", "Sekunden", "secondes"],
  "settings.sourceControl.serverEnvironment": [
    "Server environment",
    "Serverumgebung",
    "Environnement serveur",
  ],
  "settings.sourceControl.scanFailed": [
    "Could not scan the server environment",
    "Serverumgebung konnte nicht geprüft werden",
    "Impossible d’analyser l’environnement serveur",
  ],
  "settings.sourceControl.nothingDetected": [
    "Nothing detected yet",
    "Noch nichts erkannt",
    "Aucun élément détecté",
  ],
  "settings.sourceControl.emptyDescription": [
    "Install Git on the server, add optional hosting integrations or credentials your workspace needs, then rescan.",
    "Installiere Git auf dem Server, füge optionale Hosting-Integrationen oder benötigte Zugangsdaten hinzu und prüfe erneut.",
    "Installez Git sur le serveur, ajoutez les intégrations d’hébergement ou identifiants nécessaires, puis relancez l’analyse.",
  ],
  "settings.sourceControl.scan": ["Scan", "Prüfen", "Analyser"],
  "settings.sourceControl.rescan": [
    "Rescan server environment",
    "Serverumgebung erneut prüfen",
    "Analyser à nouveau l’environnement serveur",
  ],
  "settings.sourceControl.rescanTooltip": [
    "Rescan Git and hosting integrations",
    "Git- und Hosting-Integrationen erneut prüfen",
    "Analyser à nouveau Git et les intégrations d’hébergement",
  ],
  "settings.sourceControl.versionControl": [
    "Version Control",
    "Versionsverwaltung",
    "Gestion de versions",
  ],
  "settings.sourceControl.providers": [
    "Source Control Providers",
    "Quellcodeverwaltungsanbieter",
    "Fournisseurs de gestion du code source",
  ],
  "settings.integrations.system": ["System", "System", "Système"],
  "settings.integrations.light": ["Light", "Hell", "Clair"],
  "settings.integrations.dark": ["Dark", "Dunkel", "Sombre"],
  "settings.integrations.fillPanel": ["Fill panel", "Panel ausfüllen", "Remplir le panneau"],
  "settings.integrations.responsive": ["Responsive", "Responsiv", "Adaptatif"],
  "settings.integrations.viewportDescription": [
    "The viewport a browser tab opens at, for both you and agents. Fill sizes the page to the panel; any other choice opens the device toolbar at that size.",
    "Der Viewport, mit dem ein Browser-Tab für dich und Agents geöffnet wird. Ausfüllen passt die Seite an das Panel an; jede andere Auswahl öffnet die Geräteleiste in dieser Größe.",
    "La zone d’affichage utilisée à l’ouverture d’un onglet, pour vous et les agents. Remplir adapte la page au panneau ; tout autre choix ouvre la barre d’appareil à cette taille.",
  ],
  "settings.integrations.defaultViewport": [
    "Default browser viewport",
    "Standard-Browser-Viewport",
    "Zone d’affichage par défaut",
  ],
  "settings.integrations.standard": ["Standard", "Standard", "Standard"],
  "settings.integrations.viewportWidth": [
    "Default viewport width",
    "Standard-Viewport-Breite",
    "Largeur par défaut",
  ],
  "settings.integrations.viewportHeight": [
    "Default viewport height",
    "Standard-Viewport-Höhe",
    "Hauteur par défaut",
  ],
  "settings.integrations.rotateLandscape": [
    "Rotate to landscape",
    "Ins Querformat drehen",
    "Tourner en paysage",
  ],
  "settings.integrations.rotatePortrait": [
    "Rotate to portrait",
    "Ins Hochformat drehen",
    "Tourner en portrait",
  ],
  "settings.integrations.rotate": ["Rotate", "Drehen", "Pivoter"],
  "settings.integrations.zoomDescription": [
    "Page zoom applied to new browser tabs.",
    "Seitenzoom für neue Browser-Tabs.",
    "Zoom appliqué aux nouveaux onglets.",
  ],
  "settings.integrations.defaultZoom": [
    "Default browser zoom",
    "Standard-Browserzoom",
    "Zoom par défaut",
  ],
  "settings.integrations.appearanceDescription": [
    "The color scheme pages are told to prefer. System follows your OS setting.",
    "Das bevorzugte Farbschema für Seiten. System folgt der Einstellung des Betriebssystems.",
    "Le thème de couleurs préféré par les pages. Système suit le réglage du système d’exploitation.",
  ],
  "settings.integrations.defaultAppearance": [
    "Default browser appearance",
    "Standard-Browserdarstellung",
    "Apparence par défaut",
  ],
  "settings.integrations.agentAccessDescription": [
    "Let agents open and drive the preview browser. When off, the browser tools and the instructions describing them are withheld from agent sessions. Your own browser panel is unaffected.",
    "Agents dürfen den Vorschaubrowser öffnen und steuern. Wenn deaktiviert, erhalten Agent-Sitzungen weder Browser-Tools noch deren Anweisungen. Dein eigenes Browser-Panel bleibt unverändert.",
    "Autorise les agents à ouvrir et piloter le navigateur d’aperçu. Si désactivé, les outils et leurs instructions ne sont pas fournis aux sessions d’agent. Votre panneau reste inchangé.",
  ],
  "settings.integrations.agentAccessStatus": [
    "Applies to sessions started from now on; a running agent keeps the tools it was given.",
    "Gilt für ab jetzt gestartete Sitzungen; ein laufender Agent behält seine vorhandenen Tools.",
    "S’applique aux nouvelles sessions ; un agent en cours conserve les outils déjà reçus.",
  ],
  "settings.integrations.agentAccess": [
    "Agent browser access",
    "Agent-Browserzugriff",
    "Accès navigateur des agents",
  ],
  "settings.integrations.allowAgentAccess": [
    "Allow agent browser access",
    "Agent-Browserzugriff erlauben",
    "Autoriser l’accès navigateur des agents",
  ],
  "settings.integrations.autoShowDescription": [
    "Pop the floating preview into view when an agent opens a browser. An agent that explicitly asks to show or hide its preview still gets what it asked for.",
    "Blendet die schwebende Vorschau ein, wenn ein Agent einen Browser öffnet. Ausdrückliche Wünsche zum Ein- oder Ausblenden bleiben wirksam.",
    "Affiche l’aperçu flottant lorsqu’un agent ouvre un navigateur. Une demande explicite d’affichage ou de masquage reste prioritaire.",
  ],
  "settings.integrations.autoShow": [
    "Auto-show floating preview",
    "Schwebende Vorschau automatisch anzeigen",
    "Afficher automatiquement l’aperçu flottant",
  ],
  "settings.integrations.desktopOnly": [
    "Only available in the desktop app.",
    "Nur in der Desktop-App verfügbar.",
    "Disponible uniquement dans l’application de bureau.",
  ],
  "settings.integrations.browser": ["Browser", "Browser", "Navigateur"],
  "settings.skills.scanning": [
    "Scanning agent folders…",
    "Agent-Ordner werden geprüft…",
    "Analyse des dossiers d’agent…",
  ],
  "settings.skills.noSources": [
    "No agent dotfolders with importable skills were found.",
    "Keine Agent-Dotfolder mit importierbaren Skills gefunden.",
    "Aucun dossier d’agent contenant des skills importables n’a été trouvé.",
  ],
  "settings.skills.skillCount": [
    { one: "{{formattedCount}} skill", other: "{{formattedCount}} skills" },
    { one: "{{formattedCount}} Skill", other: "{{formattedCount}} Skills" },
    { one: "{{formattedCount}} skill", other: "{{formattedCount}} skills" },
  ],
  "settings.skills.mcpCount": [
    { one: "{{formattedCount}} MCP server", other: "{{formattedCount}} MCP servers" },
    { one: "{{formattedCount}} MCP-Server", other: "{{formattedCount}} MCP-Server" },
    { one: "{{formattedCount}} serveur MCP", other: "{{formattedCount}} serveurs MCP" },
  ],
  "settings.skills.importTitle": [
    "Import Agent Skills",
    "Agent-Skills importieren",
    "Importer des skills d’agent",
  ],
  "settings.skills.importDescription": [
    "Import skills from detected Codex, Cursor, Claude, and OpenCode folders into {{scope}} skills.",
    "Skills aus erkannten Codex-, Cursor-, Claude- und OpenCode-Ordnern in {{scope}} Skills importieren.",
    "Importez les skills détectés dans les dossiers Codex, Cursor, Claude et OpenCode vers les skills {{scope}}.",
  ],
  "settings.skills.globalAdjective": ["global", "globale", "globaux"],
  "settings.skills.projectAdjective": ["project", "Projekt-", "du projet"],
  "settings.skills.deduplicate": [
    "Deduplicate matching skills",
    "Übereinstimmende Skills zusammenführen",
    "Dédupliquer les skills correspondants",
  ],
  "settings.skills.import": ["Import", "Importieren", "Importer"],
  "settings.skills.name": ["Name", "Name", "Nom"],
  "settings.skills.description": ["Description", "Beschreibung", "Description"],
  "settings.skills.descriptionPlaceholder": [
    "Use when reviewing follow-up changes.",
    "Bei der Prüfung nachfolgender Änderungen verwenden.",
    "À utiliser pour examiner les modifications de suivi.",
  ],
  "settings.skills.displayName": ["Display name", "Anzeigename", "Nom affiché"],
  "settings.skills.displayNamePlaceholder": ["Review follow-up", "Nachprüfung", "Examen de suivi"],
  "settings.skills.shortDescription": [
    "Short description",
    "Kurzbeschreibung",
    "Description courte",
  ],
  "settings.skills.shortDescriptionPlaceholder": [
    "Focused review workflow",
    "Fokussierter Prüfablauf",
    "Flux d’examen ciblé",
  ],
  "settings.skills.instructions": ["Instructions", "Anweisungen", "Instructions"],
  "settings.skills.save": ["Save", "Speichern", "Enregistrer"],
  "settings.skills.selectProjectSave": [
    "Select a project before saving a project skill.",
    "Vor dem Speichern eines Projekt-Skills ein Projekt auswählen.",
    "Sélectionnez un projet avant d’enregistrer un skill de projet.",
  ],
  "settings.skills.required": [
    "Name and description are required.",
    "Name und Beschreibung sind erforderlich.",
    "Le nom et la description sont obligatoires.",
  ],
  "settings.skills.saveFailed": [
    "Failed to save skill.",
    "Skill konnte nicht gespeichert werden.",
    "Impossible d’enregistrer le skill.",
  ],
  "settings.skills.selectProjectImport": [
    "Select a project before importing project skills.",
    "Vor dem Importieren von Projekt-Skills ein Projekt auswählen.",
    "Sélectionnez un projet avant d’importer des skills de projet.",
  ],
  "settings.skills.importFailed": [
    "Failed to import skills.",
    "Skills konnten nicht importiert werden.",
    "Impossible d’importer les skills.",
  ],
  "settings.skills.deleteConfirm": [
    "Delete skill '{{skill}}'?",
    "Skill '{{skill}}' löschen?",
    "Supprimer le skill « {{skill}} » ?",
  ],
  "settings.skills.title": ["Skills", "Skills", "Skills"],
  "settings.skills.refresh": ["Refresh skills", "Skills aktualisieren", "Actualiser les skills"],
  "settings.skills.new": ["New", "Neu", "Nouveau"],
  "settings.skills.global": ["Global", "Global", "Global"],
  "settings.skills.project": ["Project", "Projekt", "Projet"],
  "settings.skills.noProject": ["No project", "Kein Projekt", "Aucun projet"],
  "settings.skills.loading": [
    "Loading skills…",
    "Skills werden geladen…",
    "Chargement des skills…",
  ],
  "settings.skills.empty": [
    "No skills in this scope.",
    "Keine Skills in diesem Bereich.",
    "Aucun skill dans cette portée.",
  ],
  "settings.skills.readOnly": ["Read-only", "Schreibgeschützt", "Lecture seule"],
  "settings.skills.editAria": ["Edit {{skill}}", "{{skill}} bearbeiten", "Modifier {{skill}}"],
  "settings.skills.deleteAria": ["Delete {{skill}}", "{{skill}} löschen", "Supprimer {{skill}}"],
  "settings.skills.editTitle": ["Edit skill", "Skill bearbeiten", "Modifier le skill"],
  "settings.skills.newTitle": ["New skill", "Neuer Skill", "Nouveau skill"],
  "settings.harness.noDatedChats": [
    "No dated chats",
    "Keine datierten Chats",
    "Aucune discussion datée",
  ],
  "settings.harness.unavailable": ["Unavailable", "Nicht verfügbar", "Indisponible"],
  "settings.harness.alreadyLocal": [
    "Already in T3 Code",
    "Bereits in T3 Code",
    "Déjà dans T3 Code",
  ],
  "settings.harness.checking": ["Checking", "Wird geprüft", "Vérification"],
  "settings.harness.moreAvailable": ["More available", "Weitere verfügbar", "Autres disponibles"],
  "settings.harness.upToDate": ["Up to date", "Aktuell", "À jour"],
  "settings.harness.changedCount": [
    { one: "{{formattedCount}} changed", other: "{{formattedCount}} changed" },
    { one: "{{formattedCount}} geändert", other: "{{formattedCount}} geändert" },
    { one: "{{formattedCount}} modifié", other: "{{formattedCount}} modifiés" },
  ],
  "settings.harness.chatCount": [
    { one: "{{formattedCount}} chat", other: "{{formattedCount}} chats" },
    { one: "{{formattedCount}} Chat", other: "{{formattedCount}} Chats" },
    { one: "{{formattedCount}} discussion", other: "{{formattedCount}} discussions" },
  ],
  "settings.harness.updateCount": [
    { one: "{{formattedCount}} update", other: "{{formattedCount}} updates" },
    { one: "{{formattedCount}} Aktualisierung", other: "{{formattedCount}} Aktualisierungen" },
    { one: "{{formattedCount}} mise à jour", other: "{{formattedCount}} mises à jour" },
  ],
  "settings.harness.sourceCounts": [
    "{{chats}} · {{updates}}",
    "{{chats}} · {{updates}}",
    "{{chats}} · {{updates}}",
  ],
  "settings.harness.shownMore": [
    "{{visible}} shown · more available",
    "{{visible}} angezeigt · weitere verfügbar",
    "{{visible}} affichées · autres disponibles",
  ],
  "settings.harness.shownMoreUpdates": [
    "{{visible}} shown · more available · {{changed}}+ updates",
    "{{visible}} angezeigt · weitere verfügbar · {{changed}}+ Aktualisierungen",
    "{{visible}} affichées · autres disponibles · {{changed}}+ mises à jour",
  ],
  "settings.harness.allExceptComplete": [
    "All matching except {{excluded}} · {{changed}} changed",
    "Alle passenden außer {{excluded}} · {{changed}} geändert",
    "Toutes les correspondances sauf {{excluded}} · {{changed}} modifiées",
  ],
  "settings.harness.allExceptIncomplete": [
    "All matching except {{excluded}} · {{visible}} shown · more available",
    "Alle passenden außer {{excluded}} · {{visible}} angezeigt · weitere verfügbar",
    "Toutes les correspondances sauf {{excluded}} · {{visible}} affichées · autres disponibles",
  ],
  "settings.harness.allSelectedComplete": [
    "All {{total}} matching selected · {{changed}} changed",
    "Alle {{total}} passenden ausgewählt · {{changed}} geändert",
    "Les {{total}} correspondances sont sélectionnées · {{changed}} modifiées",
  ],
  "settings.harness.allSelectedIncomplete": [
    "All matching selected · {{visible}} shown · more available",
    "Alle passenden ausgewählt · {{visible}} angezeigt · weitere verfügbar",
    "Toutes les correspondances sont sélectionnées · {{visible}} affichées · autres disponibles",
  ],
  "settings.harness.someSelectedComplete": [
    "{{selected}} selected · {{total}} matching · {{changed}} changed",
    "{{selected}} ausgewählt · {{total}} passend · {{changed}} geändert",
    "{{selected}} sélectionnées · {{total}} correspondances · {{changed}} modifiées",
  ],
  "settings.harness.someSelectedIncomplete": [
    "{{selected}} selected · {{visible}} shown · more available",
    "{{selected}} ausgewählt · {{visible}} angezeigt · weitere verfügbar",
    "{{selected}} sélectionnées · {{visible}} affichées · autres disponibles",
  ],
  "settings.harness.syncSummary": [
    "Synced {{synced}} of {{selected}} {{chatNoun}} · {{messages}} messages imported",
    "{{synced}} von {{selected}} {{chatNoun}} synchronisiert · {{messages}} Nachrichten importiert",
    "{{synced}} sur {{selected}} {{chatNoun}} synchronisées · {{messages}} messages importés",
  ],
  "settings.harness.chatNounOne": ["chat", "Chat", "discussion"],
  "settings.harness.chatNounOther": ["chats", "Chats", "discussions"],
  "settings.harness.activeElsewhere": ["Active elsewhere", "Anderswo aktiv", "Actif ailleurs"],
  "settings.harness.linked": ["Linked", "Verknüpft", "Lié"],
  "settings.harness.threadTitle": [
    "T3 thread {{thread}}",
    "T3-Chat {{thread}}",
    "Discussion T3 {{thread}}",
  ],
  "settings.harness.updatesAvailable": [
    "Updates available",
    "Aktualisierungen verfügbar",
    "Mises à jour disponibles",
  ],
  "settings.harness.archived": ["Archived", "Archiviert", "Archivé"],
  "settings.harness.account": ["Account", "Konto", "Compte"],
  "settings.harness.providerAccount": [
    "Provider account for {{provider}}",
    "Anbieterkonto für {{provider}}",
    "Compte fournisseur pour {{provider}}",
  ],
  "settings.harness.projectRequired": [
    "Project target required",
    "Projektziel erforderlich",
    "Projet cible requis",
  ],
  "settings.harness.willCreate": [
    "Will create {{project}}",
    "{{project}} wird erstellt",
    "Créera {{project}}",
  ],
  "settings.harness.projectMatched": ["Project matched", "Projekt zugeordnet", "Projet associé"],
  "settings.harness.selectChat": ["Select {{chat}}", "{{chat}} auswählen", "Sélectionner {{chat}}"],
  "settings.harness.noWorkingDirectory": [
    "No working directory",
    "Kein Arbeitsverzeichnis",
    "Aucun dossier de travail",
  ],
  "settings.harness.messageCount": [
    { one: "{{formattedCount}} message", other: "{{formattedCount}} messages" },
    { one: "{{formattedCount}} Nachricht", other: "{{formattedCount}} Nachrichten" },
    { one: "{{formattedCount}} message", other: "{{formattedCount}} messages" },
  ],
  "settings.harness.lastActivity": [
    "Last activity {{date}}",
    "Letzte Aktivität {{date}}",
    "Dernière activité {{date}}",
  ],
  "settings.harness.refreshChats": [
    "Refresh {{provider}} chats",
    "Chats von {{provider}} aktualisieren",
    "Actualiser les discussions {{provider}}",
  ],
  "settings.harness.searchPlaceholder": [
    "Search provider chats",
    "Anbieter-Chats durchsuchen",
    "Rechercher dans les discussions du fournisseur",
  ],
  "settings.harness.includeArchived": [
    "Include archived",
    "Archivierte einschließen",
    "Inclure les archives",
  ],
  "settings.harness.selectAll": ["Select all", "Alle auswählen", "Tout sélectionner"],
  "settings.harness.clearAll": ["Clear all", "Auswahl leeren", "Tout effacer"],
  "settings.harness.reading": [
    "Reading provider chats…",
    "Anbieter-Chats werden gelesen…",
    "Lecture des discussions du fournisseur…",
  ],
  "settings.harness.noMatches": [
    "No matching provider chats",
    "Keine passenden Anbieter-Chats",
    "Aucune discussion correspondante",
  ],
  "settings.harness.viewMore": ["View more", "Mehr anzeigen", "Afficher plus"],
  "settings.harness.allShown": [
    "All matching chats shown",
    "Alle passenden Chats angezeigt",
    "Toutes les discussions correspondantes sont affichées",
  ],
  "settings.harness.syncing": ["Syncing…", "Synchronisierung…", "Synchronisation…"],
  "settings.harness.syncSelected": [
    "Sync selected",
    "Auswahl synchronisieren",
    "Synchroniser la sélection",
  ],
  "settings.harness.chooseProject": ["Choose a project", "Projekt auswählen", "Choisir un projet"],
  "settings.harness.resolverDescription": [
    "{{count}} selected {{chatNoun}} no usable working directory. Use one T3 Code project for all unresolved chats.",
    "{{count}} ausgewählte {{chatNoun}} kein nutzbares Arbeitsverzeichnis. Verwende ein T3-Code-Projekt für alle nicht zugeordneten Chats.",
    "{{count}} {{chatNoun}} sélectionnées n’ont pas de dossier de travail utilisable. Utilisez un projet T3 Code pour toutes les discussions non résolues.",
  ],
  "settings.harness.chatHas": ["chat has", "Chat hat", "discussion a"],
  "settings.harness.chatsHave": ["chats have", "Chats haben", "discussions ont"],
  "settings.harness.addProjectFirst": [
    "Add a project in this environment before syncing these chats.",
    "Füge in dieser Umgebung ein Projekt hinzu, bevor du diese Chats synchronisierst.",
    "Ajoutez un projet dans cet environnement avant de synchroniser ces discussions.",
  ],
  "settings.harness.targetProject": ["Target project", "Zielprojekt", "Projet cible"],
  "settings.harness.targetProjectAria": [
    "Target project for unresolved chats",
    "Zielprojekt für nicht zugeordnete Chats",
    "Projet cible pour les discussions non résolues",
  ],
  "settings.harness.selectProject": [
    "Select a project",
    "Projekt auswählen",
    "Sélectionner un projet",
  ],
  "settings.harness.syncToProject": [
    "Sync to project",
    "Mit Projekt synchronisieren",
    "Synchroniser avec le projet",
  ],
  "settings.harness.providersAria": [
    "Harness providers",
    "Harness-Anbieter",
    "Fournisseurs de harness",
  ],
  "settings.harness.syncFailed": [
    "Could not sync provider chats.",
    "Anbieter-Chats konnten nicht synchronisiert werden.",
    "Impossible de synchroniser les discussions du fournisseur.",
  ],
  "settings.harness.refreshFailed": [
    "Could not refresh provider chat status.",
    "Status der Anbieter-Chats konnte nicht aktualisiert werden.",
    "Impossible d’actualiser l’état des discussions du fournisseur.",
  ],
  "settings.harness.readFailed": [
    "Could not read provider chats.",
    "Anbieter-Chats konnten nicht gelesen werden.",
    "Impossible de lire les discussions du fournisseur.",
  ],
  "settings.harness.primaryEnvironment": [
    "Primary environment",
    "Primäre Umgebung",
    "Environnement principal",
  ],
  "settings.harness.discovering": [
    "Discovering provider chat history…",
    "Anbieter-Chatverlauf wird gesucht…",
    "Recherche de l’historique des discussions…",
  ],
  "settings.harness.discoverFailed": [
    "Could not discover provider chat history.",
    "Anbieter-Chatverlauf konnte nicht gefunden werden.",
    "Impossible de rechercher l’historique des discussions.",
  ],
  "settings.harness.noSources": [
    "No harness chat sources are configured in this environment.",
    "In dieser Umgebung sind keine Harness-Chatquellen eingerichtet.",
    "Aucune source de discussion de harness n’est configurée dans cet environnement.",
  ],
  "settings.harness.sourceChats": [
    "{{provider}} chats",
    "Chats von {{provider}}",
    "Discussions {{provider}}",
  ],
  "settings.harness.refreshSources": [
    "Refresh chat sources for {{environment}}",
    "Chatquellen für {{environment}} aktualisieren",
    "Actualiser les sources de discussion pour {{environment}}",
  ],
  "settings.harness.title": [
    "Sync provider chat history",
    "Anbieter-Chatverlauf synchronisieren",
    "Synchroniser l’historique des discussions",
  ],
  "settings.harness.description": [
    "Review Codex, Claude Code, OpenCode, and other harness sessions before adding or updating T3 Code chats. Nothing syncs until you choose Sync selected.",
    "Prüfe Sitzungen von Codex, Claude Code, OpenCode und anderen Harnesses, bevor T3-Code-Chats hinzugefügt oder aktualisiert werden. Erst Auswahl synchronisieren startet die Synchronisierung.",
    "Examinez les sessions Codex, Claude Code, OpenCode et autres avant d’ajouter ou mettre à jour les discussions T3 Code. Rien n’est synchronisé avant de choisir Synchroniser la sélection.",
  ],
});

export type SettingsConnectionsInterfaceMessageKey =
  (typeof settingsConnectionsInterfaceCatalog.keys)[number];
