import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const settingsThemeVoiceInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "settings.voice.title": ["Voice input", "Spracheingabe", "Saisie vocale"],
  "settings.voice.apiKey.title": [
    "AssemblyAI API key",
    "AssemblyAI-API-Schlüssel",
    "Clé API AssemblyAI",
  ],
  "settings.voice.apiKey.description": [
    "Used server-side to mint short-lived browser streaming tokens for live voice transcription. The key is stored in the local secret store and is never sent to the web app.",
    "Wird serverseitig verwendet, um kurzlebige Browser-Streaming-Tokens für die Live-Transkription zu erstellen. Der Schlüssel liegt im lokalen Secretspeicher und wird nie an die Web-App gesendet.",
    "Utilisée côté serveur pour créer des jetons de streaming de courte durée destinés à la transcription vocale en direct. La clé est conservée dans le stockage local des secrets et n’est jamais envoyée à l’application web.",
  ],
  "settings.voice.apiKey.configured": ["Configured", "Konfiguriert", "Configurée"],
  "settings.voice.apiKey.missing": ["Missing key", "Schlüssel fehlt", "Clé manquante"],
  "settings.voice.apiKey.saved": [
    "Saved API key",
    "Gespeicherter API-Schlüssel",
    "Clé API enregistrée",
  ],
  "settings.voice.output.title": ["Output language", "Ausgabesprache", "Langue de sortie"],
  "settings.voice.output.description": [
    "Keep dictated text in its spoken language, or translate the final transcript to English.",
    "Diktierten Text in der gesprochenen Sprache beibehalten oder das fertige Transkript ins Englische übersetzen.",
    "Conserver le texte dicté dans sa langue d’origine ou traduire la transcription finale en anglais.",
  ],
  "settings.voice.output.aria": [
    "Voice input output language",
    "Ausgabesprache der Spracheingabe",
    "Langue de sortie de la saisie vocale",
  ],
  "settings.voice.output.native": ["Native", "Originalsprache", "Langue d’origine"],
  "settings.voice.output.english": ["English", "Englisch", "Anglais"],
  "settings.voice.model.title": [
    "Voice post-processing model",
    "Modell zur Sprachnachbearbeitung",
    "Modèle de post-traitement vocal",
  ],
  "settings.voice.model.resetLabel": [
    "voice post-processing model",
    "Modell zur Sprachnachbearbeitung",
    "modèle de post-traitement vocal",
  ],
  "settings.voice.model.description": [
    "Model used only for optional English translation after you stop recording. AssemblyAI still handles live speech recognition. By default, this follows the global text generation model.",
    "Modell nur für die optionale englische Übersetzung nach dem Ende der Aufnahme. AssemblyAI übernimmt weiterhin die Live-Spracherkennung. Standardmäßig folgt dies dem globalen Textgenerierungsmodell.",
    "Modèle utilisé uniquement pour la traduction facultative en anglais après l’arrêt de l’enregistrement. AssemblyAI assure toujours la reconnaissance vocale en direct. Par défaut, ce réglage suit le modèle global de génération de texte.",
  ],
  "settings.voice.context.title": [
    "Project speech context",
    "Sprachkontext des Projekts",
    "Contexte vocal du projet",
  ],
  "settings.voice.context.refresh": [
    "Refresh project speech profiles",
    "Projekt-Sprachprofile aktualisieren",
    "Actualiser les profils vocaux du projet",
  ],
  "settings.voice.context.noProjects": [
    "No T3 projects are available.",
    "Keine T3-Projekte verfügbar.",
    "Aucun projet T3 n’est disponible.",
  ],
  "settings.voice.context.environmentUnavailable": [
    "Speech profiles are unavailable for this environment. Try refreshing.",
    "Sprachprofile sind für diese Umgebung nicht verfügbar. Versuche, sie zu aktualisieren.",
    "Les profils vocaux sont indisponibles pour cet environnement. Essayez de les actualiser.",
  ],
  "settings.voice.context.projectCount": [
    { one: "{{count}} project", other: "{{count}} projects" },
    { one: "{{count}} Projekt", other: "{{count}} Projekte" },
    { one: "{{count}} projet", other: "{{count}} projets" },
  ],
  "settings.voice.profile.prompt": ["AssemblyAI prompt", "AssemblyAI-Prompt", "Prompt AssemblyAI"],
  "settings.voice.profile.keyterms": ["Keyterms", "Schlüsselbegriffe", "Termes clés"],
  "settings.voice.profile.noKeyterms": [
    "No keyterms.",
    "Keine Schlüsselbegriffe.",
    "Aucun terme clé.",
  ],
  "settings.voice.profile.technologies": ["Technologies", "Technologien", "Technologies"],
  "settings.voice.profile.noTechnologies": [
    "No technologies detected.",
    "Keine Technologien erkannt.",
    "Aucune technologie détectée.",
  ],
  "settings.voice.profile.updated": ["Updated", "Aktualisiert", "Mis à jour"],
  "settings.voice.profile.status.notIndexed": ["Not indexed", "Nicht indexiert", "Non indexé"],
  "settings.voice.profile.status.indexed": ["Indexed", "Indexiert", "Indexé"],
  "settings.voice.profile.status.basic": ["Basic context", "Basiskontext", "Contexte de base"],
  "settings.voice.profile.status.unavailable": ["Unavailable", "Nicht verfügbar", "Indisponible"],
  "settings.voice.profile.toggle": [
    "Toggle {{project}} speech profile",
    "Sprachprofil für {{project}} ein- oder ausklappen",
    "Afficher ou masquer le profil vocal de {{project}}",
  ],
  "settings.voice.profile.unavailable": [
    "This project's speech profile is unavailable. Refresh the environment and try again.",
    "Das Sprachprofil dieses Projekts ist nicht verfügbar. Aktualisiere die Umgebung und versuche es erneut.",
    "Le profil vocal de ce projet est indisponible. Actualisez l’environnement et réessayez.",
  ],
  "settings.voice.profile.missing": [
    "No speech profile exists for this project. Index it to generate repository-aware AssemblyAI context, or use basic context based on the project metadata.",
    "Für dieses Projekt existiert kein Sprachprofil. Indexiere es für repositorybezogenen AssemblyAI-Kontext oder verwende Basiskontext aus den Projektmetadaten.",
    "Aucun profil vocal n’existe pour ce projet. Indexez-le pour générer un contexte AssemblyAI lié au dépôt ou utilisez un contexte de base issu des métadonnées du projet.",
  ],
  "settings.voice.profile.loading": [
    "Loading this project's profile.",
    "Das Profil dieses Projekts wird geladen.",
    "Chargement du profil de ce projet.",
  ],
  "settings.voice.profile.index": ["Index", "Indexieren", "Indexer"],
  "settings.voice.profile.reindex": ["Reindex", "Neu indexieren", "Réindexer"],
  "settings.voice.profile.indexing": ["Indexing…", "Indexierung…", "Indexation…"],
  "settings.voice.profile.reindexing": ["Reindexing…", "Neue Indexierung…", "Réindexation…"],
  "settings.voice.profile.indexAria": [
    "{{action}} {{project}} speech profile",
    "Sprachprofil für {{project}}: {{action}}",
    "{{action}} le profil vocal de {{project}}",
  ],
  "settings.voice.profile.basic": [
    "Use basic context",
    "Basiskontext verwenden",
    "Utiliser le contexte de base",
  ],
  "settings.voice.profile.basicAria": [
    "Use basic context for {{project}}",
    "Basiskontext für {{project}} verwenden",
    "Utiliser le contexte de base pour {{project}}",
  ],
  "settings.voice.profile.creating": ["Creating…", "Wird erstellt…", "Création…"],
  "settings.voice.profile.indexFailed": [
    "Could not index this project. Try again.",
    "Dieses Projekt konnte nicht indexiert werden. Versuche es erneut.",
    "Impossible d’indexer ce projet. Réessayez.",
  ],
  "settings.voice.profile.basicFailed": [
    "Could not create basic context for this project. Try again.",
    "Der Basiskontext für dieses Projekt konnte nicht erstellt werden. Versuche es erneut.",
    "Impossible de créer le contexte de base de ce projet. Réessayez.",
  ],
  "settings.theme.format.hex": ["HEX", "HEX", "HEX"],
  "settings.theme.format.rgb": ["RGB", "RGB", "RVB"],
  "settings.theme.picker.planeAria": [
    "{{label}} saturation and brightness",
    "Sättigung und Helligkeit für {{label}}",
    "Saturation et luminosité de {{label}}",
  ],
  "settings.theme.picker.planeValue": [
    "saturation {{saturation}}%, brightness {{brightness}}%",
    "Sättigung {{saturation}} %, Helligkeit {{brightness}} %",
    "saturation {{saturation}} %, luminosité {{brightness}} %",
  ],
  "settings.theme.picker.hueAria": [
    "{{label}} hue",
    "Farbton für {{label}}",
    "Teinte de {{label}}",
  ],
  "settings.theme.picker.hexAria": [
    "{{label}} picker hex value",
    "HEX-Wert für {{label}}",
    "Valeur hexadécimale de {{label}}",
  ],
  "settings.theme.picker.rgbAria": [
    "{{label}} picker RGB value",
    "RGB-Wert für {{label}}",
    "Valeur RVB de {{label}}",
  ],
  "settings.theme.picker.chooseAria": [
    "Choose {{label}} color",
    "Farbe für {{label}} auswählen",
    "Choisir la couleur de {{label}}",
  ],
  "settings.theme.toast.saveFailed": [
    "Could not save your theme",
    "Dein Theme konnte nicht gespeichert werden",
    "Impossible d’enregistrer votre thème",
  ],
  "settings.theme.toast.storageUnavailable": [
    "Browser storage is unavailable, so the change was not kept.",
    "Der Browserspeicher ist nicht verfügbar, daher wurde die Änderung nicht beibehalten.",
    "Le stockage du navigateur est indisponible, la modification n’a donc pas été conservée.",
  ],
  "settings.theme.toast.updated": [
    "{{theme}} updated",
    "{{theme}} aktualisiert",
    "{{theme}} mis à jour",
  ],
  "settings.theme.toast.paletteAdded": [
    "Its {{appearance}} palette was added.",
    "Die {{appearance}}-Palette wurde hinzugefügt.",
    "Sa palette {{appearance}} a été ajoutée.",
  ],
  "settings.theme.toast.saved": [
    "{{theme}} saved",
    "{{theme}} gespeichert",
    "{{theme}} enregistré",
  ],
  "settings.theme.toast.changesActive": [
    "Your changes are now active.",
    "Deine Änderungen sind jetzt aktiv.",
    "Vos modifications sont maintenant actives.",
  ],
  "settings.theme.toast.changesSaved": [
    "Your changes are saved.",
    "Deine Änderungen wurden gespeichert.",
    "Vos modifications sont enregistrées.",
  ],
  "settings.theme.toast.created": ["{{theme}} created", "{{theme}} erstellt", "{{theme}} créé"],
  "settings.theme.toast.nowActive": [
    "It’s now active.",
    "Es ist jetzt aktiv.",
    "Il est maintenant actif.",
  ],
  "settings.theme.editor.group.foundation": ["Foundation", "Grundlage", "Fondations"],
  "settings.theme.editor.group.brandContent": [
    "Brand & content",
    "Marke und Inhalt",
    "Marque et contenu",
  ],
  "settings.theme.editor.group.context": ["Context", "Kontext", "Contexte"],
  "settings.theme.editor.group.status": ["Status", "Status", "État"],
  "settings.theme.editor.family.background": ["Background", "Hintergrund", "Arrière-plan"],
  "settings.theme.editor.family.surface": ["Surface", "Fläche", "Surface"],
  "settings.theme.editor.family.raisedSurface": [
    "Raised surface",
    "Erhöhte Fläche",
    "Surface surélevée",
  ],
  "settings.theme.editor.family.overlay": ["Overlay", "Overlay", "Superposition"],
  "settings.theme.editor.family.text": ["Text", "Text", "Texte"],
  "settings.theme.editor.family.mutedText": ["Muted text", "Gedämpfter Text", "Texte atténué"],
  "settings.theme.editor.family.border": ["Border", "Rahmen", "Bordure"],
  "settings.theme.editor.family.input": ["Input", "Eingabe", "Saisie"],
  "settings.theme.editor.family.subtleSurface": [
    "Subtle surface",
    "Dezente Fläche",
    "Surface discrète",
  ],
  "settings.theme.editor.family.highlightSurface": [
    "Highlight surface",
    "Hervorgehobene Fläche",
    "Surface mise en évidence",
  ],
  "settings.theme.editor.family.accent": ["Accent", "Akzent", "Accent"],
  "settings.theme.editor.family.action": ["Action", "Aktion", "Action"],
  "settings.theme.editor.family.messageSurface": [
    "Message surface",
    "Nachrichtenfläche",
    "Surface des messages",
  ],
  "settings.theme.editor.family.codeSurface": ["Code surface", "Codefläche", "Surface du code"],
  "settings.theme.editor.family.sidebarBackground": [
    "Sidebar background",
    "Seitenleisten-Hintergrund",
    "Arrière-plan de la barre latérale",
  ],
  "settings.theme.editor.family.sidebarControls": [
    "Sidebar controls",
    "Seitenleisten-Steuerung",
    "Commandes de la barre latérale",
  ],
  "settings.theme.editor.family.sidebarSelection": [
    "Sidebar selection",
    "Seitenleisten-Auswahl",
    "Sélection de la barre latérale",
  ],
  "settings.theme.editor.family.terminalBackground": [
    "Terminal background",
    "Terminal-Hintergrund",
    "Arrière-plan du terminal",
  ],
  "settings.theme.editor.family.error": ["Error", "Fehler", "Erreur"],
  "settings.theme.editor.family.warning": ["Warning", "Warnung", "Avertissement"],
  "settings.theme.editor.name": ["Theme name", "Theme-Name", "Nom du thème"],
  "settings.theme.editor.nameExample": ["e.g. Aurora", "z. B. Aurora", "p. ex. Aurora"],
  "settings.theme.editor.appearance": ["Appearance", "Darstellung", "Apparence"],
  "settings.theme.editor.appearanceAria": [
    "Theme appearance",
    "Theme-Darstellung",
    "Apparence du thème",
  ],
  "settings.theme.editor.light": ["Light", "Hell", "Clair"],
  "settings.theme.editor.dark": ["Dark", "Dunkel", "Sombre"],
  "settings.theme.editor.colors": ["Colors", "Farben", "Couleurs"],
  "settings.theme.editor.derived": [
    "Two colors, rest derived",
    "Zwei Farben, Rest abgeleitet",
    "Deux couleurs, le reste est dérivé",
  ],
  "settings.theme.editor.filter": ["Filter colors", "Farben filtern", "Filtrer les couleurs"],
  "settings.theme.editor.advanced": ["Advanced", "Erweitert", "Avancé"],
  "settings.theme.editor.advancedAria": [
    "Use advanced theme colors",
    "Erweiterte Theme-Farben verwenden",
    "Utiliser les couleurs avancées du thème",
  ],
  "settings.theme.editor.noMatches": ["No matches.", "Keine Treffer.", "Aucun résultat."],
  "settings.theme.editor.create": ["Create theme", "Theme erstellen", "Créer un thème"],
  "settings.theme.editor.edit": ["Edit theme", "Theme bearbeiten", "Modifier le thème"],
  "settings.theme.editor.closeAria": [
    "Close the theme editor",
    "Theme-Editor schließen",
    "Fermer l’éditeur de thème",
  ],
  "settings.theme.editor.inspect": ["Inspect", "Prüfen", "Inspecter"],
  "settings.theme.editor.inspectAria": [
    "Inspect app colors",
    "App-Farben prüfen",
    "Inspecter les couleurs de l’application",
  ],
  "settings.theme.editor.cancelInspectAria": [
    "Cancel inspecting app colors",
    "Prüfung der App-Farben abbrechen",
    "Annuler l’inspection des couleurs de l’application",
  ],
  "settings.theme.editor.pickFromApp": [
    "Pick a color from the app",
    "Farbe aus der App auswählen",
    "Choisir une couleur dans l’application",
  ],
  "settings.theme.editor.cancelAndClear": [
    "Cancel and clear the selection",
    "Abbrechen und Auswahl löschen",
    "Annuler et effacer la sélection",
  ],
  "settings.theme.editor.expandAria": [
    "Expand the theme editor",
    "Theme-Editor erweitern",
    "Développer l’éditeur de thème",
  ],
  "settings.theme.editor.minimizeAria": [
    "Minimize the theme editor",
    "Theme-Editor minimieren",
    "Réduire l’éditeur de thème",
  ],
  "settings.theme.editor.selectElement": [
    "Select an element · Esc to cancel",
    "Element auswählen · Esc zum Abbrechen",
    "Sélectionnez un élément · Échap pour annuler",
  ],
  "settings.theme.editor.selectColor": [
    "Select a color below",
    "Unten eine Farbe auswählen",
    "Sélectionnez une couleur ci-dessous",
  ],
  "settings.theme.editor.usage": [
    { one: "{{label}} · {{count}} use", other: "{{label}} · {{count}} uses" },
    { one: "{{label}} · {{count}} Verwendung", other: "{{label}} · {{count}} Verwendungen" },
    { one: "{{label}} · {{count}} utilisation", other: "{{label}} · {{count}} utilisations" },
  ],
  "settings.theme.editor.saveChanges": [
    "Save changes",
    "Änderungen speichern",
    "Enregistrer les modifications",
  ],
  "settings.theme.editor.mergeInto": [
    "Merge into “{{theme}}”",
    "Mit „{{theme}}“ zusammenführen",
    "Fusionner dans « {{theme}} »",
  ],
  "settings.theme.editor.addPalette": [
    "Add {{appearance}} palette",
    "{{appearance}}-Palette hinzufügen",
    "Ajouter la palette {{appearance}}",
  ],
  "settings.theme.editor.error.nameRequired": [
    "Name your theme first.",
    "Benenne dein Theme zuerst.",
    "Nommez d’abord votre thème.",
  ],
  "settings.theme.editor.missingPalette": [
    "“{{theme}}” has no {{appearance}} palette. Create a theme with the same name to add one.",
    "„{{theme}}“ hat keine {{appearance}}-Palette. Erstelle zum Hinzufügen ein Theme mit demselben Namen.",
    "« {{theme}} » ne possède pas de palette {{appearance}}. Créez un thème du même nom pour en ajouter une.",
  ],
  "settings.theme.editor.paletteTaken": [
    "“{{theme}}” already has a {{appearance}} palette.",
    "„{{theme}}“ hat bereits eine {{appearance}}-Palette.",
    "« {{theme}} » possède déjà une palette {{appearance}}.",
  ],
  "settings.theme.editor.error.paletteExists": [
    "“{{theme}}” already has a {{appearance}} palette. Pick another name.",
    "„{{theme}}“ hat bereits eine {{appearance}}-Palette. Wähle einen anderen Namen.",
    "« {{theme}} » possède déjà une palette {{appearance}}. Choisissez un autre nom.",
  ],
  "settings.theme.editor.error.bothPalettesExist": [
    "“{{theme}}” already has light and dark palettes. Pick another name.",
    "„{{theme}}“ hat bereits eine helle und eine dunkle Palette. Wähle einen anderen Namen.",
    "« {{theme}} » possède déjà des palettes claire et sombre. Choisissez un autre nom.",
  ],
  "settings.theme.editor.error.notActivated": [
    "Theme saved, but it could not be made active. Try again.",
    "Das Theme wurde gespeichert, konnte aber nicht aktiviert werden. Versuche es erneut.",
    "Le thème a été enregistré, mais n’a pas pu être activé. Réessayez.",
  ],
  "settings.theme.editor.error.save": [
    "Could not save the theme.",
    "Das Theme konnte nicht gespeichert werden.",
    "Impossible d’enregistrer le thème.",
  ],
  "settings.theme.editor.error.create": [
    "Could not create the theme.",
    "Das Theme konnte nicht erstellt werden.",
    "Impossible de créer le thème.",
  ],
  "settings.theme.import.title": ["Add a theme", "Theme hinzufügen", "Ajouter un thème"],
  "settings.theme.import.orFile": [
    "or import a file",
    "oder eine Datei importieren",
    "ou importer un fichier",
  ],
  "settings.theme.import.json": ["Theme JSON", "Theme-JSON", "JSON du thème"],
  "settings.theme.import.chooseFiles": [
    "Choose files",
    "Dateien auswählen",
    "Choisir des fichiers",
  ],
  "settings.theme.import.reading": ["Reading…", "Wird gelesen…", "Lecture…"],
  "settings.theme.import.installed": ["Already installed", "Bereits installiert", "Déjà installé"],
  "settings.theme.import.updateExisting": [
    "Update existing",
    "Vorhandene aktualisieren",
    "Mettre à jour l’existant",
  ],
  "settings.theme.import.keepBoth": ["Keep both", "Beide behalten", "Conserver les deux"],
  "settings.theme.import.back": ["Back", "Zurück", "Retour"],
  "settings.theme.import.file": ["Theme file", "Theme-Datei", "Fichier de thème"],
  "settings.theme.import.dropFiles": [
    "Drop T3 Code or VS Code .json files",
    "T3-Code- oder VS-Code-.json-Dateien hier ablegen",
    "Déposez des fichiers .json T3 Code ou VS Code",
  ],
  "settings.theme.import.add": ["Add theme", "Theme hinzufügen", "Ajouter le thème"],
  "settings.theme.import.selectFailed": [
    "Theme added, but it could not be selected. Try again.",
    "Das Theme wurde hinzugefügt, konnte aber nicht ausgewählt werden. Versuche es erneut.",
    "Le thème a été ajouté, mais n’a pas pu être sélectionné. Réessayez.",
  ],
  "settings.theme.import.invalid": [
    "That theme file is invalid.",
    "Diese Theme-Datei ist ungültig.",
    "Ce fichier de thème n’est pas valide.",
  ],
  "settings.theme.import.readFailed": [
    "Could not read that file. Paste the JSON below instead.",
    "Die Datei konnte nicht gelesen werden. Füge stattdessen unten das JSON ein.",
    "Impossible de lire ce fichier. Collez plutôt le JSON ci-dessous.",
  ],
  "settings.theme.search.title": [
    "Search community themes",
    "Community-Themes durchsuchen",
    "Rechercher des thèmes de la communauté",
  ],
  "settings.theme.search.description": [
    "Find open-source themes from Open VSX.",
    "Open-Source-Themes von Open VSX finden.",
    "Trouvez des thèmes open source sur Open VSX.",
  ],
  "settings.theme.search.aria": [
    "Search Open VSX themes",
    "Open-VSX-Themes durchsuchen",
    "Rechercher des thèmes Open VSX",
  ],
  "settings.theme.search.placeholder": [
    "Search themes…",
    "Themes durchsuchen…",
    "Rechercher des thèmes…",
  ],
  "settings.theme.search.popular": ["Popular", "Beliebt", "Populaires"],
  "settings.theme.search.sort": ["Sort", "Sortierung", "Trier"],
  "settings.theme.search.sortAria": ["Sort themes", "Themes sortieren", "Trier les thèmes"],
  "settings.theme.search.sort.downloads": [
    "Most downloaded",
    "Meiste Downloads",
    "Les plus téléchargés",
  ],
  "settings.theme.search.sort.rating": ["Best rated", "Bestbewertet", "Les mieux notés"],
  "settings.theme.search.sort.newest": ["Newest", "Neueste", "Les plus récents"],
  "settings.theme.search.sort.relevance": [
    "Most relevant",
    "Höchste Relevanz",
    "Les plus pertinents",
  ],
  "settings.theme.search.searching": [
    "Searching themes…",
    "Themes werden gesucht…",
    "Recherche de thèmes…",
  ],
  "settings.theme.search.resultCount": [
    { one: "{{count}} supported theme found.", other: "{{count}} supported themes found." },
    {
      one: "{{count}} unterstütztes Theme gefunden.",
      other: "{{count}} unterstützte Themes gefunden.",
    },
    {
      one: "{{count}} thème pris en charge trouvé.",
      other: "{{count}} thèmes pris en charge trouvés.",
    },
  ],
  "settings.theme.search.empty": [
    "No supported open-source themes found",
    "Keine unterstützten Open-Source-Themes gefunden",
    "Aucun thème open source pris en charge trouvé",
  ],
  "settings.theme.search.tryBroader": [
    "Try a broader search.",
    "Versuche eine breitere Suche.",
    "Essayez une recherche plus large.",
  ],
  "settings.theme.search.downloads": ["downloads", "Downloads", "téléchargements"],
  "settings.theme.search.fallbackDescription": [
    "A community color theme for your editor.",
    "Ein Community-Farbtheme für deinen Editor.",
    "Un thème de couleurs communautaire pour votre éditeur.",
  ],
  "settings.theme.search.viewSource": [
    "View source for {{theme}}",
    "Quelltext für {{theme}} anzeigen",
    "Afficher la source de {{theme}}",
  ],
  "settings.theme.search.install": ["Install", "Installieren", "Installer"],
  "settings.theme.search.installing": ["Installing…", "Installation…", "Installation…"],
  "settings.theme.search.update": ["Update", "Aktualisieren", "Mettre à jour"],
  "settings.theme.search.updating": ["Updating…", "Aktualisierung…", "Mise à jour…"],
  "settings.theme.search.actionAria": [
    "{{action}} {{theme}}",
    "{{theme}}: {{action}}",
    "{{action}} {{theme}}",
  ],
  "settings.theme.search.updateTitle": [
    "Update “{{theme}}”?",
    "„{{theme}}“ aktualisieren?",
    "Mettre à jour « {{theme}} » ?",
  ],
  "settings.theme.search.updateDescription": [
    "This replaces its installed variants, including any local edits. Variants no longer in the extension will be removed.",
    "Dadurch werden die installierten Varianten einschließlich lokaler Änderungen ersetzt. Varianten, die nicht mehr in der Erweiterung enthalten sind, werden entfernt.",
    "Cette opération remplace les variantes installées, y compris les modifications locales. Les variantes qui ne figurent plus dans l’extension seront supprimées.",
  ],
  "settings.theme.search.updateTheme": [
    "Update theme",
    "Theme aktualisieren",
    "Mettre à jour le thème",
  ],
  "settings.theme.settings.variantsAria": [
    "Light and dark theme variants",
    "Helle und dunkle Theme-Varianten",
    "Variantes claire et sombre du thème",
  ],
  "settings.theme.settings.duplicate": [
    "Duplicate theme",
    "Theme duplizieren",
    "Dupliquer le thème",
  ],
  "settings.theme.settings.edit": ["Edit theme", "Theme bearbeiten", "Modifier le thème"],
  "settings.theme.settings.export": [
    "Export theme file",
    "Theme-Datei exportieren",
    "Exporter le fichier de thème",
  ],
  "settings.theme.settings.saveFailed": [
    "Couldn’t save theme selection",
    "Theme-Auswahl konnte nicht gespeichert werden",
    "Impossible d’enregistrer la sélection du thème",
  ],
  "settings.theme.settings.removeFailed": [
    "Couldn’t remove theme",
    "Theme konnte nicht entfernt werden",
    "Impossible de supprimer le thème",
  ],
  "settings.theme.settings.tryAgain": ["Try again.", "Versuche es erneut.", "Réessayez."],
  "settings.theme.settings.modeAria": ["Appearance mode", "Darstellungsmodus", "Mode d’apparence"],
  "settings.theme.settings.description": [
    "Choose how T3 Code looks. Use a built-in theme or make your own.",
    "Wähle das Aussehen von T3 Code. Verwende ein integriertes Theme oder erstelle dein eigenes.",
    "Choisissez l’apparence de T3 Code. Utilisez un thème intégré ou créez le vôtre.",
  ],
  "settings.theme.settings.colorScheme": ["Color scheme", "Farbschema", "Jeu de couleurs"],
  "settings.theme.settings.themes": ["Themes", "Themes", "Thèmes"],
  "settings.theme.settings.create": ["Create theme", "Theme erstellen", "Créer un thème"],
  "settings.theme.settings.add": ["Add theme", "Theme hinzufügen", "Ajouter un thème"],
});

export type SettingsThemeVoiceInterfaceMessageKey =
  (typeof settingsThemeVoiceInterfaceCatalog.keys)[number];
