import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const settingsDiagnosticsInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "settings.diagnostics.common.unknown": ["Unknown", "Unbekannt", "Inconnu"],
  "settings.diagnostics.common.unavailable": ["Unavailable", "Nicht verfügbar", "Indisponible"],
  "settings.diagnostics.common.checking": ["Checking", "Wird geprüft", "Vérification"],
  "settings.diagnostics.common.checkedUnavailable": [
    "Checked unavailable",
    "Prüfzeit nicht verfügbar",
    "Heure de vérification indisponible",
  ],
  "settings.diagnostics.common.checked": [
    "Checked {{value}}",
    "Geprüft {{value}}",
    "Vérifié {{value}}",
  ],
  "settings.diagnostics.common.waitingSample": [
    "Waiting for sample",
    "Warten auf Messwert",
    "En attente d’un échantillon",
  ],
  "settings.diagnostics.common.updated": [
    "Updated {{value}}",
    "Aktualisiert {{value}}",
    "Mis à jour {{value}}",
  ],
  "settings.diagnostics.common.details": [
    "{{label}} details",
    "Details zu {{label}}",
    "Détails de {{label}}",
  ],
  "settings.diagnostics.common.showLess": ["Show less", "Weniger anzeigen", "Afficher moins"],
  "settings.diagnostics.common.showFullError": [
    "Show full error",
    "Vollständigen Fehler anzeigen",
    "Afficher l’erreur complète",
  ],
  "settings.diagnostics.common.showFullMessage": [
    "Show full message",
    "Vollständige Meldung anzeigen",
    "Afficher le message complet",
  ],
  "settings.diagnostics.common.copied": ["Copied", "Kopiert", "Copié"],
  "settings.diagnostics.common.copyTraceId": [
    "Copy trace ID",
    "Trace-ID kopieren",
    "Copier l’ID de trace",
  ],
  "settings.diagnostics.common.copiedTraceId": [
    "Copied trace ID",
    "Trace-ID kopiert",
    "ID de trace copié",
  ],
  "settings.diagnostics.common.copyFullTraceId": [
    "Copy full trace ID",
    "Vollständige Trace-ID kopieren",
    "Copier l’ID de trace complète",
  ],
  "settings.diagnostics.common.enabled": ["Enabled", "Aktiviert", "Activé"],
  "settings.diagnostics.common.disabled": ["Disabled", "Deaktiviert", "Désactivé"],
  "settings.diagnostics.common.active": ["Active", "Aktiv", "Actif"],
  "settings.diagnostics.common.idle": ["Idle", "Inaktiv", "Inactif"],
  "settings.diagnostics.common.locked": ["Locked", "Gesperrt", "Verrouillé"],
  "settings.diagnostics.common.unlocked": ["Unlocked", "Entsperrt", "Déverrouillé"],
  "settings.diagnostics.common.suspended": ["Suspended", "Pausiert", "Suspendu"],
  "settings.diagnostics.common.battery": ["Battery", "Akku", "Batterie"],
  "settings.diagnostics.common.externalPower": [
    "External power",
    "Netzbetrieb",
    "Alimentation externe",
  ],
  "settings.diagnostics.common.noReportedErrors": [
    "No reported errors",
    "Keine gemeldeten Fehler",
    "Aucune erreur signalée",
  ],
  "settings.diagnostics.common.desktopOnly": ["Desktop only", "Nur Desktop", "Bureau uniquement"],
  "settings.diagnostics.common.availableDesktop": [
    "Available when this page runs inside the desktop app.",
    "Verfügbar, wenn diese Seite in der Desktop-App ausgeführt wird.",
    "Disponible lorsque cette page s’exécute dans l’application de bureau.",
  ],

  "settings.diagnostics.table.name": ["Name", "Name", "Nom"],
  "settings.diagnostics.table.process": ["Process", "Prozess", "Processus"],
  "settings.diagnostics.table.category": ["Category", "Kategorie", "Catégorie"],
  "settings.diagnostics.table.cpu": ["CPU", "CPU", "CPU"],
  "settings.diagnostics.table.cpuTime": ["CPU Time", "CPU-Zeit", "Temps CPU"],
  "settings.diagnostics.table.memory": ["Memory", "Arbeitsspeicher", "Mémoire"],
  "settings.diagnostics.table.command": ["Command", "Befehl", "Commande"],
  "settings.diagnostics.table.pid": ["PID", "PID", "PID"],
  "settings.diagnostics.table.type": ["Type", "Typ", "Type"],
  "settings.diagnostics.table.kill": ["Kill", "Beenden", "Arrêter"],
  "settings.diagnostics.table.current": ["Current", "Aktuell", "Actuel"],
  "settings.diagnostics.table.average": ["Average", "Durchschnitt", "Moyenne"],
  "settings.diagnostics.table.peak": ["Peak", "Spitze", "Pic"],
  "settings.diagnostics.table.maxMemory": ["Max Mem", "Max. Speicher", "Mémoire max."],
  "settings.diagnostics.table.readPerSecond": ["Read/s", "Lesen/s", "Lecture/s"],
  "settings.diagnostics.table.writePerSecond": ["Write/s", "Schreiben/s", "Écriture/s"],
  "settings.diagnostics.table.readTotal": ["Read Total", "Lesen gesamt", "Lecture totale"],
  "settings.diagnostics.table.writeTotal": ["Write Total", "Schreiben gesamt", "Écriture totale"],
  "settings.diagnostics.table.peakCpu": ["Peak CPU", "CPU-Spitze", "Pic CPU"],
  "settings.diagnostics.table.peakMemory": ["Peak Mem", "Speicherspitze", "Pic mémoire"],
  "settings.diagnostics.table.read": ["Read", "Lesen", "Lecture"],
  "settings.diagnostics.table.write": ["Write", "Schreiben", "Écriture"],
  "settings.diagnostics.table.samples": ["Samples", "Messwerte", "Échantillons"],
  "settings.diagnostics.table.component": ["Component", "Komponente", "Composant"],
  "settings.diagnostics.table.operation": ["Operation", "Vorgang", "Opération"],
  "settings.diagnostics.table.logicalRead": ["Logical Read", "Logisch gelesen", "Lecture logique"],
  "settings.diagnostics.table.logicalWrite": [
    "Logical Write",
    "Logisch geschrieben",
    "Écriture logique",
  ],
  "settings.diagnostics.table.count": ["Count", "Anzahl", "Nombre"],
  "settings.diagnostics.table.time": ["Time", "Zeit", "Heure"],
  "settings.diagnostics.table.level": ["Level", "Stufe", "Niveau"],
  "settings.diagnostics.table.span": ["Span", "Span", "Span"],
  "settings.diagnostics.table.message": ["Message", "Meldung", "Message"],
  "settings.diagnostics.table.trace": ["Trace", "Trace", "Trace"],
  "settings.diagnostics.table.cause": ["Cause", "Ursache", "Cause"],
  "settings.diagnostics.table.duration": ["Duration", "Dauer", "Durée"],
  "settings.diagnostics.table.ended": ["Ended", "Beendet", "Terminé"],
  "settings.diagnostics.table.lastSeen": ["Last Seen", "Zuletzt gesehen", "Dernière occurrence"],
  "settings.diagnostics.table.failures": ["Failures", "Fehler", "Échecs"],
  "settings.diagnostics.table.max": ["Max", "Max.", "Max."],

  "settings.diagnostics.process.category.server": ["Server", "Server", "Serveur"],
  "settings.diagnostics.process.category.serverChild": [
    "Backend child",
    "Backend-Unterprozess",
    "Sous-processus backend",
  ],
  "settings.diagnostics.process.category.provider": ["Provider", "Provider", "Fournisseur"],
  "settings.diagnostics.process.category.terminal": ["Terminal", "Terminal", "Terminal"],
  "settings.diagnostics.process.category.electronMain": [
    "Electron main",
    "Electron-Hauptprozess",
    "Processus principal Electron",
  ],
  "settings.diagnostics.process.category.renderer": ["Renderer", "Renderer", "Moteur de rendu"],
  "settings.diagnostics.process.category.gpu": ["GPU", "GPU", "GPU"],
  "settings.diagnostics.process.category.electronUtility": [
    "Electron utility",
    "Electron-Dienstprozess",
    "Utilitaire Electron",
  ],
  "settings.diagnostics.process.category.monitor": ["Monitor", "Monitor", "Moniteur"],
  "settings.diagnostics.process.category.t3": ["T3 process", "T3-Prozess", "Processus T3"],
  "settings.diagnostics.process.type.subprocess": ["Subprocess", "Unterprozess", "Sous-processus"],
  "settings.diagnostics.process.type.agent": ["Agent", "Agent", "Agent"],
  "settings.diagnostics.process.type.process": ["Process", "Prozess", "Processus"],
  "settings.diagnostics.process.expand": [
    "Expand {{name}}",
    "{{name}} aufklappen",
    "Développer {{name}}",
  ],
  "settings.diagnostics.process.collapse": [
    "Collapse {{name}}",
    "{{name}} einklappen",
    "Réduire {{name}}",
  ],
  "settings.diagnostics.process.rootAria": [
    "Root process {{name}}",
    "Stammprozess {{name}}",
    "Processus racine {{name}}",
  ],
  "settings.diagnostics.process.childAria": [
    "Child process {{name}}",
    "Unterprozess {{name}}",
    "Processus enfant {{name}}",
  ],
  "settings.diagnostics.process.count": [
    { one: "{{count}} process", other: "{{count}} processes" },
    { one: "{{count}} Prozess", other: "{{count}} Prozesse" },
    { one: "{{count}} processus", other: "{{count}} processus" },
  ],

  "settings.diagnostics.io.storage": ["Storage bytes", "Speicherbytes", "Octets de stockage"],
  "settings.diagnostics.io.logical": ["Logical bytes", "Logische Bytes", "Octets logiques"],
  "settings.diagnostics.io.all": ["All I/O bytes", "Alle I/O-Bytes", "Tous les octets d’E/S"],

  "settings.diagnostics.source.starting": ["Starting", "Startet", "Démarrage"],
  "settings.diagnostics.source.healthy": ["Healthy", "Fehlerfrei", "Opérationnel"],
  "settings.diagnostics.source.degraded": ["Degraded", "Beeinträchtigt", "Dégradé"],
  "settings.diagnostics.source.stopped": ["Stopped", "Gestoppt", "Arrêté"],
  "settings.diagnostics.thermal.nominal": ["Nominal", "Normal", "Nominal"],
  "settings.diagnostics.thermal.fair": ["Fair", "Erhöht", "Modéré"],
  "settings.diagnostics.thermal.serious": ["Serious", "Ernst", "Sérieux"],
  "settings.diagnostics.thermal.critical": ["Critical", "Kritisch", "Critique"],

  "settings.diagnostics.signal.sendInt": ["Send SIGINT", "SIGINT senden", "Envoyer SIGINT"],
  "settings.diagnostics.signal.sendKill": ["Send SIGKILL", "SIGKILL senden", "Envoyer SIGKILL"],
  "settings.diagnostics.signal.intShort": ["INT", "INT", "INT"],
  "settings.diagnostics.signal.killShort": ["KILL", "KILL", "KILL"],
  "settings.diagnostics.signal.confirmKill": [
    "Send SIGKILL to process {{pid}}? This cannot be handled by the process.",
    "SIGKILL an Prozess {{pid}} senden? Der Prozess kann dieses Signal nicht behandeln.",
    "Envoyer SIGKILL au processus {{pid}} ? Le processus ne peut pas gérer ce signal.",
  ],
  "settings.diagnostics.signal.confirmFailed": [
    "Could not confirm signal",
    "Signal konnte nicht bestätigt werden",
    "Impossible de confirmer le signal",
  ],
  "settings.diagnostics.signal.sendFailedTitle": [
    "Could not send {{signal}}",
    "{{signal}} konnte nicht gesendet werden",
    "Impossible d’envoyer {{signal}}",
  ],
  "settings.diagnostics.signal.sendFailed": [
    "Failed to send {{signal}}.",
    "{{signal}} konnte nicht gesendet werden.",
    "Échec de l’envoi de {{signal}}.",
  ],
  "settings.diagnostics.signal.sendProcessFailed": [
    "Failed to send {{signal}} to process {{pid}}.",
    "{{signal}} konnte nicht an Prozess {{pid}} gesendet werden.",
    "Échec de l’envoi de {{signal}} au processus {{pid}}.",
  ],
  "settings.diagnostics.signal.alreadyExited": [
    "Process already exited",
    "Prozess bereits beendet",
    "Le processus est déjà terminé",
  ],
  "settings.diagnostics.signal.alreadyExitedDescription": [
    "The process is not a child of the T3 Server. It might already have exited.",
    "Der Prozess ist kein Unterprozess des T3 Servers. Möglicherweise wurde er bereits beendet.",
    "Le processus n’est pas un enfant du serveur T3. Il est peut-être déjà terminé.",
  ],

  "settings.diagnostics.live.title": ["Live Processes", "Laufende Prozesse", "Processus actifs"],
  "settings.diagnostics.live.refresh": [
    "Refresh process diagnostics",
    "Prozessdiagnose aktualisieren",
    "Actualiser le diagnostic des processus",
  ],
  "settings.diagnostics.live.childProcesses": [
    "Child Processes",
    "Unterprozesse",
    "Processus enfants",
  ],
  "settings.diagnostics.live.cpuTooltip": [
    "Total CPU across live child processes of the current server process. The desktop shell and other parent processes are not included.",
    "Gesamte CPU-Nutzung aller laufenden Unterprozesse des aktuellen Serverprozesses. Desktop-Shell und andere übergeordnete Prozesse sind nicht enthalten.",
    "CPU totale des processus enfants actifs du serveur actuel. Le shell de bureau et les autres processus parents ne sont pas inclus.",
  ],
  "settings.diagnostics.live.memoryTooltip": [
    "Total resident memory across live child processes of the current server process. The desktop shell and other parent processes are not included.",
    "Gesamter residenter Speicher aller laufenden Unterprozesse des aktuellen Serverprozesses. Desktop-Shell und andere übergeordnete Prozesse sind nicht enthalten.",
    "Mémoire résidente totale des processus enfants actifs du serveur actuel. Le shell de bureau et les autres processus parents ne sont pas inclus.",
  ],
  "settings.diagnostics.live.serverPid": ["Server PID", "Server-PID", "PID du serveur"],
  "settings.diagnostics.live.loading": [
    "Loading live processes…",
    "Laufende Prozesse werden geladen…",
    "Chargement des processus actifs…",
  ],
  "settings.diagnostics.live.empty": [
    "No live descendant processes found.",
    "Keine laufenden Unterprozesse gefunden.",
    "Aucun processus descendant actif trouvé.",
  ],

  "settings.diagnostics.history.title": [
    "Resource History",
    "Ressourcenverlauf",
    "Historique des ressources",
  ],
  "settings.diagnostics.history.refresh": [
    "Refresh resource history",
    "Ressourcenverlauf aktualisieren",
    "Actualiser l’historique des ressources",
  ],
  "settings.diagnostics.history.cpuTimeTooltip": [
    "Approximate active CPU time for the T3 server root process and its descendants during the selected window. It grows only while sampled processes use CPU and older samples leave as the window moves.",
    "Ungefähre aktive CPU-Zeit des T3 Server-Stammprozesses und seiner Unterprozesse im gewählten Zeitraum. Sie steigt nur bei CPU-Nutzung und ältere Messwerte entfallen mit dem Zeitfenster.",
    "Temps CPU actif approximatif du processus racine du serveur T3 et de ses descendants dans la période choisie. Il augmente uniquement lorsque les processus mesurés utilisent le CPU.",
  ],
  "settings.diagnostics.history.samplesTooltip": [
    "In-memory process samples retained by the server. This resets when the server restarts.",
    "Vom Server im Speicher gehaltene Prozessmesswerte. Sie werden bei einem Serverneustart zurückgesetzt.",
    "Échantillons de processus conservés en mémoire par le serveur. Ils sont réinitialisés au redémarrage du serveur.",
  ],
  "settings.diagnostics.history.interval": ["Interval", "Intervall", "Intervalle"],
  "settings.diagnostics.history.processes": ["Processes", "Prozesse", "Processus"],
  "settings.diagnostics.history.collecting": [
    "Collecting process resource samples…",
    "Prozessressourcen werden erfasst…",
    "Collecte des ressources des processus…",
  ],
  "settings.diagnostics.history.empty": [
    "No process resource samples found for this window.",
    "Keine Prozessressourcen für diesen Zeitraum gefunden.",
    "Aucun échantillon de ressources trouvé pour cette période.",
  ],
  "settings.diagnostics.history.averagePeakAria": [
    "Average CPU {{average}}%, peak CPU {{peak}}%",
    "CPU-Durchschnitt {{average}} %, CPU-Spitze {{peak}} %",
    "CPU moyenne {{average}} %, pic CPU {{peak}} %",
  ],
  "settings.diagnostics.history.averagePeak": [
    "Avg {{average}}%, peak {{peak}}%",
    "Durchschnitt {{average}} %, Spitze {{peak}} %",
    "Moyenne {{average}} %, pic {{peak}} %",
  ],
  "settings.diagnostics.window.fiveMinutes": ["5 min", "5 Min.", "5 min"],
  "settings.diagnostics.window.fifteenMinutes": ["15 min", "15 Min.", "15 min"],
  "settings.diagnostics.window.thirtyMinutes": ["30 min", "30 Min.", "30 min"],
  "settings.diagnostics.window.oneHour": ["1 h", "1 Std.", "1 h"],

  "settings.diagnostics.trace.title": [
    "Trace Diagnostics",
    "Trace-Diagnose",
    "Diagnostic des traces",
  ],
  "settings.diagnostics.trace.openLogs": [
    "Open logs folder",
    "Log-Ordner öffnen",
    "Ouvrir le dossier des journaux",
  ],
  "settings.diagnostics.trace.refresh": [
    "Refresh trace diagnostics",
    "Trace-Diagnose aktualisieren",
    "Actualiser le diagnostic des traces",
  ],
  "settings.diagnostics.trace.noEditors": [
    "No available editors found.",
    "Keine verfügbaren Editoren gefunden.",
    "Aucun éditeur disponible trouvé.",
  ],
  "settings.diagnostics.trace.noEnvironment": [
    "No environment is selected.",
    "Keine Umgebung ausgewählt.",
    "Aucun environnement sélectionné.",
  ],
  "settings.diagnostics.trace.openLogsFailed": [
    "Unable to open logs folder.",
    "Log-Ordner konnte nicht geöffnet werden.",
    "Impossible d’ouvrir le dossier des journaux.",
  ],
  "settings.diagnostics.trace.spans": ["Spans", "Spans", "Spans"],
  "settings.diagnostics.trace.failures": ["Failures", "Fehler", "Échecs"],
  "settings.diagnostics.trace.slowSpans": ["Slow Spans", "Langsame Spans", "Spans lents"],
  "settings.diagnostics.trace.slowThreshold": [
    "Spans with a duration of {{duration}} or longer.",
    "Spans mit einer Dauer von {{duration}} oder länger.",
    "Spans d’une durée de {{duration}} ou plus.",
  ],
  "settings.diagnostics.trace.slowThresholdDefault": [
    "Spans at or above the configured slow-span threshold.",
    "Spans ab dem konfigurierten Schwellenwert für langsame Spans.",
    "Spans atteignant ou dépassant le seuil configuré.",
  ],
  "settings.diagnostics.trace.parseErrors": ["Parse Errors", "Parse-Fehler", "Erreurs d’analyse"],
  "settings.diagnostics.trace.partialFailure": [
    "Some trace files could not be read, so diagnostics may be incomplete. {{detail}}",
    "Einige Trace-Dateien konnten nicht gelesen werden, daher ist die Diagnose möglicherweise unvollständig. {{detail}}",
    "Certains fichiers de trace n’ont pas pu être lus, le diagnostic peut donc être incomplet. {{detail}}",
  ],
  "settings.diagnostics.trace.latestFailures": [
    "Latest Failures",
    "Neueste Fehler",
    "Derniers échecs",
  ],
  "settings.diagnostics.trace.commonFailures": [
    "Most Common Failures",
    "Häufigste Fehler",
    "Échecs les plus fréquents",
  ],
  "settings.diagnostics.trace.slowestSpans": [
    "Slowest Spans",
    "Langsamste Spans",
    "Spans les plus lents",
  ],
  "settings.diagnostics.trace.spanLogs": ["Span Logs", "Span-Logs", "Journaux des spans"],
  "settings.diagnostics.trace.topNames": [
    "Top Span Names",
    "Häufigste Span-Namen",
    "Principaux noms de spans",
  ],
  "settings.diagnostics.trace.loadingFailures": [
    "Loading failures…",
    "Fehler werden geladen…",
    "Chargement des échecs…",
  ],
  "settings.diagnostics.trace.noFailures": [
    "No failed spans found.",
    "Keine fehlgeschlagenen Spans gefunden.",
    "Aucun span en échec trouvé.",
  ],
  "settings.diagnostics.trace.loadingGroups": [
    "Loading failure groups…",
    "Fehlergruppen werden geladen…",
    "Chargement des groupes d’échecs…",
  ],
  "settings.diagnostics.trace.noGroups": [
    "No repeated failures found.",
    "Keine wiederholten Fehler gefunden.",
    "Aucun échec répété trouvé.",
  ],
  "settings.diagnostics.trace.loadingSlow": [
    "Loading slow spans…",
    "Langsame Spans werden geladen…",
    "Chargement des spans lents…",
  ],
  "settings.diagnostics.trace.noSpans": [
    "No spans found.",
    "Keine Spans gefunden.",
    "Aucun span trouvé.",
  ],
  "settings.diagnostics.trace.loadingLogs": [
    "Loading recent logs…",
    "Aktuelle Logs werden geladen…",
    "Chargement des journaux récents…",
  ],
  "settings.diagnostics.trace.noLogs": [
    "No warnings or errors found.",
    "Keine Warnungen oder Fehler gefunden.",
    "Aucun avertissement ni erreur trouvé.",
  ],
  "settings.diagnostics.trace.loadingNames": [
    "Loading span names…",
    "Span-Namen werden geladen…",
    "Chargement des noms de spans…",
  ],

  "settings.diagnostics.resourceMonitor.title": [
    "Resource monitor",
    "Ressourcenmonitor",
    "Moniteur de ressources",
  ],
  "settings.diagnostics.resourceMonitor.native": ["Native", "Nativ", "Natif"],
  "settings.diagnostics.resourceMonitor.refresh": [
    "Refresh resource telemetry",
    "Ressourcentelemetrie aktualisieren",
    "Actualiser la télémétrie des ressources",
  ],
  "settings.diagnostics.resourceMonitor.refreshSnapshot": [
    "Refresh telemetry snapshot",
    "Telemetrie-Snapshot aktualisieren",
    "Actualiser l’instantané de télémétrie",
  ],
  "settings.diagnostics.resourceMonitor.footprint": [
    "T3 system footprint",
    "T3-Systemauslastung",
    "Empreinte système de T3",
  ],
  "settings.diagnostics.resourceMonitor.description": [
    "Live native counters for the server, providers, terminals, desktop processes, and the monitor itself.",
    "Native Live-Zähler für Server, Provider, Terminals, Desktop-Prozesse und den Monitor selbst.",
    "Compteurs natifs en direct pour le serveur, les fournisseurs, les terminaux, les processus de bureau et le moniteur.",
  ],
  "settings.diagnostics.resourceMonitor.samplingEvery": [
    "Sampling every {{interval}}",
    "Messung alle {{interval}}",
    "Échantillonnage toutes les {{interval}}",
  ],
  "settings.diagnostics.sampleInterval": [
    { one: "{{count}} second", other: "{{count}} seconds" },
    { one: "{{count}} Sekunde", other: "{{count}} Sekunden" },
    { one: "{{count}} seconde", other: "{{count}} secondes" },
  ],
  "settings.diagnostics.resourceMonitor.currentCpu": [
    "Current CPU",
    "Aktuelle CPU",
    "CPU actuelle",
  ],
  "settings.diagnostics.resourceMonitor.observedCpu": [
    "{{value}} observed CPU time",
    "{{value}} beobachtete CPU-Zeit",
    "{{value}} de temps CPU observé",
  ],
  "settings.diagnostics.resourceMonitor.residentMemory": [
    "Resident memory",
    "Residenter Speicher",
    "Mémoire résidente",
  ],
  "settings.diagnostics.resourceMonitor.combinedPeaks": [
    "{{value}} combined process peaks",
    "{{value}} kombinierte Prozessspitzen",
    "{{value}} de pics de processus combinés",
  ],
  "settings.diagnostics.resourceMonitor.processCount": [
    "Process count",
    "Prozessanzahl",
    "Nombre de processus",
  ],
  "settings.diagnostics.resourceMonitor.startsExits": [
    "{{starts}} starts · {{exits}} exits",
    "{{starts}} Starts · {{exits}} Beendigungen",
    "{{starts}} démarrages · {{exits}} arrêts",
  ],
  "settings.diagnostics.resourceMonitor.readThroughput": [
    "Read throughput",
    "Lesedurchsatz",
    "Débit de lecture",
  ],
  "settings.diagnostics.resourceMonitor.writeThroughput": [
    "Write throughput",
    "Schreibdurchsatz",
    "Débit d’écriture",
  ],
  "settings.diagnostics.resourceMonitor.observed": [
    "{{value}} observed",
    "{{value}} beobachtet",
    "{{value}} observé",
  ],
  "settings.diagnostics.resourceMonitor.speedLimit": [
    "CPU speed limit",
    "CPU-Geschwindigkeitslimit",
    "Limite de vitesse CPU",
  ],
  "settings.diagnostics.resourceMonitor.thermalState": [
    "{{state}} thermal state",
    "Thermalzustand: {{state}}",
    "État thermique : {{state}}",
  ],
  "settings.diagnostics.resourceMonitor.backend": [
    "Backend + agents",
    "Backend + Agents",
    "Backend + agents",
  ],
  "settings.diagnostics.resourceMonitor.desktop": ["Desktop", "Desktop", "Bureau"],
  "settings.diagnostics.resourceMonitor.overhead": [
    "Monitor overhead",
    "Monitor-Overhead",
    "Coût du moniteur",
  ],
  "settings.diagnostics.resourceMonitor.cpu": ["CPU", "CPU", "CPU"],
  "settings.diagnostics.resourceMonitor.memory": ["Memory", "Speicher", "Mémoire"],
  "settings.diagnostics.resourceMonitor.read": ["Read", "Lesen", "Lecture"],
  "settings.diagnostics.resourceMonitor.write": ["Write", "Schreiben", "Écriture"],
  "settings.diagnostics.resourceMonitor.restartFailed": [
    "Could not restart resource monitor",
    "Ressourcenmonitor konnte nicht neu gestartet werden",
    "Impossible de redémarrer le moniteur de ressources",
  ],
  "settings.diagnostics.resourceMonitor.retryFailed": [
    "The resource monitor retry failed.",
    "Der erneute Start des Ressourcenmonitors ist fehlgeschlagen.",
    "La nouvelle tentative du moniteur de ressources a échoué.",
  ],

  "settings.diagnostics.host.title": [
    "Host & collection",
    "Host und Erfassung",
    "Hôte et collecte",
  ],
  "settings.diagnostics.host.retry": [
    "Retry monitor",
    "Monitor erneut starten",
    "Réessayer le moniteur",
  ],
  "settings.diagnostics.host.state": ["Host state", "Hostzustand", "État de l’hôte"],
  "settings.diagnostics.host.powerSource": ["Power source", "Stromquelle", "Source d’alimentation"],
  "settings.diagnostics.host.lowPower": [
    "Low power mode",
    "Energiesparmodus",
    "Mode économie d’énergie",
  ],
  "settings.diagnostics.host.session": ["Session", "Sitzung", "Session"],
  "settings.diagnostics.host.thermal": ["Thermal", "Thermik", "Thermique"],
  "settings.diagnostics.host.signalsMissing": [
    "Desktop host signals not connected",
    "Desktop-Hostsignale nicht verbunden",
    "Signaux de l’hôte de bureau non connectés",
  ],
  "settings.diagnostics.host.signalsDescription": [
    "Power, idle, lock, and thermal state are supplied by the desktop host. Process telemetry remains fully active in this browser session.",
    "Strom-, Leerlauf-, Sperr- und Thermalzustand werden vom Desktop-Host geliefert. Die Prozesstelemetrie bleibt in dieser Browsersitzung vollständig aktiv.",
    "L’alimentation, l’inactivité, le verrouillage et l’état thermique sont fournis par l’hôte de bureau. La télémétrie des processus reste active.",
  ],
  "settings.diagnostics.host.collectionHealth": [
    "Collection health",
    "Erfassungszustand",
    "État de la collecte",
  ],
  "settings.diagnostics.host.nativeMonitor": [
    "Native process monitor",
    "Nativer Prozessmonitor",
    "Moniteur natif des processus",
  ],
  "settings.diagnostics.host.electronMain": [
    "Electron main process",
    "Electron-Hauptprozess",
    "Processus principal Electron",
  ],
  "settings.diagnostics.host.collectionTime": [
    "Collection time",
    "Erfassungszeit",
    "Temps de collecte",
  ],
  "settings.diagnostics.host.processScan": ["Process scan", "Prozessscan", "Analyse des processus"],
  "settings.diagnostics.host.retained": [
    "{{retained}}/{{scanned}} retained",
    "{{retained}}/{{scanned}} beibehalten",
    "{{retained}}/{{scanned}} conservés",
  ],
  "settings.diagnostics.host.inaccessible": ["Inaccessible", "Nicht zugänglich", "Inaccessibles"],
  "settings.diagnostics.host.sidecar": ["Sidecar", "Sidecar", "Sidecar"],
  "settings.diagnostics.host.restarts": ["Restarts", "Neustarts", "Redémarrages"],
  "settings.diagnostics.host.waitingHealth": [
    "Waiting for collector health.",
    "Warten auf den Erfassungszustand.",
    "En attente de l’état du collecteur.",
  ],

  "settings.diagnostics.timeline.title": [
    "Resource timeline",
    "Ressourcenzeitachse",
    "Chronologie des ressources",
  ],
  "settings.diagnostics.timeline.cpuAverage": ["CPU average", "CPU-Durchschnitt", "Moyenne CPU"],
  "settings.diagnostics.timeline.ioReads": ["I/O reads", "I/O-Lesevorgänge", "Lectures d’E/S"],
  "settings.diagnostics.timeline.ioWrites": [
    "I/O writes",
    "I/O-Schreibvorgänge",
    "Écritures d’E/S",
  ],
  "settings.diagnostics.timeline.cpuAverageValue": [
    "CPU avg {{value}}%",
    "CPU-Durchschnitt {{value}} %",
    "Moyenne CPU {{value}} %",
  ],
  "settings.diagnostics.timeline.cpuPeakValue": [
    "CPU peak {{value}}%",
    "CPU-Spitze {{value}} %",
    "Pic CPU {{value}} %",
  ],
  "settings.diagnostics.timeline.readValue": [
    "Read {{value}}",
    "Gelesen {{value}}",
    "Lecture {{value}}",
  ],
  "settings.diagnostics.timeline.writeValue": [
    "Write {{value}}",
    "Geschrieben {{value}}",
    "Écriture {{value}}",
  ],
  "settings.diagnostics.timeline.emptyLive": [
    "Waiting for the native process monitor.",
    "Warten auf den nativen Prozessmonitor.",
    "En attente du moniteur natif des processus.",
  ],
  "settings.diagnostics.timeline.emptyHistory": [
    "No retained process samples in this window.",
    "Keine beibehaltenen Prozessmesswerte in diesem Zeitraum.",
    "Aucun échantillon de processus conservé dans cette période.",
  ],
  "settings.diagnostics.timeline.liveTree": [
    "Live process tree",
    "Laufender Prozessbaum",
    "Arborescence des processus actifs",
  ],
  "settings.diagnostics.timeline.identity": [
    "Identity: PID + start time",
    "Identität: PID + Startzeit",
    "Identité : PID + heure de démarrage",
  ],

  "settings.diagnostics.attribution.title": [
    "Instrumented application I/O",
    "Instrumentierte Anwendungs-I/O",
    "E/S applicatives instrumentées",
  ],
  "settings.diagnostics.attribution.logical": [
    "Logical bytes by operation",
    "Logische Bytes nach Vorgang",
    "Octets logiques par opération",
  ],
  "settings.diagnostics.attribution.description": [
    "Native counters identify which process is reading or writing. These application-level counters identify known T3 operations so process spikes can be correlated with specific persistence and logging paths.",
    "Native Zähler zeigen, welcher Prozess liest oder schreibt. Diese Anwendungszähler kennzeichnen bekannte T3-Vorgänge, damit Prozessspitzen bestimmten Persistenz- und Loggingpfaden zugeordnet werden können.",
    "Les compteurs natifs indiquent quel processus lit ou écrit. Ces compteurs applicatifs identifient les opérations T3 connues afin de relier les pics aux chemins de persistance et de journalisation.",
  ],
  "settings.diagnostics.attribution.empty": [
    "No instrumented application I/O has been recorded yet.",
    "Noch keine instrumentierte Anwendungs-I/O aufgezeichnet.",
    "Aucune E/S applicative instrumentée n’a encore été enregistrée.",
  ],
});

export type SettingsDiagnosticsInterfaceMessageKey =
  (typeof settingsDiagnosticsInterfaceCatalog.keys)[number];
