import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const chatInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "chat.agent.heading": ["Agents", "Agents", "Agents"],
  "chat.agent.history": ["History", "Verlauf", "Historique"],
  "chat.agent.count": [
    { one: "{{count}} agent", other: "{{count}} agents" },
    { one: "{{count}} Agent", other: "{{count}} Agents" },
    { one: "{{count}} agent", other: "{{count}} agents" },
  ],
  "chat.agent.archivedCount": [
    { one: "{{count}} archived agent", other: "{{count}} archived agents" },
    { one: "{{count}} archivierter Agent", other: "{{count}} archivierte Agents" },
    { one: "{{count}} agent archivé", other: "{{count}} agents archivés" },
  ],
  "chat.agent.showMore": [
    "Show {{count}} more",
    "{{count}} weitere anzeigen",
    "Afficher {{count}} de plus",
  ],
  "chat.agent.activeRecentAria": [
    "Active and recent agents",
    "Aktive und kürzlich verwendete Agents",
    "Agents actifs et récents",
  ],
  "chat.agent.archivedAria": ["Archived agents", "Archivierte Agents", "Agents archivés"],
  "chat.agent.transcript.loading": [
    "Loading agent transcript",
    "Agent-Transkript wird geladen",
    "Chargement de la transcription de l’agent",
  ],
  "chat.agent.transcript.unavailable": [
    "Agent transcript unavailable",
    "Agent-Transkript nicht verfügbar",
    "Transcription de l’agent indisponible",
  ],
  "chat.agent.transcript.select": [
    "Select an agent to inspect its transcript",
    "Agent auswählen, um dessen Transkript anzuzeigen",
    "Sélectionnez un agent pour consulter sa transcription",
  ],
  "chat.agent.transcript.streaming": ["Streaming", "Streaming", "Diffusion"],
  "chat.agent.transcript.loadingEarlier": [
    "Loading earlier activity",
    "Frühere Aktivität wird geladen",
    "Chargement de l’activité précédente",
  ],
  "chat.agent.transcript.loadEarlier": [
    "Load earlier activity",
    "Frühere Aktivität laden",
    "Charger l’activité précédente",
  ],
  "chat.agent.transcript.empty": [
    "No transcript events yet.",
    "Noch keine Transkriptereignisse.",
    "Aucun événement de transcription pour le moment.",
  ],
  "chat.agent.transcript.aria": [
    "{{name}} transcript",
    "Transkript von {{name}}",
    "Transcription de {{name}}",
  ],
  "chat.agent.transcript.input": ["Input", "Eingabe", "Entrée"],
  "chat.agent.transcript.system": ["System", "System", "Système"],
  "chat.agent.transcript.eventDetails": [
    "Event details",
    "Ereignisdetails",
    "Détails de l’événement",
  ],
  "chat.agent.proposedPlan": ["Proposed plan", "Vorgeschlagener Plan", "Plan proposé"],
  "chat.transcript.exportFailed": [
    "Unable to export chat",
    "Chat konnte nicht exportiert werden",
    "Impossible d’exporter le chat",
  ],
  "chat.transcript.environmentDisconnected": [
    "The thread environment is not connected.",
    "Die Thread-Umgebung ist nicht verbunden.",
    "L’environnement du fil n’est pas connecté.",
  ],
  "chat.transcript.copied": [
    "Complete chat copied",
    "Vollständiger Chat kopiert",
    "Chat complet copié",
  ],
  "chat.transcript.unredactedMarkdown": [
    "{{file}} is unredacted Markdown.",
    "{{file}} ist ungeschwärztes Markdown.",
    "{{file}} est un Markdown non expurgé.",
  ],
  "chat.transcript.copyFailed": [
    "Unable to copy complete chat",
    "Vollständiger Chat konnte nicht kopiert werden",
    "Impossible de copier le chat complet",
  ],
  "chat.transcript.unexpectedError": [
    "An unexpected export error occurred.",
    "Beim Export ist ein unerwarteter Fehler aufgetreten.",
    "Une erreur d’exportation inattendue est survenue.",
  ],
  "chat.transcript.reconnectBeforeExport": [
    "Reconnect the thread environment before exporting.",
    "Thread-Umgebung vor dem Export erneut verbinden.",
    "Reconnectez l’environnement du fil avant l’exportation.",
  ],
  "chat.transcript.waitForTurn": [
    "Wait for the active turn to finish before exporting.",
    "Vor dem Export auf das Ende des aktiven Turns warten.",
    "Attendez la fin du tour actif avant d’exporter.",
  ],
  "chat.transcript.preparing": [
    "Preparing the complete transcript…",
    "Vollständiges Transkript wird vorbereitet…",
    "Préparation de la transcription complète…",
  ],
  "chat.transcript.completeCopied": [
    "Complete transcript copied",
    "Vollständiges Transkript kopiert",
    "Transcription complète copiée",
  ],
  "chat.transcript.copyComplete": [
    "Copy complete unredacted chat transcript",
    "Vollständiges ungeschwärztes Chat-Transkript kopieren",
    "Copier la transcription complète et non expurgée du chat",
  ],
  "chat.markdown.codeActions": [
    "Code block actions",
    "Aktionen für Codeblock",
    "Actions du bloc de code",
  ],
  "chat.markdown.copyMarkdown": ["Copy as Markdown", "Als Markdown kopieren", "Copier en Markdown"],
  "chat.markdown.copyCsv": ["Copy as CSV", "Als CSV kopieren", "Copier en CSV"],
  "chat.markdown.loadingImage": ["Loading image", "Bild wird geladen", "Chargement de l’image"],
  "chat.markdown.toggleTask": ["Toggle task", "Aufgabe umschalten", "Basculer la tâche"],
  "chat.markdown.collapseTable": [
    "Collapse table cells",
    "Tabellenzellen einklappen",
    "Réduire les cellules du tableau",
  ],
  "chat.markdown.expandTable": [
    "Expand table cells",
    "Tabellenzellen ausklappen",
    "Développer les cellules du tableau",
  ],
  "chat.markdown.copied": ["Copied", "Kopiert", "Copié"],
  "chat.markdown.copyTable": ["Copy table", "Tabelle kopieren", "Copier le tableau"],
  "chat.markdown.disableWrap": [
    "Disable line wrap",
    "Zeilenumbruch deaktivieren",
    "Désactiver le retour à la ligne",
  ],
  "chat.markdown.wrapLines": ["Wrap lines", "Zeilen umbrechen", "Renvoyer les lignes"],
  "chat.markdown.copyCode": ["Copy code", "Code kopieren", "Copier le code"],
  "chat.markdown.imageUnavailable": [
    "Image unavailable",
    "Bild nicht verfügbar",
    "Image indisponible",
  ],
  "chat.markdown.imageUnavailableAlt": [
    "Image unavailable · {{alt}}",
    "Bild nicht verfügbar · {{alt}}",
    "Image indisponible · {{alt}}",
  ],
  "chat.markdown.alert.note": ["Note", "Hinweis", "Note"],
  "chat.markdown.alert.tip": ["Tip", "Tipp", "Conseil"],
  "chat.markdown.alert.important": ["Important", "Wichtig", "Important"],
  "chat.markdown.alert.warning": ["Warning", "Warnung", "Avertissement"],
  "chat.markdown.alert.caution": ["Caution", "Vorsicht", "Attention"],
  "chat.markdown.openFileFailed": [
    "Unable to open file",
    "Datei konnte nicht geöffnet werden",
    "Impossible d’ouvrir le fichier",
  ],
  "chat.markdown.openFileBrowserFailed": [
    "Unable to open file in browser",
    "Datei konnte nicht im Browser geöffnet werden",
    "Impossible d’ouvrir le fichier dans le navigateur",
  ],
  "chat.markdown.revealFileFailed": [
    "Unable to reveal file",
    "Datei konnte nicht angezeigt werden",
    "Impossible d’afficher le fichier",
  ],
  "chat.markdown.clipboardUnavailable": [
    "Clipboard API unavailable.",
    "Zwischenablage-API nicht verfügbar.",
    "L’API du presse-papiers est indisponible.",
  ],
  "chat.markdown.openIntegratedBrowser": [
    "Open in integrated browser",
    "Im integrierten Browser öffnen",
    "Ouvrir dans le navigateur intégré",
  ],
  "chat.markdown.copyRelativePath": [
    "Copy relative path",
    "Relativen Pfad kopieren",
    "Copier le chemin relatif",
  ],
  "chat.markdown.copyFullPath": [
    "Copy full path",
    "Vollständigen Pfad kopieren",
    "Copier le chemin complet",
  ],
  "chat.markdown.relativePath": ["Relative path", "Relativer Pfad", "Chemin relatif"],
  "chat.markdown.fullPath": ["Full path", "Vollständiger Pfad", "Chemin complet"],
  "chat.markdown.copyPathFailed": [
    "Failed to copy {{target}}",
    "{{target}} konnte nicht kopiert werden",
    "Impossible de copier {{target}}",
  ],
  "chat.markdown.pathCopied": ["{{target}} copied", "{{target}} kopiert", "{{target}} copié"],
  "chat.markdown.threadContextUnavailable": [
    "Thread context is unavailable.",
    "Thread-Kontext ist nicht verfügbar.",
    "Le contexte du fil est indisponible.",
  ],
  "chat.markdown.environmentNotConnected": [
    "Environment is not connected.",
    "Die Umgebung ist nicht verbunden.",
    "L’environnement n’est pas connecté.",
  ],
  "chat.currentThread": ["Current thread", "Aktueller Thread", "Fil actuel"],
  "chat.empty.startConversation": [
    "Send a message to start the conversation.",
    "Nachricht senden, um die Unterhaltung zu beginnen.",
    "Envoyez un message pour commencer la conversation.",
  ],
  "chat.empty.addProject": [
    "Add a project to start",
    "Projekt hinzufügen, um zu beginnen",
    "Ajoutez un projet pour commencer",
  ],
  "chat.draft.changeProject": ["Change project", "Projekt wechseln", "Changer de projet"],
  "chat.draft.chooseProject": ["Choose a project", "Projekt auswählen", "Choisir un projet"],
  "chat.draft.newProject": ["New project", "Neues Projekt", "Nouveau projet"],
  "chat.draft.addProject": ["Add a project", "Projekt hinzufügen", "Ajouter un projet"],
  "chat.draft.buildPrefix": [
    "What should we build in",
    "Was sollen wir entwickeln in",
    "Que devons-nous créer dans",
  ],
  "chat.draft.startSuffix": ["to start", "um zu beginnen", "pour commencer"],
  "chat.draft.buildInProject": [
    "What should we build in {{project}}?",
    "Was sollen wir in {{project}} entwickeln?",
    "Que devons-nous créer dans {{project}} ?",
  ],
  "chat.draft.chooseToStart": [
    "{{project}} to start",
    "{{project}}, um zu beginnen",
    "{{project}} pour commencer",
  ],
  "chat.timeline.forkStartsHere": ["Fork starts here", "Fork beginnt hier", "Le fork commence ici"],
  "chat.timeline.revertMessage": [
    "Revert to this message",
    "Zu dieser Nachricht zurückkehren",
    "Revenir à ce message",
  ],
  "chat.timeline.thinking": ["Thinking", "Denkt nach", "Réflexion"],
  "chat.timeline.audioUnavailable": [
    "Audio unavailable",
    "Audio nicht verfügbar",
    "Audio indisponible",
  ],
  "chat.timeline.failed": ["Failed", "Fehlgeschlagen", "Échec"],
  "chat.timeline.completed": ["Completed", "Abgeschlossen", "Terminé"],
  "chat.timeline.empty": ["Empty", "Leer", "Vide"],
  "chat.timeline.toolFailed": [
    "Tool call failed",
    "Tool-Aufruf fehlgeschlagen",
    "Échec de l’appel d’outil",
  ],
  "chat.timeline.toolFailedLabel": [
    "{{label}}, tool call failed",
    "{{label}}, Tool-Aufruf fehlgeschlagen",
    "{{label}}, échec de l’appel d’outil",
  ],
  "chat.timeline.loadingEarlier": [
    "Loading earlier turns…",
    "Frühere Turns werden geladen…",
    "Chargement des tours précédents…",
  ],
  "chat.timeline.loadEarlier": [
    "Load earlier turns",
    "Frühere Turns laden",
    "Charger les tours précédents",
  ],
  "chat.timeline.forkedFrom": ["Forked from", "Geforkt von", "Forké depuis"],
  "chat.timeline.previewImage": ["Preview {{name}}", "Vorschau von {{name}}", "Aperçu de {{name}}"],
  "chat.timeline.downloadFile": [
    "Download {{name}}",
    "{{name}} herunterladen",
    "Télécharger {{name}}",
  ],
  "chat.timeline.retrying": [
    "Retrying response",
    "Antwort wird erneut versucht",
    "Nouvelle tentative de réponse",
  ],
  "chat.timeline.retry": ["Retry response", "Antwort erneut versuchen", "Réessayer la réponse"],
  "chat.timeline.annotatedPreviewAlt": [
    "Annotated preview crop",
    "Annotierter Vorschauausschnitt",
    "Extrait d’aperçu annoté",
  ],
  "chat.attachment.downloadFailed": [
    "Could not download {{name}}",
    "{{name}} konnte nicht heruntergeladen werden",
    "Impossible de télécharger {{name}}",
  ],
  "chat.environment.disconnected": [
    "The environment is not connected.",
    "Die Umgebung ist nicht verbunden.",
    "L’environnement n’est pas connecté.",
  ],
  "chat.environment.reconnectFailedTitle": [
    "Could not reconnect environment",
    "Umgebung konnte nicht erneut verbunden werden",
    "Impossible de reconnecter l’environnement",
  ],
  "chat.environment.reconnectFailedDescription": [
    "Failed to reconnect.",
    "Erneute Verbindung fehlgeschlagen.",
    "Échec de la reconnexion.",
  ],
  "chat.environment.status.available": ["Available", "Verfügbar", "Disponible"],
  "chat.environment.status.offline": ["Offline", "Offline", "Hors ligne"],
  "chat.environment.status.connecting": [
    "Connecting...",
    "Verbindung wird hergestellt...",
    "Connexion...",
  ],
  "chat.environment.status.reconnecting": [
    "Reconnecting...",
    "Verbindung wird wiederhergestellt...",
    "Reconnexion...",
  ],
  "chat.environment.status.reconnectingAfterFailure": [
    "Failed to connect. Reconnecting...",
    "Verbindung fehlgeschlagen. Verbindung wird wiederhergestellt...",
    "Échec de la connexion. Reconnexion...",
  ],
  "chat.environment.status.connected": ["Connected", "Verbunden", "Connecté"],
  "chat.environment.status.failed": [
    "Connection failed",
    "Verbindung fehlgeschlagen",
    "Échec de la connexion",
  ],
  "chat.environment.connectingTo": [
    "Connecting to {{environment}}",
    "Verbindung mit {{environment}} wird hergestellt",
    "Connexion à {{environment}}",
  ],
  "chat.environment.reconnectingTo": [
    "Reconnecting to {{environment}}",
    "Verbindung mit {{environment}} wird wiederhergestellt",
    "Reconnexion à {{environment}}",
  ],
  "chat.environment.mayBeUpdating": [
    "It may be finishing an update. One moment.",
    "Möglicherweise wird gerade eine Aktualisierung abgeschlossen. Einen Moment.",
    "Une mise à jour est peut-être en cours de finalisation. Un instant.",
  ],
  "chat.environment.statusTitle": [
    "{{environment}}: {{status}}",
    "{{environment}}: {{status}}",
    "{{environment}} : {{status}}",
  ],
  "chat.environment.reconnectBeforeActions": [
    "Reconnect this environment before sending messages or running actions.",
    "Diese Umgebung erneut verbinden, bevor Nachrichten gesendet oder Aktionen ausgeführt werden.",
    "Reconnectez cet environnement avant d’envoyer des messages ou d’exécuter des actions.",
  ],
  "chat.environment.reconnecting": [
    "Reconnecting...",
    "Verbindung wird wiederhergestellt...",
    "Reconnexion...",
  ],
  "chat.environment.reconnect": ["Reconnect", "Erneut verbinden", "Reconnecter"],
  "chat.environment.connections": ["Connections", "Verbindungen", "Connexions"],
  "chat.update.failed": [
    "Could not update {{server}}",
    "{{server}} konnte nicht aktualisiert werden",
    "Impossible de mettre à jour {{server}}",
  ],
  "chat.update.updating": [
    "Updating {{server}}",
    "{{server}} wird aktualisiert",
    "Mise à jour de {{server}}",
  ],
  "chat.update.available": [
    "Server update available",
    "Serveraktualisierung verfügbar",
    "Mise à jour du serveur disponible",
  ],
  "chat.update.dismiss": [
    "Dismiss update notice",
    "Aktualisierungshinweis ausblenden",
    "Masquer l’avis de mise à jour",
  ],
  "chat.scrollToEnd": ["Scroll to end", "Zum Ende scrollen", "Faire défiler jusqu’à la fin"],
  "chat.dropFilesToAttach": [
    "Drop files to attach",
    "Dateien zum Anhängen ablegen",
    "Déposez des fichiers pour les joindre",
  ],
  "chat.pullRequestsUnavailable": [
    "Pull requests unavailable",
    "Pull Requests nicht verfügbar",
    "Pull requests indisponibles",
  ],
  "chat.branchChangedWas": [
    "Branch changed - was",
    "Branch geändert - zuvor",
    "Branche modifiée - auparavant",
  ],
  "chat.branch.switchFailed": [
    "Failed to switch checkout",
    "Checkout konnte nicht gewechselt werden",
    "Impossible de changer de checkout",
  ],
  "chat.branch.threadUpdateFailed": [
    "Checkout switched, but the thread could not be updated",
    "Checkout gewechselt, aber der Thread konnte nicht aktualisiert werden",
    "Checkout changé, mais le fil n’a pas pu être mis à jour",
  ],
  "chat.branch.continueOnCurrent": [
    "This thread last ran on {{previous}}. Sending will continue on {{current}}.",
    "Dieser Thread lief zuletzt auf {{previous}}. Das Senden wird auf {{current}} fortgesetzt.",
    "Ce fil s’est exécuté pour la dernière fois sur {{previous}}. L’envoi continuera sur {{current}}.",
  ],
  "chat.branch.restoring": ["Restoring...", "Wird wiederhergestellt...", "Restauration..."],
  "chat.branch.restore": ["Restore branch", "Branch wiederherstellen", "Restaurer la branche"],
  "chat.branch.dismissNotice": [
    "Dismiss branch change notice",
    "Hinweis zum Branchwechsel ausblenden",
    "Masquer l’avis de changement de branche",
  ],
  "chat.branch.switchConfirm": [
    "Switch to {{branch}}?",
    "Zu {{branch}} wechseln?",
    "Passer à {{branch}} ?",
  ],
  "chat.branch.uncommittedWarning": [
    "You have uncommitted changes. They'll carry over to the other branch, or block the switch if they conflict.",
    "Es gibt nicht commitete Änderungen. Sie werden in den anderen Branch übernommen oder blockieren den Wechsel bei Konflikten.",
    "Vous avez des modifications non validées. Elles seront transférées vers l’autre branche ou bloqueront le changement en cas de conflit.",
  ],
  "chat.branch.switchAction": ["Switch branch", "Branch wechseln", "Changer de branche"],
  "chat.thread.unsettleFailed": [
    "Failed to un-settle thread",
    "Thread konnte nicht reaktiviert werden",
    "Impossible de réactiver le fil",
  ],
  "chat.thread.settleFailed": [
    "Failed to settle thread",
    "Thread konnte nicht erledigt werden",
    "Impossible de régler le fil",
  ],
  "chat.thread.wakeFailed": [
    "Failed to wake thread",
    "Thread konnte nicht aufgeweckt werden",
    "Impossible de réveiller le fil",
  ],
  "chat.thread.wokeTitle": [
    "This thread woke from snooze",
    "Dieser Thread wurde aus dem Snooze geweckt",
    "Ce fil s’est réveillé après sa mise en veille",
  ],
  "chat.thread.wokeDescription": [
    "Dismiss to clear the Woke indicator, or send a message to keep going.",
    "Ausblenden, um die Woke-Anzeige zu entfernen, oder eine Nachricht senden, um fortzufahren.",
    "Masquez pour effacer l’indicateur de réveil, ou envoyez un message pour continuer.",
  ],
  "chat.thread.wokeDismiss": [
    "Dismiss Woke notification",
    "Woke-Benachrichtigung ausblenden",
    "Masquer la notification de réveil",
  ],
  "chat.thread.snoozedTitle": [
    "This thread is snoozed",
    "Dieser Thread ist im Snooze",
    "Ce fil est en veille",
  ],
  "chat.thread.settledTitle": [
    "This thread is settled",
    "Dieser Thread ist erledigt",
    "Ce fil est réglé",
  ],
  "chat.thread.snoozedDescription": [
    "Sending a message wakes it and moves it back to Active in the sidebar.",
    "Eine Nachricht weckt ihn auf und verschiebt ihn in der Seitenleiste zurück zu Aktiv.",
    "L’envoi d’un message le réveille et le replace dans Actif dans la barre latérale.",
  ],
  "chat.thread.settledDescription": [
    "Sending a message moves it back to Active in the sidebar.",
    "Eine Nachricht verschiebt ihn in der Seitenleiste zurück zu Aktiv.",
    "L’envoi d’un message le replace dans Actif dans la barre latérale.",
  ],
  "chat.thread.waking": ["Waking...", "Wird aufgeweckt...", "Réveil..."],
  "chat.thread.wakeNow": ["Wake now", "Jetzt aufwecken", "Réveiller maintenant"],
  "chat.thread.unsettling": ["Un-settling...", "Wird reaktiviert...", "Réactivation..."],
  "chat.thread.unsettle": ["Un-settle", "Reaktivieren", "Réactiver"],
  "chat.harness.statusRefreshFailed": [
    "Could not refresh harness session status.",
    "Status der Harness-Sitzung konnte nicht aktualisiert werden.",
    "Impossible d’actualiser l’état de la session du harness.",
  ],
  "chat.harness.activeElsewhere": [
    "{{provider}} chat is active elsewhere",
    "{{provider}}-Chat ist an anderer Stelle aktiv",
    "Le chat {{provider}} est actif ailleurs",
  ],
  "chat.harness.sendingPaused": [
    "The synchronized history is available, but sending is paused until the original harness session becomes idle.",
    "Der synchronisierte Verlauf ist verfügbar, aber das Senden pausiert, bis die ursprüngliche Harness-Sitzung inaktiv wird.",
    "L’historique synchronisé est disponible, mais l’envoi est suspendu jusqu’à ce que la session du harness d’origine soit inactive.",
  ],
  "chat.harness.checking": ["Checking...", "Wird geprüft...", "Vérification..."],
  "chat.harness.checkAgain": ["Check again", "Erneut prüfen", "Vérifier à nouveau"],
  "chat.background.agentsWorking": [
    { one: "{{count}} agent working", other: "{{count}} agents working" },
    { one: "{{count}} Agent arbeitet", other: "{{count}} Agents arbeiten" },
    { one: "{{count}} agent travaille", other: "{{count}} agents travaillent" },
  ],
  "chat.background.work": ["Background work", "Hintergrundarbeit", "Travail en arrière-plan"],
  "chat.background.monitoring": ["Monitoring", "Überwachung", "Surveillance"],
  "chat.background.stopping": ["Stopping...", "Wird gestoppt...", "Arrêt..."],
  "chat.background.stop": ["Stop", "Stoppen", "Arrêter"],
  "chat.background.started": [
    "Started in background",
    "Im Hintergrund gestartet",
    "Démarré en arrière-plan",
  ],
  "chat.background.open": ["Open", "Öffnen", "Ouvrir"],
  "chat.background.taskStarted": [
    "Task started in the background",
    "Aufgabe im Hintergrund gestartet",
    "Tâche démarrée en arrière-plan",
  ],
  "chat.background.freshComposerError": [
    "Could not open a fresh composer: {{error}}",
    "Ein neuer Composer konnte nicht geöffnet werden: {{error}}",
    "Impossible d’ouvrir un nouveau composeur : {{error}}",
  ],
  "chat.background.freshComposerFailed": [
    "Could not open a fresh composer.",
    "Ein neuer Composer konnte nicht geöffnet werden.",
    "Impossible d’ouvrir un nouveau composeur.",
  ],
  "chat.compact.clearDraftFirst": [
    "Send or clear your draft before compacting",
    "Entwurf vor dem Komprimieren senden oder leeren",
    "Envoyez ou effacez votre brouillon avant la compaction",
  ],
  "chat.compact.chooseProjectFirst": [
    "Choose a project before compacting",
    "Vor dem Komprimieren ein Projekt auswählen",
    "Choisissez un projet avant la compaction",
  ],
  "chat.compact.enableClaudeFirst": [
    "Enable a Claude provider before compacting",
    "Vor dem Komprimieren einen Claude-Provider aktivieren",
    "Activez un fournisseur Claude avant la compaction",
  ],
  "chat.compact.unavailable": [
    "Compacting is unavailable right now",
    "Komprimieren ist derzeit nicht verfügbar",
    "La compaction est actuellement indisponible",
  ],
  "chat.compact.action": ["Compact", "Komprimieren", "Compacter"],
  "chat.compact.resumeTitle": [
    "Resume with less context",
    "Mit weniger Kontext fortsetzen",
    "Reprendre avec moins de contexte",
  ],
  "chat.compact.olderSessionTokens": [
    "{{tokens}} tokens from an older session",
    "{{tokens}} Tokens aus einer älteren Sitzung",
    "{{tokens}} jetons d’une session antérieure",
  ],
  "chat.compact.keepFullHistory": [
    "Keep full history",
    "Vollständigen Verlauf behalten",
    "Conserver l’historique complet",
  ],
  "chat.checkpoint.reconnectFirst": [
    "Reconnect {{environment}} before reverting checkpoints.",
    "{{environment}} erneut verbinden, bevor Checkpoints zurückgesetzt werden.",
    "Reconnectez {{environment}} avant de rétablir des checkpoints.",
  ],
  "chat.checkpoint.interruptFirst": [
    "Interrupt the current turn before reverting checkpoints.",
    "Den aktuellen Turn unterbrechen, bevor Checkpoints zurückgesetzt werden.",
    "Interrompez le tour actuel avant de rétablir des checkpoints.",
  ],
  "chat.checkpoint.confirm": [
    "Revert this thread to checkpoint {{count}}?",
    "Diesen Thread auf Checkpoint {{count}} zurücksetzen?",
    "Rétablir ce fil au checkpoint {{count}} ?",
  ],
  "chat.checkpoint.discardNewer": [
    "This will discard newer messages and turn diffs in this thread.",
    "Dadurch werden neuere Nachrichten und Turn-Diffs in diesem Thread verworfen.",
    "Cela supprimera les messages et diffs de tours plus récents de ce fil.",
  ],
  "chat.checkpoint.irreversible": [
    "This action cannot be undone.",
    "Diese Aktion kann nicht rückgängig gemacht werden.",
    "Cette action est irréversible.",
  ],
  "chat.checkpoint.revertFailed": [
    "Failed to revert thread state.",
    "Thread-Zustand konnte nicht zurückgesetzt werden.",
    "Impossible de rétablir l’état du fil.",
  ],
  "chat.annotation.attachedToDraft": [
    "Annotation attached to draft",
    "Annotation an Entwurf angehängt",
    "Annotation jointe au brouillon",
  ],
  "chat.annotation.sendUnavailable": [
    "Sending is unavailable right now. Finish the current action, then send.",
    "Senden ist derzeit nicht verfügbar. Aktuelle Aktion abschließen und dann senden.",
    "L’envoi est actuellement indisponible. Terminez l’action en cours, puis envoyez.",
  ],
  "chat.send.notConnectedTitle": [
    "Not connected: message not sent",
    "Nicht verbunden: Nachricht nicht gesendet",
    "Non connecté : message non envoyé",
  ],
  "chat.send.notConnectedDescription": [
    "Reconnecting to the environment. Try again once it is connected.",
    "Verbindung zur Umgebung wird wiederhergestellt. Erneut versuchen, sobald sie verbunden ist.",
    "Reconnexion à l’environnement. Réessayez une fois la connexion établie.",
  ],
  "chat.send.chooseProjectFirst": [
    "Choose a project first",
    "Zuerst ein Projekt auswählen",
    "Choisissez d’abord un projet",
  ],
  "chat.send.projectUnavailable": [
    "This draft no longer points to an available project.",
    "Dieser Entwurf verweist nicht mehr auf ein verfügbares Projekt.",
    "Ce brouillon ne pointe plus vers un projet disponible.",
  ],
  "chat.feedback.startCodexFirst": [
    "Start a Codex thread first",
    "Zuerst einen Codex-Thread starten",
    "Démarrez d’abord un fil Codex",
  ],
  "chat.feedback.sendMessageFirst": [
    "Send a message before you submit feedback.",
    "Vor dem Senden von Feedback eine Nachricht senden.",
    "Envoyez un message avant de transmettre vos commentaires.",
  ],
  "chat.feedback.sendFailed": [
    "Could not send feedback to OpenAI",
    "Feedback konnte nicht an OpenAI gesendet werden",
    "Impossible d’envoyer les commentaires à OpenAI",
  ],
  "chat.feedback.sent": [
    "Feedback sent to OpenAI",
    "Feedback an OpenAI gesendet",
    "Commentaires envoyés à OpenAI",
  ],
  "chat.feedback.threadId": ["Thread ID: {{id}}", "Thread-ID: {{id}}", "ID du fil : {{id}}"],
  "chat.feedback.copyId": ["Copy ID", "ID kopieren", "Copier l’ID"],
  "chat.feedback.copyIdFailed": [
    "Could not copy thread ID",
    "Thread-ID konnte nicht kopiert werden",
    "Impossible de copier l’ID du fil",
  ],
  "chat.terminal.none": [
    "No terminal sessions for this thread yet.",
    "Für diesen Thread gibt es noch keine Terminal-Sitzungen.",
    "Aucune session de terminal pour ce fil pour le moment.",
  ],
  "chat.terminal.addToChat": ["Add to chat", "Zum Chat hinzufügen", "Ajouter au chat"],
  "chat.terminal.copy": ["Copy", "Kopieren", "Copier"],
  "chat.terminal.paste": ["Paste", "Einfügen", "Coller"],
  "chat.action.pathCopied": ["Path copied", "Pfad kopiert", "Chemin copié"],
  "chat.action.branchCopied": ["Branch copied", "Branch kopiert", "Branche copiée"],
  "chat.action.threadIdCopied": ["Thread ID copied", "Thread-ID kopiert", "ID du fil copié"],
  "chat.action.pathCopyFailed": [
    "Failed to copy path",
    "Pfad konnte nicht kopiert werden",
    "Impossible de copier le chemin",
  ],
  "chat.action.branchCopyFailed": [
    "Failed to copy branch",
    "Branch konnte nicht kopiert werden",
    "Impossible de copier la branche",
  ],
  "chat.action.threadIdCopyFailed": [
    "Failed to copy thread ID",
    "Thread-ID konnte nicht kopiert werden",
    "Impossible de copier l’ID du fil",
  ],
  "chat.action.deleted": [
    'Deleted action "{{name}}"',
    'Aktion "{{name}}" gelöscht',
    "Action « {{name}} » supprimée",
  ],
  "chat.action.unknown": ["Unknown", "Unbekannt", "Inconnu"],
  "chat.action.deleteFailed": [
    "Could not delete action",
    "Aktion konnte nicht gelöscht werden",
    "Impossible de supprimer l’action",
  ],
  "chat.action.unexpectedError": [
    "An unexpected error occurred.",
    "Ein unerwarteter Fehler ist aufgetreten.",
    "Une erreur inattendue est survenue.",
  ],
  "chat.header.threadTitle": ["Thread title", "Thread-Titel", "Titre du fil"],
  "chat.header.breadcrumb": ["Thread breadcrumb", "Thread-Navigation", "Fil d’Ariane du fil"],
  "chat.header.newThreadIn": [
    "New thread in {{project}}",
    "Neuer Thread in {{project}}",
    "Nouveau fil dans {{project}}",
  ],
  "chat.header.emptyTitle": [
    "Thread title cannot be empty",
    "Thread-Titel darf nicht leer sein",
    "Le titre du fil ne peut pas être vide",
  ],
  "chat.header.renameFailed": [
    "Failed to rename thread",
    "Thread konnte nicht umbenannt werden",
    "Impossible de renommer le fil",
  ],
  "chat.header.genericError": [
    "An error occurred.",
    "Ein Fehler ist aufgetreten.",
    "Une erreur est survenue.",
  ],
  "chat.composer.preparingWorktree": [
    "Preparing worktree…",
    "Worktree wird vorbereitet…",
    "Préparation du worktree…",
  ],
  "chat.composer.imageCompressing": [
    "Still compressing a pasted image.",
    "Ein eingefügtes Bild wird noch komprimiert.",
    "Une image collée est encore en cours de compression.",
  ],
  "chat.composer.imageCompressBeforeSend": [
    "Send again once its thumbnail appears.",
    "Erneut senden, sobald die Miniaturansicht erscheint.",
    "Renvoyez lorsque sa miniature apparaît.",
  ],
  "chat.composer.imageCompressBeforeCompact": [
    "Compact again once its thumbnail appears.",
    "Erneut komprimieren, sobald die Miniaturansicht erscheint.",
    "Relancez la compaction lorsque sa miniature apparaît.",
  ],
  "chat.composer.interactionMode": ["Interaction mode", "Interaktionsmodus", "Mode d’interaction"],
  "chat.composer.command.modelLabel": ["/model", "/model", "/model"],
  "chat.composer.command.modelDescription": [
    "Switch response model for this thread",
    "Antwortmodell für diesen Thread wechseln",
    "Changer le modèle de réponse pour ce fil",
  ],
  "chat.composer.command.planLabel": ["/plan", "/plan", "/plan"],
  "chat.composer.command.planDescription": [
    "Switch this thread into plan mode",
    "Diesen Thread in den Planmodus versetzen",
    "Passer ce fil en mode plan",
  ],
  "chat.composer.command.defaultLabel": ["/default", "/default", "/default"],
  "chat.composer.command.defaultDescription": [
    "Switch this thread back to normal build mode",
    "Diesen Thread in den normalen Build-Modus zurückversetzen",
    "Repasser ce fil en mode de construction normal",
  ],
  "chat.composer.command.runProviderCommand": [
    "Run provider command",
    "Provider-Befehl ausführen",
    "Exécuter la commande du fournisseur",
  ],
  "chat.composer.command.providerSkillScope": [
    "{{scope}} skill",
    "Skill {{scope}}",
    "Compétence {{scope}}",
  ],
  "chat.composer.command.runProviderSkill": [
    "Run provider skill",
    "Provider-Skill ausführen",
    "Exécuter la compétence du fournisseur",
  ],
  "chat.composer.runtimeMode": ["Runtime mode", "Laufzeitmodus", "Mode d’exécution"],
  "chat.composer.customAnswer": [
    "Write custom answer",
    "Eigene Antwort verfassen",
    "Rédiger une réponse personnalisée",
  ],
  "chat.composer.expand": ["Expand composer", "Composer erweitern", "Agrandir le composeur"],
  "chat.composer.draftAttachmentWarning": [
    "Draft attachment may not persist",
    "Entwurfsanhang wird möglicherweise nicht gespeichert",
    "La pièce jointe du brouillon risque de ne pas être conservée",
  ],
  "chat.composer.attachFiles": ["Attach files", "Dateien anhängen", "Joindre des fichiers"],
  "chat.composer.attachAfterPlanQuestions": [
    "Attach files after answering plan questions.",
    "Dateien nach dem Beantworten der Planfragen anhängen.",
    "Joignez les fichiers après avoir répondu aux questions du plan.",
  ],
  "chat.composer.addToChatFailed": [
    "Unable to add to chat",
    "Konnte nicht zum Chat hinzugefügt werden",
    "Impossible d’ajouter au chat",
  ],
  "chat.composer.addToChatBusy": [
    "The composer is busy; try again once it is ready.",
    "Der Composer ist beschäftigt. Erneut versuchen, sobald er bereit ist.",
    "Le composeur est occupé. Réessayez lorsqu’il est prêt.",
  ],
  "chat.composer.noProviderAvailable": [
    "No provider available",
    "Kein Provider verfügbar",
    "Aucun fournisseur disponible",
  ],
  "chat.composer.moreControls": [
    "More composer controls",
    "Weitere Composer-Steuerungen",
    "Plus de commandes du composeur",
  ],
  "chat.composer.mode": ["Mode", "Modus", "Mode"],
  "chat.composer.mode.chat": ["Chat", "Chat", "Discussion"],
  "chat.composer.mode.plan": ["Plan", "Plan", "Plan"],
  "chat.composer.access": ["Access", "Zugriff", "Accès"],
  "chat.composer.access.supervised": ["Supervised", "Überwacht", "Supervisé"],
  "chat.composer.access.autoAccept": ["Ruled", "Regeln", "Règles"],
  "chat.composer.access.auto": ["Auto", "Auto", "Auto"],
  "chat.composer.access.full": ["Full", "Voll", "Complet"],
  "chat.composer.previousQuestion": ["Previous question", "Vorherige Frage", "Question précédente"],
  "chat.composer.previous": ["Previous", "Zurück", "Précédent"],
  "chat.composer.implementationActions": [
    "Implementation actions",
    "Implementierungsaktionen",
    "Actions d’implémentation",
  ],
  "chat.composer.suggested": ["Suggested", "Empfohlen", "Suggéré"],
  "chat.composer.planReady": ["Plan ready", "Plan bereit", "Plan prêt"],
  "chat.composer.multiSelectHint": [
    "Select one or more options.",
    "Eine oder mehrere Optionen auswählen.",
    "Sélectionnez une ou plusieurs options.",
  ],
  "chat.composer.voiceStart": [
    "Start voice input",
    "Spracheingabe starten",
    "Démarrer la saisie vocale",
  ],
  "chat.composer.voiceWaveform": [
    "Live microphone waveform",
    "Live-Mikrofonwellenform",
    "Forme d’onde du microphone en direct",
  ],
  "chat.composer.voiceCancelConnection": [
    "Cancel voice input connection",
    "Verbindung für Spracheingabe abbrechen",
    "Annuler la connexion de saisie vocale",
  ],
  "chat.composer.voiceStopping": [
    "Stopping voice input",
    "Spracheingabe wird beendet",
    "Arrêt de la saisie vocale",
  ],
  "chat.composer.voiceStop": [
    "Stop voice input",
    "Spracheingabe beenden",
    "Arrêter la saisie vocale",
  ],
  "chat.composer.voiceConnectingTooltip": [
    "Connecting to AssemblyAI · Select to cancel",
    "Verbindung zu AssemblyAI wird hergestellt · Zum Abbrechen auswählen",
    "Connexion à AssemblyAI · Sélectionnez pour annuler",
  ],
  "chat.composer.voiceStopTooltip": [
    "Stop voice input · Press Escape to cancel and restore the draft",
    "Spracheingabe beenden · Escape drücken, um abzubrechen und den Entwurf wiederherzustellen",
    "Arrêter la saisie vocale · Appuyez sur Échap pour annuler et restaurer le brouillon",
  ],
  "chat.composer.tasks.title": ["Tasks", "Aufgaben", "Tâches"],
  "chat.composer.tasks.dismiss": [
    "Dismiss tasks for this turn",
    "Aufgaben für diesen Turn ausblenden",
    "Masquer les tâches de ce tour",
  ],
  "chat.composer.tasks.progress": [
    "{{completed}} of {{total}} complete",
    "{{completed}} von {{total}} abgeschlossen",
    "{{completed}} sur {{total}} terminées",
  ],
  "chat.composer.tasks.label": [
    "Tasks: {{completed}} of {{total}} complete. Current task: {{step}}",
    "Aufgaben: {{completed}} von {{total}} abgeschlossen. Aktuelle Aufgabe: {{step}}",
    "Tâches : {{completed}} sur {{total}} terminées. Tâche actuelle : {{step}}",
  ],
  "chat.composer.tasks.collapse": [
    "Collapse tasks. {{completed}} of {{total}} complete.",
    "Aufgaben einklappen. {{completed}} von {{total}} abgeschlossen.",
    "Réduire les tâches. {{completed}} sur {{total}} terminées.",
  ],
  "chat.composer.tasks.progressAria": [
    "Tasks: {{completed}} of {{total}} complete",
    "Aufgaben: {{completed}} von {{total}} abgeschlossen",
    "Tâches : {{completed}} sur {{total}} terminées",
  ],
  "chat.composer.tasks.listAria": [
    "Task list. {{completed}} of {{total}} complete.",
    "Aufgabenliste. {{completed}} von {{total}} abgeschlossen.",
    "Liste des tâches. {{completed}} sur {{total}} terminées.",
  ],
  "chat.composer.stashClose": ["Close stash", "Ablage schließen", "Fermer la réserve"],
  "chat.composer.stashDelete": [
    "Delete stashed prompt",
    "Abgelegten Prompt löschen",
    "Supprimer le prompt mis en réserve",
  ],
  "chat.stash.otherEnvironmentTitle": [
    "Stashed files belong to another environment",
    "Abgelegte Dateien gehören zu einer anderen Umgebung",
    "Les fichiers mis en réserve appartiennent à un autre environnement",
  ],
  "chat.stash.otherEnvironmentDescription": [
    "Restore this prompt in the environment that received its files.",
    "Diesen Prompt in der Umgebung wiederherstellen, die seine Dateien empfangen hat.",
    "Restaurez ce prompt dans l’environnement qui a reçu ses fichiers.",
  ],
  "chat.stash.restoreMayReappearTitle": [
    "Restored prompt may reappear in the stash",
    "Der wiederhergestellte Prompt kann erneut in der Ablage erscheinen",
    "Le prompt restauré peut réapparaître dans la réserve",
  ],
  "chat.stash.restoreMayReappearDescription": [
    "Browser storage rejected the update, so this entry could still be there after a reload.",
    "Der Browser-Speicher hat die Aktualisierung abgelehnt. Der Eintrag kann nach dem Neuladen noch vorhanden sein.",
    "Le stockage du navigateur a refusé la mise à jour. Cette entrée peut encore être présente après le rechargement.",
  ],
  "chat.stash.reasonTooLarge": [
    "{{names}} exceeded the stash size limit when this prompt was saved.",
    "{{names}} überschritt beim Speichern dieses Prompts das Größenlimit der Ablage.",
    "{{names}} dépassait la limite de taille de la réserve lors de l’enregistrement de ce prompt.",
  ],
  "chat.stash.reasonUnreadable": [
    "{{names}} could not be read when this prompt was saved.",
    "{{names}} konnte beim Speichern dieses Prompts nicht gelesen werden.",
    "{{names}} n’a pas pu être lu lors de l’enregistrement de ce prompt.",
  ],
  "chat.stash.reasonAttachmentLimit": [
    "{{names}} could not be restored: the composer is at its {{count}}-attachment limit.",
    "{{names}} konnte nicht wiederhergestellt werden: Der Composer hat sein Limit von {{count}} Anhängen erreicht.",
    "{{names}} n’a pas pu être restauré : le composeur a atteint sa limite de {{count}} pièces jointes.",
  ],
  "chat.stash.reasonExpired": [
    "{{names}}: stashed files are kept for 24 hours and this upload expired. Attach the file again.",
    "{{names}}: Abgelegte Dateien werden 24 Stunden aufbewahrt und dieser Upload ist abgelaufen. Datei erneut anhängen.",
    "{{names}} : les fichiers mis en réserve sont conservés 24 heures et cet envoi a expiré. Joignez à nouveau le fichier.",
  ],
  "chat.stash.attachmentsNotRestored": [
    "Some attachments were not restored",
    "Einige Anhänge wurden nicht wiederhergestellt",
    "Certaines pièces jointes n’ont pas été restaurées",
  ],
  "chat.stash.deleteMayReappearTitle": [
    "Stash entry may come back",
    "Der Ablageeintrag kann erneut erscheinen",
    "L’entrée de la réserve peut réapparaître",
  ],
  "chat.stash.deleteMayReappearDescription": [
    "Browser storage rejected the delete, so this prompt could reappear after a reload.",
    "Der Browser-Speicher hat das Löschen abgelehnt. Der Prompt kann nach dem Neuladen erneut erscheinen.",
    "Le stockage du navigateur a refusé la suppression. Ce prompt peut réapparaître après le rechargement.",
  ],
  "chat.stash.attachDroppedFiles": [
    "Attach dropped files again or remove them before stashing",
    "Abgelegte Dateien erneut anhängen oder vor dem Ablegen entfernen",
    "Joignez à nouveau les fichiers déposés ou supprimez-les avant la mise en réserve",
  ],
  "chat.stash.waitForUploads": [
    "Wait for file uploads before stashing this prompt",
    "Vor dem Ablegen dieses Prompts auf die Datei-Uploads warten",
    "Attendez la fin des envois de fichiers avant de mettre ce prompt en réserve",
  ],
  "chat.stash.failedTitle": [
    "Could not stash this prompt",
    "Dieser Prompt konnte nicht abgelegt werden",
    "Impossible de mettre ce prompt en réserve",
  ],
  "chat.stash.failedDescription": [
    "Browser storage rejected the write, so the composer was left as-is. Free up site data and try again.",
    "Der Browser-Speicher hat das Schreiben abgelehnt. Der Composer wurde nicht verändert. Speicherplatz freigeben und erneut versuchen.",
    "Le stockage du navigateur a refusé l’écriture. Le composeur est resté inchangé. Libérez des données du site et réessayez.",
  ],
  "chat.stash.memoryOnlyTitle": [
    "Stashed prompt will not survive a reload",
    "Der abgelegte Prompt bleibt nach dem Neuladen nicht erhalten",
    "Le prompt mis en réserve ne survivra pas à un rechargement",
  ],
  "chat.stash.memoryOnlyDescription": [
    "Browser storage is unavailable, so this stash is kept in memory only for this session.",
    "Der Browser-Speicher ist nicht verfügbar. Diese Ablage wird nur für diese Sitzung im Arbeitsspeicher gehalten.",
    "Le stockage du navigateur est indisponible. Cette réserve est conservée en mémoire uniquement pour cette session.",
  ],
  "chat.stash.oldestDiscardedTitle": [
    "Oldest stashed prompt discarded",
    "Ältester abgelegter Prompt verworfen",
    "Le plus ancien prompt mis en réserve a été supprimé",
  ],
  "chat.stash.oldestDiscardedDescription": [
    "The stash holds {{count}} prompts; the oldest was removed to make room.",
    "Die Ablage enthält {{count}} Prompts. Der älteste wurde entfernt, um Platz zu schaffen.",
    "La réserve contient {{count}} prompts. Le plus ancien a été supprimé pour libérer de la place.",
  ],
  "chat.stash.imagesNotSavedTitle": [
    "Stashed images were not saved",
    "Abgelegte Bilder wurden nicht gespeichert",
    "Les images mises en réserve n’ont pas été enregistrées",
  ],
  "chat.stash.imagesNotSavedDescription": [
    "The prompt was stashed, but browser storage rejected its images. They will be missing if you reload.",
    "Der Prompt wurde abgelegt, aber der Browser-Speicher hat seine Bilder abgelehnt. Nach dem Neuladen fehlen sie.",
    "Le prompt a été mis en réserve, mais le stockage du navigateur a refusé ses images. Elles manqueront après le rechargement.",
  ],
  "chat.stash.imagesDidNotAttachTitle": [
    "Stashed images did not attach",
    "Abgelegte Bilder wurden nicht angehängt",
    "Les images mises en réserve n’ont pas été jointes",
  ],
  "chat.stash.imagesDidNotAttachDescription": [
    {
      one: "That prompt was restored or deleted before {{count}} image finished saving. Re-attach the image if you still need it.",
      other:
        "That prompt was restored or deleted before {{count}} images finished saving. Re-attach them if you still need them.",
    },
    {
      one: "Der Prompt wurde wiederhergestellt oder gelöscht, bevor {{count}} Bild gespeichert war. Hänge das Bild bei Bedarf erneut an.",
      other:
        "Der Prompt wurde wiederhergestellt oder gelöscht, bevor {{count}} Bilder gespeichert waren. Hänge sie bei Bedarf erneut an.",
    },
    {
      one: "Ce prompt a été restauré ou supprimé avant la fin de l’enregistrement de {{count}} image. Joignez-la à nouveau si nécessaire.",
      other:
        "Ce prompt a été restauré ou supprimé avant la fin de l’enregistrement de {{count}} images. Joignez-les à nouveau si nécessaire.",
    },
  ],
  "chat.composer.copyLink": ["Copy link", "Link kopieren", "Copier le lien"],
  "chat.composer.copyClipboard": [
    "Copy to clipboard",
    "In die Zwischenablage kopieren",
    "Copier dans le presse-papiers",
  ],
  "chat.composer.openInEditor": ["Open in editor", "Im Editor öffnen", "Ouvrir dans l’éditeur"],
  "chat.composer.noEditors": [
    "No installed editors found",
    "Keine installierten Editoren gefunden",
    "Aucun éditeur installé trouvé",
  ],
  "chat.composer.favorites": ["Favorites", "Favoriten", "Favoris"],
  "chat.composer.toggleTerminal": [
    "Toggle terminal drawer",
    "Terminal-Bereich umschalten",
    "Basculer le panneau du terminal",
  ],
  "chat.composer.toggleRightPanel": [
    "Toggle right panel",
    "Rechten Bereich umschalten",
    "Basculer le panneau droit",
  ],
  "chat.composer.dismissError": ["Dismiss error", "Fehler ausblenden", "Masquer l’erreur"],
  "chat.contextWindow.title": ["Context window", "Kontextfenster", "Fenêtre de contexte"],
  "chat.contextWindow.usage": [
    "Context window usage",
    "Nutzung des Kontextfensters",
    "Utilisation de la fenêtre de contexte",
  ],
  "chat.contextWindow.totalProcessed": ["Total processed", "Insgesamt verarbeitet", "Total traité"],
  "chat.contextWindow.size": [
    "Context window size",
    "Größe des Kontextfensters",
    "Taille de la fenêtre de contexte",
  ],
  "chat.changedFiles.openDiff": ["Open diff", "Diff öffnen", "Ouvrir le diff"],
  "chat.changedFiles.openFullDiff": [
    "Open the full diff",
    "Vollständigen Diff öffnen",
    "Ouvrir le diff complet",
  ],
  "chat.preview.cropAlt": [
    "Annotated preview crop",
    "Annotierter Vorschauausschnitt",
    "Extrait d’aperçu annoté",
  ],
  "chat.preview.annotation.element": ["element", "Element", "élément"],
  "chat.preview.annotation.region": ["region", "Bereich", "région"],
  "chat.preview.annotation.drawing": ["drawing", "Zeichnung", "dessin"],
  "chat.preview.annotation.style": ["style change", "Stiländerung", "changement de style"],
  "chat.preview.annotation.remove": [
    "Remove preview annotation",
    "Vorschauannotation entfernen",
    "Supprimer l’annotation d’aperçu",
  ],
  "chat.image.expandedPreview": [
    "Expanded image preview",
    "Vergrößerte Bildvorschau",
    "Aperçu agrandi de l’image",
  ],
  "chat.image.closePreview": [
    "Close image preview",
    "Bildvorschau schließen",
    "Fermer l’aperçu de l’image",
  ],
  "chat.image.previous": ["Previous image", "Vorheriges Bild", "Image précédente"],
  "chat.image.next": ["Next image", "Nächstes Bild", "Image suivante"],
  "chat.model.new": ["New model", "Neues Modell", "Nouveau modèle"],
  "chat.model.vision": ["Vision", "Bildverarbeitung", "Vision"],
  "chat.model.legacy": ["Legacy models", "Legacy-Modelle", "Modèles hérités"],
  "chat.model.count": [
    { one: "{{count}} model", other: "{{count}} models" },
    { one: "{{count}} Modell", other: "{{count}} Modelle" },
    { one: "{{count}} modèle", other: "{{count}} modèles" },
  ],
  "chat.model.search": ["Search models…", "Modelle suchen…", "Rechercher des modèles…"],
  "chat.model.searchOpenRouter": [
    "Search OpenRouter models…",
    "OpenRouter-Modelle suchen…",
    "Rechercher des modèles OpenRouter…",
  ],
  "chat.catalog.label": [
    "OpenRouter model catalog",
    "OpenRouter-Modellkatalog",
    "Catalogue de modèles OpenRouter",
  ],
  "chat.catalog.reset": ["Reset", "Zurücksetzen", "Réinitialiser"],
  "chat.catalog.resetFilters": [
    "Reset filters",
    "Filter zurücksetzen",
    "Réinitialiser les filtres",
  ],
  "chat.catalog.filters": ["Catalog filters", "Katalogfilter", "Filtres du catalogue"],
  "chat.catalog.refinement": [
    "Catalog refinement",
    "Katalogverfeinerung",
    "Affinement du catalogue",
  ],
  "chat.catalog.minimumContext": ["Minimum context", "Minimaler Kontext", "Contexte minimal"],
  "chat.catalog.anyContext": ["Any context", "Beliebiger Kontext", "Tout contexte"],
  "chat.catalog.modelCreators": ["Model creators", "Modellersteller", "Créateurs de modèles"],
  "chat.catalog.sortModels": ["Sort models", "Modelle sortieren", "Trier les modèles"],
  "chat.catalog.badge": ["Catalog", "Katalog", "Catalogue"],
  "chat.catalog.modelCount": [
    { one: "{{matching}} of {{total}} model", other: "{{matching}} of {{total}} models" },
    { one: "{{matching}} von {{total}} Modell", other: "{{matching}} von {{total}} Modellen" },
    { one: "{{matching}} modèle sur {{total}}", other: "{{matching}} modèles sur {{total}}" },
  ],
  "chat.catalog.contextPrefix": [
    "Context: {{label}}",
    "Kontext: {{label}}",
    "Contexte : {{label}}",
  ],
  "chat.catalog.creators": ["Creators", "Ersteller", "Créateurs"],
  "chat.catalog.creatorsCount": [
    "Creators ({{count}})",
    "Ersteller ({{count}})",
    "Créateurs ({{count}})",
  ],
  "chat.catalog.clearCreators": ["Clear creators", "Ersteller leeren", "Effacer les créateurs"],
  "chat.catalog.sortPrefix": ["Sort: {{label}}", "Sortierung: {{label}}", "Tri : {{label}}"],
  "chat.plan.label": ["Plan", "Plan", "Plan"],
  "chat.plan.actions": ["Plan actions", "Planaktionen", "Actions du plan"],
  "chat.plan.downloadMarkdown": [
    "Download as markdown",
    "Als Markdown herunterladen",
    "Télécharger en Markdown",
  ],
  "chat.plan.saveTitle": [
    "Save plan to workspace",
    "Plan im Workspace speichern",
    "Enregistrer le plan dans l’espace de travail",
  ],
  "chat.plan.workspacePath": ["Workspace path", "Workspace-Pfad", "Chemin de l’espace de travail"],
  "chat.speechIndex.privacy": [
    "AssemblyAI indexing privacy",
    "Datenschutz bei AssemblyAI-Indizierung",
    "Confidentialité de l’indexation AssemblyAI",
  ],
  "chat.speechIndex.setupTitle": [
    "Set up speech recognition for {{project}}",
    "Spracherkennung für {{project}} einrichten",
    "Configurer la reconnaissance vocale pour {{project}}",
  ],
  "chat.speechIndex.description": [
    "Give AssemblyAI a small vocabulary tailored to this project.",
    "AssemblyAI ein kleines, auf dieses Projekt zugeschnittenes Vokabular bereitstellen.",
    "Fournissez à AssemblyAI un petit vocabulaire adapté à ce projet.",
  ],
  "chat.speechIndex.privacyPrefix": [
    "Indexing extracts only",
    "Die Indizierung extrahiert nur",
    "L’indexation extrait uniquement",
  ],
  "chat.speechIndex.privacySuffix": [
    "for AssemblyAI. No source snippets are sent.",
    "für AssemblyAI. Es werden keine Quelltextausschnitte gesendet.",
    "pour AssemblyAI. Aucun extrait de code source n’est envoyé.",
  ],
  "chat.speechIndex.creatingBasic": [
    "Creating basic speech context from project metadata.",
    "Einfacher Sprachkontext wird aus Projektmetadaten erstellt.",
    "Création d’un contexte vocal de base à partir des métadonnées du projet.",
  ],
  "chat.speechIndex.indexing": [
    "Indexing project terminology and technology names. No source snippets are sent.",
    "Projektbegriffe und Technologienamen werden indiziert. Es werden keine Quelltextausschnitte gesendet.",
    "Indexation de la terminologie du projet et des noms de technologies. Aucun extrait de code source n’est envoyé.",
  ],
  "chat.speechIndex.basicReady": [
    "Basic speech context will be used for AssemblyAI. You can index this project later.",
    "Für AssemblyAI wird einfacher Sprachkontext verwendet. Das Projekt kann später indiziert werden.",
    "Un contexte vocal de base sera utilisé pour AssemblyAI. Vous pourrez indexer ce projet plus tard.",
  ],
  "chat.speechIndex.failed": [
    "Project indexing could not be completed.",
    "Die Projektindizierung konnte nicht abgeschlossen werden.",
    "L’indexation du projet n’a pas pu être effectuée.",
  ],
  "chat.speechIndex.createFailed": [
    "Could not create speech context",
    "Sprachkontext konnte nicht erstellt werden",
    "Impossible de créer le contexte vocal",
  ],
  "chat.speechIndex.basicCreateTitle": [
    "Could not create basic context",
    "Einfacher Kontext konnte nicht erstellt werden",
    "Impossible de créer le contexte de base",
  ],
  "chat.speechIndex.basicCreateFailed": [
    "Basic context could not be created.",
    "Einfacher Kontext konnte nicht erstellt werden.",
    "Le contexte de base n’a pas pu être créé.",
  ],
  "chat.speechIndex.progress": [
    "Project indexing progress",
    "Fortschritt der Projektindizierung",
    "Progression de l’indexation du projet",
  ],
  "chat.speechIndex.notNow": ["Not now", "Nicht jetzt", "Pas maintenant"],
  "chat.speechIndex.basicContext": [
    "Use basic context",
    "Einfachen Kontext verwenden",
    "Utiliser le contexte de base",
  ],
  "chat.speechIndex.indexProject": ["Index project", "Projekt indizieren", "Indexer le projet"],
  "chat.speechIndex.terminology": [
    "project terminology and technology names",
    "Projektbegriffe und Technologienamen",
    "terminologie du projet et noms de technologies",
  ],
  "chat.speechIndex.basicFallback": [
    "Basic speech context will be used instead.",
    "Stattdessen wird einfacher Sprachkontext verwendet.",
    "Le contexte vocal de base sera utilisé à la place.",
  ],
  "chat.changedFiles.count": [
    { one: "{{count}} changed file", other: "{{count}} changed files" },
    { one: "{{count}} geänderte Datei", other: "{{count}} geänderte Dateien" },
    { one: "{{count}} fichier modifié", other: "{{count}} fichiers modifiés" },
  ],
  "chat.changedFiles.scopeCount": [
    { one: "{{count}} file", other: "{{count}} files" },
    { one: "{{count}} Datei", other: "{{count}} Dateien" },
    { one: "{{count}} fichier", other: "{{count}} fichiers" },
  ],
  "chat.changedFiles.hide": ["Hide files", "Dateien ausblenden", "Masquer les fichiers"],
  "chat.changedFiles.show": ["Show files", "Dateien anzeigen", "Afficher les fichiers"],
  "chat.changedFiles.showAll": [
    { one: "Show all {{count}} file", other: "Show all {{count}} files" },
    { one: "Alle {{count}} Datei anzeigen", other: "Alle {{count}} Dateien anzeigen" },
    { one: "Afficher {{count}} fichier", other: "Afficher les {{count}} fichiers" },
  ],
  "chat.changedFiles.collapseFolders": [
    "Collapse all folders",
    "Alle Ordner einklappen",
    "Réduire tous les dossiers",
  ],
  "chat.changedFiles.expandFolders": [
    "Expand all folders",
    "Alle Ordner ausklappen",
    "Développer tous les dossiers",
  ],
  "chat.composer.interaction.build": ["Build", "Erstellen", "Créer"],
  "chat.composer.interaction.buildDescription": [
    "Work directly on the task",
    "Direkt an der Aufgabe arbeiten",
    "Travailler directement sur la tâche",
  ],
  "chat.composer.interaction.planDescription": [
    "Explore and agree on a plan before implementation",
    "Vor der Umsetzung einen Plan untersuchen und abstimmen",
    "Explorer et convenir d’un plan avant l’implémentation",
  ],
  "chat.composer.tasks.completed": ["Completed", "Abgeschlossen", "Terminée"],
  "chat.composer.tasks.inProgress": ["In progress", "In Bearbeitung", "En cours"],
  "chat.composer.tasks.pending": ["Pending", "Ausstehend", "En attente"],
  "chat.composer.tasks.now": ["Now", "Jetzt", "Maintenant"],
  "chat.composer.terminalUnavailable": [
    "Terminal drawer is unavailable",
    "Terminal-Bereich ist nicht verfügbar",
    "Le panneau du terminal est indisponible",
  ],
  "chat.composer.rightPanelUnavailable": [
    "Right panel is unavailable",
    "Rechter Bereich ist nicht verfügbar",
    "Le panneau droit est indisponible",
  ],
  "chat.composer.restorePanel": [
    "Restore panel size",
    "Bereichsgröße wiederherstellen",
    "Restaurer la taille du panneau",
  ],
  "chat.composer.maximizePanel": ["Maximize panel", "Bereich maximieren", "Agrandir le panneau"],
  "chat.preview.openImage": ["Preview {{name}}", "Vorschau von {{name}}", "Aperçu de {{name}}"],
  "chat.preview.retryUpload": [
    "Retry upload for {{name}}",
    "Upload für {{name}} erneut versuchen",
    "Réessayer l’envoi de {{name}}",
  ],
  "chat.model.free": ["Free", "Kostenlos", "Gratuit"],
  "chat.model.reasoning": ["Reasoning", "Reasoning", "Raisonnement"],
  "chat.model.context": ["{{tokens}} context", "{{tokens}} Kontext", "Contexte {{tokens}}"],
  "chat.model.addFavorite": [
    "Add {{model}} to favorites",
    "{{model}} zu Favoriten hinzufügen",
    "Ajouter {{model}} aux favoris",
  ],
  "chat.model.removeFavorite": [
    "Remove {{model}} from favorites",
    "{{model}} aus Favoriten entfernen",
    "Retirer {{model}} des favoris",
  ],
  "chat.model.newBadge": ["New", "Neu", "Nouveau"],
  "chat.model.unavailable": ["Unavailable", "Nicht verfügbar", "Indisponible"],
  "chat.model.startNewThreadReason": [
    "{{reason}} Start a new thread to use this model.",
    "{{reason}} Starte einen neuen Thread, um dieses Modell zu verwenden.",
    "{{reason}} Démarrez un nouveau fil pour utiliser ce modèle.",
  ],
  "chat.plan.copyFailed": [
    "Could not copy plan",
    "Plan konnte nicht kopiert werden",
    "Impossible de copier le plan",
  ],
  "chat.plan.copyError": [
    "An error occurred while copying.",
    "Beim Kopieren ist ein Fehler aufgetreten.",
    "Une erreur est survenue lors de la copie.",
  ],
  "chat.plan.workspaceUnavailable": [
    "Workspace path is unavailable",
    "Workspace-Pfad ist nicht verfügbar",
    "Le chemin de l’espace de travail est indisponible",
  ],
  "chat.plan.workspaceUnavailableDescription": [
    "This thread does not have a workspace path to save into.",
    "Dieser Thread hat keinen Workspace-Pfad zum Speichern.",
    "Ce fil ne possède pas de chemin d’espace de travail où enregistrer le plan.",
  ],
  "chat.plan.saved": [
    "Plan saved to workspace",
    "Plan im Workspace gespeichert",
    "Plan enregistré dans l’espace de travail",
  ],
  "chat.plan.saveFailed": [
    "Could not save plan",
    "Plan konnte nicht gespeichert werden",
    "Impossible d’enregistrer le plan",
  ],
  "chat.plan.saveError": [
    "An error occurred while saving.",
    "Beim Speichern ist ein Fehler aufgetreten.",
    "Une erreur est survenue lors de l’enregistrement.",
  ],
  "chat.plan.copied": ["Copied!", "Kopiert!", "Copié !"],
  "chat.plan.saveWorkspace": [
    "Save to workspace",
    "Im Workspace speichern",
    "Enregistrer dans l’espace de travail",
  ],
  "chat.plan.collapse": ["Collapse plan", "Plan einklappen", "Réduire le plan"],
  "chat.plan.expand": ["Expand plan", "Plan ausklappen", "Développer le plan"],
  "chat.plan.relativePath": [
    "Enter a path relative to {{workspace}}.",
    "Pfad relativ zu {{workspace}} eingeben.",
    "Saisissez un chemin relatif à {{workspace}}.",
  ],
  "chat.plan.workspace": ["the workspace", "dem Workspace", "l’espace de travail"],
  "chat.plan.saving": ["Saving…", "Wird gespeichert…", "Enregistrement…"],
  "chat.plan.save": ["Save", "Speichern", "Enregistrer"],
  "chat.plan.implementationThreadFailed": [
    "Could not start implementation thread",
    "Implementierungs-Thread konnte nicht gestartet werden",
    "Impossible de démarrer le fil d’implémentation",
  ],
  "chat.plan.implementationThreadError": [
    "An error occurred while creating the new thread.",
    "Beim Erstellen des neuen Threads ist ein Fehler aufgetreten.",
    "Une erreur est survenue lors de la création du nouveau fil.",
  ],
  "chat.openIn.preferred": [
    "Open file in preferred editor",
    "Datei im bevorzugten Editor öffnen",
    "Ouvrir le fichier dans l’éditeur préféré",
  ],
  "chat.openIn.chooseEditor": ["Choose editor", "Editor auswählen", "Choisir un éditeur"],
  "chat.openIn.copyOptions": ["Copy options", "Kopieroptionen", "Options de copie"],
  "chat.openIn.noSshRoute": [
    "No SSH route to {{environment}}",
    "Keine SSH-Route zu {{environment}}",
    "Aucune route SSH vers {{environment}}",
  ],
  "chat.openIn.sshHint": [
    "Opens over SSH. Needs your key on {{environment}}",
    "Wird über SSH geöffnet. Benötigt deinen Schlüssel auf {{environment}}",
    "S’ouvre via SSH. Nécessite votre clé sur {{environment}}",
  ],
  "chat.openIn.thisMachine": ["this machine", "diesem Gerät", "cette machine"],
  "chat.copy.failed": ["Failed to copy", "Kopieren fehlgeschlagen", "Échec de la copie"],
  "chat.copy.copied": ["Copied!", "Kopiert!", "Copié !"],
  "chat.contextWindow.usedPercent": [
    "Context window {{percent}} used",
    "Kontextfenster zu {{percent}} verwendet",
    "Fenêtre de contexte utilisée à {{percent}}",
  ],
  "chat.contextWindow.tokensUsed": [
    "Context window: {{tokens}} tokens used",
    "Kontextfenster: {{tokens}} Tokens verwendet",
    "Fenêtre de contexte : {{tokens}} jetons utilisés",
  ],
  "chat.contextWindow.pickerLabel": [
    "Context window: {{label}}",
    "Kontextfenster: {{label}}",
    "Fenêtre de contexte : {{label}}",
  ],
  "chat.contextWindow.savedDescription": [
    "Saved for this chat and applied to the next Codex turn.",
    "Wird für diesen Chat gespeichert und auf den nächsten Codex-Turn angewendet.",
    "Enregistré pour ce chat et appliqué au prochain tour Codex.",
  ],
  "chat.contextWindow.modelDefault": ["Model default", "Modellstandard", "Valeur du modèle"],
  "chat.contextWindow.custom": ["Custom", "Benutzerdefiniert", "Personnalisé"],
  "chat.composer.access.supervisedDescription": [
    "Ask before commands and file changes.",
    "Vor Befehlen und Dateiänderungen nachfragen.",
    "Demander avant les commandes et les modifications de fichiers.",
  ],
  "chat.composer.access.autoAcceptDescription": [
    "Auto-approve edits, ask before other actions.",
    "Änderungen automatisch genehmigen, vor anderen Aktionen nachfragen.",
    "Approuver automatiquement les modifications, demander avant les autres actions.",
  ],
  "chat.composer.access.autoDescription": [
    "Supported providers approve routine actions; others still ask.",
    "Unterstützte Provider genehmigen Routineaktionen; andere fragen weiterhin nach.",
    "Les fournisseurs compatibles approuvent les actions courantes ; les autres demandent encore.",
  ],
  "chat.composer.access.fullDescription": [
    "Allow commands and edits without prompts.",
    "Befehle und Änderungen ohne Rückfrage zulassen.",
    "Autoriser les commandes et les modifications sans confirmation.",
  ],
  "chat.composer.draftAttachmentWarningDetail": [
    "Draft attachment could not be saved locally and may be lost on navigation.",
    "Der Entwurfsanhang konnte nicht lokal gespeichert werden und kann beim Navigieren verloren gehen.",
    "La pièce jointe du brouillon n’a pas pu être enregistrée localement et peut être perdue lors de la navigation.",
  ],
  "chat.composer.customAnswerPlaceholder": [
    "Type your own answer, or leave this blank to use the selected option",
    "Eigene Antwort eingeben oder leer lassen, um die ausgewählte Option zu verwenden",
    "Saisissez votre propre réponse ou laissez vide pour utiliser l’option sélectionnée",
  ],
  "chat.composer.enableProvider": [
    "Enable a provider in Settings",
    "Provider in den Einstellungen aktivieren",
    "Activez un fournisseur dans les réglages",
  ],
  "chat.composer.askAnything": ["Ask anything…", "Frag etwas…", "Posez une question…"],
  "chat.composer.fastModeOn": ["Fast mode on", "Schnellmodus aktiv", "Mode rapide activé"],
  "chat.composer.command.searchingSkills": [
    "Searching workspace skills...",
    "Workspace-Skills werden gesucht...",
    "Recherche des compétences de l’espace de travail...",
  ],
  "chat.composer.command.searchingFiles": [
    "Searching workspace files...",
    "Workspace-Dateien werden gesucht...",
    "Recherche des fichiers de l’espace de travail...",
  ],
  "chat.composer.command.noSkills": [
    "No skills found. Try / to browse provider commands.",
    "Keine Skills gefunden. Mit / kannst du Provider-Befehle durchsuchen.",
    "Aucune compétence trouvée. Utilisez / pour parcourir les commandes du fournisseur.",
  ],
  "chat.composer.command.noFiles": [
    "No matching files or folders.",
    "Keine passenden Dateien oder Ordner.",
    "Aucun fichier ou dossier correspondant.",
  ],
  "chat.composer.command.noCommand": [
    "No matching command.",
    "Kein passender Befehl.",
    "Aucune commande correspondante.",
  ],
  "chat.composer.command.skillPrefix": ["/skill:", "/skill:", "/skill:"],
  "chat.approval.cancel": ["Cancel", "Abbrechen", "Annuler"],
  "chat.approval.decline": ["Decline", "Ablehnen", "Refuser"],
  "chat.approval.alwaysAllowSession": [
    "Always allow this session",
    "Für diese Sitzung immer zulassen",
    "Toujours autoriser pour cette session",
  ],
  "chat.approval.approve": ["Approve", "Genehmigen", "Approuver"],
  "chat.stash.label": ["Stash", "Ablage", "Réserve"],
  "chat.stash.listAria": ["Stashed prompts", "Abgelegte Prompts", "Prompts mis en réserve"],
  "chat.stash.restoreAria": [
    "Restore stashed prompt: {{prompt}}",
    "Abgelegten Prompt wiederherstellen: {{prompt}}",
    "Restaurer le prompt mis en réserve : {{prompt}}",
  ],
  "chat.stash.openAria": [
    "Stashed prompts: {{count}}. Open stash.",
    "Abgelegte Eingaben: {{count}}. Ablage öffnen.",
    "Invites mises en réserve : {{count}}. Ouvrir la réserve.",
  ],
  "chat.stash.none": [
    "Nothing stashed yet.",
    "Noch nichts abgelegt.",
    "Aucun élément dans la réserve.",
  ],
  "chat.stash.shortcutHint": [
    "Press {{shortcut}} with a prompt in the composer to stash it.",
    "Drücke bei einer Eingabe im Composer {{shortcut}}, um sie abzulegen.",
    "Appuyez sur {{shortcut}} lorsqu’une invite est dans le composeur pour la mettre en réserve.",
  ],
  "chat.stash.emptyEntry": ["(empty)", "(leer)", "(vide)"],
  "chat.stash.attachmentCount": [
    { one: "{{count}} attachment", other: "{{count}} attachments" },
    { one: "{{count}} Anhang", other: "{{count}} Anhänge" },
    { one: "{{count}} pièce jointe", other: "{{count}} pièces jointes" },
  ],
  "chat.stash.fileCount": [
    { one: "{{count}} file", other: "{{count}} files" },
    { one: "{{count}} Datei", other: "{{count}} Dateien" },
    { one: "{{count}} fichier", other: "{{count}} fichiers" },
  ],
  "chat.stash.imageCount": [
    { one: "{{count}} image", other: "{{count}} images" },
    { one: "{{count}} Bild", other: "{{count}} Bilder" },
    { one: "{{count}} image", other: "{{count}} images" },
  ],
  "chat.stash.savingImages": [
    { one: "saving {{count}} image…", other: "saving {{count}} images…" },
    { one: "{{count}} Bild wird gespeichert…", other: "{{count}} Bilder werden gespeichert…" },
    {
      one: "enregistrement de {{count}} image…",
      other: "enregistrement de {{count}} images…",
    },
  ],
  "chat.stash.droppedImages": [
    { one: "{{count}} image dropped", other: "{{count}} images dropped" },
    { one: "{{count}} Bild verworfen", other: "{{count}} Bilder verworfen" },
    { one: "{{count}} image ignorée", other: "{{count}} images ignorées" },
  ],
  "chat.contextWindow.compact": [
    "Compact context",
    "Kontext komprimieren",
    "Compacter le contexte",
  ],
  "chat.fork.handoffBudget": [
    "The complete fork history and all attachments are carried over separately. Nothing inherited is removed; normal limits apply only to this new message.",
    "Der vollständige Fork-Verlauf und alle Anhänge werden separat übernommen. Nichts Geerbtes wird entfernt; normale Grenzen gelten nur für diese neue Nachricht.",
    "L’historique complet du fork et toutes les pièces jointes sont repris séparément. Aucun élément hérité n’est supprimé ; les limites habituelles ne s’appliquent qu’à ce nouveau message.",
  ],
  "chat.model.noneFound": ["No models found", "Keine Modelle gefunden", "Aucun modèle trouvé"],
  "chat.plan.enterWorkspacePath": [
    "Enter a workspace path",
    "Workspace-Pfad eingeben",
    "Saisissez un chemin d’espace de travail",
  ],
  "chat.timeline.workingFor": ["Working for", "Arbeitet seit", "Travaille depuis"],
  "chat.timeline.working": ["Working...", "Arbeitet...", "En cours..."],
  "chat.timeline.modelReasoning": ["Model reasoning", "Modellbegründung", "Raisonnement du modèle"],
  "chat.timeline.toolCalls": [
    { one: "{{count}} tool call", other: "{{count}} tool calls" },
    { one: "{{count}} Tool-Aufruf", other: "{{count}} Tool-Aufrufe" },
    { one: "{{count}} appel d’outil", other: "{{count}} appels d’outil" },
  ],
  "chat.timeline.workLog": ["Work log", "Arbeitsprotokoll", "Journal de travail"],
  "chat.timeline.toolCallFailedAria": [
    "{{summary}}, tool call failed",
    "{{summary}}, Tool-Aufruf fehlgeschlagen",
    "{{summary}}, échec de l’appel d’outil",
  ],
  "chat.timeline.showFewerToolCalls": [
    "Show fewer tool calls",
    "Weniger Tool-Aufrufe anzeigen",
    "Afficher moins d’appels d’outils",
  ],
  "chat.timeline.showFewerLogEntries": [
    "Show fewer log entries",
    "Weniger Protokolleinträge anzeigen",
    "Afficher moins d’entrées du journal",
  ],
  "chat.timeline.previousToolCalls": [
    { one: "{{count}} previous tool call", other: "{{count}} previous tool calls" },
    { one: "{{count}} vorheriger Tool-Aufruf", other: "{{count}} vorherige Tool-Aufrufe" },
    { one: "{{count}} appel d’outil précédent", other: "{{count}} appels d’outils précédents" },
  ],
  "chat.timeline.previousLogEntries": [
    { one: "{{count}} previous log entry", other: "{{count}} previous log entries" },
    {
      one: "{{count}} vorheriger Protokolleintrag",
      other: "{{count}} vorherige Protokolleinträge",
    },
    {
      one: "{{count}} entrée précédente du journal",
      other: "{{count}} entrées précédentes du journal",
    },
  ],
  "chat.timeline.previousIncludesFailure": [
    "+{{entries}}, includes a failure",
    "+{{entries}}, enthält einen Fehler",
    "+{{entries}}, contient un échec",
  ],
  "chat.timeline.subagentsStarted": [
    { one: "Kicked off {{count}} subagent", other: "Kicked off {{count}} subagents" },
    { one: "{{count}} Subagent gestartet", other: "{{count}} Subagents gestartet" },
    { one: "{{count}} sous-agent lancé", other: "{{count}} sous-agents lancés" },
  ],
  "chat.timeline.subagentsRan": [
    { one: "Ran {{count}} subagent", other: "Ran {{count}} subagents" },
    { one: "{{count}} Subagent ausgeführt", other: "{{count}} Subagents ausgeführt" },
    { one: "{{count}} sous-agent exécuté", other: "{{count}} sous-agents exécutés" },
  ],
  "chat.timeline.phaseWorking": [
    "{{phase}} · {{count}} working",
    "{{phase}} · {{count}} aktiv",
    "{{phase}} · {{count}} en cours",
  ],
  "chat.timeline.workingCount": ["{{count}} working", "{{count}} aktiv", "{{count}} en cours"],
  "chat.timeline.failedCount": [
    "{{count}} failed",
    "{{count}} fehlgeschlagen",
    "{{count}} en échec",
  ],
  "chat.timeline.completedCheck": ["✓ completed", "✓ abgeschlossen", "✓ terminé"],
  "chat.timeline.inputTokens": ["Input", "Eingabe", "Entrée"],
  "chat.timeline.outputTokens": ["Output", "Ausgabe", "Sortie"],
  "chat.timeline.totalTokens": ["Total", "Gesamt", "Total"],
  "chat.traits.default": ["Default", "Standard", "Par défaut"],
  "chat.traits.auto": ["Auto", "Auto", "Auto"],
  "chat.traits.autoDescription": [
    "Selects the reasoning level automatically.",
    "Wählt die Reasoning-Stufe automatisch.",
    "Sélectionne automatiquement le niveau de raisonnement.",
  ],
  "chat.traits.ultrathinkLocked": [
    'Your prompt contains "ultrathink" in the text. Remove it to change this option.',
    'Deine Eingabe enthält "ultrathink" im Text. Entferne es, um diese Option zu ändern.',
    'Votre invite contient "ultrathink" dans le texte. Retirez-le pour modifier cette option.',
  ],
  "chat.catalog.quickContext": ["128K+", "128K+", "128K+"],
  "chat.composer.analyzingPlan": ["Analyzing plan…", "Plan wird analysiert…", "Analyse du plan…"],
  "chat.composer.planReviewFallback": [
    "AI review unavailable; using plan structure estimate.",
    "KI-Prüfung nicht verfügbar; die Schätzung aus der Planstruktur wird verwendet.",
    "Révision par l’IA indisponible ; estimation basée sur la structure du plan.",
  ],
  "chat.composer.implement": ["Implement", "Implementieren", "Implémenter"],
  "chat.composer.implementNewThread": [
    "Implement in a new thread",
    "In einem neuen Thread implementieren",
    "Implémenter dans un nouveau fil",
  ],
  "chat.composer.implementNormally": [
    "Implement normally",
    "Normal implementieren",
    "Implémenter normalement",
  ],
  "chat.composer.implementNormallyNewThread": [
    "Implement normally in a new thread",
    "Normal in einem neuen Thread implementieren",
    "Implémenter normalement dans un nouveau fil",
  ],
  "chat.composer.implementWithSubagents": [
    { one: "Implement with {{count}} subagent", other: "Implement with {{count}} subagents" },
    {
      one: "Mit {{count}} Subagent implementieren",
      other: "Mit {{count}} Subagents implementieren",
    },
    {
      one: "Implémenter avec {{count}} sous-agent",
      other: "Implémenter avec {{count}} sous-agents",
    },
  ],
  "chat.composer.implementWithSubagentsNewThread": [
    {
      one: "Implement with {{count}} subagent in a new thread",
      other: "Implement with {{count}} subagents in a new thread",
    },
    {
      one: "Mit {{count}} Subagent in einem neuen Thread implementieren",
      other: "Mit {{count}} Subagents in einem neuen Thread implementieren",
    },
    {
      one: "Implémenter avec {{count}} sous-agent dans un nouveau fil",
      other: "Implémenter avec {{count}} sous-agents dans un nouveau fil",
    },
  ],
  "chat.composer.subagentCount": [
    { one: "{{count}} subagent", other: "{{count}} subagents" },
    { one: "{{count}} Subagent", other: "{{count}} Subagents" },
    { one: "{{count}} sous-agent", other: "{{count}} sous-agents" },
  ],
  "chat.composer.submitting": ["Submitting...", "Wird gesendet...", "Envoi..."],
  "chat.composer.submit": ["Submit", "Senden", "Envoyer"],
  "chat.composer.next": ["Next", "Weiter", "Suivant"],
  "chat.composer.nextQuestion": ["Next question", "Nächste Frage", "Question suivante"],
  "chat.composer.submitAnswers": ["Submit answers", "Antworten senden", "Envoyer les réponses"],
  "chat.composer.submitAnswer": ["Submit answer", "Antwort senden", "Envoyer la réponse"],
  "chat.composer.showOtherNotices": [
    "Show other notices",
    "Weitere Hinweise anzeigen",
    "Afficher les autres notifications",
  ],
  "chat.composer.forceStoppingGeneration": [
    "Force stopping generation",
    "Generierung wird zwangsweise beendet",
    "Arrêt forcé de la génération",
  ],
  "chat.composer.forceStopGeneration": [
    "Force stop generation",
    "Generierung zwangsweise beenden",
    "Forcer l’arrêt de la génération",
  ],
  "chat.composer.stopGeneration": [
    "Stop generation",
    "Generierung stoppen",
    "Arrêter la génération",
  ],
  "chat.composer.sendingProgress": ["Sending...", "Wird gesendet...", "Envoi..."],
  "chat.composer.refine": ["Refine", "Verfeinern", "Affiner"],
  "chat.composer.environmentDisconnected": [
    "Environment disconnected",
    "Umgebung getrennt",
    "Environnement déconnecté",
  ],
  "chat.composer.connecting": ["Connecting", "Verbindung wird hergestellt", "Connexion"],
  "chat.composer.preparingWorktreeLabel": [
    "Preparing worktree",
    "Worktree wird vorbereitet",
    "Préparation du worktree",
  ],
  "chat.composer.sending": ["Sending", "Wird gesendet", "Envoi"],
  "chat.composer.sendMessage": ["Send message", "Nachricht senden", "Envoyer le message"],
});

export type ChatInterfaceMessageKey = (typeof chatInterfaceCatalog.keys)[number];
