import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const settingsMcpInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "settings.mcp.store.title": [
    "Browse tools & skills",
    "Tools & Skills entdecken",
    "Explorer les outils et compétences",
  ],
  "settings.mcp.store.browse": ["Browse", "Entdecken", "Explorer"],
  "settings.mcp.store.kind": ["Item type", "Eintragstyp", "Type d’élément"],
  "settings.mcp.store.installedDescription": [
    "Manage what you’ve added to this environment and project.",
    "Verwalte, was du dieser Umgebung und diesem Projekt hinzugefügt hast.",
    "Gérez les éléments ajoutés à cet environnement et à ce projet.",
  ],
  "settings.mcp.store.installedServers": [
    "Installed MCP servers",
    "Installierte MCP-Server",
    "Serveurs MCP installés",
  ],
  "settings.mcp.store.installedSkills": [
    "Installed skills",
    "Installierte Skills",
    "Compétences installées",
  ],
  "settings.mcp.store.notInstalled": ["Not installed", "Nicht installiert", "Non installé"],
  "settings.mcp.store.manage": ["Manage", "Verwalten", "Gérer"],
  "settings.mcp.store.activeProviders": [
    "Active providers",
    "Aktive Provider",
    "Fournisseurs actifs",
  ],
  "settings.mcp.store.noActiveProviders": [
    "No active providers available. Enable a provider in Settings → Providers.",
    "Keine aktiven Provider verfügbar. Aktiviere einen unter Einstellungen → Provider.",
    "Aucun fournisseur actif. Activez-en un dans Réglages → Fournisseurs.",
  ],
  "settings.mcp.store.sharedSkills": [
    "Skills are shared across providers in the selected scope.",
    "Skills werden im gewählten Bereich von allen Providern gemeinsam genutzt.",
    "Les compétences sont partagées entre les fournisseurs dans la portée choisie.",
  ],
  "settings.mcp.store.skills": ["Skills", "Skills", "Compétences"],
  "settings.mcp.store.servers": ["MCP servers", "MCP-Server", "Serveurs MCP"],
  "settings.mcp.store.description": [
    "Explore the catalog. Add what you need to your installed tools and skills.",
    "Entdecke den Katalog und ergänze deine installierten Tools und Skills.",
    "Explorez le catalogue et ajoutez des outils et compétences à votre collection.",
  ],
  "settings.mcp.store.mcpDescription": [
    "Connect services, data, and tools from the official MCP Registry.",
    "Verbinde Dienste, Daten und Tools aus dem offiziellen MCP-Register.",
    "Connectez des services, des données et des outils du registre MCP officiel.",
  ],
  "settings.mcp.store.skillDescription": [
    "Discover reusable instructions from the skills.sh community catalog.",
    "Entdecke wiederverwendbare Anleitungen im Community-Katalog von skills.sh.",
    "Découvrez les instructions réutilisables du catalogue communautaire skills.sh.",
  ],
  "settings.mcp.store.search": [
    "Search the registry",
    "Register durchsuchen",
    "Rechercher dans le registre",
  ],
  "settings.mcp.store.searchMcp": [
    "Search servers, e.g. GitHub or Playwright",
    "Server suchen, z. B. GitHub oder Playwright",
    "Rechercher des serveurs, par ex. GitHub ou Playwright",
  ],
  "settings.mcp.store.searchSkills": [
    "Search skills, e.g. React or code review",
    "Skills suchen, z. B. React oder Code-Review",
    "Rechercher des compétences, par ex. React ou revue de code",
  ],
  "settings.mcp.store.suggestions": [
    "Suggested skills to get started. Choose one to preview and install.",
    "Skill-Vorschläge für den Einstieg. Wähle einen aus, um ihn anzusehen und zu installieren.",
    "Suggestions pour commencer. Choisissez une compétence pour la découvrir et l’installer.",
  ],
  "settings.mcp.store.searching": [
    "Searching the registry…",
    "Register wird durchsucht…",
    "Recherche dans le registre…",
  ],
  "settings.mcp.store.noResults": [
    "No matches. Try a different search.",
    "Keine Treffer. Versuche einen anderen Suchbegriff.",
    "Aucun résultat. Essayez une autre recherche.",
  ],
  "settings.mcp.store.retry": ["Try again", "Erneut versuchen", "Réessayer"],
  "settings.mcp.store.next": ["More results", "Weitere Ergebnisse", "Plus de résultats"],
  "settings.mcp.store.back": [
    "Back to first results",
    "Zurück zu den ersten Ergebnissen",
    "Revenir aux premiers résultats",
  ],
  "settings.mcp.store.source": ["View source", "Quelle ansehen", "Voir la source"],
  "settings.mcp.store.openExternal": [
    "Open in browser",
    "Im Browser öffnen",
    "Ouvrir dans le navigateur",
  ],
  "settings.mcp.store.sourceLoading": [
    "Loading source page…",
    "Quellseite wird geladen…",
    "Chargement de la page source…",
  ],
  "settings.mcp.store.sourceFailed": [
    "The source page could not be loaded. Try again or open it in your browser.",
    "Die Quellseite konnte nicht geladen werden. Versuche es erneut oder öffne sie im Browser.",
    "La page source n’a pas pu être chargée. Réessayez ou ouvrez-la dans votre navigateur.",
  ],
  "settings.mcp.store.sourceDesktop": [
    "The full source page can be viewed here in the desktop app. You can also open it in your browser.",
    "In der Desktop-App kannst du die vollständige Quellseite hier ansehen. Du kannst sie auch im Browser öffnen.",
    "L’application de bureau affiche ici la page source complète. Vous pouvez aussi l’ouvrir dans votre navigateur.",
  ],
  "settings.mcp.store.preview": [
    "Preview & install",
    "Ansehen & installieren",
    "Aperçu et installation",
  ],
  "settings.mcp.store.setup": ["Set up", "Einrichten", "Configurer"],
  "settings.mcp.store.install": ["Install skill", "Skill installieren", "Installer la compétence"],
  "settings.mcp.store.addServer": ["Add server", "Server hinzufügen", "Ajouter le serveur"],
  "settings.mcp.store.installing": ["Installing…", "Wird installiert…", "Installation…"],
  "settings.mcp.store.installed": ["Installed", "Installiert", "Installé"],
  "settings.mcp.store.installs": ["installs", "Installationen", "installations"],
  "settings.mcp.store.success": [
    "Added to Installed.",
    "Unter Installiert hinzugefügt.",
    "Ajouté aux éléments installés.",
  ],
  "settings.mcp.store.scope": ["Install for", "Installieren für", "Installer pour"],
  "settings.mcp.store.global": [
    "All projects in this environment",
    "Alle Projekte dieser Umgebung",
    "Tous les projets de cet environnement",
  ],
  "settings.mcp.store.project": ["This project", "Dieses Projekt", "Ce projet"],
  "settings.mcp.store.connection": ["Connection", "Verbindung", "Connexion"],
  "settings.mcp.store.provider": ["Provider", "Provider", "Fournisseur"],
  "settings.mcp.store.allProviders": [
    "All active providers",
    "Alle aktiven Provider",
    "Tous les fournisseurs actifs",
  ],
  "settings.mcp.store.required": ["Required", "Erforderlich", "Obligatoire"],
  "settings.mcp.store.optional": ["Optional", "Optional", "Facultatif"],
  "settings.mcp.store.files": [
    "Includes {{count}} files, with supporting resources.",
    "Enthält {{count}} Dateien einschließlich unterstützender Ressourcen.",
    "Inclut {{count}} fichiers avec les ressources associées.",
  ],
  "settings.mcp.store.previewLoading": [
    "Loading skill preview…",
    "Skill-Vorschau wird geladen…",
    "Chargement de l’aperçu…",
  ],
  "settings.mcp.store.instructions": [
    "Skill instructions",
    "Skill-Anleitungen",
    "Instructions de la compétence",
  ],
  "settings.mcp.store.community": [
    "Community content. Review the source and instructions before installing.",
    "Community-Inhalte. Prüfe Quelle und Anleitungen vor der Installation.",
    "Contenu communautaire. Consultez la source et les instructions avant l’installation.",
  ],
  "settings.mcp.store.localSetup": [
    "Adding this server allows the environment to run the command below. Its runtime must be installed on the environment host.",
    "Dieser Server führt den folgenden Befehl in der Umgebung aus. Die Laufzeit muss auf dem Host installiert sein.",
    "Ce serveur peut exécuter la commande ci-dessous dans l’environnement. Le moteur doit être installé sur l’hôte.",
  ],
  "settings.mcp.store.remoteSetup": [
    "Connect to the endpoint below. Some services require a separate account or subscription.",
    "Verbinde dich mit dem folgenden Endpunkt. Manche Dienste benötigen ein eigenes Konto oder Abonnement.",
    "Connectez-vous au point d’accès ci-dessous. Certains services nécessitent un compte ou un abonnement.",
  ],
  "settings.mcp.store.manual": [
    "This server requires manual setup. Follow the source instructions and use New in MCP servers.",
    "Dieser Server muss manuell eingerichtet werden. Folge der Anleitung in der Quelle und verwende Neu unter MCP-Server.",
    "Ce serveur nécessite une configuration manuelle. Suivez les instructions de la source puis utilisez Nouveau dans Serveurs MCP.",
  ],
  "settings.mcp.store.upgrade": [
    "Update this environment’s T3 server to browse and install from the store.",
    "Aktualisiere den T3-Server dieser Umgebung, um den Store zu nutzen.",
    "Mettez à jour le serveur T3 de cet environnement pour utiliser le catalogue.",
  ],
  "settings.mcp.store.readOnly": [
    "You can browse here. Installing requires permission to operate this environment.",
    "Du kannst den Store durchsuchen. Installieren erfordert Schreibzugriff auf diese Umgebung.",
    "Vous pouvez parcourir le catalogue. L’installation nécessite l’autorisation de modifier cet environnement.",
  ],
  "settings.mcp.store.diagnostics": ["Diagnostics", "Diagnose", "Diagnostic"],
  "settings.mcp.store.noSession": [
    "Connect an agent to see live tools",
    "Verbinde einen Agenten, um aktive Tools zu sehen",
    "Connectez un agent pour voir les outils actifs",
  ],
  "settings.mcp.store.noSessionDescription": [
    "Send a message in chat, then return here to inspect connections. You can browse and install tools and skills before starting a session.",
    "Sende eine Nachricht im Chat und kehre hierher zurück, um Verbindungen zu prüfen. Tools und Skills kannst du schon vorher suchen und installieren.",
    "Envoyez un message dans le chat, puis revenez vérifier les connexions. Vous pouvez déjà rechercher et installer des outils et compétences.",
  ],
  "settings.mcp.editor.add": ["Add", "Hinzufügen", "Ajouter"],
  "settings.mcp.editor.emptyValues": [
    "No values configured.",
    "Keine Werte konfiguriert.",
    "Aucune valeur configurée.",
  ],
  "settings.mcp.editor.storedSecret": [
    "Stored secret",
    "Gespeichertes Secret",
    "Secret enregistré",
  ],
  "settings.mcp.editor.value": ["Value", "Wert", "Valeur"],
  "settings.mcp.editor.sensitive": ["Sensitive", "Vertraulich", "Sensible"],
  "settings.mcp.editor.removeValue": [
    "Remove {{name}} value",
    "Wert {{name}} entfernen",
    "Supprimer la valeur {{name}}",
  ],
  "settings.mcp.editor.editTitle": [
    "Edit MCP server",
    "MCP-Server bearbeiten",
    "Modifier le serveur MCP",
  ],
  "settings.mcp.editor.newTitle": ["New MCP server", "Neuer MCP-Server", "Nouveau serveur MCP"],
  "settings.mcp.editor.description": [
    "T3 stores MCP configuration locally and resolves it when a provider session starts.",
    "T3 speichert die MCP-Konfiguration lokal und löst sie beim Start einer Provider-Sitzung auf.",
    "T3 conserve la configuration MCP localement et la résout au démarrage d’une session fournisseur.",
  ],
  "settings.mcp.editor.name": ["Name", "Name", "Nom"],
  "settings.mcp.editor.namePlaceholder": ["GitHub", "GitHub", "GitHub"],
  "settings.mcp.editor.identifier": ["Identifier", "Kennung", "Identifiant"],
  "settings.mcp.editor.scope": ["Scope", "Geltungsbereich", "Portée"],
  "settings.mcp.editor.global": ["Global", "Global", "Globale"],
  "settings.mcp.editor.project": ["Project", "Projekt", "Projet"],
  "settings.mcp.editor.noProject": ["No project", "Kein Projekt", "Aucun projet"],
  "settings.mcp.editor.enabled": ["Enabled", "Aktiviert", "Activé"],
  "settings.mcp.editor.enableFor": ["Enable for", "Aktivieren für", "Activer pour"],
  "settings.mcp.editor.allAccounts": [
    "All provider accounts",
    "Alle Provider-Konten",
    "Tous les comptes fournisseur",
  ],
  "settings.mcp.editor.allProvidersDescription": [
    "This server will be available to every configured provider that supports MCP.",
    "Dieser Server ist für jeden konfigurierten Provider verfügbar, der MCP unterstützt.",
    "Ce serveur sera disponible pour chaque fournisseur configuré prenant en charge MCP.",
  ],
  "settings.mcp.editor.transport": ["Transport", "Transport", "Transport"],
  "settings.mcp.editor.transport.stdio": ["stdio", "stdio", "stdio"],
  "settings.mcp.editor.transport.sse": ["SSE", "SSE", "SSE"],
  "settings.mcp.editor.transport.http": ["HTTP", "HTTP", "HTTP"],
  "settings.mcp.editor.command": ["Command", "Befehl", "Commande"],
  "settings.mcp.editor.commandPlaceholder": ["npx", "npx", "npx"],
  "settings.mcp.editor.cwd": ["Working directory", "Arbeitsverzeichnis", "Répertoire de travail"],
  "settings.mcp.editor.cwdPlaceholder": ["/repo", "/repo", "/repo"],
  "settings.mcp.editor.arguments": ["Arguments", "Argumente", "Arguments"],
  "settings.mcp.editor.argumentsPlaceholder": [
    "-y\n@modelcontextprotocol/server-github",
    "-y\n@modelcontextprotocol/server-github",
    "-y\n@modelcontextprotocol/server-github",
  ],
  "settings.mcp.editor.environment": ["Environment", "Umgebung", "Environnement"],
  "settings.mcp.editor.url": ["URL", "URL", "URL"],
  "settings.mcp.editor.headers": ["Headers", "Header", "En-têtes"],
  "settings.mcp.editor.save": ["Save", "Speichern", "Enregistrer"],
  "settings.mcp.import.scanning": [
    "Scanning agent folders…",
    "Agent-Ordner werden durchsucht…",
    "Analyse des dossiers d’agents…",
  ],
  "settings.mcp.import.noneFound": [
    "No agent dotfolders with importable MCP config were found.",
    "Keine Agent-Dotfolder mit importierbarer MCP-Konfiguration gefunden.",
    "Aucun dossier caché d’agent avec une configuration MCP importable n’a été trouvé.",
  ],
  "settings.mcp.import.server": ["MCP server", "MCP-Server", "serveur MCP"],
  "settings.mcp.import.skill": ["skill", "Skill", "compétence"],
  "settings.mcp.import.skillCount": [
    { one: "{{count}} skill", other: "{{count}} skills" },
    { one: "{{count}} Skill", other: "{{count}} Skills" },
    { one: "{{count}} compétence", other: "{{count}} compétences" },
  ],
  "settings.mcp.import.title": [
    "Import Agent Configs",
    "Agent-Konfigurationen importieren",
    "Importer des configurations d’agents",
  ],
  "settings.mcp.import.description": [
    "Import MCP servers from detected Codex, Cursor, Claude, and OpenCode folders.",
    "MCP-Server aus erkannten Codex-, Cursor-, Claude- und OpenCode-Ordnern importieren.",
    "Importer des serveurs MCP depuis les dossiers Codex, Cursor, Claude et OpenCode détectés.",
  ],
  "settings.mcp.import.enableFor": [
    "Enable imported servers for",
    "Importierte Server aktivieren für",
    "Activer les serveurs importés pour",
  ],
  "settings.mcp.import.allAccounts": ["All accounts", "Alle Konten", "Tous les comptes"],
  "settings.mcp.import.replace": [
    "Replace existing MCP servers",
    "Vorhandene MCP-Server ersetzen",
    "Remplacer les serveurs MCP existants",
  ],
  "settings.mcp.import.deduplicate": [
    "Deduplicate matching MCP servers",
    "Übereinstimmende MCP-Server deduplizieren",
    "Dédupliquer les serveurs MCP correspondants",
  ],
  "settings.mcp.import.action": ["Import", "Importieren", "Importer"],
  "settings.mcp.export.title": [
    "Export Cursor JSON",
    "Cursor-JSON exportieren",
    "Exporter le JSON Cursor",
  ],
  "settings.mcp.export.description": [
    "Export the selected MCP servers as Cursor-compatible JSON.",
    "Ausgewählte MCP-Server als Cursor-kompatibles JSON exportieren.",
    "Exporter les serveurs MCP sélectionnés au format JSON compatible avec Cursor.",
  ],
  "settings.mcp.export.assignmentWarning": [
    "This export contains the servers enabled for the selected provider account. Cursor JSON does not preserve T3 provider assignments.",
    "Dieser Export enthält die für das ausgewählte Provider-Konto aktivierten Server. Cursor-JSON behält T3-Provider-Zuweisungen nicht bei.",
    "Cet export contient les serveurs activés pour le compte fournisseur sélectionné. Le JSON Cursor ne conserve pas les affectations de fournisseurs T3.",
  ],
  "settings.mcp.export.all": ["All", "Alle", "Tous"],
  "settings.mcp.export.includeDisabled": [
    "Include disabled servers",
    "Deaktivierte Server einschließen",
    "Inclure les serveurs désactivés",
  ],
  "settings.mcp.export.refresh": ["Refresh", "Aktualisieren", "Actualiser"],
  "settings.mcp.export.copy": ["Copy", "Kopieren", "Copier"],
  "settings.mcp.toast.updateFailed": [
    "Could not update MCP server",
    "MCP-Server konnte nicht aktualisiert werden",
    "Impossible de mettre à jour le serveur MCP",
  ],
  "settings.mcp.toast.deleteFailed": [
    "Could not delete MCP server",
    "MCP-Server konnte nicht gelöscht werden",
    "Impossible de supprimer le serveur MCP",
  ],
  "settings.mcp.toast.copied": ["MCP JSON copied", "MCP-JSON kopiert", "JSON MCP copié"],
  "settings.mcp.toast.authorizationFailed": [
    "Could not open authorization",
    "Autorisierung konnte nicht geöffnet werden",
    "Impossible d’ouvrir l’autorisation",
  ],
  "settings.mcp.toast.actionFailed": [
    "MCP action failed",
    "MCP-Aktion fehlgeschlagen",
    "Échec de l’action MCP",
  ],
  "settings.mcp.toast.inventoryFailed": [
    "Could not load MCP inventory",
    "MCP-Inventar konnte nicht geladen werden",
    "Impossible de charger l’inventaire MCP",
  ],
  "settings.mcp.session.ended": [
    "Ended or unavailable session",
    "Beendete oder nicht verfügbare Sitzung",
    "Session terminée ou indisponible",
  ],
  "settings.mcp.page.title": ["MCP Servers", "MCP-Server", "Serveurs MCP"],
  "settings.mcp.page.import": ["Import", "Importieren", "Importer"],
  "settings.mcp.page.export": ["Export", "Exportieren", "Exporter"],
  "settings.mcp.page.new": ["New", "Neu", "Nouveau"],
  "settings.mcp.workspace.providerManaged": [
    "Provider-managed servers",
    "Vom Provider verwaltete Server",
    "Serveurs gérés par le fournisseur",
  ],
  "settings.mcp.provider.discoveredIn": [
    "Discovered in {{path}}",
    "Erkannt in {{path}}",
    "Détecté dans {{path}}",
  ],
  "settings.mcp.workspace.systemServer": [
    "T3 Code System Server",
    "T3-Code-Systemserver",
    "Serveur système T3 Code",
  ],
  "settings.mcp.workspace.resourcesAria": ["MCP resources", "MCP-Ressourcen", "Ressources MCP"],
  "settings.mcp.workspace.resourceTemplatesAria": [
    "MCP resource templates",
    "MCP-Ressourcenvorlagen",
    "Modèles de ressources MCP",
  ],
});

export type SettingsMcpInterfaceMessageKey = (typeof settingsMcpInterfaceCatalog.keys)[number];
