import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const settingsInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "settings.common.search": ["Search", "Suchen", "Rechercher"],
  "settings.common.clear": ["Clear", "Leeren", "Effacer"],
  "settings.common.cancel": ["Cancel", "Abbrechen", "Annuler"],
  "settings.common.close": ["Close", "Schließen", "Fermer"],
  "settings.common.save": ["Save", "Speichern", "Enregistrer"],
  "settings.common.add": ["Add", "Hinzufügen", "Ajouter"],
  "settings.common.remove": ["Remove", "Entfernen", "Supprimer"],
  "settings.common.delete": ["Delete", "Löschen", "Supprimer"],
  "settings.common.edit": ["Edit", "Bearbeiten", "Modifier"],
  "settings.common.refresh": ["Refresh", "Aktualisieren", "Actualiser"],
  "settings.common.restoreDefaults": [
    "Restore defaults",
    "Standardeinstellungen wiederherstellen",
    "Restaurer les valeurs par défaut",
  ],
  "settings.common.retry": ["Retry", "Erneut versuchen", "Réessayer"],
  "settings.common.loading": ["Loading…", "Wird geladen…", "Chargement…"],
  "settings.common.none": ["None", "Keine", "Aucun"],
  "settings.common.on": ["On", "Ein", "Activé"],
  "settings.common.off": ["Off", "Aus", "Désactivé"],
  "settings.common.enabled": ["Enabled", "Aktiviert", "Activé"],
  "settings.common.disabled": ["Disabled", "Deaktiviert", "Désactivé"],
  "settings.common.available": ["Available", "Verfügbar", "Disponible"],
  "settings.common.unavailable": ["Unavailable", "Nicht verfügbar", "Indisponible"],
  "settings.common.copy": ["Copy", "Kopieren", "Copier"],
  "settings.common.copied": ["Copied", "Kopiert", "Copié"],
  "settings.common.unknown": ["Unknown", "Unbekannt", "Inconnu"],
  "settings.providers.add.title": [
    "Add provider instance",
    "Provider-Instanz hinzufügen",
    "Ajouter une instance de fournisseur",
  ],
  "settings.providers.instanceNamed": [
    "Provider instance {{name}}",
    "Provider-Instanz {{name}}",
    "Instance de fournisseur {{name}}",
  ],
  "settings.mcp.serverCount": [
    { one: "{{count}} server", other: "{{count}} servers" },
    { one: "{{count}} Server", other: "{{count}} Server" },
    { one: "{{count}} serveur", other: "{{count}} serveurs" },
  ],
  "settings.mcp.workspace.title": ["MCP workspace", "MCP-Workspace", "Espace de travail MCP"],
  "settings.mcp.workspace.providers": ["MCP providers", "MCP-Provider", "Fournisseurs MCP"],
  "settings.mcp.workspace.runtimeSession": [
    "Runtime session",
    "Laufzeitsitzung",
    "Session d’exécution",
  ],
  "settings.mcp.workspace.views": [
    "MCP workspace views",
    "Ansichten des MCP-Workspace",
    "Vues de l’espace de travail MCP",
  ],
  "settings.mcp.workspace.expand": [
    "Expand MCP workspace",
    "MCP-Workspace erweitern",
    "Développer l’espace de travail MCP",
  ],
  "settings.mcp.workspace.serverStatus": [
    "MCP server status",
    "MCP-Serverstatus",
    "État du serveur MCP",
  ],
  "settings.mcp.workspace.upgradeRequired": [
    "Server upgrade required",
    "Server-Upgrade erforderlich",
    "Mise à niveau du serveur requise",
  ],
  "settings.mcp.workspace.noRuntime": [
    "No exact runtime session",
    "Keine passende Laufzeitsitzung",
    "Aucune session d’exécution exacte",
  ],
  "settings.mcp.workspace.overview": ["MCP overview", "MCP-Übersicht", "Vue d’ensemble MCP"],
  "settings.mcp.workspace.connected": [
    "{{connected}} / {{expected}} connected",
    "{{connected}} / {{expected}} verbunden",
    "{{connected}} / {{expected}} connectés",
  ],
  "settings.mcp.workspace.configuredServerCount": [
    { one: "{{count}} configured server", other: "{{count}} configured servers" },
    { one: "{{count}} konfigurierter Server", other: "{{count}} konfigurierte Server" },
    { one: "{{count}} serveur configuré", other: "{{count}} serveurs configurés" },
  ],
  "settings.mcp.workspace.needsAttention": [
    { one: "{{count}} needs attention", other: "{{count}} need attention" },
    { one: "{{count}} benötigt Aufmerksamkeit", other: "{{count}} benötigen Aufmerksamkeit" },
    { one: "{{count}} nécessite une attention", other: "{{count}} nécessitent une attention" },
  ],
  "settings.mcp.workspace.noIssues": [
    "No known issues",
    "Keine bekannten Probleme",
    "Aucun problème connu",
  ],
  "settings.mcp.workspace.toolsUnknown": ["Tools unknown", "Tools unbekannt", "Outils inconnus"],
  "settings.mcp.workspace.knownToolCount": [
    { one: "{{count}} known tool", other: "{{count}} known tools" },
    { one: "{{count}} bekanntes Tool", other: "{{count}} bekannte Tools" },
    { one: "{{count}} outil connu", other: "{{count}} outils connus" },
  ],
  "settings.mcp.workspace.servers": ["Servers", "Server", "Serveurs"],
  "settings.mcp.workspace.runtime": ["Runtime", "Laufzeit", "Exécution"],
  "settings.mcp.workspace.endedSession": [
    "Ended or unavailable session",
    "Beendete oder nicht verfügbare Sitzung",
    "Session terminée ou indisponible",
  ],
  "settings.mcp.workspace.noActiveSession": [
    "No active session",
    "Keine aktive Sitzung",
    "Aucune session active",
  ],
  "settings.mcp.workspace.loadingExactRuntime": [
    "Loading this exact MCP runtime session…",
    "Diese genaue MCP-Laufzeitsitzung wird geladen…",
    "Chargement de cette session d’exécution MCP exacte…",
  ],
  "settings.mcp.workspace.runtimeEnded": [
    "This runtime session has ended or has no active MCP servers.",
    "Diese Laufzeitsitzung wurde beendet oder hat keine aktiven MCP-Server.",
    "Cette session d’exécution est terminée ou ne possède aucun serveur MCP actif.",
  ],
  "settings.mcp.workspace.upgradeDescription": [
    "Configuration remains available, but this server version cannot provide the MCP workspace runtime and context streams.",
    "Die Konfiguration bleibt verfügbar, aber diese Serverversion kann die MCP-Workspace-Laufzeit und Kontextstreams nicht bereitstellen.",
    "La configuration reste disponible, mais cette version du serveur ne peut pas fournir l’exécution de l’espace de travail MCP ni les flux de contexte.",
  ],
  "settings.mcp.workspace.selectedRuntimeEnded": [
    "The selected runtime has ended or is no longer retained. Choose another exact session.",
    "Die ausgewählte Laufzeit wurde beendet oder wird nicht mehr vorgehalten. Wähle eine andere genaue Sitzung.",
    "L’exécution sélectionnée est terminée ou n’est plus conservée. Choisissez une autre session exacte.",
  ],
  "settings.mcp.workspace.startSession": [
    "Start a provider session to inspect connected servers, tools, resources, and templates.",
    "Starte eine Provider-Sitzung, um verbundene Server, Tools, Ressourcen und Vorlagen zu prüfen.",
    "Démarrez une session de fournisseur pour inspecter les serveurs, outils, ressources et modèles connectés.",
  ],
  "settings.mcp.workspace.collapse": [
    "Collapse MCP workspace",
    "MCP-Workspace einklappen",
    "Réduire l’espace de travail MCP",
  ],
  "settings.mcp.workspace.resize": [
    "Resize MCP workspace vertically",
    "Höhe des MCP-Workspace ändern",
    "Redimensionner verticalement l’espace de travail MCP",
  ],
  "settings.mcp.workspace.active": ["Active", "Aktiv", "Active"],
  "settings.mcp.workspace.ended": ["Ended", "Beendet", "Terminée"],
  "settings.mcp.scope.label": ["Scope", "Geltungsbereich", "Portée"],
  "settings.mcp.scope.global": ["Global", "Global", "Globale"],
  "settings.mcp.scope.project": ["Project", "Projekt", "Projet"],
  "settings.mcp.scope.noProject": ["No project", "Kein Projekt", "Aucun projet"],
  "settings.mcp.runtime.servers": ["MCP servers", "MCP-Server", "Serveurs MCP"],
  "settings.mcp.runtime.status": ["MCP server status", "MCP-Serverstatus", "État des serveurs MCP"],
  "settings.mcp.runtime.empty": [
    "No runtime MCP status is available for this session.",
    "Für diese Sitzung ist kein MCP-Laufzeitstatus verfügbar.",
    "Aucun état d’exécution MCP n’est disponible pour cette session.",
  ],
  "settings.mcp.runtime.source.t3Managed": [
    "T3-managed servers",
    "Von T3 verwaltete Server",
    "Serveurs gérés par T3",
  ],
  "settings.mcp.runtime.source.providerManaged": [
    "Provider-managed servers",
    "Vom Provider verwaltete Server",
    "Serveurs gérés par le fournisseur",
  ],
  "settings.mcp.runtime.source.system": [
    "T3 Code system server",
    "T3-Code-Systemserver",
    "Serveur système T3 Code",
  ],
  "settings.mcp.runtime.toolCount": [
    { one: "{{count}} tool", other: "{{count}} tools" },
    { one: "{{count}} Tool", other: "{{count}} Tools" },
    { one: "{{count}} outil", other: "{{count}} outils" },
  ],
  "settings.mcp.runtime.appliesNextSession": [
    "Applies next session",
    "Gilt ab der nächsten Sitzung",
    "S’applique à la prochaine session",
  ],
  "settings.mcp.runtime.operateRequired": [
    "Runtime actions require operate access.",
    "Laufzeitaktionen erfordern Betriebszugriff.",
    "Les actions d’exécution nécessitent un accès opérationnel.",
  ],
  "settings.mcp.runtime.authorizeOnHost": [
    "Complete authorization on the environment host.",
    "Schließe die Autorisierung auf dem Umgebungshost ab.",
    "Terminez l’autorisation sur l’hôte de l’environnement.",
  ],
  "settings.mcp.runtime.version": [
    "Version {{version}}",
    "Version {{version}}",
    "Version {{version}}",
  ],
  "settings.mcp.runtime.resourceCount": [
    { one: "{{count}} resource", other: "{{count}} resources" },
    { one: "{{count}} Ressource", other: "{{count}} Ressourcen" },
    { one: "{{count}} ressource", other: "{{count}} ressources" },
  ],
  "settings.mcp.runtime.templateCount": [
    { one: "{{count}} template", other: "{{count}} templates" },
    { one: "{{count}} Vorlage", other: "{{count}} Vorlagen" },
    { one: "{{count}} modèle", other: "{{count}} modèles" },
  ],
  "settings.mcp.runtime.loadingInventory": [
    "Loading MCP inventory…",
    "MCP-Inventar wird geladen…",
    "Chargement de l’inventaire MCP…",
  ],
  "settings.mcp.runtime.noTools": [
    "No tools were reported by this server.",
    "Dieser Server hat keine Tools gemeldet.",
    "Ce serveur n’a signalé aucun outil.",
  ],
  "settings.mcp.runtime.noToolDetails": [
    "This provider does not report tool details.",
    "Dieser Provider meldet keine Tool-Details.",
    "Ce fournisseur ne fournit pas de détails sur les outils.",
  ],
  "settings.mcp.runtime.manage": [
    "Manage MCP servers",
    "MCP-Server verwalten",
    "Gérer les serveurs MCP",
  ],
  "settings.mcp.runtime.noInventory": [
    "No tools, resources, or templates were reported by this server.",
    "Dieser Server hat keine Tools, Ressourcen oder Vorlagen gemeldet.",
    "Ce serveur n’a signalé aucun outil, ressource ou modèle.",
  ],
  "settings.mcp.runtime.noInventoryDetails": [
    "This provider does not report MCP inventory details.",
    "Dieser Provider meldet keine Details zum MCP-Inventar.",
    "Ce fournisseur ne fournit pas de détails sur l’inventaire MCP.",
  ],
  "settings.mcp.runtime.tools": ["Tools", "Tools", "Outils"],
  "settings.mcp.runtime.resources": ["Resources", "Ressourcen", "Ressources"],
  "settings.mcp.runtime.resourceTemplates": [
    "Resource templates",
    "Ressourcenvorlagen",
    "Modèles de ressources",
  ],
  "settings.mcp.runtime.inventoryAria": [
    "{{server}} {{section}}",
    "{{server}} {{section}}",
    "{{section}} de {{server}}",
  ],
  "settings.mcp.runtime.additional": [
    "{{count}} additional {{section}} are available in Settings.",
    "{{count}} weitere {{section}} sind in den Einstellungen verfügbar.",
    "{{count}} {{section}} supplémentaires sont disponibles dans les réglages.",
  ],
  "settings.mcp.runtime.annotation.readOnly": ["Read only", "Schreibgeschützt", "Lecture seule"],
  "settings.mcp.runtime.annotation.destructive": ["Destructive", "Destruktiv", "Destructif"],
  "settings.mcp.runtime.annotation.openWorld": ["Open world", "Offene Welt", "Monde ouvert"],
  "settings.mcp.runtime.aggregateUnavailable": [
    "MCP status unavailable",
    "MCP-Status nicht verfügbar",
    "État MCP indisponible",
  ],
  "settings.mcp.runtime.aggregateAll": [
    { one: "All MCP servers connected", other: "All {{count}} MCP servers connected" },
    { one: "Alle MCP-Server verbunden", other: "Alle {{count}} MCP-Server verbunden" },
    {
      one: "Tous les serveurs MCP sont connectés",
      other: "Les {{count}} serveurs MCP sont connectés",
    },
  ],
  "settings.mcp.runtime.aggregateConnected": [
    "{{connected}} of {{expected}} MCP servers connected",
    "{{connected}} von {{expected}} MCP-Servern verbunden",
    "{{connected}} serveurs MCP connectés sur {{expected}}",
  ],
  "settings.mcp.runtime.state.not-started": ["Not started", "Nicht gestartet", "Non démarré"],
  "settings.mcp.runtime.state.starting": ["Starting", "Wird gestartet", "Démarrage"],
  "settings.mcp.runtime.state.connected": ["Connected", "Verbunden", "Connecté"],
  "settings.mcp.runtime.state.auth-required": [
    "Authorization required",
    "Autorisierung erforderlich",
    "Autorisation requise",
  ],
  "settings.mcp.runtime.state.setup-required": [
    "Setup required",
    "Einrichtung erforderlich",
    "Configuration requise",
  ],
  "settings.mcp.runtime.state.failed": ["Failed", "Fehlgeschlagen", "Échec"],
  "settings.mcp.runtime.state.disabled": ["Disabled", "Deaktiviert", "Désactivé"],
  "settings.mcp.runtime.state.unsupported": [
    "Status unavailable",
    "Status nicht verfügbar",
    "État indisponible",
  ],
  "settings.mcp.runtime.state.unknown": ["Unknown", "Unbekannt", "Inconnu"],
  "settings.mcp.runtime.state.stale": [
    "Status may be outdated",
    "Status möglicherweise veraltet",
    "L’état est peut-être obsolète",
  ],
  "settings.mcp.action.authorize": ["Authorize", "Autorisieren", "Autoriser"],
  "settings.mcp.action.reconnect": ["Reconnect", "Erneut verbinden", "Reconnecter"],
  "settings.mcp.action.refresh": ["Refresh", "Aktualisieren", "Actualiser"],
  "settings.mcp.action.edit": ["Edit", "Bearbeiten", "Modifier"],
  "settings.mcp.action.duplicate": ["Duplicate", "Duplizieren", "Dupliquer"],
  "settings.mcp.action.delete": ["Delete", "Löschen", "Supprimer"],
  "settings.mcp.action.authorizing": ["Authorizing", "Wird autorisiert", "Autorisation"],
  "settings.mcp.action.reconnecting": [
    "Reconnecting",
    "Verbindung wird wiederhergestellt",
    "Reconnexion",
  ],
  "settings.mcp.action.refreshing": ["Refreshing", "Wird aktualisiert", "Actualisation"],
  "settings.mcp.action.enabled": ["Enabled", "Aktiviert", "Activé"],
  "settings.mcp.action.assignmentAria": [
    "{{action}} {{server}} for selected provider",
    "{{server}} für den ausgewählten Provider {{action}}",
    "{{action}} {{server}} pour le fournisseur sélectionné",
  ],
  "settings.mcp.action.enable": ["Enable", "Aktivieren", "Activer"],
  "settings.mcp.action.disable": ["Disable", "Deaktivieren", "Désactiver"],
  "settings.mcp.action.menuAria": [
    "Actions for {{server}}",
    "Aktionen für {{server}}",
    "Actions pour {{server}}",
  ],
  "settings.mcp.provider.toolsAvailable": [
    "Tools available",
    "Tools verfügbar",
    "Outils disponibles",
  ],
  "settings.mcp.provider.externalAccess": ["External access", "Externer Zugriff", "Accès externe"],
  "settings.mcp.provider.additionalResources": [
    "{{count}} additional resources are not shown.",
    "{{count}} weitere Ressourcen werden nicht angezeigt.",
    "{{count}} ressources supplémentaires ne sont pas affichées.",
  ],
  "settings.mcp.provider.additionalTemplates": [
    "{{count}} additional templates are not shown.",
    "{{count}} weitere Vorlagen werden nicht angezeigt.",
    "{{count}} modèles supplémentaires ne sont pas affichés.",
  ],
  "settings.mcp.provider.enableNext": [
    "Enable next session",
    "Ab der nächsten Sitzung aktivieren",
    "Activer à la prochaine session",
  ],
  "settings.mcp.provider.disableNext": [
    "Disable next session",
    "Ab der nächsten Sitzung deaktivieren",
    "Désactiver à la prochaine session",
  ],
  "settings.mcp.provider.detailsAria": [
    "{{action}} details for {{server}}",
    "Details für {{server}} {{action}}",
    "{{action}} les détails de {{server}}",
  ],
  "settings.mcp.provider.show": ["Show", "Anzeigen", "Afficher"],
  "settings.mcp.provider.hide": ["Hide", "Ausblenden", "Masquer"],
  "settings.mcp.provider.accounts": [
    "MCP provider accounts",
    "MCP-Provider-Konten",
    "Comptes de fournisseurs MCP",
  ],
  "settings.mcp.provider.noneConfigured": [
    "No provider accounts are configured. Add one in Provider settings.",
    "Es sind keine Provider-Konten konfiguriert. Füge eines in den Provider-Einstellungen hinzu.",
    "Aucun compte de fournisseur n’est configuré. Ajoutez-en un dans les réglages des fournisseurs.",
  ],
  "settings.mcp.provider.noneConfiguredPrefix": [
    "No provider accounts are configured. Add one in",
    "Es sind keine Provider-Konten konfiguriert. Füge eines hinzu unter",
    "Aucun compte de fournisseur n’est configuré. Ajoutez-en un dans",
  ],
  "settings.mcp.provider.settings": [
    "Provider settings",
    "Provider-Einstellungen",
    "Réglages des fournisseurs",
  ],
  "settings.mcp.provider.statusAria": [
    "Provider status: {{status}}",
    "Provider-Status: {{status}}",
    "État du fournisseur : {{status}}",
  ],
  "settings.mcp.provider.toggleAccount": [
    "Toggle provider account visibility",
    "Sichtbarkeit des Provider-Kontos umschalten",
    "Afficher ou masquer le compte du fournisseur",
  ],
  "settings.mcp.provider.revealAccount": [
    "Click to reveal account",
    "Klicken, um das Konto anzuzeigen",
    "Cliquer pour afficher le compte",
  ],
  "settings.mcp.provider.hideAccount": [
    "Click to hide account",
    "Klicken, um das Konto auszublenden",
    "Cliquer pour masquer le compte",
  ],
  "settings.mcp.provider.configured": ["Configured", "Konfiguriert", "Configuré"],
  "settings.mcp.provider.off": [
    "Off for this provider",
    "Für diesen Provider deaktiviert",
    "Désactivé pour ce fournisseur",
  ],
  "settings.mcp.provider.valueCount": [
    { one: "{{count}} value", other: "{{count}} values" },
    { one: "{{count}} Wert", other: "{{count}} Werte" },
    { one: "{{count}} valeur", other: "{{count}} valeurs" },
  ],
  "settings.mcp.provider.t3Managed": ["T3 managed", "Von T3 verwaltet", "Géré par T3"],
  "settings.mcp.provider.configuredNewSessions": [
    "Configured for new sessions",
    "Für neue Sitzungen konfiguriert",
    "Configuré pour les nouvelles sessions",
  ],
  "settings.mcp.provider.runtimeDescription": [
    "Connection health is reported by this provider session, not by an independent probe.",
    "Der Verbindungsstatus wird von dieser Provider-Sitzung gemeldet, nicht von einer unabhängigen Prüfung.",
    "L’état de la connexion est signalé par cette session de fournisseur, et non par une sonde indépendante.",
  ],
  "settings.mcp.provider.live": ["Live", "Live", "En direct"],
  "settings.mcp.provider.lastKnown": ["Last known", "Zuletzt bekannt", "Dernier état connu"],
  "settings.mcp.provider.runtimeUnsupported": [
    "This server version does not report MCP runtime status. Configuration remains available, but live health and actions are disabled.",
    "Diese Serverversion meldet keinen MCP-Laufzeitstatus. Die Konfiguration bleibt verfügbar, aber Live-Status und Aktionen sind deaktiviert.",
    "Cette version du serveur ne signale pas l’état d’exécution MCP. La configuration reste disponible, mais l’état en direct et les actions sont désactivés.",
  ],
  "settings.mcp.provider.userMcpUnsupported": [
    "{{provider}} does not support user-configured MCP servers. Its T3 system server is shown separately when a runtime reports it.",
    "{{provider}} unterstützt keine benutzerkonfigurierten MCP-Server. Der T3-Systemserver wird separat angezeigt, wenn eine Laufzeit ihn meldet.",
    "{{provider}} ne prend pas en charge les serveurs MCP configurés par l’utilisateur. Son serveur système T3 est affiché séparément lorsqu’une exécution le signale.",
  ],
  "settings.mcp.provider.loadingStatus": [
    "Loading session MCP status…",
    "MCP-Sitzungsstatus wird geladen…",
    "Chargement de l’état MCP de la session…",
  ],
  "settings.mcp.provider.readOnly": [
    "You have read-only access. Runtime status and configuration remain visible, but MCP changes and runtime actions are disabled.",
    "Du hast schreibgeschützten Zugriff. Laufzeitstatus und Konfiguration bleiben sichtbar, aber MCP-Änderungen und Laufzeitaktionen sind deaktiviert.",
    "Vous disposez d’un accès en lecture seule. L’état d’exécution et la configuration restent visibles, mais les modifications MCP et les actions d’exécution sont désactivées.",
  ],
  "settings.mcp.provider.managedDescription": [
    "The switch is specific to this provider account. Edit, duplicate, and delete change the shared server definition.",
    "Der Schalter gilt nur für dieses Provider-Konto. Bearbeiten, Duplizieren und Löschen ändern die gemeinsame Serverdefinition.",
    "Le commutateur est propre à ce compte fournisseur. Modifier, dupliquer et supprimer changent la définition partagée du serveur.",
  ],
  "settings.mcp.provider.noServers": [
    "No MCP servers in this scope.",
    "Keine MCP-Server in diesem Geltungsbereich.",
    "Aucun serveur MCP dans cette portée.",
  ],
  "settings.providers.add.label": ["Label", "Bezeichnung", "Libellé"],
  "settings.providers.add.instanceId": ["Instance ID", "Instanz-ID", "ID de l’instance"],
  "settings.providers.add.accentColor": ["Accent color", "Akzentfarbe", "Couleur d’accent"],
  "settings.providers.add.workPlaceholder": ["e.g. Work", "z. B. Arbeit", "p. ex. Travail"],
  "settings.providers.add.accentColorAria": [
    "Provider instance accent color",
    "Akzentfarbe der Provider-Instanz",
    "Couleur d’accent de l’instance de fournisseur",
  ],
  "settings.providers.add.description": [
    "Configure an additional provider instance on {{environment}}, for example a second Codex install pointed at a different workspace.",
    "Konfiguriere eine zusätzliche Provider-Instanz auf {{environment}}, zum Beispiel eine zweite Codex-Installation für einen anderen Workspace.",
    "Configurez une instance de fournisseur supplémentaire sur {{environment}}, par exemple une deuxième installation Codex associée à un autre espace de travail.",
  ],
  "settings.providers.add.driver": ["Driver", "Treiber", "Pilote"],
  "settings.providers.add.comingSoon": ["Coming Soon", "Demnächst", "Bientôt disponible"],
  "settings.providers.add.labelDescription": [
    "Shown in the provider list. Optional.",
    "Wird in der Provider-Liste angezeigt. Optional.",
    "Affiché dans la liste des fournisseurs. Facultatif.",
  ],
  "settings.providers.add.idDescription": [
    "Routing key used by threads and sessions. Letters, digits, '-', or '_'.",
    "Routing-Schlüssel für Chats und Sitzungen. Buchstaben, Ziffern, „-“ oder „_“.",
    "Clé de routage utilisée par les discussions et les sessions. Lettres, chiffres, « - » ou « _ ».",
  ],
  "settings.providers.add.accentDescription": [
    "Optional marker shown in the picker.",
    "Optionale Markierung in der Auswahl.",
    "Repère facultatif affiché dans le sélecteur.",
  ],
  "settings.providers.add.useAccent": [
    "Use {{color}} accent",
    "Akzent {{color}} verwenden",
    "Utiliser l’accent {{color}}",
  ],
  "settings.providers.add.workspaceName": [
    "{{provider}} Workspace",
    "{{provider}}-Workspace",
    "Espace de travail {{provider}}",
  ],
  "settings.providers.add.validation.required": [
    "Instance ID is required.",
    "Eine Instanz-ID ist erforderlich.",
    "L’ID de l’instance est requis.",
  ],
  "settings.providers.add.validation.tooLong": [
    "Instance ID must be 64 characters or fewer.",
    "Die Instanz-ID darf höchstens 64 Zeichen lang sein.",
    "L’ID de l’instance doit contenir au maximum 64 caractères.",
  ],
  "settings.providers.add.validation.pattern": [
    "Instance ID must start with a letter and use only letters, digits, '-', or '_'.",
    "Die Instanz-ID muss mit einem Buchstaben beginnen und darf nur Buchstaben, Ziffern, „-“ oder „_“ enthalten.",
    "L’ID de l’instance doit commencer par une lettre et ne contenir que des lettres, chiffres, « - » ou « _ ».",
  ],
  "settings.providers.add.validation.exists": [
    "An instance named '{{id}}' already exists.",
    "Eine Instanz namens „{{id}}“ ist bereits vorhanden.",
    "Une instance nommée « {{id}} » existe déjà.",
  ],
  "settings.providers.add.successTitle": [
    "Provider instance added",
    "Provider-Instanz hinzugefügt",
    "Instance de fournisseur ajoutée",
  ],
  "settings.providers.add.successDescription": [
    "{{provider}} instance '{{id}}' was added.",
    "{{provider}}-Instanz „{{id}}“ wurde hinzugefügt.",
    "L’instance {{provider}} « {{id}} » a été ajoutée.",
  ],
  "settings.providers.add.failedTitle": [
    "Could not add provider instance",
    "Provider-Instanz konnte nicht hinzugefügt werden",
    "Impossible d’ajouter l’instance de fournisseur",
  ],
  "settings.providers.add.failedFallback": [
    "Update failed.",
    "Aktualisierung fehlgeschlagen.",
    "Échec de la mise à jour.",
  ],
  "settings.providers.add.noConfiguration": [
    "This driver has no required configuration. You can add the instance now.",
    "Dieser Treiber benötigt keine Konfiguration. Die Instanz kann jetzt hinzugefügt werden.",
    "Ce pilote ne nécessite aucune configuration. Vous pouvez ajouter l’instance maintenant.",
  ],
  "settings.providers.add.back": ["Back", "Zurück", "Retour"],
  "settings.providers.add.next": ["Next", "Weiter", "Suivant"],
  "settings.providers.add.submit": ["Add instance", "Instanz hinzufügen", "Ajouter l’instance"],
  "settings.providers.auth.connect": ["Connect", "Verbinden", "Connecter"],
  "settings.providers.auth.reconnect": ["Reconnect", "Erneut verbinden", "Reconnecter"],
  "settings.providers.auth.disconnect": ["Disconnect", "Trennen", "Déconnecter"],
  "settings.providers.auth.credential": ["credential", "Zugangsdaten", "identifiants"],
  "settings.providers.auth.addCredential": [
    "Add {{label}}",
    "{{label}} hinzufügen",
    "Ajouter {{label}}",
  ],
  "settings.providers.auth.replaceCredential": [
    "Replace {{label}}",
    "{{label}} ersetzen",
    "Remplacer {{label}}",
  ],
  "settings.providers.auth.actionAria": [
    "{{action}} for {{provider}}",
    "{{action}} für {{provider}}",
    "{{action}} pour {{provider}}",
  ],
  "settings.providers.auth.browserDescription": [
    "Complete {{provider}} sign-in in your browser. T3 never sends the resulting credential back to this client.",
    "Schließe die Anmeldung bei {{provider}} im Browser ab. T3 sendet die resultierenden Zugangsdaten niemals an diesen Client zurück.",
    "Terminez la connexion à {{provider}} dans votre navigateur. T3 ne renvoie jamais les identifiants obtenus à ce client.",
  ],
  "settings.providers.auth.continueBrowser": [
    "Continue in browser",
    "Im Browser fortfahren",
    "Continuer dans le navigateur",
  ],
  "settings.providers.auth.deviceDescription": [
    "Open the verification page on any device, then enter this one-time code.",
    "Öffne die Bestätigungsseite auf einem beliebigen Gerät und gib dann diesen Einmalcode ein.",
    "Ouvrez la page de vérification sur n’importe quel appareil, puis saisissez ce code à usage unique.",
  ],
  "settings.providers.auth.openVerification": [
    "Open verification page",
    "Bestätigungsseite öffnen",
    "Ouvrir la page de vérification",
  ],
  "settings.providers.auth.connected": [
    "{{provider}} connected. Provider status will refresh automatically.",
    "{{provider}} verbunden. Der Provider-Status wird automatisch aktualisiert.",
    "{{provider}} est connecté. L’état du fournisseur sera actualisé automatiquement.",
  ],
  "settings.providers.auth.cancelled": [
    "Sign-in was cancelled. You can retry without changing providers.",
    "Die Anmeldung wurde abgebrochen. Du kannst es erneut versuchen, ohne den Provider zu wechseln.",
    "La connexion a été annulée. Vous pouvez réessayer sans changer de fournisseur.",
  ],
  "settings.providers.auth.preparing": [
    "Preparing secure {{provider}} sign-in…",
    "Sichere Anmeldung bei {{provider}} wird vorbereitet…",
    "Préparation de la connexion sécurisée à {{provider}}…",
  ],
  "settings.providers.auth.signInFailed": [
    "{{provider}} sign-in failed.",
    "Anmeldung bei {{provider}} fehlgeschlagen.",
    "Échec de la connexion à {{provider}}.",
  ],
  "settings.providers.auth.saveFailed": [
    "Could not save {{label}}.",
    "{{label}} konnte nicht gespeichert werden.",
    "Impossible d’enregistrer {{label}}.",
  ],
  "settings.providers.auth.disconnectFailed": [
    "Could not disconnect {{provider}}.",
    "{{provider}} konnte nicht getrennt werden.",
    "Impossible de déconnecter {{provider}}.",
  ],
  "settings.providers.auth.readOnly": [
    "Authentication actions require edit access to this environment.",
    "Authentifizierungsaktionen erfordern Bearbeitungszugriff auf diese Umgebung.",
    "Les actions d’authentification nécessitent un accès en modification à cet environnement.",
  ],
  "settings.providers.auth.environmentCredential": [
    "Using the instance environment credential. Remove it from the provider environment to disconnect, or save a key here to override it.",
    "Die Zugangsdaten aus der Instanzumgebung werden verwendet. Entferne sie aus der Provider-Umgebung, um die Verbindung zu trennen, oder speichere hier einen Schlüssel, um sie zu überschreiben.",
    "Les identifiants de l’environnement de l’instance sont utilisés. Retirez-les de l’environnement du fournisseur pour vous déconnecter, ou enregistrez une clé ici pour les remplacer.",
  ],
  "settings.providers.auth.disconnectAria": [
    "Disconnect {{provider}}",
    "{{provider}} trennen",
    "Déconnecter {{provider}}",
  ],
  "settings.providers.auth.connectTitle": [
    "Connect {{provider}}",
    "{{provider}} verbinden",
    "Connecter {{provider}}",
  ],
  "settings.providers.auth.connectDescription": [
    "Sign in with the account this provider instance should use.",
    "Melde dich mit dem Konto an, das diese Provider-Instanz verwenden soll.",
    "Connectez-vous avec le compte que cette instance de fournisseur doit utiliser.",
  ],
  "settings.providers.auth.credentialTitle": [
    "{{action}} for {{provider}}",
    "{{action}} für {{provider}}",
    "{{action}} pour {{provider}}",
  ],
  "settings.providers.auth.credentialDescription": [
    "The key is validated by this environment and stored only for this provider instance. It is never returned to the app.",
    "Der Schlüssel wird von dieser Umgebung geprüft und nur für diese Provider-Instanz gespeichert. Er wird niemals an die App zurückgegeben.",
    "La clé est validée par cet environnement et stockée uniquement pour cette instance de fournisseur. Elle n’est jamais renvoyée à l’application.",
  ],
  "settings.providers.auth.saveAria": [
    "Save {{label}} for {{provider}}",
    "{{label}} für {{provider}} speichern",
    "Enregistrer {{label}} pour {{provider}}",
  ],
  "settings.providers.auth.validating": ["Validating…", "Wird geprüft…", "Validation…"],
  "settings.providers.auth.disconnectTitle": [
    "Disconnect {{provider}}?",
    "{{provider}} trennen?",
    "Déconnecter {{provider}} ?",
  ],
  "settings.providers.auth.disconnectDescription": [
    "This stops new turns for this instance, interrupts its active turns, and removes only this instance's isolated credential.",
    "Dadurch werden neue Durchläufe dieser Instanz gestoppt, aktive Durchläufe unterbrochen und nur die isolierten Zugangsdaten dieser Instanz entfernt.",
    "Cela bloque les nouveaux tours de cette instance, interrompt ses tours actifs et supprime uniquement les identifiants isolés de cette instance.",
  ],
  "settings.providers.auth.confirmDisconnectAria": [
    "Confirm disconnect {{provider}}",
    "Trennen von {{provider}} bestätigen",
    "Confirmer la déconnexion de {{provider}}",
  ],
  "settings.providers.auth.disconnecting": [
    "Disconnecting…",
    "Verbindung wird getrennt…",
    "Déconnexion…",
  ],
  "settings.providers.accent.customHex": [
    "Custom hex accent color",
    "Eigene Hex-Akzentfarbe",
    "Couleur d’accent hexadécimale personnalisée",
  ],
  "settings.providers.accent.label": ["Accent color", "Akzentfarbe", "Couleur d’accent"],
  "settings.providers.accent.chooseCustom": [
    "Choose custom accent color for {{name}}",
    "Eigene Akzentfarbe für {{name}} auswählen",
    "Choisir une couleur d’accent personnalisée pour {{name}}",
  ],
  "settings.providers.accent.clear": [
    "Clear accent color for {{name}}",
    "Akzentfarbe für {{name}} löschen",
    "Effacer la couleur d’accent de {{name}}",
  ],
  "settings.projects.preview.description": [
    "Choose how many chats each project shows before Show more in the Classic sidebar. This syncs through compatible connected T3 servers.",
    "Legt fest, wie viele Chats jedes Projekt vor „Mehr anzeigen“ in der klassischen Seitenleiste zeigt. Diese Einstellung wird über kompatible verbundene T3-Server synchronisiert.",
    "Choisissez le nombre de discussions affichées par projet avant « Afficher plus » dans la barre latérale classique. Ce réglage se synchronise via les serveurs T3 compatibles connectés.",
  ],
  "settings.projects.preview.resetLabel": [
    "chats per project",
    "Chats pro Projekt",
    "discussions par projet",
  ],
  "settings.projects.preview.aria": [
    "Chats per project",
    "Chats pro Projekt",
    "Discussions par projet",
  ],
  "settings.sidebar.layout": [
    "Sidebar layout",
    "Seitenleistenlayout",
    "Disposition de la barre latérale",
  ],
  "settings.projects.checkpoints.create": [
    "Create checkpoints after turns",
    "Nach Durchläufen Checkpoints erstellen",
    "Créer des points de contrôle après les tours",
  ],
  "settings.projects.checkpoints.mixed": ["Mixed", "Gemischt", "Mixte"],
  "settings.projects.checkpoints.disableAll": [
    "Disable all",
    "Alle deaktivieren",
    "Tout désactiver",
  ],
  "settings.projects.checkpoints.enableAll": ["Enable all", "Alle aktivieren", "Tout activer"],
  "settings.projects.empty.title": ["No projects", "Keine Projekte", "Aucun projet"],
  "settings.projects.empty.description": [
    "Add a project from the sidebar to configure checkpoint creation.",
    "Füge über die Seitenleiste ein Projekt hinzu, um die Checkpoint-Erstellung zu konfigurieren.",
    "Ajoutez un projet depuis la barre latérale pour configurer la création de points de contrôle.",
  ],
  "settings.projects.checkoutCount": [
    { one: "{{count}} checkout", other: "{{count}} grouped checkouts" },
    { one: "{{count}} Checkout", other: "{{count}} gruppierte Checkouts" },
    { one: "{{count}} extraction", other: "{{count}} extractions groupées" },
  ],
  "settings.projects.checkpoints.status": [
    "Checkpoints {{status}}",
    "Checkpoints {{status}}",
    "Points de contrôle {{status}}",
  ],
  "settings.projects.checkpoints.configure": ["Configure", "Konfigurieren", "Configurer"],
  "settings.projects.checkpoints.configureAria": [
    "Configure checkpoints for {{name}}",
    "Checkpoints für {{name}} konfigurieren",
    "Configurer les points de contrôle pour {{name}}",
  ],
  "settings.chatImport.title": ["Import chats", "Chats importieren", "Importer des discussions"],
  "settings.chatImport.scan": [
    "Scan for T3 Code instances",
    "Nach T3-Code-Instanzen suchen",
    "Rechercher des instances T3 Code",
  ],
  "settings.chatImport.noDatedChats": [
    "No dated chats",
    "Keine datierten Chats",
    "Aucune discussion datée",
  ],
  "settings.chatImport.latestChat": [
    "Latest chat {{date}}",
    "Neuester Chat {{date}}",
    "Dernière discussion {{date}}",
  ],
  "settings.chatImport.chatCount": [
    { one: "{{count}} chat", other: "{{count}} chats" },
    { one: "{{count}} Chat", other: "{{count}} Chats" },
    { one: "{{count}} discussion", other: "{{count}} discussions" },
  ],
  "settings.chatImport.importing": ["Importing…", "Wird importiert…", "Importation…"],
  "settings.chatImport.summary": [
    "Synced {{threads}} chats and {{messages}} messages from {{projects}} projects.",
    "{{threads}} Chats und {{messages}} Nachrichten aus {{projects}} Projekten synchronisiert.",
    "{{threads}} discussions et {{messages}} messages synchronisés depuis {{projects}} projets.",
  ],
  "settings.chatImport.attachments": [
    "{{copied}} attachments copied, {{skipped}} unavailable.",
    "{{copied}} Anhänge kopiert, {{skipped}} nicht verfügbar.",
    "{{copied}} pièces jointes copiées, {{skipped}} indisponibles.",
  ],
  "settings.chatImport.attachmentsCopied": [
    "{{copied}} attachments copied.",
    "{{copied}} Anhänge kopiert.",
    "{{copied}} pièces jointes copiées.",
  ],
  "settings.chatImport.failed": [
    "Could not import chats.",
    "Chats konnten nicht importiert werden.",
    "Impossible d’importer les discussions.",
  ],
  "settings.chatImport.scanning": [
    "Looking for other T3 Code instances…",
    "Andere T3-Code-Instanzen werden gesucht…",
    "Recherche d’autres instances T3 Code…",
  ],
  "settings.chatImport.scanFailed": [
    "Could not scan for T3 Code instances.",
    "T3-Code-Instanzen konnten nicht gesucht werden.",
    "Impossible de rechercher les instances T3 Code.",
  ],
  "settings.chatImport.empty": [
    "No other T3 Code chats found",
    "Keine anderen T3-Code-Chats gefunden",
    "Aucune autre discussion T3 Code trouvée",
  ],
  "settings.chatImport.scanDescription": [
    "T3 Code scans local .t3 and .t3-* data directories on this computer.",
    "T3 Code durchsucht die lokalen Datenverzeichnisse .t3 und .t3-* auf diesem Computer.",
    "T3 Code analyse les répertoires de données locaux .t3 et .t3-* sur cet ordinateur.",
  ],
  "settings.chatImport.note": [
    "Imported chats receive new local IDs and do not resume sessions from the source instance. Running the import again safely syncs the same chats without creating duplicates.",
    "Importierte Chats erhalten neue lokale IDs und setzen keine Sitzungen der Quellinstanz fort. Ein erneuter Import synchronisiert dieselben Chats sicher, ohne Duplikate zu erstellen.",
    "Les discussions importées reçoivent de nouveaux identifiants locaux et ne reprennent pas les sessions de l’instance source. Relancer l’importation synchronise les mêmes discussions sans créer de doublons.",
  ],
  "settings.chatVisuals.group": ["Chat visuals", "Chatdarstellung", "Affichage des discussions"],
  "settings.chatVisuals.current": ["Current", "Aktuell", "Actuel"],
  "settings.chatVisuals.classic": ["Classic", "Klassisch", "Classique"],
  "settings.chatVisuals.optionAria": [
    "{{mode}} chat visuals",
    "Chatdarstellung {{mode}}",
    "Affichage des discussions {{mode}}",
  ],
  "settings.chatVisuals.description": [
    "Current is the default. Classic restores the compact pre-merge transcript visuals.",
    "„Aktuell“ ist der Standard. „Klassisch“ stellt die kompakte Transcript-Darstellung vor der Zusammenführung wieder her.",
    "« Actuel » est le réglage par défaut. « Classique » restaure l’affichage compact des transcriptions antérieur à la fusion.",
  ],
  "settings.font.terminalPreview": [
    "Terminal font preview",
    "Vorschau der Terminalschrift",
    "Aperçu de la police du terminal",
  ],
  "settings.theme.color.choose": ["Choose a color", "Farbe auswählen", "Choisir une couleur"],
  "settings.breadcrumb.aria": [
    "Settings breadcrumb",
    "Einstellungs-Breadcrumb",
    "Fil d’Ariane des réglages",
  ],
  "settings.breadcrumb.root": ["Settings", "Einstellungen", "Réglages"],
  "settings.common.backgroundPolicyDetails": [
    "Background policy details",
    "Details zur Hintergrundrichtlinie",
    "Détails de la politique d’arrière-plan",
  ],
  "settings.common.resetAria": [
    "Reset {{label}} to default",
    "{{label}} auf den Standard zurücksetzen",
    "Rétablir la valeur par défaut de {{label}}",
  ],
  "settings.common.reset": [
    "Reset to default",
    "Auf Standard zurücksetzen",
    "Rétablir la valeur par défaut",
  ],
  "settings.general.version": ["Version", "Version", "Version"],
  "settings.general.updateTrack": ["Update track", "Update-Kanal", "Canal de mise à jour"],
  "settings.general.updateTrack.desktopDescription": [
    "Stable follows full releases. Nightly follows the nightly desktop channel and can switch back to stable immediately.",
    "Stable folgt vollständigen Releases. Nightly folgt dem nächtlichen Desktop-Kanal und kann sofort zu Stable zurückwechseln.",
    "Stable suit les versions complètes. Nightly suit le canal de bureau nocturne et peut revenir immédiatement à Stable.",
  ],
  "settings.general.updateTrack.hostedDescription": [
    "Switches the hosted app release channel.",
    "Wechselt den Release-Kanal der gehosteten App.",
    "Change le canal de publication de l’application hébergée.",
  ],
  "settings.background.title": [
    "Background Activity",
    "Hintergrundaktivität",
    "Activité en arrière-plan",
  ],
  "settings.background.sharedPolicy": [
    "Shared policy",
    "Gemeinsame Richtlinie",
    "Politique partagée",
  ],
  "settings.background.gitFetchInterval": [
    "Git fetch interval",
    "Git-Fetch-Intervall",
    "Intervalle de récupération Git",
  ],
  "settings.background.providerHealthInterval": [
    "Provider health interval",
    "Provider-Prüfintervall",
    "Intervalle de contrôle des fournisseurs",
  ],
  "settings.background.hostPowerMonitor": [
    "Host power monitor",
    "Host-Energiemonitor",
    "Surveillance de l’alimentation de l’hôte",
  ],
  "settings.background.idleHostMonitor": [
    "Idle host monitor",
    "Leerlaufmonitor des Hosts",
    "Surveillance de l’hôte inactif",
  ],
  "settings.background.seconds": ["seconds", "Sekunden", "secondes"],
  "settings.background.configure": [
    "Configure background activity",
    "Hintergrundaktivität konfigurieren",
    "Configurer l’activité en arrière-plan",
  ],
  "settings.background.decreaseGit": [
    "Decrease Git fetch interval",
    "Git-Fetch-Intervall verringern",
    "Réduire l’intervalle de récupération Git",
  ],
  "settings.background.gitSeconds": [
    "Git fetch interval in seconds",
    "Git-Fetch-Intervall in Sekunden",
    "Intervalle de récupération Git en secondes",
  ],
  "settings.background.increaseGit": [
    "Increase Git fetch interval",
    "Git-Fetch-Intervall erhöhen",
    "Augmenter l’intervalle de récupération Git",
  ],
  "settings.background.decreaseProvider": [
    "Decrease provider health interval",
    "Provider-Prüfintervall verringern",
    "Réduire l’intervalle de contrôle des fournisseurs",
  ],
  "settings.background.providerSeconds": [
    "Provider health interval in seconds",
    "Provider-Prüfintervall in Sekunden",
    "Intervalle de contrôle des fournisseurs en secondes",
  ],
  "settings.background.increaseProvider": [
    "Increase provider health interval",
    "Provider-Prüfintervall erhöhen",
    "Augmenter l’intervalle de contrôle des fournisseurs",
  ],
  "settings.background.decreaseActiveHost": [
    "Decrease active host power interval",
    "Intervall des aktiven Host-Energiemonitors verringern",
    "Réduire l’intervalle d’alimentation de l’hôte actif",
  ],
  "settings.background.activeHostSeconds": [
    "Active host power interval in seconds",
    "Intervall des aktiven Host-Energiemonitors in Sekunden",
    "Intervalle d’alimentation de l’hôte actif en secondes",
  ],
  "settings.background.increaseActiveHost": [
    "Increase active host power interval",
    "Intervall des aktiven Host-Energiemonitors erhöhen",
    "Augmenter l’intervalle d’alimentation de l’hôte actif",
  ],
  "settings.background.decreaseIdleHost": [
    "Decrease idle host power interval",
    "Intervall des Leerlaufmonitors verringern",
    "Réduire l’intervalle d’alimentation de l’hôte inactif",
  ],
  "settings.background.idleHostSeconds": [
    "Idle host power interval in seconds",
    "Intervall des Leerlaufmonitors in Sekunden",
    "Intervalle d’alimentation de l’hôte inactif en secondes",
  ],
  "settings.background.increaseIdleHost": [
    "Increase idle host power interval",
    "Intervall des Leerlaufmonitors erhöhen",
    "Augmenter l’intervalle d’alimentation de l’hôte inactif",
  ],
  "settings.common.done": ["Done", "Fertig", "Terminé"],
  "settings.appearance.title": ["Appearance", "Darstellung", "Apparence"],
  "settings.appearance.interfaceLanguage": [
    "Interface language",
    "Oberflächensprache",
    "Langue de l’interface",
  ],
  "settings.appearance.contrastDescription": [
    "Adjust the contrast of colors and borders across the interface.",
    "Passt den Kontrast von Farben und Rahmen in der gesamten Oberfläche an.",
    "Ajuste le contraste des couleurs et des bordures dans toute l’interface.",
  ],
  "settings.appearance.contrast": ["Contrast", "Kontrast", "Contraste"],
  "settings.appearance.glassDescription": [
    "Control how transparent glass surfaces are. Higher values make menus, dialogs, and the composer more solid.",
    "Steuert die Transparenz von Glasflächen. Höhere Werte machen Menüs, Dialoge und den Composer deckender.",
    "Contrôle la transparence des surfaces vitrées. Des valeurs plus élevées rendent les menus, dialogues et l’éditeur plus opaques.",
  ],
  "settings.appearance.glassOpacity": ["Glass opacity", "Glasdeckkraft", "Opacité du verre"],
  "settings.appearance.reasoningDescription": [
    "Show provider-supplied reasoning updates directly in the chat. Availability depends on the selected provider and model.",
    "Zeigt vom Provider gelieferte Reasoning-Updates direkt im Chat. Die Verfügbarkeit hängt vom ausgewählten Provider und Modell ab.",
    "Affiche directement dans la discussion les mises à jour de raisonnement du fournisseur. La disponibilité dépend du fournisseur et du modèle sélectionnés.",
  ],
  "settings.appearance.modelReasoning": [
    "Model reasoning",
    "Modell-Reasoning",
    "Raisonnement du modèle",
  ],
  "settings.appearance.showReasoning": [
    "Show model reasoning in chat",
    "Modell-Reasoning im Chat anzeigen",
    "Afficher le raisonnement du modèle dans la discussion",
  ],
  "settings.appearance.expandedControlsDescription": [
    "Show separate provider, context, mode, and access controls in the chat composer when space permits. Narrow chats continue to use the controls menu.",
    "Zeigt bei ausreichendem Platz getrennte Provider-, Kontext-, Modus- und Zugriffssteuerungen im Chat-Composer. Schmale Chats verwenden weiterhin das Steuerungsmenü.",
    "Affiche des commandes distinctes pour le fournisseur, le contexte, le mode et l’accès dans l’éditeur lorsque l’espace le permet. Les discussions étroites utilisent toujours le menu des commandes.",
  ],
  "settings.appearance.expandedControls": [
    "Expanded chat controls",
    "Erweiterte Chat-Steuerung",
    "Commandes de discussion étendues",
  ],
  "settings.appearance.showExpandedControls": [
    "Show expanded chat controls",
    "Erweiterte Chat-Steuerung anzeigen",
    "Afficher les commandes de discussion étendues",
  ],
  "settings.appearance.environmentIdentificationDescription": [
    "Choose how Dev and Nightly environments are identified.",
    "Legt fest, wie Dev- und Nightly-Umgebungen gekennzeichnet werden.",
    "Choisissez comment les environnements Dev et Nightly sont identifiés.",
  ],
  "settings.appearance.environmentIdentification": [
    "Environment identification",
    "Umgebungskennzeichnung",
    "Identification de l’environnement",
  ],
  "settings.appearance.sidebar": ["Sidebar", "Seitenleiste", "Barre latérale"],
  "settings.appearance.sidebarDescription": [
    "Choose between the current activity-focused sidebar and the classic per-project thread trees.",
    "Wählt zwischen der aktuellen aktivitätsorientierten Seitenleiste und den klassischen Chat-Bäumen pro Projekt.",
    "Choisissez entre la barre latérale actuelle centrée sur l’activité et les arborescences classiques de discussions par projet.",
  ],
  "settings.appearance.uiFontDescription": [
    "Everything outside code blocks and the terminal.",
    "Alles außerhalb von Codeblöcken und Terminal.",
    "Tout ce qui se trouve hors des blocs de code et du terminal.",
  ],
  "settings.appearance.promptFontDescription": [
    "Only the box you write prompts in. Mono works well here.",
    "Nur das Eingabefeld für Prompts. Eine Monospace-Schrift eignet sich hier gut.",
    "Uniquement la zone de saisie des prompts. Une police monospace convient bien ici.",
  ],
  "settings.appearance.codeFontDescription": [
    "Code blocks, diffs, and file previews.",
    "Codeblöcke, Diffs und Dateivorschauen.",
    "Blocs de code, différences et aperçus de fichiers.",
  ],
  "settings.appearance.terminalFontDescription": [
    "Terminal output, independent from code blocks and diffs.",
    "Terminalausgabe, unabhängig von Codeblöcken und Diffs.",
    "Sortie du terminal, indépendante des blocs de code et des différences.",
  ],
  "settings.appearance.fontSmoothingDescription": [
    "Render text with thinner grayscale anti-aliasing instead of macOS's heavier default.",
    "Rendert Text mit dünnerem Graustufen-Anti-Aliasing statt der kräftigeren macOS-Voreinstellung.",
    "Rend le texte avec un anticrénelage en niveaux de gris plus fin que le réglage macOS plus épais.",
  ],
  "settings.appearance.fontSmoothing": ["Font smoothing", "Schriftglättung", "Lissage des polices"],
  "settings.appearance.wordWrapDescription": [
    "Wrap long lines in code blocks, tables, diffs, and file previews by default.",
    "Bricht lange Zeilen in Codeblöcken, Tabellen, Diffs und Dateivorschauen standardmäßig um.",
    "Renvoie par défaut les longues lignes dans les blocs de code, tableaux, différences et aperçus de fichiers.",
  ],
  "settings.appearance.wordWrap": ["Word wrapping", "Zeilenumbruch", "Retour à la ligne"],
  "settings.appearance.wordWrapAria": [
    "Wrap code, tables, diffs, and file previews by default",
    "Code, Tabellen, Diffs und Dateivorschauen standardmäßig umbrechen",
    "Renvoyer par défaut le code, les tableaux, les différences et les aperçus de fichiers",
  ],
  "settings.appearance.monospaceFont": ["Monospace font", "Monospace-Schrift", "Police monospace"],
  "settings.appearance.monospaceDescription": [
    "Code blocks, diffs, file previews, and the terminal.",
    "Codeblöcke, Diffs, Dateivorschauen und Terminal.",
    "Blocs de code, différences, aperçus de fichiers et terminal.",
  ],
  "settings.appearance.typography": ["Typography", "Typografie", "Typographie"],
  "settings.appearance.advancedTypography": [
    "Show advanced typography settings",
    "Erweiterte Typografieeinstellungen anzeigen",
    "Afficher les réglages typographiques avancés",
  ],
  "settings.experimental.planDescription": [
    "Brings back the Build/Plan selector in the composer along with the /plan and /default commands and the Shift+Tab shortcut. While off, every thread runs in Build mode.",
    "Bringt die Build-/Plan-Auswahl im Composer sowie die Befehle /plan und /default und das Kürzel Umschalt+Tab zurück. Wenn deaktiviert, läuft jeder Chat im Build-Modus.",
    "Rétablit le sélecteur Build/Plan dans l’éditeur, les commandes /plan et /default et le raccourci Maj+Tab. Lorsqu’il est désactivé, chaque discussion utilise le mode Build.",
  ],
  "settings.experimental.planAria": [
    "Plan mode (legacy)",
    "Planmodus (Legacy)",
    "Mode Plan (hérité)",
  ],
  "settings.experimental.tokenDescription": [
    "Paints assistant output token by token instead of in complete chunks. Not recommended: it is significantly slower, and long responses become harder to follow. Kept only for compatibility with the old behavior.",
    "Zeigt die Assistentenausgabe Token für Token statt in vollständigen Blöcken. Nicht empfohlen: deutlich langsamer und lange Antworten sind schwerer zu verfolgen. Nur zur Kompatibilität mit dem alten Verhalten vorhanden.",
    "Affiche la sortie de l’assistant jeton par jeton au lieu de blocs complets. Non recommandé : c’est nettement plus lent et les longues réponses deviennent difficiles à suivre. Conservé uniquement pour compatibilité avec l’ancien comportement.",
  ],
  "settings.experimental.tokenAria": [
    "Stream token by token (legacy)",
    "Tokenweise streamen (Legacy)",
    "Diffuser jeton par jeton (hérité)",
  ],
  "settings.general.title": ["General", "Allgemein", "Général"],
  "settings.general.projectGroupingDescription": [
    "Combine matching repositories across environments.",
    "Fasst passende Repositories über Umgebungen hinweg zusammen.",
    "Regroupe les dépôts correspondants entre environnements.",
  ],
  "settings.general.projectGrouping": [
    "Project grouping",
    "Projektgruppierung",
    "Regroupement des projets",
  ],
  "settings.general.autoSettleMergeDescription": [
    "Settle a thread when its pull request merges. Closed pull requests still settle automatically.",
    "Schließt einen Chat ab, wenn dessen Pull Request zusammengeführt wird. Geschlossene Pull Requests werden weiterhin automatisch abgeschlossen.",
    "Classe une discussion lorsque sa demande de tirage est fusionnée. Les demandes fermées sont toujours classées automatiquement.",
  ],
  "settings.general.autoSettleMerge": [
    "Auto-settle on merge",
    "Bei Merge automatisch abschließen",
    "Classer automatiquement après fusion",
  ],
  "settings.general.autoSettleMergeAria": [
    "Auto-settle merged threads",
    "Zusammengeführte Chats automatisch abschließen",
    "Classer automatiquement les discussions fusionnées",
  ],
  "settings.general.autoSettleDescription": [
    "Sidebar threads with no activity for this long settle automatically.",
    "Chats in der Seitenleiste ohne Aktivität über diesen Zeitraum werden automatisch abgeschlossen.",
    "Les discussions sans activité pendant cette durée sont automatiquement classées.",
  ],
  "settings.general.autoSettle": [
    "Auto-settle",
    "Automatisch abschließen",
    "Classement automatique",
  ],
  "settings.general.autoSettleAria": [
    "Auto-settle inactive threads",
    "Inaktive Chats automatisch abschließen",
    "Classer automatiquement les discussions inactives",
  ],
  "settings.general.inactivityDays": [
    "Days of inactivity before auto-settle",
    "Inaktive Tage bis zum automatischen Abschluss",
    "Jours d’inactivité avant classement automatique",
  ],
  "settings.general.unsettleDescription": [
    "Any new activity un-settles a thread automatically.",
    "Neue Aktivität reaktiviert einen Chat automatisch.",
    "Toute nouvelle activité réactive automatiquement une discussion.",
  ],
  "settings.general.timeDescription": [
    "System default follows your browser or OS clock preference.",
    "Der Systemstandard folgt der Uhrzeiteinstellung des Browsers oder Betriebssystems.",
    "La valeur système suit la préférence d’horloge du navigateur ou du système d’exploitation.",
  ],
  "settings.general.timeFormat": ["Time format", "Zeitformat", "Format de l’heure"],
  "settings.general.timestampAria": [
    "Timestamp format",
    "Zeitstempelformat",
    "Format d’horodatage",
  ],
  "settings.general.diffDescription": [
    "Set whether the diff panel ignores whitespace-only edits by default.",
    "Legt fest, ob das Diff-Panel reine Leerzeichenänderungen standardmäßig ignoriert.",
    "Définit si le panneau des différences ignore par défaut les modifications d’espacement uniquement.",
  ],
  "settings.general.diffWhitespace": [
    "Diff whitespace changes",
    "Leerzeichenänderungen im Diff",
    "Modifications d’espacement dans les différences",
  ],
  "settings.general.diffWhitespaceAria": [
    "Hide whitespace changes by default",
    "Leerzeichenänderungen standardmäßig ausblenden",
    "Masquer par défaut les modifications d’espacement",
  ],
  "settings.general.skillsSlashDescription": [
    "Also include skills in the / command menu. Skills always appear when you type $.",
    "Fügt Skills auch dem /-Befehlsmenü hinzu. Bei Eingabe von $ werden Skills immer angezeigt.",
    "Inclut aussi les compétences dans le menu des commandes /. Elles apparaissent toujours lorsque vous saisissez $.",
  ],
  "settings.general.skillsSlash": [
    "Skills in slash menu",
    "Skills im Slash-Menü",
    "Compétences dans le menu slash",
  ],
  "settings.general.skillsSlashAria": [
    "Show skills in slash menu",
    "Skills im Slash-Menü anzeigen",
    "Afficher les compétences dans le menu slash",
  ],
  "settings.general.providerUpdatesDescription": [
    "Check installed provider CLIs for newer available versions.",
    "Prüft installierte Provider-CLIs auf neuere verfügbare Versionen.",
    "Recherche des versions plus récentes des CLI de fournisseurs installées.",
  ],
  "settings.general.providerUpdates": [
    "Provider update checks",
    "Provider-Updateprüfungen",
    "Vérification des mises à jour des fournisseurs",
  ],
  "settings.general.providerUpdatesAria": [
    "Check provider versions",
    "Provider-Versionen prüfen",
    "Vérifier les versions des fournisseurs",
  ],
  "settings.general.backgroundActivity": [
    "Background activity",
    "Hintergrundaktivität",
    "Activité en arrière-plan",
  ],
  "settings.general.backgroundProfileAria": [
    "Background activity profile",
    "Profil der Hintergrundaktivität",
    "Profil d’activité en arrière-plan",
  ],
  "settings.general.defaultWorkspaceDescription": [
    "Pick the default workspace mode for newly created draft threads.",
    "Wählt den Standard-Workspace-Modus für neu erstellte Chatentwürfe.",
    "Choisissez le mode d’espace de travail par défaut des nouveaux brouillons de discussion.",
  ],
  "settings.general.newThreads": ["New threads", "Neue Chats", "Nouvelles discussions"],
  "settings.general.defaultThreadModeAria": [
    "Default thread mode",
    "Standardmodus für Chats",
    "Mode de discussion par défaut",
  ],
  "settings.general.originWorktreeDescription": [
    "Creates the worktree from the latest matching branch on origin instead of your local branch.",
    "Erstellt den Worktree aus dem neuesten passenden Branch auf origin statt aus dem lokalen Branch.",
    "Crée le worktree depuis la dernière branche correspondante sur origin plutôt que depuis la branche locale.",
  ],
  "settings.general.originWorktree": [
    "New worktrees start from origin",
    "Neue Worktrees starten von origin",
    "Les nouveaux worktrees partent d’origin",
  ],
  "settings.general.originWorktreeAria": [
    "Start new worktrees from origin by default",
    "Neue Worktrees standardmäßig von origin starten",
    "Démarrer par défaut les nouveaux worktrees depuis origin",
  ],
  "settings.general.projectBaseDescription": [
    "Leave empty to use '~/‘ when the Add Project browser opens.",
    "Leer lassen, um beim Öffnen des Projektbrowsers „~/“ zu verwenden.",
    "Laissez vide pour utiliser « ~/ » à l’ouverture du sélecteur de projet.",
  ],
  "settings.general.projectBase": [
    "Add project base directory",
    "Basisverzeichnis für neue Projekte",
    "Répertoire de base des projets",
  ],
  "settings.general.unpinDescription": [
    "Ask before unpinning a thread from the pinned section.",
    "Fragt nach, bevor ein Chat aus dem angehefteten Bereich gelöst wird.",
    "Demande confirmation avant de désépingler une discussion.",
  ],
  "settings.general.unpinConfirmation": [
    "Unpin confirmation",
    "Bestätigung beim Lösen",
    "Confirmation de désépinglage",
  ],
  "settings.general.unpinAria": [
    "Confirm thread unpinning",
    "Lösen eines Chats bestätigen",
    "Confirmer le désépinglage de la discussion",
  ],
  "settings.general.archiveDescription": [
    "Require a second click on the inline archive action before a thread is archived.",
    "Erfordert einen zweiten Klick auf die Inline-Archivaktion, bevor ein Chat archiviert wird.",
    "Exige un second clic sur l’action d’archivage intégrée avant d’archiver une discussion.",
  ],
  "settings.general.archiveConfirmation": [
    "Archive confirmation",
    "Archivierungsbestätigung",
    "Confirmation d’archivage",
  ],
  "settings.general.archiveAria": [
    "Confirm thread archiving",
    "Archivierung eines Chats bestätigen",
    "Confirmer l’archivage de la discussion",
  ],
  "settings.general.deleteDescription": [
    "Ask before deleting a thread and its chat history.",
    "Fragt vor dem Löschen eines Chats und seines Verlaufs nach.",
    "Demande confirmation avant de supprimer une discussion et son historique.",
  ],
  "settings.general.deleteConfirmation": [
    "Delete confirmation",
    "Löschbestätigung",
    "Confirmation de suppression",
  ],
  "settings.general.deleteAria": [
    "Confirm thread deletion",
    "Löschen eines Chats bestätigen",
    "Confirmer la suppression de la discussion",
  ],
  "settings.general.quitDescription": [
    "Require holding the quit shortcut before the desktop app quits. A quick tap shows a hint instead.",
    "Erfordert das Gedrückthalten des Beenden-Kürzels, bevor die Desktop-App beendet wird. Ein kurzes Antippen zeigt stattdessen einen Hinweis.",
    "Exige de maintenir le raccourci de fermeture avant de quitter l’application de bureau. Un appui bref affiche plutôt une indication.",
  ],
  "settings.general.quitConfirmation": [
    "Quit confirmation",
    "Beenden bestätigen",
    "Confirmation de fermeture",
  ],
  "settings.general.quitAria": ["Hold to quit", "Zum Beenden halten", "Maintenir pour quitter"],
  "settings.general.textModelDescription": [
    "Default model for generated text like thread titles, source control content, voice translation, and prompt improvement. Source control settings can override it with a dedicated source control writer model.",
    "Standardmodell für generierten Text wie Chat-Titel, Versionsverwaltungsinhalte, Sprachübersetzung und Prompt-Verbesserung. Die Versionsverwaltung kann ein eigenes Schreibmodell verwenden.",
    "Modèle par défaut pour le texte généré comme les titres de discussion, le contenu de gestion de sources, la traduction vocale et l’amélioration des prompts. Les réglages de gestion de sources peuvent le remplacer par un modèle dédié.",
  ],
  "settings.general.textModel": [
    "Text generation model",
    "Textgenerierungsmodell",
    "Modèle de génération de texte",
  ],
  "settings.general.promptImprovementDescription": [
    "Improve the wording and structure of normal chat prompts before they are sent, without changing their language or scope.",
    "Verbessert Formulierung und Struktur normaler Chat-Prompts vor dem Senden, ohne Sprache oder Umfang zu ändern.",
    "Améliore la formulation et la structure des prompts avant leur envoi, sans modifier leur langue ni leur portée.",
  ],
  "settings.general.promptImprovement": [
    "Prompt improvement",
    "Prompt-Verbesserung",
    "Amélioration du prompt",
  ],
  "settings.general.promptImprovementAria": [
    "Improve prompts before sending",
    "Prompts vor dem Senden verbessern",
    "Améliorer les prompts avant l’envoi",
  ],
  "settings.about.title": ["About", "Über", "À propos"],
  "settings.about.versionDescription": [
    "Current version of the application.",
    "Aktuelle Version der Anwendung.",
    "Version actuelle de l’application.",
  ],
  "settings.thread.unarchive": ["Unarchive", "Dearchivieren", "Désarchiver"],
});

export type SettingsInterfaceMessageKey = (typeof settingsInterfaceCatalog.keys)[number];
