import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const knowledgeGraphInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "knowledgeGraph.title": [
    "Project Knowledge Graph",
    "Projekt-Wissensgraph",
    "Graphe de connaissances du projet",
  ],
  "knowledgeGraph.launchDescription": [
    "Explore project relationships.",
    "Projektbeziehungen erkunden.",
    "Explorer les relations du projet.",
  ],
  "knowledgeGraph.search.label": [
    "Search the Knowledge Graph",
    "Wissensgraph durchsuchen",
    "Rechercher dans le graphe de connaissances",
  ],
  "knowledgeGraph.search.placeholder": [
    "Search files, symbols, technologies, and relationships",
    "Dateien, Symbole, Technologien und Beziehungen suchen",
    "Rechercher fichiers, symboles, technologies et relations",
  ],
  "knowledgeGraph.filters.label": [
    "Filter node kinds",
    "Knotenarten filtern",
    "Filtrer les types de nœuds",
  ],
  "knowledgeGraph.filter.all": ["All kinds", "Alle Arten", "Tous les types"],
  "knowledgeGraph.zoomIn": ["Zoom in", "Vergrößern", "Agrandir"],
  "knowledgeGraph.zoomOut": ["Zoom out", "Verkleinern", "Réduire"],
  "knowledgeGraph.resetView": ["Reset view", "Ansicht zurücksetzen", "Réinitialiser la vue"],
  "knowledgeGraph.expandNode": ["Expand node", "Knoten erweitern", "Développer le nœud"],
  "knowledgeGraph.collapseNode": ["Collapse node", "Knoten einklappen", "Réduire le nœud"],
  "knowledgeGraph.openSource": ["Open source", "Quelldatei öffnen", "Ouvrir la source"],
  "knowledgeGraph.provenance": ["Provenance", "Herkunft", "Provenance"],
  "knowledgeGraph.provenance.deterministic": ["Deterministic", "Deterministisch", "Déterministe"],
  "knowledgeGraph.provenance.semantic": ["Semantic", "Semantisch", "Sémantique"],
  "knowledgeGraph.confidence": ["Confidence", "Konfidenz", "Confiance"],
  "knowledgeGraph.relationships": ["Relationships", "Beziehungen", "Relations"],
  "knowledgeGraph.noRelationships": [
    "No relationships found",
    "Keine Beziehungen gefunden",
    "Aucune relation trouvée",
  ],
  "knowledgeGraph.empty": [
    "No indexed knowledge is available yet.",
    "Noch kein indexiertes Wissen verfügbar.",
    "Aucune connaissance indexée n’est encore disponible.",
  ],
  "knowledgeGraph.loading": [
    "Loading Knowledge Graph…",
    "Wissensgraph wird geladen…",
    "Chargement du graphe de connaissances…",
  ],
  "knowledgeGraph.unsupported": [
    "This environment does not support the Knowledge Graph.",
    "Diese Umgebung unterstützt den Wissensgraph nicht.",
    "Cet environnement ne prend pas en charge le graphe de connaissances.",
  ],
  "knowledgeGraph.disabled": [
    "Enable the Knowledge Graph in Better T3 settings.",
    "Den Wissensgraph in den Better-T3-Einstellungen aktivieren.",
    "Activez le graphe de connaissances dans les réglages Better T3.",
  ],
  "knowledgeGraph.error": [
    "The Knowledge Graph could not be loaded.",
    "Der Wissensgraph konnte nicht geladen werden.",
    "Le graphe de connaissances n’a pas pu être chargé.",
  ],
  "knowledgeGraph.retry": ["Retry", "Erneut versuchen", "Réessayer"],
  "knowledgeGraph.truncated": [
    "Some graph results are omitted by safety bounds.",
    "Einige Graphergebnisse wurden durch Sicherheitsgrenzen ausgelassen.",
    "Certains résultats du graphe sont omis par les limites de sécurité.",
  ],
  "knowledgeGraph.omittedNodes": [
    { one: "{{count}} node omitted", other: "{{count}} nodes omitted" },
    { one: "{{count}} Knoten ausgelassen", other: "{{count}} Knoten ausgelassen" },
    { one: "{{count}} nœud omis", other: "{{count}} nœuds omis" },
  ],
  "knowledgeGraph.sourceUnavailable": [
    "Source content is unavailable.",
    "Quellinhalt ist nicht verfügbar.",
    "Le contenu source est indisponible.",
  ],
  "knowledgeGraph.rebuild": ["Rebuild", "Neu aufbauen", "Reconstruire"],
  "knowledgeGraph.rebuild.incremental": [
    "Incremental rebuild",
    "Inkrementell neu aufbauen",
    "Reconstruction incrémentielle",
  ],
  "knowledgeGraph.rebuild.full": [
    "Full rebuild",
    "Vollständig neu aufbauen",
    "Reconstruction complète",
  ],
  "knowledgeGraph.pause": ["Pause indexing", "Indexierung pausieren", "Suspendre l’indexation"],
  "knowledgeGraph.resume": ["Resume indexing", "Indexierung fortsetzen", "Reprendre l’indexation"],
  "knowledgeGraph.cancel": ["Cancel indexing", "Indexierung abbrechen", "Annuler l’indexation"],
  "knowledgeGraph.clear": ["Clear graph", "Graph leeren", "Effacer le graphe"],
  "knowledgeGraph.clearConfirm.title": [
    "Clear the Knowledge Graph?",
    "Wissensgraph leeren?",
    "Effacer le graphe de connaissances ?",
  ],
  "knowledgeGraph.clearConfirm.description": [
    "Derived graph data will be removed. Repository files and orchestration history are not changed.",
    "Abgeleitete Graphdaten werden entfernt. Repository-Dateien und Orchestrierungsverlauf bleiben unverändert.",
    "Les données dérivées du graphe seront supprimées. Les fichiers du dépôt et l’historique d’orchestration ne seront pas modifiés.",
  ],
  "knowledgeGraph.resultCount": [
    { one: "{{count}} result", other: "{{count}} results" },
    { one: "{{count}} Ergebnis", other: "{{count}} Ergebnisse" },
    { one: "{{count}} résultat", other: "{{count}} résultats" },
  ],
  "knowledgeGraph.indexedFileCount": [
    { one: "{{count}} indexed file", other: "{{count}} indexed files" },
    { one: "{{count}} indexierte Datei", other: "{{count}} indexierte Dateien" },
    { one: "{{count}} fichier indexé", other: "{{count}} fichiers indexés" },
  ],
  "knowledgeGraph.nodeCount": [
    { one: "{{count}} node", other: "{{count}} nodes" },
    { one: "{{count}} Knoten", other: "{{count}} Knoten" },
    { one: "{{count}} nœud", other: "{{count}} nœuds" },
  ],
  "knowledgeGraph.sourceSummary": [
    "Source: {{source}}",
    "Quelle: {{source}}",
    "Source : {{source}}",
  ],
  "knowledgeGraph.direction.incoming": ["Incoming", "Eingehend", "Entrantes"],
  "knowledgeGraph.direction.outgoing": ["Outgoing", "Ausgehend", "Sortantes"],
  "knowledgeGraph.nodeKind.repository": ["Repository", "Repository", "Dépôt"],
  "knowledgeGraph.nodeKind.package": ["Package", "Paket", "Paquet"],
  "knowledgeGraph.nodeKind.directory": ["Directory", "Verzeichnis", "Dossier"],
  "knowledgeGraph.nodeKind.file": ["File", "Datei", "Fichier"],
  "knowledgeGraph.nodeKind.symbol": ["Symbol", "Symbol", "Symbole"],
  "knowledgeGraph.nodeKind.dependency": ["Dependency", "Abhängigkeit", "Dépendance"],
  "knowledgeGraph.nodeKind.technology": ["Technology", "Technologie", "Technologie"],
  "knowledgeGraph.nodeKind.documentation": ["Documentation", "Dokumentation", "Documentation"],
  "knowledgeGraph.nodeKind.architecture": ["Architecture", "Architektur", "Architecture"],
  "knowledgeGraph.edgeKind.contains": ["Contains", "Enthält", "Contient"],
  "knowledgeGraph.edgeKind.declares": ["Declares", "Deklariert", "Déclare"],
  "knowledgeGraph.edgeKind.imports": ["Imports", "Importiert", "Importe"],
  "knowledgeGraph.edgeKind.depends-on": ["Depends on", "Hängt ab von", "Dépend de"],
  "knowledgeGraph.edgeKind.uses": ["Uses", "Verwendet", "Utilise"],
  "knowledgeGraph.edgeKind.implements": ["Implements", "Implementiert", "Implémente"],
  "knowledgeGraph.edgeKind.extends": ["Extends", "Erweitert", "Étend"],
  "knowledgeGraph.edgeKind.documents": ["Documents", "Dokumentiert", "Documente"],
  "knowledgeGraph.edgeKind.configures": ["Configures", "Konfiguriert", "Configure"],
  "knowledgeGraph.edgeKind.co-changes-with": [
    "Changes together with",
    "Ändert sich gemeinsam mit",
    "Évolue avec",
  ],
  "knowledgeGraph.edgeKind.relates-to": ["Relates to", "Steht in Beziehung zu", "Est lié à"],
  "knowledgeGraph.status.disabled": ["Disabled", "Deaktiviert", "Désactivé"],
  "knowledgeGraph.status.idle": ["Idle", "Bereit", "Inactif"],
  "knowledgeGraph.status.indexing": ["Indexing", "Indexierung läuft", "Indexation"],
  "knowledgeGraph.status.semantic": [
    "Enriching relationships",
    "Beziehungen werden angereichert",
    "Enrichissement des relations",
  ],
  "knowledgeGraph.status.ready": ["Ready", "Fertig", "Prêt"],
  "knowledgeGraph.status.paused": ["Paused", "Pausiert", "En pause"],
  "knowledgeGraph.status.rate-limited": [
    "Waiting for the model rate limit",
    "Warten auf das Modell-Limit",
    "En attente de la limite du modèle",
  ],
  "knowledgeGraph.status.cancelling": ["Cancelling", "Abbruch läuft", "Annulation"],
  "knowledgeGraph.status.error": ["Error", "Fehler", "Erreur"],
  "knowledgeGraph.accessibility.canvas": [
    "Interactive project relationship graph",
    "Interaktiver Projekt-Beziehungsgraph",
    "Graphe interactif des relations du projet",
  ],
  "knowledgeGraph.accessibility.node": [
    "Graph node: {{label}}",
    "Graphknoten: {{label}}",
    "Nœud du graphe : {{label}}",
  ],
  "knowledgeGraph.accessibility.nodeHint": [
    "Open details and related source",
    "Details und zugehörige Quelle öffnen",
    "Ouvrir les détails et la source associée",
  ],
  "knowledgeGraph.accessibility.relationship": [
    "{{source}} {{relationship}} {{target}}",
    "{{source}} {{relationship}} {{target}}",
    "{{source}} {{relationship}} {{target}}",
  ],
  "knowledgeGraph.accessibility.zoomControls": [
    "Knowledge Graph zoom controls",
    "Zoomsteuerung für den Wissensgraph",
    "Commandes de zoom du graphe de connaissances",
  ],
});

export type KnowledgeGraphInterfaceMessageKey =
  (typeof knowledgeGraphInterfaceCatalog.keys)[number];
