import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const settingsMcpInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "settings.mcp.editor.add": ["Add", "Hinzufügen", "Ajouter"],
  "settings.mcp.editor.emptyValues": [
    "No values configured.",
    "Keine Werte konfiguriert.",
    "Aucune valeur configurée.",
  ],
  "settings.mcp.editor.storedSecret": [
    "Stored secret",
    "Gespeichertes Secret",
    "Secret enregistré",
  ],
  "settings.mcp.editor.value": ["Value", "Wert", "Valeur"],
  "settings.mcp.editor.sensitive": ["Sensitive", "Vertraulich", "Sensible"],
  "settings.mcp.editor.removeValue": [
    "Remove {{name}} value",
    "Wert {{name}} entfernen",
    "Supprimer la valeur {{name}}",
  ],
  "settings.mcp.editor.editTitle": [
    "Edit MCP server",
    "MCP-Server bearbeiten",
    "Modifier le serveur MCP",
  ],
  "settings.mcp.editor.newTitle": ["New MCP server", "Neuer MCP-Server", "Nouveau serveur MCP"],
  "settings.mcp.editor.description": [
    "T3 stores MCP configuration locally and resolves it when a provider session starts.",
    "T3 speichert die MCP-Konfiguration lokal und löst sie beim Start einer Provider-Sitzung auf.",
    "T3 conserve la configuration MCP localement et la résout au démarrage d’une session fournisseur.",
  ],
  "settings.mcp.editor.name": ["Name", "Name", "Nom"],
  "settings.mcp.editor.namePlaceholder": ["GitHub", "GitHub", "GitHub"],
  "settings.mcp.editor.identifier": ["Identifier", "Kennung", "Identifiant"],
  "settings.mcp.editor.scope": ["Scope", "Geltungsbereich", "Portée"],
  "settings.mcp.editor.global": ["Global", "Global", "Globale"],
  "settings.mcp.editor.project": ["Project", "Projekt", "Projet"],
  "settings.mcp.editor.noProject": ["No project", "Kein Projekt", "Aucun projet"],
  "settings.mcp.editor.enabled": ["Enabled", "Aktiviert", "Activé"],
  "settings.mcp.editor.enableFor": ["Enable for", "Aktivieren für", "Activer pour"],
  "settings.mcp.editor.allAccounts": [
    "All provider accounts",
    "Alle Provider-Konten",
    "Tous les comptes fournisseur",
  ],
  "settings.mcp.editor.allProvidersDescription": [
    "This server will be available to every configured provider that supports MCP.",
    "Dieser Server ist für jeden konfigurierten Provider verfügbar, der MCP unterstützt.",
    "Ce serveur sera disponible pour chaque fournisseur configuré prenant en charge MCP.",
  ],
  "settings.mcp.editor.transport": ["Transport", "Transport", "Transport"],
  "settings.mcp.editor.transport.stdio": ["stdio", "stdio", "stdio"],
  "settings.mcp.editor.transport.sse": ["SSE", "SSE", "SSE"],
  "settings.mcp.editor.transport.http": ["HTTP", "HTTP", "HTTP"],
  "settings.mcp.editor.command": ["Command", "Befehl", "Commande"],
  "settings.mcp.editor.commandPlaceholder": ["npx", "npx", "npx"],
  "settings.mcp.editor.cwd": ["Working directory", "Arbeitsverzeichnis", "Répertoire de travail"],
  "settings.mcp.editor.cwdPlaceholder": ["/repo", "/repo", "/repo"],
  "settings.mcp.editor.arguments": ["Arguments", "Argumente", "Arguments"],
  "settings.mcp.editor.argumentsPlaceholder": [
    "-y\n@modelcontextprotocol/server-github",
    "-y\n@modelcontextprotocol/server-github",
    "-y\n@modelcontextprotocol/server-github",
  ],
  "settings.mcp.editor.environment": ["Environment", "Umgebung", "Environnement"],
  "settings.mcp.editor.url": ["URL", "URL", "URL"],
  "settings.mcp.editor.headers": ["Headers", "Header", "En-têtes"],
  "settings.mcp.editor.save": ["Save", "Speichern", "Enregistrer"],
  "settings.mcp.import.scanning": [
    "Scanning agent folders…",
    "Agent-Ordner werden durchsucht…",
    "Analyse des dossiers d’agents…",
  ],
  "settings.mcp.import.noneFound": [
    "No agent dotfolders with importable MCP config were found.",
    "Keine Agent-Dotfolder mit importierbarer MCP-Konfiguration gefunden.",
    "Aucun dossier caché d’agent avec une configuration MCP importable n’a été trouvé.",
  ],
  "settings.mcp.import.server": ["MCP server", "MCP-Server", "serveur MCP"],
  "settings.mcp.import.skill": ["skill", "Skill", "compétence"],
  "settings.mcp.import.skillCount": [
    { one: "{{count}} skill", other: "{{count}} skills" },
    { one: "{{count}} Skill", other: "{{count}} Skills" },
    { one: "{{count}} compétence", other: "{{count}} compétences" },
  ],
  "settings.mcp.import.title": [
    "Import Agent Configs",
    "Agent-Konfigurationen importieren",
    "Importer des configurations d’agents",
  ],
  "settings.mcp.import.description": [
    "Import MCP servers from detected Codex, Cursor, Claude, and OpenCode folders.",
    "MCP-Server aus erkannten Codex-, Cursor-, Claude- und OpenCode-Ordnern importieren.",
    "Importer des serveurs MCP depuis les dossiers Codex, Cursor, Claude et OpenCode détectés.",
  ],
  "settings.mcp.import.enableFor": [
    "Enable imported servers for",
    "Importierte Server aktivieren für",
    "Activer les serveurs importés pour",
  ],
  "settings.mcp.import.allAccounts": ["All accounts", "Alle Konten", "Tous les comptes"],
  "settings.mcp.import.replace": [
    "Replace existing MCP servers",
    "Vorhandene MCP-Server ersetzen",
    "Remplacer les serveurs MCP existants",
  ],
  "settings.mcp.import.deduplicate": [
    "Deduplicate matching MCP servers",
    "Übereinstimmende MCP-Server deduplizieren",
    "Dédupliquer les serveurs MCP correspondants",
  ],
  "settings.mcp.import.action": ["Import", "Importieren", "Importer"],
  "settings.mcp.export.title": [
    "Export Cursor JSON",
    "Cursor-JSON exportieren",
    "Exporter le JSON Cursor",
  ],
  "settings.mcp.export.description": [
    "Export the selected MCP servers as Cursor-compatible JSON.",
    "Ausgewählte MCP-Server als Cursor-kompatibles JSON exportieren.",
    "Exporter les serveurs MCP sélectionnés au format JSON compatible avec Cursor.",
  ],
  "settings.mcp.export.assignmentWarning": [
    "This export contains the servers enabled for the selected provider account. Cursor JSON does not preserve T3 provider assignments.",
    "Dieser Export enthält die für das ausgewählte Provider-Konto aktivierten Server. Cursor-JSON behält T3-Provider-Zuweisungen nicht bei.",
    "Cet export contient les serveurs activés pour le compte fournisseur sélectionné. Le JSON Cursor ne conserve pas les affectations de fournisseurs T3.",
  ],
  "settings.mcp.export.all": ["All", "Alle", "Tous"],
  "settings.mcp.export.includeDisabled": [
    "Include disabled servers",
    "Deaktivierte Server einschließen",
    "Inclure les serveurs désactivés",
  ],
  "settings.mcp.export.refresh": ["Refresh", "Aktualisieren", "Actualiser"],
  "settings.mcp.export.copy": ["Copy", "Kopieren", "Copier"],
  "settings.mcp.toast.updateFailed": [
    "Could not update MCP server",
    "MCP-Server konnte nicht aktualisiert werden",
    "Impossible de mettre à jour le serveur MCP",
  ],
  "settings.mcp.toast.deleteFailed": [
    "Could not delete MCP server",
    "MCP-Server konnte nicht gelöscht werden",
    "Impossible de supprimer le serveur MCP",
  ],
  "settings.mcp.toast.copied": ["MCP JSON copied", "MCP-JSON kopiert", "JSON MCP copié"],
  "settings.mcp.toast.authorizationFailed": [
    "Could not open authorization",
    "Autorisierung konnte nicht geöffnet werden",
    "Impossible d’ouvrir l’autorisation",
  ],
  "settings.mcp.toast.actionFailed": [
    "MCP action failed",
    "MCP-Aktion fehlgeschlagen",
    "Échec de l’action MCP",
  ],
  "settings.mcp.toast.inventoryFailed": [
    "Could not load MCP inventory",
    "MCP-Inventar konnte nicht geladen werden",
    "Impossible de charger l’inventaire MCP",
  ],
  "settings.mcp.session.ended": [
    "Ended or unavailable session",
    "Beendete oder nicht verfügbare Sitzung",
    "Session terminée ou indisponible",
  ],
  "settings.mcp.page.title": ["MCP Servers", "MCP-Server", "Serveurs MCP"],
  "settings.mcp.page.import": ["Import", "Importieren", "Importer"],
  "settings.mcp.page.export": ["Export", "Exportieren", "Exporter"],
  "settings.mcp.page.new": ["New", "Neu", "Nouveau"],
  "settings.mcp.workspace.providerManaged": [
    "Provider-managed servers",
    "Vom Provider verwaltete Server",
    "Serveurs gérés par le fournisseur",
  ],
  "settings.mcp.workspace.systemServer": [
    "T3 Code System Server",
    "T3-Code-Systemserver",
    "Serveur système T3 Code",
  ],
  "settings.mcp.workspace.resourcesAria": ["MCP resources", "MCP-Ressourcen", "Ressources MCP"],
  "settings.mcp.workspace.resourceTemplatesAria": [
    "MCP resource templates",
    "MCP-Ressourcenvorlagen",
    "Modèles de ressources MCP",
  ],
});

export type SettingsMcpInterfaceMessageKey = (typeof settingsMcpInterfaceCatalog.keys)[number];
