import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const desktopInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "desktop.menu.file": ["File", "Datei", "Fichier"],
  "desktop.menu.view": ["View", "Ansicht", "Affichage"],
  "desktop.menu.help": ["Help", "Hilfe", "Aide"],
  "desktop.menu.settings": ["Settings...", "Einstellungen...", "Réglages..."],
  "desktop.menu.checkForUpdates": [
    "Check for Updates...",
    "Nach Updates suchen...",
    "Rechercher les mises à jour...",
  ],
  "desktop.menu.actualSize": ["Actual Size", "Tatsächliche Größe", "Taille réelle"],
  "desktop.menu.zoomIn": ["Zoom In", "Vergrößern", "Agrandir"],
  "desktop.menu.zoomOut": ["Zoom Out", "Verkleinern", "Réduire"],
  "desktop.update.upToDateTitle": [
    "You're up to date!",
    "T3 Code ist aktuell",
    "T3 Code est à jour",
  ],
  "desktop.update.upToDateMessage": [
    "T3 Code {{version}} is currently the newest version available.",
    "T3 Code {{version}} ist derzeit die neueste verfügbare Version.",
    "T3 Code {{version}} est actuellement la version la plus récente disponible.",
  ],
  "desktop.update.checkFailedTitle": [
    "Update check failed",
    "Update-Prüfung fehlgeschlagen",
    "Échec de la recherche de mise à jour",
  ],
  "desktop.update.checkFailedMessage": [
    "Could not check for updates.",
    "Es konnte nicht nach Updates gesucht werden.",
    "Impossible de rechercher les mises à jour.",
  ],
  "desktop.update.unknownError": [
    "An unknown error occurred. Please try again later.",
    "Ein unbekannter Fehler ist aufgetreten. Später erneut versuchen.",
    "Une erreur inconnue s’est produite. Veuillez réessayer ultérieurement.",
  ],
  "desktop.update.unavailableTitle": [
    "Updates unavailable",
    "Updates nicht verfügbar",
    "Mises à jour indisponibles",
  ],
  "desktop.update.unavailableMessage": [
    "Automatic updates are not available right now.",
    "Automatische Updates sind derzeit nicht verfügbar.",
    "Les mises à jour automatiques ne sont pas disponibles actuellement.",
  ],
  "desktop.update.disabled.noFeed": [
    "Automatic updates are not available because no update feed is configured.",
    "Automatische Updates sind nicht verfügbar, weil keine Update-Quelle konfiguriert ist.",
    "Les mises à jour automatiques sont indisponibles, car aucune source de mise à jour n’est configurée.",
  ],
  "desktop.update.disabled.development": [
    "Automatic updates are only available in packaged production builds.",
    "Automatische Updates sind nur in paketierten Produktions-Builds verfügbar.",
    "Les mises à jour automatiques sont uniquement disponibles dans les versions de production empaquetées.",
  ],
  "desktop.update.disabled.environment": [
    "Automatic updates are disabled by the T3CODE_DISABLE_AUTO_UPDATE setting.",
    "Automatische Updates wurden durch die Einstellung T3CODE_DISABLE_AUTO_UPDATE deaktiviert.",
    "Les mises à jour automatiques sont désactivées par le réglage T3CODE_DISABLE_AUTO_UPDATE.",
  ],
  "desktop.update.disabled.linuxPackage": [
    "Automatic updates on Linux require running the AppImage build.",
    "Automatische Updates unter Linux erfordern den AppImage-Build.",
    "Sous Linux, les mises à jour automatiques nécessitent la version AppImage.",
  ],
  "desktop.startup.failedTitle": [
    "T3 Code failed to start",
    "T3 Code konnte nicht gestartet werden",
    "Échec du démarrage de T3 Code",
  ],
  "desktop.startup.failedContent": [
    "Stage: {{stage}}\n{{message}}{{detail}}",
    "Phase: {{stage}}\n{{message}}{{detail}}",
    "Étape : {{stage}}\n{{message}}{{detail}}",
  ],
  "desktop.wsl.stillUnavailableTitle": [
    "WSL backend is still unavailable",
    "WSL-Backend ist weiterhin nicht verfügbar",
    "Le backend WSL est toujours indisponible",
  ],
  "desktop.wsl.fallbackTemporaryMessage": [
    "{{reason}}\n\nT3 Code will use the Windows backend for this launch and retry WSL the next time the app starts.",
    "{{reason}}\n\nT3 Code verwendet für diesen Start das Windows-Backend und versucht WSL beim nächsten App-Start erneut.",
    "{{reason}}\n\nT3 Code utilisera le backend Windows pour ce démarrage et réessaiera WSL au prochain lancement de l’application.",
  ],
  "desktop.wsl.couldNotStartTitle": [
    "WSL backend couldn't start",
    "WSL-Backend konnte nicht gestartet werden",
    "Impossible de démarrer le backend WSL",
  ],
  "desktop.wsl.fallbackPersistentMessage": [
    "{{reason}}\n\nFalling back to the Windows backend so T3 Code can open. Re-enable the WSL backend from Settings > Connections once the WSL distro is fixed.",
    "{{reason}}\n\nT3 Code wechselt zum Windows-Backend, damit die App geöffnet werden kann. Aktiviere das WSL-Backend unter Einstellungen > Verbindungen erneut, sobald die WSL-Distribution repariert ist.",
    "{{reason}}\n\nT3 Code revient au backend Windows afin de pouvoir s’ouvrir. Réactivez le backend WSL dans Réglages > Connexions après avoir réparé la distribution WSL.",
  ],
  "desktop.picker.images": ["Images", "Bilder", "Images"],
  "desktop.endpoint.provider.manual": ["Manual", "Manuell", "Manuel"],
  "desktop.endpoint.thisMachine": ["This machine", "Dieser Computer", "Cet ordinateur"],
  "desktop.endpoint.thisMachineDescription": [
    "Loopback endpoint for this desktop app.",
    "Loopback-Endpunkt für diese Desktop-App.",
    "Point de terminaison local pour cette application de bureau.",
  ],
  "desktop.endpoint.localNetwork": ["Local network", "Lokales Netzwerk", "Réseau local"],
  "desktop.endpoint.localNetworkDescription": [
    "Reachable from devices on the same network.",
    "Von Geräten im selben Netzwerk erreichbar.",
    "Accessible depuis les appareils du même réseau.",
  ],
  "desktop.endpoint.customHttps": ["Custom HTTPS", "Eigenes HTTPS", "HTTPS personnalisé"],
  "desktop.endpoint.custom": [
    "Custom endpoint",
    "Eigener Endpunkt",
    "Point de terminaison personnalisé",
  ],
  "desktop.endpoint.customHttpsDescription": [
    "User-configured HTTPS endpoint for this desktop backend.",
    "Vom Benutzer konfigurierter HTTPS-Endpunkt für dieses Desktop-Backend.",
    "Point de terminaison HTTPS configuré par l’utilisateur pour ce backend de bureau.",
  ],
  "desktop.endpoint.customDescription": [
    "User-configured endpoint for this desktop backend.",
    "Vom Benutzer konfigurierter Endpunkt für dieses Desktop-Backend.",
    "Point de terminaison configuré par l’utilisateur pour ce backend de bureau.",
  ],
  "desktop.endpoint.sameTailnetDescription": [
    "Reachable from devices on the same Tailnet.",
    "Von Geräten im selben Tailnet erreichbar.",
    "Accessible depuis les appareils du même Tailnet.",
  ],
  "desktop.endpoint.tailscaleServeDescription": [
    "HTTPS endpoint served by Tailscale Serve.",
    "Von Tailscale Serve bereitgestellter HTTPS-Endpunkt.",
    "Point de terminaison HTTPS fourni par Tailscale Serve.",
  ],
  "desktop.endpoint.tailscaleConfigureDescription": [
    "MagicDNS hostname. Configure Tailscale Serve for HTTPS access.",
    "MagicDNS-Hostname. Konfiguriere Tailscale Serve für den HTTPS-Zugriff.",
    "Nom d’hôte MagicDNS. Configurez Tailscale Serve pour l’accès HTTPS.",
  ],
  "desktop.wsl.defaultEnvironmentLabel": [
    "WSL (default distro)",
    "WSL (Standarddistribution)",
    "WSL (distribution par défaut)",
  ],
  "desktop.wsl.environmentLabel": ["WSL ({{distro}})", "WSL ({{distro}})", "WSL ({{distro}})"],
  "desktop.contextMenu.noSuggestions": ["No suggestions", "Keine Vorschläge", "Aucune suggestion"],
  "desktop.contextMenu.copyLink": ["Copy Link", "Link kopieren", "Copier le lien"],
  "desktop.contextMenu.copyImage": ["Copy Image", "Bild kopieren", "Copier l’image"],
  "desktop.preview.liveBrowserPreview": [
    "Live browser preview",
    "Live-Browser-Vorschau",
    "Aperçu du navigateur en direct",
  ],
  "desktop.preview.annotation.styleValue": ["Style value", "Stilwert", "Valeur du style"],
  "desktop.preview.annotation.expandEditor": [
    "Expand annotation editor",
    "Anmerkungseditor erweitern",
    "Développer l’éditeur d’annotations",
  ],
  "desktop.preview.annotation.collapseEditor": [
    "Collapse annotation editor",
    "Anmerkungseditor einklappen",
    "Réduire l’éditeur d’annotations",
  ],
  "desktop.preview.annotation.describeChange": [
    "Describe the change…",
    "Änderung beschreiben…",
    "Décrivez la modification…",
  ],
  "desktop.preview.annotation.dragEditor": [
    "Drag annotation editor",
    "Anmerkungseditor verschieben",
    "Déplacer l’éditeur d’annotations",
  ],
  "desktop.preview.annotation.attach": ["Attach", "Anhängen", "Joindre"],
  "desktop.preview.annotation.attachTitle": [
    "Attach annotation and screenshot (Enter)",
    "Anmerkung und Screenshot anhängen (Eingabetaste)",
    "Joindre l’annotation et la capture d’écran (Entrée)",
  ],
  "desktop.preview.annotation.capturing": ["Capturing…", "Aufnahme läuft…", "Capture en cours…"],
  "desktop.preview.annotation.font": ["Font", "Schriftart", "Police"],
  "desktop.preview.annotation.fontSize": ["Font size", "Schriftgröße", "Taille de police"],
  "desktop.preview.annotation.fontWeight": ["Font weight", "Schriftstärke", "Graisse de police"],
  "desktop.preview.annotation.lineHeight": ["Line height", "Zeilenhöhe", "Hauteur de ligne"],
  "desktop.preview.annotation.textColor": ["Text color", "Textfarbe", "Couleur du texte"],
  "desktop.preview.annotation.colorValue": [
    "{{label}} value",
    "Wert für {{label}}",
    "Valeur de {{label}}",
  ],
  "desktop.preview.annotation.background": ["Background", "Hintergrund", "Arrière-plan"],
  "desktop.preview.annotation.opacity": ["Opacity", "Deckkraft", "Opacité"],
  "desktop.preview.annotation.radius": ["Radius", "Radius", "Rayon"],
  "desktop.preview.annotation.borderColor": ["Border color", "Rahmenfarbe", "Couleur de bordure"],
  "desktop.preview.annotation.borderWidth": ["Border width", "Rahmenbreite", "Largeur de bordure"],
  "desktop.preview.annotation.width": ["Width", "Breite", "Largeur"],
  "desktop.preview.annotation.height": ["Height", "Höhe", "Hauteur"],
  "desktop.preview.annotation.lockAspectRatio": [
    "Lock aspect ratio",
    "Seitenverhältnis sperren",
    "Verrouiller les proportions",
  ],
  "desktop.preview.annotation.padding": ["Padding", "Innenabstand", "Marge intérieure"],
  "desktop.preview.annotation.margin": ["Margin", "Außenabstand", "Marge extérieure"],
  "desktop.preview.annotation.gap": ["Gap", "Abstand", "Espacement"],
  "desktop.preview.annotation.select": ["Select", "Auswählen", "Sélectionner"],
  "desktop.preview.annotation.selectTitle": [
    "Select elements (V)",
    "Elemente auswählen (V)",
    "Sélectionner des éléments (V)",
  ],
  "desktop.preview.annotation.region": ["Region", "Bereich", "Région"],
  "desktop.preview.annotation.regionTitle": [
    "Draw a region or marquee-select elements (R)",
    "Bereich zeichnen oder Elemente per Auswahlrahmen auswählen (R)",
    "Dessiner une région ou sélectionner des éléments par zone (R)",
  ],
  "desktop.preview.annotation.draw": ["Draw", "Zeichnen", "Dessiner"],
  "desktop.preview.annotation.drawTitle": [
    "Draw freehand (D)",
    "Freihand zeichnen (D)",
    "Dessiner à main levée (D)",
  ],
  "desktop.preview.annotation.erase": ["Erase", "Löschen", "Effacer"],
  "desktop.preview.annotation.eraseTitle": [
    "Remove an annotation target (E)",
    "Anmerkungsziel entfernen (E)",
    "Supprimer une cible d’annotation (E)",
  ],
  "desktop.ssh.randomnessUnavailable": [
    "Secure randomness is unavailable.",
    "Sichere Zufallswerte sind nicht verfügbar.",
    "La génération aléatoire sécurisée est indisponible.",
  ],
  "desktop.ssh.windowUnavailable": [
    "T3 Code window is not available for SSH authentication.",
    "Das T3-Code-Fenster ist für die SSH-Authentifizierung nicht verfügbar.",
    "La fenêtre T3 Code n’est pas disponible pour l’authentification SSH.",
  ],
  "desktop.ssh.timedOut": [
    "SSH authentication timed out for {{destination}}.",
    "Zeitüberschreitung bei der SSH-Authentifizierung für {{destination}}.",
    "L’authentification SSH a expiré pour {{destination}}.",
  ],
  "desktop.ssh.cancelled": [
    "SSH authentication cancelled for {{destination}}.",
    "SSH-Authentifizierung für {{destination}} abgebrochen.",
    "Authentification SSH annulée pour {{destination}}.",
  ],
  "desktop.ssh.windowClosed": [
    "SSH authentication was cancelled because the app window closed.",
    "Die SSH-Authentifizierung wurde abgebrochen, weil das App-Fenster geschlossen wurde.",
    "L’authentification SSH a été annulée, car la fenêtre de l’application a été fermée.",
  ],
  "desktop.ssh.serviceStopped": [
    "SSH password prompt service stopped.",
    "Der Dienst für SSH-Passwortabfragen wurde beendet.",
    "Le service de demande de mot de passe SSH s’est arrêté.",
  ],
});

export type DesktopInterfaceMessageKey = (typeof desktopInterfaceCatalog.keys)[number];
