import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const settingsApplicationInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "settings.application.section.general": ["General", "Allgemein", "Général"],
  "settings.application.section.projects": ["Projects", "Projekte", "Projets"],
  "settings.application.section.appearance": ["Appearance", "Darstellung", "Apparence"],
  "settings.application.section.keybindings": ["Keybindings", "Tastenkürzel", "Raccourcis clavier"],
  "settings.application.section.providers": ["Providers", "Provider", "Fournisseurs"],
  "settings.application.section.betterT3": ["Better T3", "Better T3", "Better T3"],
  "settings.application.section.skills": ["Skills", "Skills", "Compétences"],
  "settings.application.section.mcp": ["MCP Servers", "MCP-Server", "Serveurs MCP"],
  "settings.application.section.integrations": ["Integrations", "Integrationen", "Intégrations"],
  "settings.application.section.sourceControl": [
    "Source Control",
    "Versionsverwaltung",
    "Gestion de versions",
  ],
  "settings.application.section.connections": ["Connections", "Verbindungen", "Connexions"],
  "settings.application.section.experimental": ["Experimental", "Experimentell", "Expérimental"],
  "settings.application.section.importChats": [
    "Import Chats",
    "Chats importieren",
    "Importer des discussions",
  ],
  "settings.application.section.archive": ["Archive", "Archiv", "Archives"],
  "settings.application.section.diagnostics": ["Diagnostics", "Diagnose", "Diagnostics"],
  "settings.application.search.placeholder": ["Search", "Suchen", "Rechercher"],
  "settings.application.search.aria": [
    "Search settings",
    "Einstellungen durchsuchen",
    "Rechercher dans les réglages",
  ],
  "settings.application.search.clearAria": [
    "Clear settings search",
    "Einstellungssuche leeren",
    "Effacer la recherche dans les réglages",
  ],
  "settings.application.search.resultsAria": [
    "Settings search results",
    "Ergebnisse der Einstellungssuche",
    "Résultats de recherche des réglages",
  ],
  "settings.application.search.empty": [
    "No settings found",
    "Keine Einstellungen gefunden",
    "Aucun réglage trouvé",
  ],
  "settings.application.title.betterT3": ["Better T3", "Better T3", "Better T3"],
  "settings.application.title.knowledgeGraph": [
    "Knowledge Graph",
    "Wissensgraph",
    "Graphe de connaissances",
  ],
  "settings.application.title.harnessChatSync": [
    "Harness chat sync",
    "Harness-Chat-Synchronisierung",
    "Synchronisation des discussions du harnais",
  ],
  "settings.application.title.checkpoints": ["Checkpoints", "Checkpoints", "Points de contrôle"],
  "settings.application.title.colorScheme": ["Color scheme", "Farbschema", "Palette de couleurs"],
  "settings.application.title.themes": ["Themes", "Themes", "Thèmes"],
  "settings.application.title.interfaceLanguage": ["Language", "Sprache", "Langue"],
  "settings.application.title.contrast": ["Contrast", "Kontrast", "Contraste"],
  "settings.application.title.glassOpacity": ["Glass opacity", "Glasdeckkraft", "Opacité du verre"],
  "settings.application.title.macosTransparency": [
    "Background transparency and blur",
    "Hintergrundtransparenz und Unschärfe",
    "Transparence et flou de l’arrière-plan",
  ],
  "settings.application.title.modelReasoning": [
    "Model reasoning",
    "Modellüberlegungen",
    "Raisonnement du modèle",
  ],
  "settings.application.title.chatVisuals": [
    "Chat visuals",
    "Chat-Darstellung",
    "Visuels de discussion",
  ],
  "settings.application.title.expandedChatControls": [
    "Expanded chat controls",
    "Erweiterte Chat-Steuerung",
    "Commandes de discussion étendues",
  ],
  "settings.application.title.environmentIdentification": [
    "Environment identification",
    "Umgebungskennzeichnung",
    "Identification de l’environnement",
  ],
  "settings.application.title.sidebarLayout": [
    "Sidebar layout",
    "Seitenleistenlayout",
    "Disposition de la barre latérale",
  ],
  "settings.application.title.chatsPerProject": [
    "Chats per project",
    "Chats pro Projekt",
    "Discussions par projet",
  ],
  "settings.application.title.interfaceFont": [
    "Interface font",
    "Oberflächenschrift",
    "Police de l’interface",
  ],
  "settings.application.title.promptFont": ["Prompt font", "Prompt-Schrift", "Police des invites"],
  "settings.application.title.codeFont": ["Code font", "Code-Schrift", "Police du code"],
  "settings.application.title.terminalFont": [
    "Terminal font",
    "Terminal-Schrift",
    "Police du terminal",
  ],
  "settings.application.title.fontSmoothing": [
    "Font smoothing",
    "Schriftglättung",
    "Lissage des polices",
  ],
  "settings.application.title.wordWrap": ["Word wrap", "Zeilenumbruch", "Retour à la ligne"],
  "settings.application.title.projectGrouping": [
    "Project grouping",
    "Projektgruppierung",
    "Regroupement des projets",
  ],
  "settings.application.title.autoSettleInactive": [
    "Auto-settle inactive threads",
    "Inaktive Threads automatisch ablegen",
    "Classer automatiquement les fils inactifs",
  ],
  "settings.application.title.autoSettleMerged": [
    "Auto-settle merged threads",
    "Zusammengeführte Threads automatisch ablegen",
    "Classer automatiquement les fils fusionnés",
  ],
  "settings.application.title.timeFormat": ["Time format", "Zeitformat", "Format de l’heure"],
  "settings.application.title.hideWhitespace": [
    "Hide whitespace changes",
    "Leerraumänderungen ausblenden",
    "Masquer les modifications d’espaces",
  ],
  "settings.application.title.skillsSlashMenu": [
    "Show skills in slash menu",
    "Skills im Slash-Menü anzeigen",
    "Afficher les compétences dans le menu barre oblique",
  ],
  "settings.application.title.providerUpdateChecks": [
    "Provider update checks",
    "Provider-Updateprüfungen",
    "Vérification des mises à jour des fournisseurs",
  ],
  "settings.application.title.newThreads": ["New threads", "Neue Threads", "Nouveaux fils"],
  "settings.application.title.startFromOrigin": [
    "Start from origin",
    "Von Origin starten",
    "Démarrer depuis origin",
  ],
  "settings.application.title.addProjectStartsIn": [
    "Add project starts in",
    "Projektbrowser startet in",
    "Le sélecteur de projet démarre dans",
  ],
  "settings.application.title.unpinConfirmation": [
    "Unpin confirmation",
    "Bestätigung beim Loslösen",
    "Confirmation de désépinglage",
  ],
  "settings.application.title.archiveConfirmation": [
    "Archive confirmation",
    "Bestätigung beim Archivieren",
    "Confirmation d’archivage",
  ],
  "settings.application.title.deleteConfirmation": [
    "Delete confirmation",
    "Bestätigung beim Löschen",
    "Confirmation de suppression",
  ],
  "settings.application.title.quitConfirmation": [
    "Hold to quit",
    "Zum Beenden gedrückt halten",
    "Maintenir pour quitter",
  ],
  "settings.application.title.textGenerationModel": [
    "Text generation model",
    "Textgenerierungsmodell",
    "Modèle de génération de texte",
  ],
  "settings.application.title.promptImprovement": [
    "Prompt improvement",
    "Prompt-Verbesserung",
    "Amélioration des invites",
  ],
  "settings.application.title.diagnostics": ["Diagnostics", "Diagnose", "Diagnostics"],
  "settings.application.title.legacyPlanMode": [
    "Plan mode (legacy)",
    "Planmodus (Legacy)",
    "Mode Plan (ancien)",
  ],
  "settings.application.title.legacyTokenStreaming": [
    "Stream token by token (legacy)",
    "Tokenweise streamen (Legacy)",
    "Diffuser jeton par jeton (ancien)",
  ],
  "settings.application.title.keybindings": ["Keybindings", "Tastenkürzel", "Raccourcis clavier"],
  "settings.application.title.providers": ["Providers", "Provider", "Fournisseurs"],
  "settings.application.title.skills": ["Skills", "Skills", "Compétences"],
  "settings.application.title.mcpServers": ["MCP servers", "MCP-Server", "Serveurs MCP"],
  "settings.application.title.agentBrowserAccess": [
    "Agent browser access",
    "Browserzugriff für Agents",
    "Accès navigateur des agents",
  ],
  "settings.application.title.browserDefaultViewport": [
    "Default browser viewport",
    "Standard-Browsergröße",
    "Fenêtre de navigateur par défaut",
  ],
  "settings.application.title.browserDefaultZoom": [
    "Default browser zoom",
    "Standard-Browserzoom",
    "Zoom du navigateur par défaut",
  ],
  "settings.application.title.browserDefaultAppearance": [
    "Default browser appearance",
    "Standard-Browserdarstellung",
    "Apparence du navigateur par défaut",
  ],
  "settings.application.title.browserFloatingPreview": [
    "Auto-show floating preview",
    "Schwebende Vorschau automatisch anzeigen",
    "Afficher automatiquement l’aperçu flottant",
  ],
  "settings.application.title.sourceControl": [
    "Source control",
    "Versionsverwaltung",
    "Gestion de versions",
  ],
  "settings.application.title.remoteEnvironments": [
    "Remote environments",
    "Entfernte Umgebungen",
    "Environnements distants",
  ],
  "settings.application.title.experimentalFeatures": [
    "Experimental features",
    "Experimentelle Funktionen",
    "Fonctionnalités expérimentales",
  ],
  "settings.application.title.importChats": [
    "Import chats",
    "Chats importieren",
    "Importer des discussions",
  ],
  "settings.application.title.archivedThreads": [
    "Archived threads",
    "Archivierte Threads",
    "Fils archivés",
  ],
  "settings.application.experimental.notice": [
    "Experimental features may change, break, or be removed without notice. Enable them only when you are comfortable testing unfinished workflows.",
    "Experimentelle Funktionen können sich ohne Vorankündigung ändern, ausfallen oder entfernt werden. Aktiviere sie nur, wenn du unfertige Abläufe testen möchtest.",
    "Les fonctionnalités expérimentales peuvent changer, cesser de fonctionner ou être supprimées sans préavis. Activez-les uniquement si vous acceptez de tester des flux inachevés.",
  ],
  "settings.application.experimental.fetch.title": ["Fetch", "Fetch", "Fetch"],
  "settings.application.experimental.fetch.description": [
    "Let T3 use transient read-only workers only when parallel repository exploration would materially help; the main agent handles simple or focused requests itself.",
    "T3 darf kurzlebige schreibgeschützte Worker nur einsetzen, wenn parallele Repository-Erkundung deutlich hilft; einfache oder fokussierte Anfragen bearbeitet der Hauptagent selbst.",
    "Autorise T3 à utiliser des workers temporaires en lecture seule uniquement lorsque l’exploration parallèle du dépôt apporte une aide réelle ; l’agent principal traite lui-même les demandes simples ou ciblées.",
  ],
  "settings.application.experimental.fetch.enableAria": [
    "Enable Fetch repository exploration",
    "Fetch-Repository-Erkundung aktivieren",
    "Activer l’exploration de dépôt avec Fetch",
  ],
  "settings.application.experimental.fetchModel.title": [
    "Fetch model",
    "Fetch-Modell",
    "Modèle Fetch",
  ],
  "settings.application.experimental.fetchModel.description": [
    "Choose an independent provider and model for Fetch. T3 chooses the smallest useful worker count dynamically; multiple provider sessions may consume additional provider quota.",
    "Wähle einen unabhängigen Provider und ein Modell für Fetch. T3 bestimmt dynamisch die kleinste sinnvolle Worker-Anzahl; mehrere Provider-Sitzungen können zusätzliches Kontingent verbrauchen.",
    "Choisissez un fournisseur et un modèle indépendants pour Fetch. T3 détermine dynamiquement le plus petit nombre utile de workers ; plusieurs sessions peuvent consommer davantage de quota fournisseur.",
  ],
  "settings.application.experimental.fetchModel.auto": ["Auto", "Automatisch", "Auto"],
  "settings.application.experimental.fetchWarning.model": [
    "The selected Fetch model is unavailable. The main turn will continue without Fetch.",
    "Das ausgewählte Fetch-Modell ist nicht verfügbar. Der Hauptlauf wird ohne Fetch fortgesetzt.",
    "Le modèle Fetch sélectionné est indisponible. Le tour principal continuera sans Fetch.",
  ],
  "settings.application.experimental.fetchWarning.provider": [
    "The selected Fetch provider is unavailable. The main turn will continue without Fetch.",
    "Der ausgewählte Fetch-Provider ist nicht verfügbar. Der Hauptlauf wird ohne Fetch fortgesetzt.",
    "Le fournisseur Fetch sélectionné est indisponible. Le tour principal continuera sans Fetch.",
  ],
  "settings.application.experimental.fetchWarning.none": [
    "No Fetch-capable provider model is currently available. The main turn will continue without Fetch.",
    "Derzeit ist kein Fetch-fähiges Provider-Modell verfügbar. Der Hauptlauf wird ohne Fetch fortgesetzt.",
    "Aucun modèle fournisseur compatible avec Fetch n’est disponible. Le tour principal continuera sans Fetch.",
  ],
  "settings.application.experimental.parallel.title": [
    "Parallel plan implementation",
    "Parallele Planumsetzung",
    "Implémentation parallèle du plan",
  ],
  "settings.application.experimental.parallel.description": [
    "Suggest a provider-native subagent strategy when implementing a completed plan.",
    "Bei der Umsetzung eines fertigen Plans eine provider-native Subagent-Strategie vorschlagen.",
    "Suggérer une stratégie de sous-agents native au fournisseur lors de l’implémentation d’un plan terminé.",
  ],
  "settings.application.experimental.parallel.enableAria": [
    "Use subagents when implementing plans",
    "Subagents bei der Planumsetzung verwenden",
    "Utiliser des sous-agents pour implémenter les plans",
  ],
  "settings.application.experimental.reviewModel.title": [
    "Agent count review model",
    "Prüfmodell für Agentenanzahl",
    "Modèle d’évaluation du nombre d’agents",
  ],
  "settings.application.experimental.reviewModel.description": [
    "Fast model used to estimate how many provider-native subagents can implement a completed plan in parallel.",
    "Schnelles Modell zur Schätzung, wie viele provider-native Subagents einen fertigen Plan parallel umsetzen können.",
    "Modèle rapide utilisé pour estimer combien de sous-agents natifs au fournisseur peuvent implémenter un plan terminé en parallèle.",
  ],
  "settings.application.experimental.reviewModel.triggerAria": [
    "Select agent count review model",
    "Prüfmodell für Agentenanzahl auswählen",
    "Sélectionner le modèle d’évaluation du nombre d’agents",
  ],
  "settings.application.font.default": ["default", "Standard", "par défaut"],
  "settings.application.font.searchPlaceholder": [
    "Search fonts…",
    "Schriften suchen…",
    "Rechercher des polices…",
  ],
  "settings.application.font.empty": [
    "No fonts found.",
    "Keine Schriften gefunden.",
    "Aucune police trouvée.",
  ],
  "settings.application.keybindings.search": [
    "Search keybindings",
    "Tastenkürzel durchsuchen",
    "Rechercher des raccourcis",
  ],
  "settings.application.keybindings.condition": ["Condition", "Bedingung", "Condition"],
  "settings.application.keybindings.removeConditionAria": [
    "Remove condition",
    "Bedingung entfernen",
    "Supprimer la condition",
  ],
  "settings.application.keybindings.negateConditionAria": [
    "Negate {{condition}}",
    "{{condition}} negieren",
    "Nier {{condition}}",
  ],
  "settings.application.keybindings.negateGroupAria": [
    "Negate group",
    "Gruppe negieren",
    "Nier le groupe",
  ],
  "settings.application.keybindings.removeNegatedGroupAria": [
    "Remove negated group",
    "Negierte Gruppe entfernen",
    "Supprimer le groupe nié",
  ],
  "settings.application.keybindings.removeGroupAria": [
    "Remove group",
    "Gruppe entfernen",
    "Supprimer le groupe",
  ],
  "settings.application.keybindings.when": ["When", "Wenn", "Quand"],
  "settings.application.keybindings.always": ["Always", "Immer", "Toujours"],
  "settings.application.keybindings.whenExpressionAria": [
    "When expression",
    "Wenn-Ausdruck",
    "Expression Quand",
  ],
  "settings.application.keybindings.saving": ["Saving", "Wird gespeichert", "Enregistrement"],
  "settings.application.keybindings.pressShortcut": [
    "Press shortcut",
    "Tastenkürzel drücken",
    "Appuyez sur le raccourci",
  ],
  "settings.application.keybindings.unassigned": ["Unassigned", "Nicht zugewiesen", "Non attribué"],
  "settings.application.keybindings.new": [
    "New keybinding",
    "Neues Tastenkürzel",
    "Nouveau raccourci",
  ],
  "settings.application.keybindings.command": ["Command", "Befehl", "Commande"],
  "settings.application.keybindings.cancelNewAria": [
    "Cancel new keybinding",
    "Neues Tastenkürzel abbrechen",
    "Annuler le nouveau raccourci",
  ],
  "settings.application.keybindings.openFailed": [
    "Unable to open keybindings file",
    "Tastenkürzeldatei konnte nicht geöffnet werden",
    "Impossible d’ouvrir le fichier des raccourcis",
  ],
  "settings.application.keybindings.openFailedFallback": [
    "The keybindings file was not opened.",
    "Die Tastenkürzeldatei wurde nicht geöffnet.",
    "Le fichier des raccourcis n’a pas été ouvert.",
  ],
  "settings.application.keybindings.saveFailed": [
    "Unable to save keybinding",
    "Tastenkürzel konnte nicht gespeichert werden",
    "Impossible d’enregistrer le raccourci",
  ],
  "settings.application.keybindings.saveFailedFallback": [
    "The keybinding was not saved.",
    "Das Tastenkürzel wurde nicht gespeichert.",
    "Le raccourci n’a pas été enregistré.",
  ],
  "settings.application.keybindings.removeFailed": [
    "Unable to remove keybinding",
    "Tastenkürzel konnte nicht entfernt werden",
    "Impossible de supprimer le raccourci",
  ],
  "settings.application.keybindings.removeFailedFallback": [
    "The keybinding was not removed.",
    "Das Tastenkürzel wurde nicht entfernt.",
    "Le raccourci n’a pas été supprimé.",
  ],
  "settings.application.keybindings.count": [
    { one: "{{count}} binding", other: "{{count}} bindings" },
    { one: "{{count}} Tastenkürzel", other: "{{count}} Tastenkürzel" },
    { one: "{{count}} raccourci", other: "{{count}} raccourcis" },
  ],
  "settings.application.keybindings.addAria": [
    "Add keybinding",
    "Tastenkürzel hinzufügen",
    "Ajouter un raccourci",
  ],
  "settings.application.keybindings.openFileAria": [
    "Open keybindings.json",
    "keybindings.json öffnen",
    "Ouvrir keybindings.json",
  ],
  "settings.application.keybindings.parseHint": [
    "Use variables with !, &&, ||, and parentheses.",
    "Verwende Variablen mit !, &&, || und Klammern.",
    "Utilisez des variables avec !, &&, || et des parenthèses.",
  ],
  "settings.application.keybindings.unknownConditions": [
    { one: "Unknown condition: {{identifiers}}", other: "Unknown conditions: {{identifiers}}" },
    {
      one: "Unbekannte Bedingung: {{identifiers}}",
      other: "Unbekannte Bedingungen: {{identifiers}}",
    },
    {
      one: "Condition inconnue : {{identifiers}}",
      other: "Conditions inconnues : {{identifiers}}",
    },
  ],
  "settings.application.keybindings.unknownConditionDescription": [
    "T3 Code does not recognize this condition yet. It can still be saved, but it may not match unless the runtime provides it.",
    "T3 Code kennt diese Bedingung noch nicht. Sie kann gespeichert werden, greift aber möglicherweise nur, wenn die Laufzeit sie bereitstellt.",
    "T3 Code ne reconnaît pas encore cette condition. Elle peut être enregistrée, mais risque de ne pas correspondre si l’environnement d’exécution ne la fournit pas.",
  ],
  "settings.application.keybindings.conflicts": [
    "Conflicts with {{labels}}.",
    "Konflikt mit {{labels}}.",
    "Conflit avec {{labels}}.",
  ],
  "settings.application.keybindings.andMore": [
    "{{labels}}, and more",
    "{{labels}} und weiteren",
    "{{labels}}, et d’autres",
  ],
  "settings.application.keybindings.conflictDescription": [
    "{{conflict}} The most recent matching binding wins when both conditions can apply.",
    "{{conflict}} Das neueste passende Tastenkürzel gewinnt, wenn beide Bedingungen gelten können.",
    "{{conflict}} Le raccourci correspondant le plus récent l’emporte lorsque les deux conditions peuvent s’appliquer.",
  ],
  "settings.application.keybindings.not": ["Not", "Nicht", "Non"],
  "settings.application.keybindings.and": ["and", "und", "et"],
  "settings.application.keybindings.or": ["or", "oder", "ou"],
  "settings.application.keybindings.group": ["Group", "Gruppe", "Groupe"],
  "settings.application.keybindings.fixExpression": [
    "Fix the expression above to continue editing visually.",
    "Korrigiere den Ausdruck oben, um visuell weiterzuarbeiten.",
    "Corrigez l’expression ci-dessus pour poursuivre l’édition visuelle.",
  ],
  "settings.application.keybindings.editShortcutAria": [
    "Edit shortcut for {{label}}: {{shortcut}}",
    "Tastenkürzel für {{label}} bearbeiten: {{shortcut}}",
    "Modifier le raccourci de {{label}} : {{shortcut}}",
  ],
  "settings.application.keybindings.keybindingForAria": [
    "Keybinding for {{label}}",
    "Tastenkürzel für {{label}}",
    "Raccourci pour {{label}}",
  ],
  "settings.application.keybindings.editWhenAria": [
    "Edit when clause for {{label}}",
    "Wenn-Klausel für {{label}} bearbeiten",
    "Modifier la clause Quand pour {{label}}",
  ],
  "settings.application.keybindings.actionsAria": [
    "Actions for {{label}}",
    "Aktionen für {{label}}",
    "Actions pour {{label}}",
  ],
  "settings.application.keybindings.resetDefault": [
    "Reset to default",
    "Auf Standard zurücksetzen",
    "Rétablir la valeur par défaut",
  ],
  "settings.application.keybindings.source.custom": ["Custom", "Benutzerdefiniert", "Personnalisé"],
  "settings.application.keybindings.source.project": ["Project", "Projekt", "Projet"],
  "settings.application.keybindings.source.default": ["Default", "Standard", "Par défaut"],
  "settings.application.keybindings.runScript": [
    "Run Script: {{name}}",
    "Skript ausführen: {{name}}",
    "Exécuter le script : {{name}}",
  ],
  "settings.application.keybindings.empty": [
    "No keybindings match your search.",
    "Keine Tastenkürzel entsprechen deiner Suche.",
    "Aucun raccourci ne correspond à votre recherche.",
  ],
  "settings.application.keybindings.browserNotice": [
    "Some shortcuts may be claimed by the browser before T3 Code sees them. Use the desktop app for better keybinding support.",
    "Einige Tastenkürzel können vom Browser abgefangen werden, bevor T3 Code sie erkennt. Verwende die Desktop-App für bessere Tastenkürzel-Unterstützung.",
    "Certains raccourcis peuvent être interceptés par le navigateur avant que T3 Code ne les voie. Utilisez l’application de bureau pour une meilleure prise en charge.",
  ],
  "settings.application.restore.browserViewport": [
    "Browser viewport",
    "Browsergröße",
    "Fenêtre du navigateur",
  ],
  "settings.application.restore.browserZoom": ["Browser zoom", "Browserzoom", "Zoom du navigateur"],
  "settings.application.restore.browserAppearance": [
    "Browser appearance",
    "Browserdarstellung",
    "Apparence du navigateur",
  ],
  "settings.application.restore.floatingPreview": [
    "Floating preview",
    "Schwebende Vorschau",
    "Aperçu flottant",
  ],
  "settings.application.diagnostics.localTrace": [
    "Local trace file",
    "Lokale Trace-Datei",
    "Fichier de trace local",
  ],
  "settings.application.diagnostics.terminalLogs": [
    "Terminal logs only",
    "Nur Terminalprotokolle",
    "Journaux du terminal uniquement",
  ],
  "settings.application.diagnostics.exportCombined": [
    "{{mode}}. Exporting OTEL to {{url}}.",
    "{{mode}}. OTEL wird nach {{url}} exportiert.",
    "{{mode}}. Export OTEL vers {{url}}.",
  ],
  "settings.application.diagnostics.exportSeparate": [
    "{{mode}}. Exporting OTEL traces to {{tracesUrl}} and metrics to {{metricsUrl}}.",
    "{{mode}}. OTEL-Traces werden nach {{tracesUrl}} und Metriken nach {{metricsUrl}} exportiert.",
    "{{mode}}. Export des traces OTEL vers {{tracesUrl}} et des métriques vers {{metricsUrl}}.",
  ],
  "settings.application.diagnostics.exportTraces": [
    "{{mode}}. Exporting OTEL traces to {{url}}.",
    "{{mode}}. OTEL-Traces werden nach {{url}} exportiert.",
    "{{mode}}. Export des traces OTEL vers {{url}}.",
  ],
  "settings.application.diagnostics.exportMetrics": [
    "{{mode}}. Exporting OTEL metrics to {{url}}.",
    "{{mode}}. OTEL-Metriken werden nach {{url}} exportiert.",
    "{{mode}}. Export des métriques OTEL vers {{url}}.",
  ],
  "settings.application.diagnostics.modeOnly": ["{{mode}}.", "{{mode}}.", "{{mode}}."],
});

export type SettingsApplicationInterfaceMessageKey =
  (typeof settingsApplicationInterfaceCatalog.keys)[number];
