import { defineLocalizedInterfaceCatalog } from "./interfaceLanguageCatalog.types.ts";

export const settingsEnvironmentsInterfaceCatalog = defineLocalizedInterfaceCatalog({
  "settings.connections.grantedScopes": [
    "Granted scopes",
    "Gewährte Berechtigungen",
    "Portées accordées",
  ],
  "settings.connections.scopeCount": [
    { one: "{{count}} scope", other: "{{count}} scopes" },
    { one: "{{count}} Berechtigung", other: "{{count}} Berechtigungen" },
    { one: "{{count}} portée", other: "{{count}} portées" },
  ],
  "settings.connections.showScopes": [
    "{{label}}: show {{scopeCount}}",
    "{{label}}: {{scopeCount}} anzeigen",
    "{{label}} : afficher {{scopeCount}}",
  ],
  "settings.connections.pairingScopes": [
    "Pairing link scopes",
    "Berechtigungen des Kopplungslinks",
    "Portées du lien d’association",
  ],
  "settings.connections.clientScopes": [
    "Client scopes",
    "Client-Berechtigungen",
    "Portées du client",
  ],
  "settings.connections.scope.view.title": [
    "View environment",
    "Umgebung anzeigen",
    "Voir l’environnement",
  ],
  "settings.connections.scope.view.description": [
    "Read threads, status, diffs, and configuration.",
    "Chats, Status, Unterschiede und Konfiguration lesen.",
    "Lire les discussions, l’état, les différences et la configuration.",
  ],
  "settings.connections.scope.operate.title": [
    "Operate tasks",
    "Aufgaben steuern",
    "Piloter les tâches",
  ],
  "settings.connections.scope.operate.description": [
    "Start tasks and perform changes in the environment.",
    "Aufgaben starten und Änderungen in der Umgebung vornehmen.",
    "Démarrer des tâches et modifier l’environnement.",
  ],
  "settings.connections.scope.terminal.title": [
    "Use terminals",
    "Terminals verwenden",
    "Utiliser les terminaux",
  ],
  "settings.connections.scope.terminal.description": [
    "Create terminals and send input to running shells.",
    "Terminals erstellen und Eingaben an laufende Shells senden.",
    "Créer des terminaux et envoyer des saisies aux shells en cours.",
  ],
  "settings.connections.scope.review.title": [
    "Write reviews",
    "Reviews verfassen",
    "Rédiger des revues",
  ],
  "settings.connections.scope.review.description": [
    "Create comments while reviewing changes.",
    "Beim Prüfen von Änderungen Kommentare erstellen.",
    "Créer des commentaires lors de la revue des modifications.",
  ],
  "settings.connections.scope.accessRead.title": [
    "View access",
    "Zugriff anzeigen",
    "Voir les accès",
  ],
  "settings.connections.scope.accessRead.description": [
    "Inspect pairing links and authorized clients.",
    "Kopplungslinks und autorisierte Clients prüfen.",
    "Consulter les liens d’association et les clients autorisés.",
  ],
  "settings.connections.scope.accessWrite.title": [
    "Manage access",
    "Zugriff verwalten",
    "Gérer les accès",
  ],
  "settings.connections.scope.accessWrite.description": [
    "Issue and revoke credentials for other clients.",
    "Zugangsdaten für andere Clients ausstellen und widerrufen.",
    "Émettre et révoquer les identifiants d’autres clients.",
  ],
  "settings.connections.scope.relayRead.title": ["View relay", "Relay anzeigen", "Voir le relais"],
  "settings.connections.scope.relayRead.description": [
    "Inspect managed relay connectivity.",
    "Verwaltete Relay-Verbindungen prüfen.",
    "Consulter la connectivité du relais géré.",
  ],
  "settings.connections.scope.relayWrite.title": [
    "Manage relay",
    "Relay verwalten",
    "Gérer le relais",
  ],
  "settings.connections.scope.relayWrite.description": [
    "Change managed tunnel connectivity.",
    "Verwaltete Tunnelverbindungen ändern.",
    "Modifier la connectivité du tunnel géré.",
  ],
  "settings.connections.qrTitle": [
    "Pairing link, scan to open on another device",
    "Kopplungslink, zum Öffnen auf einem anderen Gerät scannen",
    "Lien d’association, à scanner pour l’ouvrir sur un autre appareil",
  ],
  "settings.connections.endpointAria": [
    "Endpoint the pairing QR code and URL use",
    "Endpunkt für Kopplungs-QR-Code und URL",
    "Point de terminaison utilisé par le code QR et l’URL d’association",
  ],
  "settings.connections.reachVia": [
    "Reach this machine via",
    "Diesen Computer erreichen über",
    "Accéder à cette machine via",
  ],
  "settings.connections.copyLink": ["Copy link", "Link kopieren", "Copier le lien"],
  "settings.connections.copyCode": ["Copy code", "Code kopieren", "Copier le code"],
  "settings.connections.copyCodeOnly": [
    "Copy code only",
    "Nur Code kopieren",
    "Copier uniquement le code",
  ],
  "settings.connections.share": ["Share", "Teilen", "Partager"],
  "settings.connections.done": ["Done", "Fertig", "Terminé"],
  "settings.connections.noQrLoopback": [
    "No QR for this endpoint. Another device scanning a loopback link would dial itself; copy the URL for use on this machine instead.",
    "Für diesen Endpunkt gibt es keinen QR-Code. Ein anderes Gerät würde mit einem Loopback-Link sich selbst verbinden; kopiere stattdessen die URL für diesen Computer.",
    "Aucun code QR pour ce point de terminaison. Un autre appareil qui scannerait un lien de bouclage se connecterait à lui-même ; copiez plutôt l’URL pour cette machine.",
  ],
  "settings.connections.tokenInstruction": [
    "Copy the token and pair from another client using this backend's reachable host.",
    "Kopiere das Token und kopple einen anderen Client über den erreichbaren Host dieses Backends.",
    "Copiez le jeton et associez un autre client via l’hôte accessible de ce backend.",
  ],
  "settings.connections.thisDevice": ["This device", "Dieses Gerät", "Cet appareil"],
  "settings.connections.createPairing": [
    "Create pairing link",
    "Kopplungslink erstellen",
    "Créer un lien d’association",
  ],
  "settings.connections.createPairingDescription": [
    "Generate a one-time link that another device can use to pair with this backend as an authorized client.",
    "Erstelle einen einmaligen Link, mit dem sich ein anderes Gerät als autorisierter Client mit diesem Backend koppeln kann.",
    "Générez un lien à usage unique permettant à un autre appareil de s’associer à ce backend comme client autorisé.",
  ],
  "settings.connections.clientLabel": [
    "Client label (optional)",
    "Client-Bezeichnung (optional)",
    "Libellé du client (facultatif)",
  ],
  "settings.connections.permissions": ["Permissions", "Berechtigungen", "Autorisations"],
  "settings.connections.permissionsDescription": [
    "Limit what the paired client can do.",
    "Lege fest, was der gekoppelte Client tun darf.",
    "Limitez les actions autorisées pour le client associé.",
  ],
  "settings.connections.readOnly": ["Read only", "Nur lesen", "Lecture seule"],
  "settings.connections.standard": ["Standard", "Standard", "Standard"],
  "settings.connections.selectPermission": [
    "Select at least one permission.",
    "Wähle mindestens eine Berechtigung aus.",
    "Sélectionnez au moins une autorisation.",
  ],
  "settings.connections.accessWriteWarning": [
    "This client can create or revoke access for other devices.",
    "Dieser Client kann Zugriff für andere Geräte erstellen oder widerrufen.",
    "Ce client peut créer ou révoquer l’accès d’autres appareils.",
  ],
  "settings.connections.emptySessions": [
    "No pairing links or client sessions.",
    "Keine Kopplungslinks oder Client-Sitzungen.",
    "Aucun lien d’association ni session client.",
  ],
  "settings.connections.reachableAt": ["Reachable at", "Erreichbar unter", "Accessible à"],
  "settings.connections.clientNamePlaceholder": [
    "e.g. Living room iPad",
    "z. B. Wohnzimmer-iPad",
    "p. ex. iPad du salon",
  ],
  "settings.connections.setupRequired": [
    "Setup required",
    "Einrichtung erforderlich",
    "Configuration requise",
  ],
  "settings.connections.default": ["Default", "Standard", "Par défaut"],
  "settings.connections.setDefault": [
    "Set as default",
    "Als Standard festlegen",
    "Définir par défaut",
  ],
  "settings.connections.connect.title": ["T3 Connect", "T3 Connect", "T3 Connect"],
  "settings.connections.publishActivity": [
    "Publish agent activity",
    "Agentenaktivität veröffentlichen",
    "Publier l’activité de l’agent",
  ],
  "settings.connections.publishActivityDescription": [
    "Send activity from this environment to your mobile clients for push notifications and Live Activities. Works without a T3 Connect tunnel.",
    "Sendet Aktivität aus dieser Umgebung für Push-Benachrichtigungen und Live-Aktivitäten an mobile Clients. Funktioniert ohne T3-Connect-Tunnel.",
    "Envoie l’activité de cet environnement aux clients mobiles pour les notifications push et les activités en direct. Fonctionne sans tunnel T3 Connect.",
  ],
  "settings.connections.remote.empty": [
    "No saved remote environments",
    "Keine gespeicherten entfernten Umgebungen",
    "Aucun environnement distant enregistré",
  ],
  "settings.connections.remote.emptyCloud": [
    "Click “Add environment” to pair another environment, or connect one from T3 Connect.",
    "Klicke auf „Umgebung hinzufügen“, um eine weitere Umgebung zu koppeln, oder verbinde eine über T3 Connect.",
    "Cliquez sur « Ajouter un environnement » pour en associer un autre, ou connectez-en un depuis T3 Connect.",
  ],
  "settings.connections.remote.emptyLocal": [
    "Click “Add environment” to pair another environment.",
    "Klicke auf „Umgebung hinzufügen“, um eine weitere Umgebung zu koppeln.",
    "Cliquez sur « Ajouter un environnement » pour en associer un autre.",
  ],
  "settings.connections.ssh.host": ["Host", "Host", "Hôte"],
  "settings.connections.ssh.hostPlaceholder": [
    "backend.example.com",
    "backend.beispiel.de",
    "backend.exemple.fr",
  ],
  "settings.connections.ssh.pairingCode": ["Pairing code", "Kopplungscode", "Code d’association"],
  "settings.connections.ssh.pairingCodePlaceholder": ["PAIRCODE", "KOPPELCODE", "CODEASSOC"],
  "settings.connections.ssh.pairingUrlHint": [
    "Paste a full pairing URL here to fill both fields automatically.",
    "Füge hier eine vollständige Kopplungs-URL ein, um beide Felder automatisch auszufüllen.",
    "Collez ici une URL d’association complète pour remplir automatiquement les deux champs.",
  ],
  "settings.connections.ssh.hostAlias": [
    "SSH host or alias",
    "SSH-Host oder Alias",
    "Hôte SSH ou alias",
  ],
  "settings.connections.ssh.hostSearchPlaceholder": [
    "Search hosts or type devbox",
    "Hosts suchen oder devbox eingeben",
    "Rechercher des hôtes ou saisir devbox",
  ],
  "settings.connections.ssh.username": ["Username", "Benutzername", "Nom d’utilisateur"],
  "settings.connections.ssh.usernamePlaceholder": ["root", "root", "root"],
  "settings.connections.ssh.port": ["Port", "Port", "Port"],
  "settings.connections.ssh.suggested": [
    "Suggested hosts",
    "Vorgeschlagene Hosts",
    "Hôtes suggérés",
  ],
  "settings.connections.ssh.source": [
    "From SSH config and known hosts",
    "Aus SSH-Konfiguration und bekannten Hosts",
    "Depuis la configuration SSH et les hôtes connus",
  ],
  "settings.connections.ssh.noneDiscovered": [
    "No new SSH hosts were discovered.",
    "Keine neuen SSH-Hosts gefunden.",
    "Aucun nouvel hôte SSH n’a été découvert.",
  ],
  "settings.connections.network.enable": [
    "Enable network access",
    "Netzwerkzugriff aktivieren",
    "Activer l’accès réseau",
  ],
  "settings.connections.network.title": ["Network access", "Netzwerkzugriff", "Accès réseau"],
  "settings.connections.network.exposureControlledAtHost": [
    "Network exposure changes restart the backend and must be controlled where the server process is launched.",
    "Änderungen am Netzwerkzugriff starten das Backend neu und müssen dort gesteuert werden, wo der Serverprozess gestartet wurde.",
    "Les modifications d’exposition réseau redémarrent le backend et doivent être effectuées là où le processus serveur est lancé.",
  ],
  "settings.connections.wsl.title": ["WSL backend", "WSL-Backend", "Backend WSL"],
  "settings.connections.wsl.loadFailed": [
    "Couldn't load the WSL backend state.",
    "Der WSL-Backend-Status konnte nicht geladen werden.",
    "Impossible de charger l’état du backend WSL.",
  ],
  "settings.connections.wsl.unavailable": [
    "WSL is no longer available, so the Windows backend is running instead. Switch off the WSL backend to clear this preference.",
    "WSL ist nicht mehr verfügbar, daher läuft stattdessen das Windows-Backend. Deaktiviere das WSL-Backend, um diese Einstellung zu löschen.",
    "WSL n’est plus disponible, le backend Windows est donc utilisé. Désactivez le backend WSL pour effacer cette préférence.",
  ],
  "settings.connections.wsl.switchWindows": [
    "Switch to Windows",
    "Zu Windows wechseln",
    "Passer à Windows",
  ],
  "settings.connections.wsl.description": [
    "Run a second backend inside a WSL distro alongside the Windows one. Pick a distro to start it; pick Off to stop it. Projects opened against the WSL backend live on the Linux side; Windows projects stay where they are.",
    "Führt zusätzlich zum Windows-Backend ein zweites Backend in einer WSL-Distribution aus. Wähle eine Distribution zum Starten oder Aus zum Stoppen. WSL-Projekte liegen auf der Linux-Seite; Windows-Projekte bleiben unverändert.",
    "Exécute un second backend dans une distribution WSL en parallèle du backend Windows. Choisissez une distribution pour le démarrer ou Désactivé pour l’arrêter. Les projets WSL résident côté Linux, les projets Windows restent en place.",
  ],
  "settings.connections.wsl.startFailed": [
    "WSL backend couldn't start: {{detail}}",
    "WSL-Backend konnte nicht gestartet werden: {{detail}}",
    "Le backend WSL n’a pas pu démarrer : {{detail}}",
  ],
  "settings.connections.wsl.off": ["Off", "Aus", "Désactivé"],
  "settings.connections.wsl.defaultDistro": [
    "Default distro",
    "Standarddistribution",
    "Distribution par défaut",
  ],
  "settings.connections.wsl.defaultSuffix": [" (default)", " (Standard)", " (par défaut)"],
  "settings.connections.wsl.only": ["WSL only", "Nur WSL", "WSL uniquement"],
  "settings.connections.wsl.onlyDescription": [
    "Stop the Windows backend and run only the WSL backend. Useful if you develop entirely inside WSL and don't want a second backend process. T3 Code restarts when you change this.",
    "Stoppt das Windows-Backend und führt nur das WSL-Backend aus. Nützlich für vollständige Entwicklung in WSL ohne zweiten Backend-Prozess. T3 Code startet bei Änderungen neu.",
    "Arrête le backend Windows et n’exécute que le backend WSL. Utile si vous travaillez entièrement dans WSL sans second processus backend. T3 Code redémarre après ce changement.",
  ],
  "settings.connections.wsl.onlyAria": [
    "Run WSL only",
    "Nur WSL ausführen",
    "Exécuter uniquement WSL",
  ],
  "settings.connections.tailscale.title": ["Tailscale HTTPS", "Tailscale HTTPS", "HTTPS Tailscale"],
  "settings.connections.tailscale.enable": [
    "Enable Tailscale HTTPS",
    "Tailscale HTTPS aktivieren",
    "Activer HTTPS Tailscale",
  ],
  "settings.connections.environment.title": [
    "This environment",
    "Diese Umgebung",
    "Cet environnement",
  ],
  "settings.connections.authorizedClients": [
    "Authorized clients",
    "Autorisierte Clients",
    "Clients autorisés",
  ],
  "settings.connections.administrative": [
    "Administrative access",
    "Administrativer Zugriff",
    "Accès administratif",
  ],
  "settings.connections.administrativeDescription": [
    "Pairing links and client-session management require the access:write scope for this backend.",
    "Kopplungslinks und die Verwaltung von Client-Sitzungen benötigen die Berechtigung access:write für dieses Backend.",
    "Les liens d’association et la gestion des sessions client nécessitent la portée access:write pour ce backend.",
  ],
  "settings.connections.addEnvironment": [
    "Add environment",
    "Umgebung hinzufügen",
    "Ajouter un environnement",
  ],
  "settings.connections.addEnvironmentTitle": [
    "Add Environment",
    "Umgebung hinzufügen",
    "Ajouter un environnement",
  ],
  "settings.connections.addEnvironmentDescription": [
    "Pair another environment to this client.",
    "Kopple eine weitere Umgebung mit diesem Client.",
    "Associez un autre environnement à ce client.",
  ],
  "settings.connections.remoteLink": ["Remote link", "Remote-Link", "Lien distant"],
  "settings.connections.remoteLinkDescription": [
    "Enter a backend host and pairing code.",
    "Gib einen Backend-Host und Kopplungscode ein.",
    "Saisissez l’hôte du backend et le code d’association.",
  ],
  "settings.connections.sshModeDescription": [
    "Use local SSH config, agent, and tunnels for the backend.",
    "Verwende lokale SSH-Konfiguration, Agent und Tunnel für das Backend.",
    "Utilisez la configuration SSH locale, l’agent et les tunnels pour le backend.",
  ],
  "settings.connections.disableTailscale": [
    "Disable Tailscale HTTPS?",
    "Tailscale HTTPS deaktivieren?",
    "Désactiver HTTPS Tailscale ?",
  ],
  "settings.connections.disableTailscaleDescription": [
    "T3 Code will restart the local backend without Tailscale Serve.",
    "T3 Code startet das lokale Backend ohne Tailscale Serve neu.",
    "T3 Code redémarrera le backend local sans Tailscale Serve.",
  ],
  "settings.connections.setupTailscale": [
    "Set up Tailscale HTTPS?",
    "Tailscale HTTPS einrichten?",
    "Configurer HTTPS Tailscale ?",
  ],
  "settings.connections.setupTailscaleDescription": [
    "T3 Code will restart the local backend with Tailscale Serve enabled and ask Tailscale to proxy HTTPS traffic to this backend.",
    "T3 Code startet das lokale Backend mit Tailscale Serve neu und lässt Tailscale HTTPS-Datenverkehr an dieses Backend weiterleiten.",
    "T3 Code redémarrera le backend local avec Tailscale Serve et demandera à Tailscale de transférer le trafic HTTPS vers ce backend.",
  ],
  "settings.connections.httpsPort": ["HTTPS port", "HTTPS-Port", "Port HTTPS"],
  "settings.connections.invalidPort": [
    "Enter a port from 1 to 65535.",
    "Gib einen Port von 1 bis 65535 ein.",
    "Saisissez un port compris entre 1 et 65535.",
  ],
  "settings.connections.httpsEndpoint": [
    "HTTPS endpoint",
    "HTTPS-Endpunkt",
    "Point de terminaison HTTPS",
  ],
  "settings.connections.copy.hostedSuccess": [
    "Hosted app link copied",
    "Link zur gehosteten App kopiert",
    "Lien de l’application hébergée copié",
  ],
  "settings.connections.copy.urlSuccess": [
    "Pairing URL copied",
    "Kopplungs-URL kopiert",
    "URL d’association copiée",
  ],
  "settings.connections.copy.codeSuccess": [
    "Pairing code copied",
    "Kopplungscode kopiert",
    "Code d’association copié",
  ],
  "settings.connections.copy.hostedSuccessDescription": [
    "Open it in the browser on the device you want to connect.",
    "Öffne ihn im Browser des Geräts, das du verbinden möchtest.",
    "Ouvrez-le dans le navigateur de l’appareil à connecter.",
  ],
  "settings.connections.copy.urlSuccessDescription": [
    "Open it in the client you want to pair to this environment.",
    "Öffne sie im Client, den du mit dieser Umgebung koppeln möchtest.",
    "Ouvrez-la dans le client à associer à cet environnement.",
  ],
  "settings.connections.copy.codeSuccessDescription": [
    "Paste it into another client to finish pairing.",
    "Füge ihn in einen anderen Client ein, um die Kopplung abzuschließen.",
    "Collez-le dans un autre client pour terminer l’association.",
  ],
  "settings.connections.copy.hostedFailed": [
    "Could not copy hosted app link",
    "Link zur gehosteten App konnte nicht kopiert werden",
    "Impossible de copier le lien de l’application hébergée",
  ],
  "settings.connections.copy.urlFailed": [
    "Could not copy pairing URL",
    "Kopplungs-URL konnte nicht kopiert werden",
    "Impossible de copier l’URL d’association",
  ],
  "settings.connections.copy.codeFailed": [
    "Could not copy pairing code",
    "Kopplungscode konnte nicht kopiert werden",
    "Impossible de copier le code d’association",
  ],
  "settings.connections.copy.unavailable": [
    "Clipboard copy unavailable",
    "Kopieren in die Zwischenablage nicht verfügbar",
    "Copie dans le presse-papiers indisponible",
  ],
  "settings.connections.copy.showingValue": [
    "Showing the full value instead.",
    "Stattdessen wird der vollständige Wert angezeigt.",
    "La valeur complète est affichée à la place.",
  ],
  "settings.connections.copy.hostedManual": [
    "Clipboard copy is unavailable here. Open or manually copy this hosted app link on the device you want to connect.",
    "Die Zwischenablage ist hier nicht verfügbar. Öffne oder kopiere diesen Link zur gehosteten App manuell auf dem zu verbindenden Gerät.",
    "La copie est indisponible ici. Ouvrez ou copiez manuellement ce lien sur l’appareil à connecter.",
  ],
  "settings.connections.copy.urlManual": [
    "Clipboard copy is unavailable here. Open or manually copy this full pairing URL on the device you want to connect.",
    "Die Zwischenablage ist hier nicht verfügbar. Öffne oder kopiere die vollständige Kopplungs-URL manuell auf dem zu verbindenden Gerät.",
    "La copie est indisponible ici. Ouvrez ou copiez manuellement l’URL complète sur l’appareil à connecter.",
  ],
  "settings.connections.copy.codeManual": [
    "Clipboard copy is unavailable here. Manually copy this code into another client.",
    "Die Zwischenablage ist hier nicht verfügbar. Kopiere diesen Code manuell in einen anderen Client.",
    "La copie est indisponible ici. Copiez manuellement ce code dans un autre client.",
  ],
  "settings.connections.pairingLink": ["Pairing link", "Kopplungslink", "Lien d’association"],
  "settings.connections.hostedPairingLink": [
    "Hosted app pairing link",
    "Kopplungslink zur gehosteten App",
    "Lien d’association de l’application hébergée",
  ],
  "settings.connections.linkCreatedAt": [
    "Link created at {{timestamp}}",
    "Link erstellt am {{timestamp}}",
    "Lien créé le {{timestamp}}",
  ],
  "settings.connections.showLink": ["Show link", "Link anzeigen", "Afficher le lien"],
  "settings.connections.showCode": ["Show code", "Code anzeigen", "Afficher le code"],
  "settings.connections.revoke": ["Revoke", "Widerrufen", "Révoquer"],
  "settings.connections.revoking": ["Revoking…", "Wird widerrufen…", "Révocation…"],
  "settings.connections.revokeOthers": [
    "Revoke others",
    "Andere widerrufen",
    "Révoquer les autres",
  ],
  "settings.connections.status.connected": ["Connected", "Verbunden", "Connecté"],
  "settings.connections.status.notConnected": [
    "Not connected yet.",
    "Noch nicht verbunden.",
    "Pas encore connecté.",
  ],
  "settings.connections.createLink": ["Create link", "Link erstellen", "Créer le lien"],
  "settings.connections.creating": ["Creating…", "Wird erstellt…", "Création…"],
  "settings.connections.restarting": ["Restarting…", "Neustart…", "Redémarrage…"],
  "settings.connections.applying": ["Applying…", "Wird angewendet…", "Application…"],
  "settings.connections.adding": ["Adding…", "Wird hinzugefügt…", "Ajout…"],
  "settings.connections.setup": ["Setup", "Einrichten", "Configurer"],
  "settings.connections.disable": ["Disable", "Deaktivieren", "Désactiver"],
  "settings.connections.hide": ["Hide", "Ausblenden", "Masquer"],
  "settings.connections.retry": ["Retry", "Erneut versuchen", "Réessayer"],
  "settings.connections.update": ["Update", "Aktualisieren", "Mettre à jour"],
  "settings.connections.remove": ["Remove", "Entfernen", "Supprimer"],
  "settings.connections.removing": ["Removing…", "Wird entfernt…", "Suppression…"],
  "settings.connections.connect": ["Connect", "Verbinden", "Connecter"],
  "settings.connections.connecting": ["Connecting…", "Verbindung…", "Connexion…"],
  "settings.connections.disconnect": ["Disconnect", "Trennen", "Déconnecter"],
  "settings.connections.disconnecting": [
    "Disconnecting…",
    "Verbindung wird getrennt…",
    "Déconnexion…",
  ],
  "settings.connections.serverUpdateAvailable": [
    "Server update available",
    "Serveraktualisierung verfügbar",
    "Mise à jour du serveur disponible",
  ],
  "settings.connections.copyTraceId": [
    "Copy trace ID",
    "Trace-ID kopieren",
    "Copier l’identifiant de trace",
  ],
  "settings.connections.managedAbove": ["Managed above", "Oben verwaltet", "Géré ci-dessus"],
  "settings.connections.managedAboveDescription": [
    "The WSL backend is managed by the WSL setting above; turn it on or off there.",
    "Das WSL-Backend wird über die obige WSL-Einstellung verwaltet; aktiviere oder deaktiviere es dort.",
    "Le backend WSL est géré par le réglage ci-dessus ; activez-le ou désactivez-le à cet endroit.",
  ],
  "settings.connections.updateToClient": [
    "Update to match this client.",
    "An diesen Client anpassen.",
    "Mettre à jour pour correspondre à ce client.",
  ],
  "settings.connections.ssh.mode": ["SSH", "SSH", "SSH"],
  "settings.connections.toast.createPairingFailed": [
    "Could not create pairing URL",
    "Kopplungs-URL konnte nicht erstellt werden",
    "Impossible de créer l’URL d’association",
  ],
  "settings.connections.toast.traceCopied": [
    "Trace ID copied",
    "Trace-ID kopiert",
    "Identifiant de trace copié",
  ],
  "settings.connections.toast.traceCopyFailed": [
    "Could not copy trace ID",
    "Trace-ID konnte nicht kopiert werden",
    "Impossible de copier l’identifiant de trace",
  ],
  "settings.connections.toast.networkFailed": [
    "Could not update network access",
    "Netzwerkzugriff konnte nicht aktualisiert werden",
    "Impossible de mettre à jour l’accès réseau",
  ],
  "settings.connections.toast.tailscaleSetupFailed": [
    "Could not set up Tailscale HTTPS",
    "Tailscale HTTPS konnte nicht eingerichtet werden",
    "Impossible de configurer HTTPS Tailscale",
  ],
  "settings.connections.toast.tailscaleDisableFailed": [
    "Could not disable Tailscale HTTPS",
    "Tailscale HTTPS konnte nicht deaktiviert werden",
    "Impossible de désactiver HTTPS Tailscale",
  ],
  "settings.connections.toast.revokePairingFailed": [
    "Could not revoke pairing link",
    "Kopplungslink konnte nicht widerrufen werden",
    "Impossible de révoquer le lien d’association",
  ],
  "settings.connections.toast.revokeClientFailed": [
    "Could not revoke client access",
    "Client-Zugriff konnte nicht widerrufen werden",
    "Impossible de révoquer l’accès du client",
  ],
  "settings.connections.toast.revokedOthersDescription": [
    "Other paired clients will need a new pairing link before reconnecting.",
    "Andere gekoppelte Clients benötigen vor dem erneuten Verbinden einen neuen Kopplungslink.",
    "Les autres clients associés auront besoin d’un nouveau lien avant de se reconnecter.",
  ],
  "settings.connections.toast.revokeOthersFailed": [
    "Could not revoke other clients",
    "Andere Clients konnten nicht widerrufen werden",
    "Impossible de révoquer les autres clients",
  ],
  "settings.connections.toast.environmentConnected": [
    "Environment connected",
    "Umgebung verbunden",
    "Environnement connecté",
  ],
  "settings.connections.toast.environmentReconnected": [
    "Environment reconnected",
    "Umgebung erneut verbunden",
    "Environnement reconnecté",
  ],
  "settings.connections.toast.addBackendFailed": [
    "Could not add backend",
    "Backend konnte nicht hinzugefügt werden",
    "Impossible d’ajouter le backend",
  ],
  "settings.connections.toast.backendAdded": [
    "Backend added",
    "Backend hinzugefügt",
    "Backend ajouté",
  ],
  "settings.connections.toast.backendAddedDescription": [
    "The environment is saved and will reconnect on app startup.",
    "Die Umgebung ist gespeichert und verbindet sich beim App-Start erneut.",
    "L’environnement est enregistré et se reconnectera au démarrage de l’application.",
  ],
  "settings.connections.toast.connectBackendFailed": [
    "Could not connect backend",
    "Backend konnte nicht verbunden werden",
    "Impossible de connecter le backend",
  ],
  "settings.connections.toast.removeBackendFailed": [
    "Could not remove backend",
    "Backend konnte nicht entfernt werden",
    "Impossible de supprimer le backend",
  ],
  "settings.connections.toast.sshReady": [
    "{{environment}} is ready over an SSH-managed tunnel.",
    "{{environment}} ist über einen SSH-verwalteten Tunnel bereit.",
    "{{environment}} est prêt via un tunnel géré par SSH.",
  ],
  "settings.connections.toast.wslFailed": [
    "Could not change WSL backend",
    "WSL-Backend konnte nicht geändert werden",
    "Impossible de modifier le backend WSL",
  ],
  "settings.connections.endpoint.hostedHint": [
    "Opens the hosted app, no install needed",
    "Öffnet die gehostete App, keine Installation erforderlich",
    "Ouvre l’application hébergée, sans installation",
  ],
  "settings.connections.endpoint.lanHint": [
    "Devices on the same network",
    "Geräte im selben Netzwerk",
    "Appareils sur le même réseau",
  ],
  "settings.connections.endpoint.privateHint": [
    "Devices on your private network",
    "Geräte in deinem privaten Netzwerk",
    "Appareils sur votre réseau privé",
  ],
  "settings.connections.endpoint.publicHint": [
    "Reachable from anywhere",
    "Von überall erreichbar",
    "Accessible de partout",
  ],
  "settings.connections.endpoint.loopbackHint": [
    "Clients on this machine",
    "Clients auf diesem Computer",
    "Clients sur cette machine",
  ],
  "settings.connections.status.connectedFor": [
    "Connected for {{duration}}",
    "Seit {{duration}} verbunden",
    "Connecté depuis {{duration}}",
  ],
  "settings.connections.status.lastConnectedAt": [
    "Last connected at {{timestamp}}",
    "Zuletzt verbunden am {{timestamp}}",
    "Dernière connexion le {{timestamp}}",
  ],
  "settings.connections.cloud.signInRequired": [
    "Sign in to T3 Connect to manage this environment.",
    "Melde dich bei T3 Connect an, um diese Umgebung zu verwalten.",
    "Connectez-vous à T3 Connect pour gérer cet environnement.",
  ],
  "settings.connections.cloud.permissionRequired": [
    "Your session does not have permission to manage T3 Connect access.",
    "Deine Sitzung darf den T3-Connect-Zugriff nicht verwalten.",
    "Votre session n’est pas autorisée à gérer l’accès T3 Connect.",
  ],
  "settings.connections.cloud.linked": [
    "T3 Connect linked",
    "T3 Connect verbunden",
    "T3 Connect associé",
  ],
  "settings.connections.cloud.tunnelDisabled": [
    "T3 Connect tunnel disabled",
    "T3-Connect-Tunnel deaktiviert",
    "Tunnel T3 Connect désactivé",
  ],
  "settings.connections.cloud.unlinked": [
    "T3 Connect unlinked",
    "T3 Connect getrennt",
    "T3 Connect dissocié",
  ],
  "settings.connections.cloud.available": [
    "This environment is available through T3 Connect.",
    "Diese Umgebung ist über T3 Connect verfügbar.",
    "Cet environnement est disponible via T3 Connect.",
  ],
  "settings.connections.cloud.tunnelRemovedPublishingOn": [
    "The managed tunnel was removed. Agent activity publishing stays on.",
    "Der verwaltete Tunnel wurde entfernt. Die Veröffentlichung der Agentenaktivität bleibt aktiv.",
    "Le tunnel géré a été supprimé. La publication de l’activité reste active.",
  ],
  "settings.connections.cloud.unavailable": [
    "This environment is no longer available through T3 Connect.",
    "Diese Umgebung ist nicht mehr über T3 Connect verfügbar.",
    "Cet environnement n’est plus disponible via T3 Connect.",
  ],
  "settings.connections.cloud.activityEnabled": [
    "Agent activity enabled",
    "Agentenaktivität aktiviert",
    "Activité de l’agent activée",
  ],
  "settings.connections.cloud.activityDisabled": [
    "Agent activity disabled",
    "Agentenaktivität deaktiviert",
    "Activité de l’agent désactivée",
  ],
  "settings.connections.cloud.activityEnabledDescription": [
    "This environment publishes agent activity to your mobile clients.",
    "Diese Umgebung veröffentlicht Agentenaktivität an deine mobilen Clients.",
    "Cet environnement publie l’activité de l’agent vers vos clients mobiles.",
  ],
  "settings.connections.cloud.activityDisabledDescription": [
    "This environment will stop publishing agent activity.",
    "Diese Umgebung veröffentlicht keine Agentenaktivität mehr.",
    "Cet environnement cessera de publier l’activité de l’agent.",
  ],
  "settings.connections.cloud.otherDevicesAvailable": [
    "This environment is available to your other devices through T3 Connect.",
    "Diese Umgebung ist über T3 Connect für deine anderen Geräte verfügbar.",
    "Cet environnement est disponible sur vos autres appareils via T3 Connect.",
  ],
  "settings.connections.cloud.otherDevicesEnable": [
    "Make this environment available to your other devices through T3 Connect.",
    "Stelle diese Umgebung deinen anderen Geräten über T3 Connect bereit.",
    "Rendez cet environnement disponible sur vos autres appareils via T3 Connect.",
  ],
  "settings.connections.cloud.publishAria": [
    "Publish agent activity to mobile clients",
    "Agentenaktivität an mobile Clients veröffentlichen",
    "Publier l’activité de l’agent vers les clients mobiles",
  ],
  "settings.connections.tailscale.setupHint": [
    "Use Tailscale Serve to expose this backend through a MagicDNS HTTPS URL.",
    "Verwende Tailscale Serve, um dieses Backend über eine MagicDNS-HTTPS-URL bereitzustellen.",
    "Utilisez Tailscale Serve pour exposer ce backend via une URL HTTPS MagicDNS.",
  ],
  "settings.connections.tailscale.startHint": [
    "Start Tailscale to set up HTTPS access through MagicDNS.",
    "Starte Tailscale, um HTTPS-Zugriff über MagicDNS einzurichten.",
    "Démarrez Tailscale pour configurer l’accès HTTPS via MagicDNS.",
  ],
  "settings.connections.tailscale.pendingEndpoint": [
    "Pending MagicDNS endpoint",
    "Ausstehender MagicDNS-Endpunkt",
    "Point de terminaison MagicDNS en attente",
  ],
  "settings.connections.network.reachableAt": [
    "Reachable at {{endpoint}}",
    "Erreichbar unter {{endpoint}}",
    "Accessible à {{endpoint}}",
  ],
  "settings.connections.network.exposedWithHost": [
    "Exposed on all interfaces. Pairing links use {{host}}.",
    "Auf allen Schnittstellen erreichbar. Kopplungslinks verwenden {{host}}.",
    "Exposé sur toutes les interfaces. Les liens d’association utilisent {{host}}.",
  ],
  "settings.connections.network.exposed": [
    "Exposed on all interfaces.",
    "Auf allen Schnittstellen erreichbar.",
    "Exposé sur toutes les interfaces.",
  ],
  "settings.connections.network.localOnly": [
    "Limited to this machine.",
    "Auf diesen Computer beschränkt.",
    "Limité à cette machine.",
  ],
  "settings.connections.loading": ["Loading…", "Wird geladen…", "Chargement…"],
  "settings.connections.network.remoteManaged": [
    "This backend is already configured for remote access. Network exposure changes must be made where the server is launched.",
    "Dieses Backend ist bereits für Remote-Zugriff konfiguriert. Änderungen am Netzwerkzugriff müssen dort erfolgen, wo der Server gestartet wurde.",
    "Ce backend est déjà configuré pour l’accès distant. L’exposition réseau doit être modifiée là où le serveur est lancé.",
  ],
  "settings.connections.network.restartForRemote": [
    "This backend is only reachable on this machine. Restart it with a non-loopback host to enable remote pairing.",
    "Dieses Backend ist nur auf diesem Computer erreichbar. Starte es mit einem Nicht-Loopback-Host neu, um Remote-Kopplung zu aktivieren.",
    "Ce backend n’est accessible que sur cette machine. Redémarrez-le avec un hôte hors bouclage pour activer l’association distante.",
  ],
  "settings.connections.serverUpdateFailed": [
    "Update failed",
    "Aktualisierung fehlgeschlagen",
    "Échec de la mise à jour",
  ],
  "settings.connections.serverUpdating": [
    "Updating server",
    "Server wird aktualisiert",
    "Mise à jour du serveur",
  ],
  "settings.connections.network.enableTitle": [
    "Enable network access?",
    "Netzwerkzugriff aktivieren?",
    "Activer l’accès réseau ?",
  ],
  "settings.connections.network.disableTitle": [
    "Disable network access?",
    "Netzwerkzugriff deaktivieren?",
    "Désactiver l’accès réseau ?",
  ],
  "settings.connections.network.enableDescription": [
    "T3 Code will restart to expose this environment over the network.",
    "T3 Code startet neu, um diese Umgebung im Netzwerk bereitzustellen.",
    "T3 Code redémarrera pour exposer cet environnement sur le réseau.",
  ],
  "settings.connections.network.disableDescription": [
    "T3 Code will restart and limit this environment back to this machine.",
    "T3 Code startet neu und beschränkt diese Umgebung wieder auf diesen Computer.",
    "T3 Code redémarrera et limitera de nouveau cet environnement à cette machine.",
  ],
  "settings.connections.restartEnable": [
    "Restart and enable",
    "Neu starten und aktivieren",
    "Redémarrer et activer",
  ],
  "settings.connections.restartDisable": [
    "Restart and disable",
    "Neu starten und deaktivieren",
    "Redémarrer et désactiver",
  ],
  "settings.connections.enable": ["Enable", "Aktivieren", "Activer"],
  "settings.connections.wsl.dialog.disableOnlyTitle": [
    "Turn off WSL and switch back to Windows?",
    "WSL ausschalten und zu Windows zurückkehren?",
    "Désactiver WSL et revenir à Windows ?",
  ],
  "settings.connections.wsl.dialog.disableTitle": [
    "Disable WSL backend?",
    "WSL-Backend deaktivieren?",
    "Désactiver le backend WSL ?",
  ],
  "settings.connections.wsl.dialog.distroTitle": [
    "Switch WSL distro?",
    "WSL-Distribution wechseln?",
    "Changer de distribution WSL ?",
  ],
  "settings.connections.wsl.dialog.enableTitle": [
    "Start the WSL backend",
    "WSL-Backend starten",
    "Démarrer le backend WSL",
  ],
  "settings.connections.wsl.dialog.onlyTitle": [
    "Run only the WSL backend?",
    "Nur das WSL-Backend ausführen?",
    "Exécuter uniquement le backend WSL ?",
  ],
  "settings.connections.wsl.dialog.windowsTitle": [
    "Re-enable the Windows backend?",
    "Windows-Backend wieder aktivieren?",
    "Réactiver le backend Windows ?",
  ],
  "settings.connections.wsl.dialog.disableOnlyDescription": [
    "T3 Code will restart on the Windows backend. Threads and projects opened against WSL stay safe inside the distro and become available again when you re-enable WSL.",
    "T3 Code startet mit dem Windows-Backend neu. In WSL geöffnete Chats und Projekte bleiben in der Distribution sicher und werden beim erneuten Aktivieren von WSL wieder verfügbar.",
    "T3 Code redémarrera sur le backend Windows. Les discussions et projets WSL restent dans la distribution et redeviendront disponibles lorsque vous réactiverez WSL.",
  ],
  "settings.connections.wsl.dialog.disableDescription": [
    "The WSL backend will stop. Threads and projects opened against WSL stay safe inside the distro, but they'll be unavailable in T3 Code until you re-enable WSL.",
    "Das WSL-Backend wird gestoppt. In WSL geöffnete Chats und Projekte bleiben in der Distribution sicher, sind aber bis zur erneuten Aktivierung nicht verfügbar.",
    "Le backend WSL s’arrêtera. Les discussions et projets restent dans la distribution, mais seront indisponibles jusqu’à la réactivation de WSL.",
  ],
  "settings.connections.wsl.dialog.distroDescription": [
    "T3 Code will restart the WSL backend on the new distro. Sessions still running on the current distro will be interrupted.",
    "T3 Code startet das WSL-Backend in der neuen Distribution neu. Laufende Sitzungen in der aktuellen Distribution werden unterbrochen.",
    "T3 Code redémarrera le backend WSL dans la nouvelle distribution. Les sessions encore actives dans l’ancienne seront interrompues.",
  ],
  "settings.connections.wsl.dialog.enableDescription": [
    "Run the WSL backend alongside the Windows one, or stop the Windows backend and use only WSL? You can change this later from Settings.",
    "Soll das WSL-Backend neben Windows laufen oder das Windows-Backend stoppen und nur WSL verwenden? Du kannst dies später in den Einstellungen ändern.",
    "Exécuter le backend WSL avec Windows ou arrêter Windows et utiliser uniquement WSL ? Vous pourrez modifier ce choix plus tard.",
  ],
  "settings.connections.wsl.dialog.onlyDescription": [
    "T3 Code will restart and start only the WSL backend. Your Windows-side projects won't be accessible until you turn this off again.",
    "T3 Code startet neu und führt nur das WSL-Backend aus. Windows-Projekte sind nicht verfügbar, bis du dies wieder ausschaltest.",
    "T3 Code redémarrera avec uniquement le backend WSL. Vos projets Windows resteront indisponibles jusqu’à la désactivation de ce mode.",
  ],
  "settings.connections.wsl.dialog.windowsDescription": [
    "T3 Code will restart and bring the Windows backend back up alongside WSL.",
    "T3 Code startet neu und aktiviert das Windows-Backend wieder neben WSL.",
    "T3 Code redémarrera et réactivera le backend Windows aux côtés de WSL.",
  ],
  "settings.connections.wsl.useOnly": [
    "Use only WSL",
    "Nur WSL verwenden",
    "Utiliser uniquement WSL",
  ],
  "settings.connections.wsl.runBoth": [
    "Run both backends",
    "Beide Backends ausführen",
    "Exécuter les deux backends",
  ],
  "settings.connections.wsl.disable": ["Disable WSL", "WSL deaktivieren", "Désactiver WSL"],
  "settings.connections.wsl.switchDistro": [
    "Switch distro",
    "Distribution wechseln",
    "Changer de distribution",
  ],
  "settings.connections.retrying": ["Retrying…", "Erneuter Versuch…", "Nouvel essai…"],
  "settings.connections.ssh.hostRequired": [
    "SSH host or alias is required.",
    "SSH-Host oder Alias ist erforderlich.",
    "Un hôte SSH ou un alias est requis.",
  ],
  "settings.connections.ssh.portInvalid": [
    "SSH port must be between 1 and 65535.",
    "Der SSH-Port muss zwischen 1 und 65535 liegen.",
    "Le port SSH doit être compris entre 1 et 65535.",
  ],
  "settings.connections.remote.hostRequired": [
    "Enter a backend host.",
    "Gib einen Backend-Host ein.",
    "Saisissez un hôte de backend.",
  ],
  "settings.connections.remote.codeRequired": [
    "Enter a pairing code.",
    "Gib einen Kopplungscode ein.",
    "Saisissez un code d’association.",
  ],
  "settings.connections.error.createPairingFallback": [
    "Failed to create pairing URL.",
    "Kopplungs-URL konnte nicht erstellt werden.",
    "Impossible de créer l’URL d’association.",
  ],
  "settings.connections.error.sshConnectFallback": [
    "Failed to connect SSH host.",
    "Verbindung zum SSH-Host fehlgeschlagen.",
    "Échec de la connexion à l’hôte SSH.",
  ],
  "settings.connections.error.networkFallback": [
    "Failed to update network exposure.",
    "Netzwerkfreigabe konnte nicht aktualisiert werden.",
    "Échec de la mise à jour de l’exposition réseau.",
  ],
  "settings.connections.error.tailscaleSetupFallback": [
    "Failed to configure Tailscale HTTPS.",
    "Tailscale HTTPS konnte nicht konfiguriert werden.",
    "Échec de la configuration de HTTPS Tailscale.",
  ],
  "settings.connections.error.tailscaleDisableFallback": [
    "Failed to disable Tailscale HTTPS.",
    "Tailscale HTTPS konnte nicht deaktiviert werden.",
    "Échec de la désactivation de HTTPS Tailscale.",
  ],
  "settings.connections.error.revokeClientFallback": [
    "Failed to revoke client access.",
    "Client-Zugriff konnte nicht widerrufen werden.",
    "Échec de la révocation de l’accès du client.",
  ],
  "settings.connections.error.revokeOthersFallback": [
    "Failed to revoke other clients.",
    "Andere Clients konnten nicht widerrufen werden.",
    "Échec de la révocation des autres clients.",
  ],
  "settings.connections.error.addBackendFallback": [
    "Failed to add backend.",
    "Backend konnte nicht hinzugefügt werden.",
    "Échec de l’ajout du backend.",
  ],
  "settings.connections.error.removeBackendFallback": [
    "Failed to remove backend.",
    "Backend konnte nicht entfernt werden.",
    "Échec de la suppression du backend.",
  ],
  "settings.connections.error.wslFallback": [
    "Failed to update WSL backend.",
    "WSL-Backend konnte nicht aktualisiert werden.",
    "Échec de la mise à jour du backend WSL.",
  ],
  "settings.connections.toast.revokedOthers": [
    { one: "Revoked {{count}} other client", other: "Revoked {{count}} clients" },
    { one: "{{count}} weiterer Client widerrufen", other: "{{count}} Clients widerrufen" },
    { one: "{{count}} autre client révoqué", other: "{{count}} clients révoqués" },
  ],
});

export type SettingsEnvironmentsInterfaceMessageKey =
  (typeof settingsEnvironmentsInterfaceCatalog.keys)[number];
