import * as NodeModule from "node:module";

import { describe, expect, it } from "vite-plus/test";

type AndroidManifest = {
  manifest: {
    application?: Array<{ $?: Record<string, string> }>;
  };
};

type AndroidResourceItem = { _: string; $: { name: string } };
type AndroidStyle = {
  $: { name: string; parent?: string };
  item?: Array<AndroidResourceItem>;
};
type AndroidColor = { _: string; $: { name: string } };
type AndroidResources = {
  resources: {
    color?: Array<AndroidColor>;
    style?: Array<AndroidStyle>;
  };
};

type CleartextPlugin = {
  configureCleartextTraffic(manifest: AndroidManifest): AndroidManifest;
};
type GradleProperty = {
  key?: string;
  type: string;
  value?: string;
};
type GradleHeapPlugin = {
  configureGradleProperties(properties: Array<GradleProperty>): Array<GradleProperty>;
};
type MainActivityPlugin = {
  patchMainActivity(contents: string, language?: string): string;
};
type ResourcePlugin = {
  configureColors(resources: AndroidResources, appearance: "light" | "night"): AndroidResources;
  configureStyles(resources: AndroidResources): AndroidResources;
  drawables: Readonly<Record<string, string>>;
};

const require = NodeModule.createRequire(import.meta.url);
const loadCjs = (path: string): unknown => require(path);

const cleartextPlugin = loadCjs("./withAndroidCleartextTraffic.cjs") as CleartextPlugin;
const gradleHeapPlugin = loadCjs("./withAndroidGradleHeap.cjs") as GradleHeapPlugin;
const predictiveBackPlugin = loadCjs("./withAndroidPredictiveBackCompat.cjs") as MainActivityPlugin;
const tabletOrientationPlugin = loadCjs("./withAndroidTabletOrientation.cjs") as MainActivityPlugin;
const popupMenuPlugin = loadCjs("./withAndroidModernPopupMenu.cjs") as ResourcePlugin;
const alertDialogPlugin = loadCjs("./withAndroidModernAlertDialog.cjs") as ResourcePlugin;

const MAIN_ACTIVITY_TEMPLATE = `package com.t3tools.t3code

import android.os.Bundle

class MainActivity : ReactActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(null)
  }

  override fun invokeDefaultOnBackPressed() {
    super.invokeDefaultOnBackPressed()
  }
}
`;

function countOccurrences(contents: string, marker: string): number {
  return contents.split(marker).length - 1;
}

function findStyle(resources: AndroidResources, name: string): AndroidStyle | undefined {
  return resources.resources.style?.find((style) => style.$.name === name);
}

function findStyleItem(style: AndroidStyle | undefined, name: string): string | undefined {
  return style?.item?.find((item) => item.$.name === name)?._;
}

function findColor(resources: AndroidResources, name: string): string | undefined {
  return resources.resources.color?.find((color) => color.$.name === name)?._;
}

function createThemeResources(): AndroidResources {
  return {
    resources: {
      style: [
        {
          $: { name: "AppTheme", parent: "Theme.AppCompat.DayNight.NoActionBar" },
          item: [],
        },
      ],
    },
  };
}

describe("Android native config plugins", () => {
  it("enables cleartext traffic without duplicating the manifest attribute", () => {
    const manifest: AndroidManifest = { manifest: { application: [{}] } };

    cleartextPlugin.configureCleartextTraffic(manifest);
    cleartextPlugin.configureCleartextTraffic(manifest);

    expect(manifest.manifest.application?.[0]?.$).toEqual({
      "android:usesCleartextTraffic": "true",
    });
  });

  it("fails clearly when the manifest application anchor disappears", () => {
    expect(() => cleartextPlugin.configureCleartextTraffic({ manifest: {} })).toThrowError(
      /missing the application element/,
    );
  });

  it("replaces stale Gradle heap settings once while preserving unrelated properties", () => {
    const properties: Array<GradleProperty> = [
      { type: "comment", value: "Generated by Expo" },
      { type: "property", key: "org.gradle.jvmargs", value: "-Xmx2048m" },
      { type: "property", key: "android.useAndroidX", value: "true" },
      { type: "property", key: "org.gradle.jvmargs", value: "-Xmx1024m" },
    ];

    const configured = gradleHeapPlugin.configureGradleProperties(properties);
    const reapplied = gradleHeapPlugin.configureGradleProperties(configured);

    expect(reapplied).toEqual(configured);
    expect(reapplied.filter((property) => property.key === "org.gradle.jvmargs")).toEqual([
      {
        type: "property",
        key: "org.gradle.jvmargs",
        value: "-Xmx4096m -XX:MaxMetaspaceSize=1024m",
      },
    ]);
    expect(reapplied).toContainEqual({ type: "comment", value: "Generated by Expo" });
    expect(reapplied).toContainEqual({
      type: "property",
      key: "android.useAndroidX",
      value: "true",
    });
  });

  it("patches predictive back and tablet orientation once in either plugin order", () => {
    const predictiveThenTablet = tabletOrientationPlugin.patchMainActivity(
      predictiveBackPlugin.patchMainActivity(MAIN_ACTIVITY_TEMPLATE),
    );
    const tabletThenPredictive = predictiveBackPlugin.patchMainActivity(
      tabletOrientationPlugin.patchMainActivity(MAIN_ACTIVITY_TEMPLATE),
    );

    for (const patched of [predictiveThenTablet, tabletThenPredictive]) {
      const reapplied = tabletOrientationPlugin.patchMainActivity(
        predictiveBackPlugin.patchMainActivity(patched),
      );

      expect(reapplied).toBe(patched);
      expect(countOccurrences(patched, "predictiveBackCompatCallback =")).toBe(1);
      expect(countOccurrences(patched, "applyTabletOrientation()")).toBe(3);
      expect(countOccurrences(patched, "override fun onConfigurationChanged")).toBe(1);
      expect(patched).toContain("Build.VERSION.SDK_INT < Build.VERSION_CODES.BAKLAVA");
      expect(patched).toContain("ActivityInfo.SCREEN_ORIENTATION_FULL_USER");
      expect(patched).toContain("ActivityInfo.SCREEN_ORIENTATION_PORTRAIT");
    }
  });

  it("fails closed when Expo MainActivity anchors drift or the template stops being Kotlin", () => {
    expect(() =>
      predictiveBackPlugin.patchMainActivity(MAIN_ACTIVITY_TEMPLATE, "java"),
    ).toThrowError(/must be Kotlin/);
    expect(() =>
      predictiveBackPlugin.patchMainActivity(
        MAIN_ACTIVITY_TEMPLATE.replace(
          "super.onCreate(null)",
          "super.onCreate(savedInstanceState)",
        ),
      ),
    ).toThrowError(/super\.onCreate call/);
    expect(() =>
      predictiveBackPlugin.patchMainActivity(
        MAIN_ACTIVITY_TEMPLATE.replace("override fun invokeDefaultOnBackPressed() {", ""),
      ),
    ).toThrowError(/invokeDefaultOnBackPressed/);
    expect(() =>
      tabletOrientationPlugin.patchMainActivity(
        MAIN_ACTIVITY_TEMPLATE.replace(
          "class MainActivity : ReactActivity() {",
          "class MainActivity",
        ),
      ),
    ).toThrowError(/MainActivity class declaration/);
  });

  it("generates idempotent popup styles, palettes, and drawable resources", () => {
    const resources = createThemeResources();

    popupMenuPlugin.configureStyles(resources);
    popupMenuPlugin.configureColors(resources, "light");
    const once = structuredClone(resources);
    popupMenuPlugin.configureStyles(resources);
    popupMenuPlugin.configureColors(resources, "light");

    expect(resources).toEqual(once);
    expect(findStyleItem(findStyle(resources, "AppTheme"), "popupMenuStyle")).toBe(
      "@style/AppPopupMenu",
    );
    expect(findStyleItem(findStyle(resources, "AppPopupMenu"), "android:popupBackground")).toBe(
      "@drawable/popup_menu_background",
    );
    expect(findColor(resources, "popup_menu_background")).toBe("#F7F7F7");
    expect(findColor(resources, "popup_menu_item_text")).toBe("#262626");
    expect(Object.keys(popupMenuPlugin.drawables).sort()).toEqual([
      "ic_menu_check.xml",
      "popup_menu_background.xml",
      "popup_menu_check_button.xml",
      "popup_menu_submenu_arrow.xml",
    ]);
    expect(popupMenuPlugin.drawables["popup_menu_submenu_arrow.xml"]).toContain(
      "@color/popup_menu_item_text",
    );
  });

  it("generates idempotent alert styles, day/night palettes, and drawable resources", () => {
    const lightResources = createThemeResources();
    const nightResources: AndroidResources = { resources: {} };

    alertDialogPlugin.configureStyles(lightResources);
    alertDialogPlugin.configureColors(lightResources, "light");
    alertDialogPlugin.configureColors(nightResources, "night");
    const once = structuredClone(lightResources);
    alertDialogPlugin.configureStyles(lightResources);
    alertDialogPlugin.configureColors(lightResources, "light");

    expect(lightResources).toEqual(once);
    expect(findStyleItem(findStyle(lightResources, "AppTheme"), "alertDialogTheme")).toBe(
      "@style/AppAlertDialog",
    );
    expect(
      findStyleItem(findStyle(lightResources, "AppAlertDialog"), "android:windowBackground"),
    ).toBe("@drawable/alert_dialog_background");
    expect(findColor(lightResources, "alert_dialog_background")).toBe("#FFFFFF");
    expect(findColor(nightResources, "alert_dialog_background")).toBe("#171717");
    expect(alertDialogPlugin.drawables["alert_dialog_background.xml"]).toContain(
      "@color/alert_dialog_background",
    );
  });
});
